!
! VWN_RPA: LDA exchange-correlation kernel.
!
! GENERATED by tools/exchcxx_to_fortran.py from ExchCXX's
! include/exchcxx/impl/builtin/kernels/vwn_rpa.hpp -- do not edit.
!
! The arithmetic is ExchCXX's (MIT; Copyright (c) 2020-2024, The Regents
! of the University of California, through Lawrence Berkeley National
! Laboratory; portions Copyright (c) Microsoft Corporation), itself
! generated by Maple from the functional's definition. See
! https://github.com/wavefunction91/ExchCXX.
!
! Every routine is scalar, pure, and callable from `do concurrent`.
! The public `<name>_<what>_<polar>` routines apply the density and
! gradient thresholds the way ExchCXX's screening_interface.hpp does;
! the `_impl` bodies below them are the bare Maple expressions.
!
! Unpolarised routines take the TOTAL density and its gradient
! invariant; polarised ones take the two spin densities and the three
! gradient invariants. `eps` is the energy per particle, so the
! integrand is rho * eps.
!
module trc_xc_vwn_rpa
   use trc_boys, only: dp
   use trc_xc_util, only: m_cbrt_2, m_cbrt_3, m_cbrt_4, m_cbrt_one_ov_pi, xc_cbrt
   implicit none
   private

   public :: vwn_rpa_exc_unpolar
   public :: vwn_rpa_exc_vxc_unpolar
   public :: vwn_rpa_fxc_unpolar
   public :: vwn_rpa_vxc_fxc_unpolar
   public :: vwn_rpa_exc_polar
   public :: vwn_rpa_exc_vxc_polar
   public :: vwn_rpa_fxc_polar
   public :: vwn_rpa_vxc_fxc_polar

   real(dp), parameter :: dens_tol = 1e-24_dp
   real(dp), parameter :: zeta_tol = 1e-15_dp
   real(dp), parameter :: sigma_tol = 1.000000000000004e-32_dp
   real(dp), parameter :: tau_tol = 1e-20_dp

contains

   pure subroutine vwn_rpa_exc_unpolar(rho, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps
      real(dp) :: rho_c
      eps = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_rpa_exc_unpolar_impl(rho_c, eps)
      end if
   end subroutine vwn_rpa_exc_unpolar

   pure subroutine vwn_rpa_exc_vxc_unpolar(rho, eps, vrho)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps, vrho
      real(dp) :: rho_c
      eps = 0.0_dp
      vrho = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_rpa_exc_vxc_unpolar_impl(rho_c, eps, vrho)
      end if
   end subroutine vwn_rpa_exc_vxc_unpolar

   pure subroutine vwn_rpa_fxc_unpolar(rho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: v2rho2
      real(dp) :: rho_c
      v2rho2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_rpa_fxc_unpolar_impl(rho_c, v2rho2)
      end if
   end subroutine vwn_rpa_fxc_unpolar

   pure subroutine vwn_rpa_vxc_fxc_unpolar(rho, vrho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: vrho, v2rho2
      real(dp) :: rho_c
      vrho = 0.0_dp
      v2rho2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_rpa_vxc_fxc_unpolar_impl(rho_c, vrho, v2rho2)
      end if
   end subroutine vwn_rpa_vxc_fxc_unpolar

   pure subroutine vwn_rpa_exc_polar(rho_a, rho_b, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps
      real(dp) :: rho_a_c, rho_b_c
      eps = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_rpa_exc_polar_impl(rho_a_c, rho_b_c, eps)
      end if
   end subroutine vwn_rpa_exc_polar

   pure subroutine vwn_rpa_exc_vxc_polar(rho_a, rho_b, eps, vrho_a, vrho_b)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps, vrho_a, vrho_b
      real(dp) :: rho_a_c, rho_b_c
      eps = 0.0_dp
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_rpa_exc_vxc_polar_impl(rho_a_c, rho_b_c, eps, vrho_a, vrho_b)
      end if
   end subroutine vwn_rpa_exc_vxc_polar

   pure subroutine vwn_rpa_fxc_polar(rho_a, rho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb
      real(dp) :: rho_a_c, rho_b_c
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_rpa_fxc_polar_impl(rho_a_c, rho_b_c, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      end if
   end subroutine vwn_rpa_fxc_polar

   pure subroutine vwn_rpa_vxc_fxc_polar(rho_a, rho_b, vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, &
      v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb
      real(dp) :: rho_a_c, rho_b_c
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_rpa_vxc_fxc_polar_impl(rho_a_c, rho_b_c, vrho_a, vrho_b, v2rho2_aa, &
            v2rho2_ab, v2rho2_bb)
      end if
   end subroutine vwn_rpa_vxc_fxc_polar

   pure subroutine vwn_rpa_exc_unpolar_impl(rho, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps
      real(dp) :: t1, t3, t5, t39, t4, t6, t7, t8
      real(dp) :: t9, t10, t11, t12, t14, t15, t19, t21
      real(dp) :: t24, t26, t27, t28, t30, t34, t36, t38
      real(dp) :: t42, t44, t45, t47, t48, t52, t54, t57
      real(dp) :: t59, t60, t62, t66
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t39 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.6536e1_dp * t12 + 0.427198e2_dp
      t15 = 0.1e1_dp / t14
      t19 = log(t4 * t9 * t15 / 0.4e1_dp)
      t21 = t12 + 0.13072e2_dp
      t24 = atan(0.44899888641287296627e-1_dp / t21)
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.409286e0_dp
      t28 = t27 * t27
      t30 = log(t28 * t15)
      t34 = xc_cbrt(zeta_tol)
      t36 = merge(t34 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t38 = 0.2e1_dp * t36 - 0.2e1_dp
      t42 = 0.1e1_dp / (0.2e1_dp * t39 - 0.2e1_dp)
      t44 = -t38 * t42 + 0.1e1_dp
      t45 = (0.310907e-1_dp * t19 + 0.20521972937837502661e2_dp * t24 + &
         0.44313737677495382697e-2_dp * t30) * t44
      t47 = t11 + 0.1006155e2_dp * t12 + 0.101578e3_dp
      t48 = 0.1e1_dp / t47
      t52 = log(t4 * t9 * t48 / 0.4e1_dp)
      t54 = t12 + 0.201231e2_dp
      t57 = atan(0.11716852777089929792e1_dp / t54)
      t59 = t26 + 0.743294e0_dp
      t60 = t59 * t59
      t62 = log(t60 * t48)
      t66 = (0.1554535e-1_dp * t52 + 0.61881802979060631482e0_dp * t57 + &
         0.26673100072733151594e-2_dp * t62) * t38 * t42
      eps = t45 + t66
   end subroutine vwn_rpa_exc_unpolar_impl

   pure subroutine vwn_rpa_exc_vxc_unpolar_impl(rho, eps, vrho)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps, vrho
      real(dp) :: t1, t3, t5, t39, t4, t6, t73, t81
      real(dp) :: t90, t92, t7, t8, t9, t10, t11, t12
      real(dp) :: t14, t15, t19, t21, t24, t26, t27, t28
      real(dp) :: t30, t34, t36, t38, t42, t44, t45, t47
      real(dp) :: t48, t52, t54, t57, t59, t60, t62, t66
      real(dp) :: t68, t69, t74, t75, t76, t77, t78, t79
      real(dp) :: t80, t83, t85, t93, t94, t95, t98, t99
      real(dp) :: t101, t103, t104, t109, t110, t113, t115, t116
      real(dp) :: t117, t121, t125, t126, t127, t129, t135, t136
      real(dp) :: t139, t140, t142, t144, t145, t150, t151, t154
      real(dp) :: t156, t157, t158, t163
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t39 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t73 = t4 * t6
      t81 = t3 * t6
      t90 = t1 * t1
      t92 = 0.1e1_dp / t3
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.6536e1_dp * t12 + 0.427198e2_dp
      t15 = 0.1e1_dp / t14
      t19 = log(t4 * t9 * t15 / 0.4e1_dp)
      t21 = t12 + 0.13072e2_dp
      t24 = atan(0.44899888641287296627e-1_dp / t21)
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.409286e0_dp
      t28 = t27 * t27
      t30 = log(t28 * t15)
      t34 = xc_cbrt(zeta_tol)
      t36 = merge(t34 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t38 = 0.2e1_dp * t36 - 0.2e1_dp
      t42 = 0.1e1_dp / (0.2e1_dp * t39 - 0.2e1_dp)
      t44 = -t38 * t42 + 0.1e1_dp
      t45 = (0.310907e-1_dp * t19 + 0.20521972937837502661e2_dp * t24 + &
         0.44313737677495382697e-2_dp * t30) * t44
      t47 = t11 + 0.1006155e2_dp * t12 + 0.101578e3_dp
      t48 = 0.1e1_dp / t47
      t52 = log(t4 * t9 * t48 / 0.4e1_dp)
      t54 = t12 + 0.201231e2_dp
      t57 = atan(0.11716852777089929792e1_dp / t54)
      t59 = t26 + 0.743294e0_dp
      t60 = t59 * t59
      t62 = log(t60 * t48)
      t66 = (0.1554535e-1_dp * t52 + 0.61881802979060631482e0_dp * t57 + &
         0.26673100072733151594e-2_dp * t62) * t38 * t42
      t68 = 0.1e1_dp / t7 / rho
      t69 = t6 * t68
      t74 = t14 * t14
      t75 = 0.1e1_dp / t74
      t76 = t8 * t75
      t77 = t4 * t69
      t78 = t77 / 0.12e2_dp
      t79 = 0.1e1_dp / t12
      t80 = t79 * t1
      t83 = t80 * t81 * t68
      t85 = -t78 - 0.10893333333333333333e1_dp * t83
      t93 = (-t4 * t69 * t15 / 0.12e2_dp - t73 * t76 * t85 / 0.4e1_dp) * t90 * t92
      t94 = t5 * t7
      t95 = t94 * t14
      t98 = t21 * t21
      t99 = 0.1e1_dp / t98
      t101 = t99 * t79 * t1
      t103 = 0.2016e-2_dp * t99 + 0.1e1_dp
      t104 = 0.1e1_dp / t103
      t109 = t27 * t15
      t110 = t109 * t79
      t113 = t28 * t75
      t115 = -t110 * t77 / 0.6e1_dp - t113 * t85
      t116 = 0.1e1_dp / t28
      t117 = t115 * t116
      t121 = (0.10363566666666666667e-1_dp * t93 * t95 + 0.15357238326806922974e0_dp * t101 * &
         t81 * t68 * t104 + 0.44313737677495382697e-2_dp * t117 * t14) * t44
      t125 = t47 * t47
      t126 = 0.1e1_dp / t125
      t127 = t8 * t126
      t129 = -t78 - 0.1676925e1_dp * t83
      t135 = (-t4 * t69 * t48 / 0.12e2_dp - t73 * t127 * t129 / 0.4e1_dp) * t90 * t92
      t136 = t94 * t47
      t139 = t54 * t54
      t140 = 0.1e1_dp / t139
      t142 = t140 * t79 * t1
      t144 = 0.137284639e1_dp * t140 + 0.1e1_dp
      t145 = 0.1e1_dp / t144
      t150 = t59 * t48
      t151 = t150 * t79
      t154 = t60 * t126
      t156 = -t151 * t77 / 0.6e1_dp - t154 * t129
      t157 = 0.1e1_dp / t60
      t158 = t156 * t157
      t163 = (0.51817833333333333333e-2_dp * t135 * t136 + 0.12084332918108974175e0_dp * t142 &
         * t81 * t68 * t145 + 0.26673100072733151594e-2_dp * t158 * t47) * t38 * t42
      eps = t45 + t66
      vrho = t45 + t66 + rho * (t121 + t163)
   end subroutine vwn_rpa_exc_vxc_unpolar_impl

   pure subroutine vwn_rpa_fxc_unpolar_impl(rho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: v2rho2
      real(dp) :: t1, t3, t5, t39, t4, t6, t73, t81
      real(dp) :: t90, t92, t191, t192, t254, t7, t8, t9
      real(dp) :: t10, t11, t12, t14, t15, t21, t26, t27
      real(dp) :: t28, t34, t36, t38, t42, t44, t47, t48
      real(dp) :: t54, t59, t60, t68, t69, t74, t75, t76
      real(dp) :: t77, t78, t79, t80, t83, t85, t93, t94
      real(dp) :: t95, t98, t99, t101, t103, t104, t109, t110
      real(dp) :: t113, t115, t116, t117, t121, t125, t126, t127
      real(dp) :: t129, t135, t136, t139, t140, t142, t144, t145
      real(dp) :: t150, t151, t154, t156, t157, t158, t163, t168
      real(dp) :: t170, t171, t173, t175, t180, t181, t182, t186
      real(dp) :: t187, t189, t190, t193, t195, t197, t200, t202
      real(dp) :: t208, t212, t213, t216, t219, t221, t222, t227
      real(dp) :: t236, t238, t239, t240, t241, t242, t247, t248
      real(dp) :: t249, t253, t255, t256, t261, t265, t266, t270
      real(dp) :: t271, t272, t273, t279, t281, t283, t288, t289
      real(dp) :: t290, t296, t302, t305, t308, t311, t313, t314
      real(dp) :: t319, t328, t330, t331, t332, t333, t334, t339
      real(dp) :: t340, t341, t345, t350, t354, t355, t359, t360
      real(dp) :: t361, t362, t369
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t39 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t73 = t4 * t6
      t81 = t3 * t6
      t90 = t1 * t1
      t92 = 0.1e1_dp / t3
      t191 = t3 * t3
      t192 = t191 * t5
      t254 = t90 * t191
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.6536e1_dp * t12 + 0.427198e2_dp
      t15 = 0.1e1_dp / t14
      t21 = t12 + 0.13072e2_dp
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.409286e0_dp
      t28 = t27 * t27
      t34 = xc_cbrt(zeta_tol)
      t36 = merge(t34 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t38 = 0.2e1_dp * t36 - 0.2e1_dp
      t42 = 0.1e1_dp / (0.2e1_dp * t39 - 0.2e1_dp)
      t44 = -t38 * t42 + 0.1e1_dp
      t47 = t11 + 0.1006155e2_dp * t12 + 0.101578e3_dp
      t48 = 0.1e1_dp / t47
      t54 = t12 + 0.201231e2_dp
      t59 = t26 + 0.743294e0_dp
      t60 = t59 * t59
      t68 = 0.1e1_dp / t7 / rho
      t69 = t6 * t68
      t74 = t14 * t14
      t75 = 0.1e1_dp / t74
      t76 = t8 * t75
      t77 = t4 * t69
      t78 = t77 / 0.12e2_dp
      t79 = 0.1e1_dp / t12
      t80 = t79 * t1
      t83 = t80 * t81 * t68
      t85 = -t78 - 0.10893333333333333333e1_dp * t83
      t93 = (-t4 * t69 * t15 / 0.12e2_dp - t73 * t76 * t85 / 0.4e1_dp) * t90 * t92
      t94 = t5 * t7
      t95 = t94 * t14
      t98 = t21 * t21
      t99 = 0.1e1_dp / t98
      t101 = t99 * t79 * t1
      t103 = 0.2016e-2_dp * t99 + 0.1e1_dp
      t104 = 0.1e1_dp / t103
      t109 = t27 * t15
      t110 = t109 * t79
      t113 = t28 * t75
      t115 = -t110 * t77 / 0.6e1_dp - t113 * t85
      t116 = 0.1e1_dp / t28
      t117 = t115 * t116
      t121 = (0.10363566666666666667e-1_dp * t93 * t95 + 0.15357238326806922974e0_dp * t101 * &
         t81 * t68 * t104 + 0.44313737677495382697e-2_dp * t117 * t14) * t44
      t125 = t47 * t47
      t126 = 0.1e1_dp / t125
      t127 = t8 * t126
      t129 = -t78 - 0.1676925e1_dp * t83
      t135 = (-t4 * t69 * t48 / 0.12e2_dp - t73 * t127 * t129 / 0.4e1_dp) * t90 * t92
      t136 = t94 * t47
      t139 = t54 * t54
      t140 = 0.1e1_dp / t139
      t142 = t140 * t79 * t1
      t144 = 0.137284639e1_dp * t140 + 0.1e1_dp
      t145 = 0.1e1_dp / t144
      t150 = t59 * t48
      t151 = t150 * t79
      t154 = t60 * t126
      t156 = -t151 * t77 / 0.6e1_dp - t154 * t129
      t157 = 0.1e1_dp / t60
      t158 = t156 * t157
      t163 = (0.51817833333333333333e-2_dp * t135 * t136 + 0.12084332918108974175e0_dp * t142 &
         * t81 * t68 * t145 + 0.26673100072733151594e-2_dp * t158 * t47) * t38 * t42
      t168 = rho * rho
      t170 = 0.1e1_dp / t7 / t168
      t171 = t6 * t170
      t173 = t4 * t171 * t15
      t175 = t68 * t75
      t180 = 0.1e1_dp / t74 / t14
      t181 = t8 * t180
      t182 = t85 * t85
      t186 = t4 * t171
      t187 = t186 / 0.9e1_dp
      t189 = 0.1e1_dp / t12 / t10
      t190 = t189 * t90
      t193 = t7 * t7
      t195 = 0.1e1_dp / t193 / t168
      t197 = t190 * t192 * t195
      t200 = t80 * t81 * t170
      t202 = t187 - 0.7262222222222222222e0_dp * t197 + 0.14524444444444444444e1_dp * t200
      t208 = (t173 / 0.9e1_dp + t73 * t175 * t85 / 0.6e1_dp + t73 * t181 * t182 / 0.2e1_dp - &
         t73 * t76 * t202 / 0.4e1_dp) * t90 * t92
      t212 = t5 / t193
      t213 = t212 * t14
      t216 = t94 * t85
      t219 = t98 * t21
      t221 = 0.1e1_dp / t219 * t1
      t222 = t221 * t3
      t227 = t99 * t189 * t90
      t236 = t98 * t98
      t238 = 0.1e1_dp / t236 / t21
      t239 = t238 * t1
      t240 = t239 * t3
      t241 = t103 * t103
      t242 = 0.1e1_dp / t241
      t247 = t27 * t75
      t248 = t247 * t80
      t249 = t68 * t85
      t253 = t109 * t189
      t255 = t5 * t195
      t256 = t254 * t255
      t261 = t28 * t180
      t265 = t173 / 0.72e2_dp + t248 * t81 * t249 / 0.3e1_dp - t253 * t256 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t110 * t186 + 0.2e1_dp * t261 * t182 - t113 * t202
      t266 = t265 * t116
      t270 = 0.1e1_dp / t28 / t27
      t271 = t115 * t270
      t272 = t14 * t79
      t273 = t271 * t272
      t279 = (0.10363566666666666667e-1_dp * t208 * t95 + 0.34545222222222222223e-2_dp * t93 &
         * t213 + 0.10363566666666666667e-1_dp * t93 * t216 + 0.51190794422689743247e-1_dp * &
         t222 * t171 * t104 + 0.10238158884537948649e0_dp * t227 * t192 * t195 * t104 - &
         0.20476317769075897299e0_dp * t101 * t81 * t170 * t104 - &
         0.10320064155614252239e-3_dp * t240 * t171 * t242 + 0.44313737677495382697e-2_dp * &
         t266 * t14 + 0.73856229462492304495e-3_dp * t273 * t77 + &
         0.44313737677495382697e-2_dp * t117 * t85) * t44
      t281 = t4 * t171 * t48
      t283 = t68 * t126
      t288 = 0.1e1_dp / t125 / t47
      t289 = t8 * t288
      t290 = t129 * t129
      t296 = t187 - 0.111795e1_dp * t197 + 0.22359e1_dp * t200
      t302 = (t281 / 0.9e1_dp + t73 * t283 * t129 / 0.6e1_dp + t73 * t289 * t290 / 0.2e1_dp - &
         t73 * t127 * t296 / 0.4e1_dp) * t90 * t92
      t305 = t212 * t47
      t308 = t94 * t129
      t311 = t139 * t54
      t313 = 0.1e1_dp / t311 * t1
      t314 = t313 * t3
      t319 = t140 * t189 * t90
      t328 = t139 * t139
      t330 = 0.1e1_dp / t328 / t54
      t331 = t330 * t1
      t332 = t331 * t3
      t333 = t144 * t144
      t334 = 0.1e1_dp / t333
      t339 = t59 * t126
      t340 = t339 * t80
      t341 = t68 * t129
      t345 = t150 * t189
      t350 = t60 * t288
      t354 = t281 / 0.72e2_dp + t340 * t81 * t341 / 0.3e1_dp - t345 * t256 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t151 * t186 + 0.2e1_dp * t350 * t290 - t154 * t296
      t355 = t354 * t157
      t359 = 0.1e1_dp / t60 / t59
      t360 = t156 * t359
      t361 = t47 * t79
      t362 = t360 * t361
      t369 = (0.51817833333333333333e-2_dp * t302 * t136 + 0.17272611111111111111e-2_dp * &
         t135 * t305 + 0.51817833333333333333e-2_dp * t135 * t308 + &
         0.40281109727029913917e-1_dp * t314 * t171 * t145 + 0.80562219454059827833e-1_dp * &
         t319 * t192 * t195 * t145 - 0.16112443890811965567e0_dp * t142 * t81 * t170 * t145 - &
         0.55299776073946902743e-1_dp * t332 * t171 * t334 + 0.26673100072733151594e-2_dp * &
         t355 * t47 + 0.4445516678788858599e-3_dp * t362 * t77 + 0.26673100072733151594e-2_dp &
         * t158 * t129) * t38 * t42
      v2rho2 = 0.2e1_dp * t121 + 0.2e1_dp * t163 + rho * (t279 + t369)
   end subroutine vwn_rpa_fxc_unpolar_impl

   pure subroutine vwn_rpa_vxc_fxc_unpolar_impl(rho, vrho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: vrho, v2rho2
      real(dp) :: t1, t3, t5, t39, t4, t6, t73, t81
      real(dp) :: t90, t92, t191, t192, t254, t7, t8, t9
      real(dp) :: t10, t11, t12, t14, t15, t19, t21, t24
      real(dp) :: t26, t27, t28, t30, t34, t36, t38, t42
      real(dp) :: t44, t45, t47, t48, t52, t54, t57, t59
      real(dp) :: t60, t62, t66, t68, t69, t74, t75, t76
      real(dp) :: t77, t78, t79, t80, t83, t85, t93, t94
      real(dp) :: t95, t98, t99, t101, t103, t104, t109, t110
      real(dp) :: t113, t115, t116, t117, t121, t125, t126, t127
      real(dp) :: t129, t135, t136, t139, t140, t142, t144, t145
      real(dp) :: t150, t151, t154, t156, t157, t158, t163, t168
      real(dp) :: t170, t171, t173, t175, t180, t181, t182, t186
      real(dp) :: t187, t189, t190, t193, t195, t197, t200, t202
      real(dp) :: t208, t212, t213, t216, t219, t221, t222, t227
      real(dp) :: t236, t238, t239, t240, t241, t242, t247, t248
      real(dp) :: t249, t253, t255, t256, t261, t265, t266, t270
      real(dp) :: t271, t272, t273, t279, t281, t283, t288, t289
      real(dp) :: t290, t296, t302, t305, t308, t311, t313, t314
      real(dp) :: t319, t328, t330, t331, t332, t333, t334, t339
      real(dp) :: t340, t341, t345, t350, t354, t355, t359, t360
      real(dp) :: t361, t362, t369
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t39 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t73 = t4 * t6
      t81 = t3 * t6
      t90 = t1 * t1
      t92 = 0.1e1_dp / t3
      t191 = t3 * t3
      t192 = t191 * t5
      t254 = t90 * t191
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.6536e1_dp * t12 + 0.427198e2_dp
      t15 = 0.1e1_dp / t14
      t19 = log(t4 * t9 * t15 / 0.4e1_dp)
      t21 = t12 + 0.13072e2_dp
      t24 = atan(0.44899888641287296627e-1_dp / t21)
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.409286e0_dp
      t28 = t27 * t27
      t30 = log(t28 * t15)
      t34 = xc_cbrt(zeta_tol)
      t36 = merge(t34 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t38 = 0.2e1_dp * t36 - 0.2e1_dp
      t42 = 0.1e1_dp / (0.2e1_dp * t39 - 0.2e1_dp)
      t44 = -t38 * t42 + 0.1e1_dp
      t45 = (0.310907e-1_dp * t19 + 0.20521972937837502661e2_dp * t24 + &
         0.44313737677495382697e-2_dp * t30) * t44
      t47 = t11 + 0.1006155e2_dp * t12 + 0.101578e3_dp
      t48 = 0.1e1_dp / t47
      t52 = log(t4 * t9 * t48 / 0.4e1_dp)
      t54 = t12 + 0.201231e2_dp
      t57 = atan(0.11716852777089929792e1_dp / t54)
      t59 = t26 + 0.743294e0_dp
      t60 = t59 * t59
      t62 = log(t60 * t48)
      t66 = (0.1554535e-1_dp * t52 + 0.61881802979060631482e0_dp * t57 + &
         0.26673100072733151594e-2_dp * t62) * t38 * t42
      t68 = 0.1e1_dp / t7 / rho
      t69 = t6 * t68
      t74 = t14 * t14
      t75 = 0.1e1_dp / t74
      t76 = t8 * t75
      t77 = t4 * t69
      t78 = t77 / 0.12e2_dp
      t79 = 0.1e1_dp / t12
      t80 = t79 * t1
      t83 = t80 * t81 * t68
      t85 = -t78 - 0.10893333333333333333e1_dp * t83
      t93 = (-t4 * t69 * t15 / 0.12e2_dp - t73 * t76 * t85 / 0.4e1_dp) * t90 * t92
      t94 = t5 * t7
      t95 = t94 * t14
      t98 = t21 * t21
      t99 = 0.1e1_dp / t98
      t101 = t99 * t79 * t1
      t103 = 0.2016e-2_dp * t99 + 0.1e1_dp
      t104 = 0.1e1_dp / t103
      t109 = t27 * t15
      t110 = t109 * t79
      t113 = t28 * t75
      t115 = -t110 * t77 / 0.6e1_dp - t113 * t85
      t116 = 0.1e1_dp / t28
      t117 = t115 * t116
      t121 = (0.10363566666666666667e-1_dp * t93 * t95 + 0.15357238326806922974e0_dp * t101 * &
         t81 * t68 * t104 + 0.44313737677495382697e-2_dp * t117 * t14) * t44
      t125 = t47 * t47
      t126 = 0.1e1_dp / t125
      t127 = t8 * t126
      t129 = -t78 - 0.1676925e1_dp * t83
      t135 = (-t4 * t69 * t48 / 0.12e2_dp - t73 * t127 * t129 / 0.4e1_dp) * t90 * t92
      t136 = t94 * t47
      t139 = t54 * t54
      t140 = 0.1e1_dp / t139
      t142 = t140 * t79 * t1
      t144 = 0.137284639e1_dp * t140 + 0.1e1_dp
      t145 = 0.1e1_dp / t144
      t150 = t59 * t48
      t151 = t150 * t79
      t154 = t60 * t126
      t156 = -t151 * t77 / 0.6e1_dp - t154 * t129
      t157 = 0.1e1_dp / t60
      t158 = t156 * t157
      t163 = (0.51817833333333333333e-2_dp * t135 * t136 + 0.12084332918108974175e0_dp * t142 &
         * t81 * t68 * t145 + 0.26673100072733151594e-2_dp * t158 * t47) * t38 * t42
      t168 = rho * rho
      t170 = 0.1e1_dp / t7 / t168
      t171 = t6 * t170
      t173 = t4 * t171 * t15
      t175 = t68 * t75
      t180 = 0.1e1_dp / t74 / t14
      t181 = t8 * t180
      t182 = t85 * t85
      t186 = t4 * t171
      t187 = t186 / 0.9e1_dp
      t189 = 0.1e1_dp / t12 / t10
      t190 = t189 * t90
      t193 = t7 * t7
      t195 = 0.1e1_dp / t193 / t168
      t197 = t190 * t192 * t195
      t200 = t80 * t81 * t170
      t202 = t187 - 0.7262222222222222222e0_dp * t197 + 0.14524444444444444444e1_dp * t200
      t208 = (t173 / 0.9e1_dp + t73 * t175 * t85 / 0.6e1_dp + t73 * t181 * t182 / 0.2e1_dp - &
         t73 * t76 * t202 / 0.4e1_dp) * t90 * t92
      t212 = t5 / t193
      t213 = t212 * t14
      t216 = t94 * t85
      t219 = t98 * t21
      t221 = 0.1e1_dp / t219 * t1
      t222 = t221 * t3
      t227 = t99 * t189 * t90
      t236 = t98 * t98
      t238 = 0.1e1_dp / t236 / t21
      t239 = t238 * t1
      t240 = t239 * t3
      t241 = t103 * t103
      t242 = 0.1e1_dp / t241
      t247 = t27 * t75
      t248 = t247 * t80
      t249 = t68 * t85
      t253 = t109 * t189
      t255 = t5 * t195
      t256 = t254 * t255
      t261 = t28 * t180
      t265 = t173 / 0.72e2_dp + t248 * t81 * t249 / 0.3e1_dp - t253 * t256 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t110 * t186 + 0.2e1_dp * t261 * t182 - t113 * t202
      t266 = t265 * t116
      t270 = 0.1e1_dp / t28 / t27
      t271 = t115 * t270
      t272 = t14 * t79
      t273 = t271 * t272
      t279 = (0.10363566666666666667e-1_dp * t208 * t95 + 0.34545222222222222223e-2_dp * t93 &
         * t213 + 0.10363566666666666667e-1_dp * t93 * t216 + 0.51190794422689743247e-1_dp * &
         t222 * t171 * t104 + 0.10238158884537948649e0_dp * t227 * t192 * t195 * t104 - &
         0.20476317769075897299e0_dp * t101 * t81 * t170 * t104 - &
         0.10320064155614252239e-3_dp * t240 * t171 * t242 + 0.44313737677495382697e-2_dp * &
         t266 * t14 + 0.73856229462492304495e-3_dp * t273 * t77 + &
         0.44313737677495382697e-2_dp * t117 * t85) * t44
      t281 = t4 * t171 * t48
      t283 = t68 * t126
      t288 = 0.1e1_dp / t125 / t47
      t289 = t8 * t288
      t290 = t129 * t129
      t296 = t187 - 0.111795e1_dp * t197 + 0.22359e1_dp * t200
      t302 = (t281 / 0.9e1_dp + t73 * t283 * t129 / 0.6e1_dp + t73 * t289 * t290 / 0.2e1_dp - &
         t73 * t127 * t296 / 0.4e1_dp) * t90 * t92
      t305 = t212 * t47
      t308 = t94 * t129
      t311 = t139 * t54
      t313 = 0.1e1_dp / t311 * t1
      t314 = t313 * t3
      t319 = t140 * t189 * t90
      t328 = t139 * t139
      t330 = 0.1e1_dp / t328 / t54
      t331 = t330 * t1
      t332 = t331 * t3
      t333 = t144 * t144
      t334 = 0.1e1_dp / t333
      t339 = t59 * t126
      t340 = t339 * t80
      t341 = t68 * t129
      t345 = t150 * t189
      t350 = t60 * t288
      t354 = t281 / 0.72e2_dp + t340 * t81 * t341 / 0.3e1_dp - t345 * t256 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t151 * t186 + 0.2e1_dp * t350 * t290 - t154 * t296
      t355 = t354 * t157
      t359 = 0.1e1_dp / t60 / t59
      t360 = t156 * t359
      t361 = t47 * t79
      t362 = t360 * t361
      t369 = (0.51817833333333333333e-2_dp * t302 * t136 + 0.17272611111111111111e-2_dp * &
         t135 * t305 + 0.51817833333333333333e-2_dp * t135 * t308 + &
         0.40281109727029913917e-1_dp * t314 * t171 * t145 + 0.80562219454059827833e-1_dp * &
         t319 * t192 * t195 * t145 - 0.16112443890811965567e0_dp * t142 * t81 * t170 * t145 - &
         0.55299776073946902743e-1_dp * t332 * t171 * t334 + 0.26673100072733151594e-2_dp * &
         t355 * t47 + 0.4445516678788858599e-3_dp * t362 * t77 + 0.26673100072733151594e-2_dp &
         * t158 * t129) * t38 * t42
      vrho = t45 + t66 + rho * (t121 + t163)
      v2rho2 = 0.2e1_dp * t121 + 0.2e1_dp * t163 + rho * (t279 + t369)
   end subroutine vwn_rpa_vxc_fxc_unpolar_impl

   pure subroutine vwn_rpa_exc_polar_impl(rho_a, rho_b, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps
      logical :: t38, t45
      real(dp) :: t1, t3, t5, t50, t4, t6, t7, t8
      real(dp) :: t9, t10, t11, t12, t13, t15, t16, t20
      real(dp) :: t22, t25, t27, t28, t29, t31, t33, t34
      real(dp) :: t35, t36, t37, t39, t40, t41, t43, t44
      real(dp) :: t46, t48, t49, t53, t55, t56, t58, t59
      real(dp) :: t63, t65, t68, t70, t71, t73, t75, t77
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t50 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.6536e1_dp * t13 + 0.427198e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t22 = t13 + 0.13072e2_dp
      t25 = atan(0.44899888641287296627e-1_dp / t22)
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.409286e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t33 = 0.310907e-1_dp * t20 + 0.20521972937837502661e2_dp * t25 + &
         0.44313737677495382697e-2_dp * t31
      t34 = rho_a - rho_b
      t35 = 0.1e1_dp / t7
      t36 = t34 * t35
      t37 = 0.1e1_dp + t36
      t38 = t37 <= zeta_tol
      t39 = xc_cbrt(zeta_tol)
      t40 = t39 * zeta_tol
      t41 = xc_cbrt(t37)
      t43 = merge(t40, t41 * t37, t38)
      t44 = 0.1e1_dp - t36
      t45 = t44 <= zeta_tol
      t46 = xc_cbrt(t44)
      t48 = merge(t40, t46 * t44, t45)
      t49 = t43 + t48 - 0.2e1_dp
      t53 = 0.1e1_dp / (0.2e1_dp * t50 - 0.2e1_dp)
      t55 = -t49 * t53 + 0.1e1_dp
      t56 = t33 * t55
      t58 = t12 + 0.1006155e2_dp * t13 + 0.101578e3_dp
      t59 = 0.1e1_dp / t58
      t63 = log(t4 * t10 * t59 / 0.4e1_dp)
      t65 = t13 + 0.201231e2_dp
      t68 = atan(0.11716852777089929792e1_dp / t65)
      t70 = t27 + 0.743294e0_dp
      t71 = t70 * t70
      t73 = log(t71 * t59)
      t75 = 0.1554535e-1_dp * t63 + 0.61881802979060631482e0_dp * t68 + &
         0.26673100072733151594e-2_dp * t73
      t77 = t75 * t49 * t53
      eps = t56 + t77
   end subroutine vwn_rpa_exc_polar_impl

   pure subroutine vwn_rpa_exc_vxc_polar_impl(rho_a, rho_b, eps, vrho_a, vrho_b)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps, vrho_a, vrho_b
      logical :: t38, t45
      real(dp) :: t1, t3, t5, t50, t4, t6, t84, t92
      real(dp) :: t101, t103, t7, t8, t9, t10, t11, t12
      real(dp) :: t13, t15, t16, t20, t22, t25, t27, t28
      real(dp) :: t29, t31, t33, t34, t35, t36, t37, t39
      real(dp) :: t40, t41, t43, t44, t46, t48, t49, t53
      real(dp) :: t55, t56, t58, t59, t63, t65, t68, t70
      real(dp) :: t71, t73, t75, t77, t79, t80, t85, t86
      real(dp) :: t87, t88, t89, t90, t91, t94, t96, t104
      real(dp) :: t105, t106, t109, t110, t112, t114, t115, t120
      real(dp) :: t121, t124, t126, t127, t128, t131, t132, t133
      real(dp) :: t134, t135, t136, t139, t140, t143, t144, t146
      real(dp) :: t150, t151, t152, t154, t160, t161, t164, t165
      real(dp) :: t167, t169, t170, t175, t176, t179, t181, t182
      real(dp) :: t183, t186, t188, t190, t193, t196, t197, t200
      real(dp) :: t201, t203, t205
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t50 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t84 = t4 * t6
      t92 = t3 * t6
      t101 = t1 * t1
      t103 = 0.1e1_dp / t3
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.6536e1_dp * t13 + 0.427198e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t22 = t13 + 0.13072e2_dp
      t25 = atan(0.44899888641287296627e-1_dp / t22)
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.409286e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t33 = 0.310907e-1_dp * t20 + 0.20521972937837502661e2_dp * t25 + &
         0.44313737677495382697e-2_dp * t31
      t34 = rho_a - rho_b
      t35 = 0.1e1_dp / t7
      t36 = t34 * t35
      t37 = 0.1e1_dp + t36
      t38 = t37 <= zeta_tol
      t39 = xc_cbrt(zeta_tol)
      t40 = t39 * zeta_tol
      t41 = xc_cbrt(t37)
      t43 = merge(t40, t41 * t37, t38)
      t44 = 0.1e1_dp - t36
      t45 = t44 <= zeta_tol
      t46 = xc_cbrt(t44)
      t48 = merge(t40, t46 * t44, t45)
      t49 = t43 + t48 - 0.2e1_dp
      t53 = 0.1e1_dp / (0.2e1_dp * t50 - 0.2e1_dp)
      t55 = -t49 * t53 + 0.1e1_dp
      t56 = t33 * t55
      t58 = t12 + 0.1006155e2_dp * t13 + 0.101578e3_dp
      t59 = 0.1e1_dp / t58
      t63 = log(t4 * t10 * t59 / 0.4e1_dp)
      t65 = t13 + 0.201231e2_dp
      t68 = atan(0.11716852777089929792e1_dp / t65)
      t70 = t27 + 0.743294e0_dp
      t71 = t70 * t70
      t73 = log(t71 * t59)
      t75 = 0.1554535e-1_dp * t63 + 0.61881802979060631482e0_dp * t68 + &
         0.26673100072733151594e-2_dp * t73
      t77 = t75 * t49 * t53
      t79 = 0.1e1_dp / t8 / t7
      t80 = t6 * t79
      t85 = t15 * t15
      t86 = 0.1e1_dp / t85
      t87 = t9 * t86
      t88 = t4 * t80
      t89 = t88 / 0.12e2_dp
      t90 = 0.1e1_dp / t13
      t91 = t90 * t1
      t94 = t91 * t92 * t79
      t96 = -t89 - 0.10893333333333333333e1_dp * t94
      t104 = (-t4 * t80 * t16 / 0.12e2_dp - t84 * t87 * t96 / 0.4e1_dp) * t101 * t103
      t105 = t5 * t8
      t106 = t105 * t15
      t109 = t22 * t22
      t110 = 0.1e1_dp / t109
      t112 = t110 * t90 * t1
      t114 = 0.2016e-2_dp * t110 + 0.1e1_dp
      t115 = 0.1e1_dp / t114
      t120 = t28 * t16
      t121 = t120 * t90
      t124 = t29 * t86
      t126 = -t121 * t88 / 0.6e1_dp - t124 * t96
      t127 = 0.1e1_dp / t29
      t128 = t126 * t127
      t131 = 0.10363566666666666667e-1_dp * t104 * t106 + 0.15357238326806922974e0_dp * t112 &
         * t92 * t79 * t115 + 0.44313737677495382697e-2_dp * t128 * t15
      t132 = t131 * t55
      t133 = t7 * t7
      t134 = 0.1e1_dp / t133
      t135 = t34 * t134
      t136 = t35 - t135
      t139 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t41 * t136, t38)
      t140 = -t136
      t143 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t46 * t140, t45)
      t144 = t139 + t143
      t146 = t33 * t144 * t53
      t150 = t58 * t58
      t151 = 0.1e1_dp / t150
      t152 = t9 * t151
      t154 = -t89 - 0.1676925e1_dp * t94
      t160 = (-t4 * t80 * t59 / 0.12e2_dp - t84 * t152 * t154 / 0.4e1_dp) * t101 * t103
      t161 = t105 * t58
      t164 = t65 * t65
      t165 = 0.1e1_dp / t164
      t167 = t165 * t90 * t1
      t169 = 0.137284639e1_dp * t165 + 0.1e1_dp
      t170 = 0.1e1_dp / t169
      t175 = t70 * t59
      t176 = t175 * t90
      t179 = t71 * t151
      t181 = -t176 * t88 / 0.6e1_dp - t179 * t154
      t182 = 0.1e1_dp / t71
      t183 = t181 * t182
      t186 = 0.51817833333333333333e-2_dp * t160 * t161 + 0.12084332918108974175e0_dp * t167 &
         * t92 * t79 * t170 + 0.26673100072733151594e-2_dp * t183 * t58
      t188 = t186 * t49 * t53
      t190 = t75 * t144 * t53
      t193 = -t35 - t135
      t196 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t41 * t193, t38)
      t197 = -t193
      t200 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t46 * t197, t45)
      t201 = t196 + t200
      t203 = t33 * t201 * t53
      t205 = t75 * t201 * t53
      eps = t56 + t77
      vrho_a = t56 + t77 + t7 * (t132 - t146 + t188 + t190)
      vrho_b = t56 + t77 + t7 * (t132 - t203 + t188 + t205)
   end subroutine vwn_rpa_exc_vxc_polar_impl

   pure subroutine vwn_rpa_fxc_polar_impl(rho_a, rho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb
      logical :: t38, t45
      real(dp) :: t1, t3, t5, t50, t4, t6, t84, t92
      real(dp) :: t101, t103, t234, t235, t297, t7, t8, t9
      real(dp) :: t10, t11, t12, t13, t15, t16, t20, t22
      real(dp) :: t25, t27, t28, t29, t31, t33, t34, t35
      real(dp) :: t36, t37, t39, t40, t41, t43, t44, t46
      real(dp) :: t48, t49, t53, t55, t58, t59, t63, t65
      real(dp) :: t68, t70, t71, t73, t75, t79, t80, t85
      real(dp) :: t86, t87, t88, t89, t90, t91, t94, t96
      real(dp) :: t104, t105, t106, t109, t110, t112, t114, t115
      real(dp) :: t120, t121, t124, t126, t127, t128, t131, t132
      real(dp) :: t133, t134, t135, t136, t139, t140, t143, t144
      real(dp) :: t146, t150, t151, t152, t154, t160, t161, t164
      real(dp) :: t165, t167, t169, t170, t175, t176, t179, t181
      real(dp) :: t182, t183, t186, t188, t190, t193, t196, t197
      real(dp) :: t200, t201, t203, t205, t208, t210, t213, t214
      real(dp) :: t216, t218, t223, t224, t225, t229, t230, t232
      real(dp) :: t233, t236, t238, t240, t243, t245, t251, t255
      real(dp) :: t256, t259, t262, t263, t264, t265, t270, t279
      real(dp) :: t281, t282, t283, t284, t285, t290, t291, t292
      real(dp) :: t296, t298, t299, t304, t308, t309, t313, t314
      real(dp) :: t315, t316, t321, t322, t324, t325, t326, t327
      real(dp) :: t328, t331, t332, t333, t335, t339, t340, t341
      real(dp) :: t342, t345, t349, t350, t352, t354, t356, t361
      real(dp) :: t362, t363, t369, t375, t378, t381, t384, t385
      real(dp) :: t386, t387, t392, t401, t403, t404, t405, t406
      real(dp) :: t407, t412, t413, t414, t418, t423, t427, t428
      real(dp) :: t432, t433, t434, t435, t440, t442, t444, t445
      real(dp) :: t447, t451, t452, t455, t459, t460, t463, t467
      real(dp) :: t468, t470, t472, t474, t479, t480, t484, t488
      real(dp) :: t489, t492, t496, t497, t499, t500, t502
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t50 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t84 = t4 * t6
      t92 = t3 * t6
      t101 = t1 * t1
      t103 = 0.1e1_dp / t3
      t234 = t3 * t3
      t235 = t234 * t5
      t297 = t101 * t234
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.6536e1_dp * t13 + 0.427198e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t22 = t13 + 0.13072e2_dp
      t25 = atan(0.44899888641287296627e-1_dp / t22)
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.409286e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t33 = 0.310907e-1_dp * t20 + 0.20521972937837502661e2_dp * t25 + &
         0.44313737677495382697e-2_dp * t31
      t34 = rho_a - rho_b
      t35 = 0.1e1_dp / t7
      t36 = t34 * t35
      t37 = 0.1e1_dp + t36
      t38 = t37 <= zeta_tol
      t39 = xc_cbrt(zeta_tol)
      t40 = t39 * zeta_tol
      t41 = xc_cbrt(t37)
      t43 = merge(t40, t41 * t37, t38)
      t44 = 0.1e1_dp - t36
      t45 = t44 <= zeta_tol
      t46 = xc_cbrt(t44)
      t48 = merge(t40, t46 * t44, t45)
      t49 = t43 + t48 - 0.2e1_dp
      t53 = 0.1e1_dp / (0.2e1_dp * t50 - 0.2e1_dp)
      t55 = -t49 * t53 + 0.1e1_dp
      t58 = t12 + 0.1006155e2_dp * t13 + 0.101578e3_dp
      t59 = 0.1e1_dp / t58
      t63 = log(t4 * t10 * t59 / 0.4e1_dp)
      t65 = t13 + 0.201231e2_dp
      t68 = atan(0.11716852777089929792e1_dp / t65)
      t70 = t27 + 0.743294e0_dp
      t71 = t70 * t70
      t73 = log(t71 * t59)
      t75 = 0.1554535e-1_dp * t63 + 0.61881802979060631482e0_dp * t68 + &
         0.26673100072733151594e-2_dp * t73
      t79 = 0.1e1_dp / t8 / t7
      t80 = t6 * t79
      t85 = t15 * t15
      t86 = 0.1e1_dp / t85
      t87 = t9 * t86
      t88 = t4 * t80
      t89 = t88 / 0.12e2_dp
      t90 = 0.1e1_dp / t13
      t91 = t90 * t1
      t94 = t91 * t92 * t79
      t96 = -t89 - 0.10893333333333333333e1_dp * t94
      t104 = (-t4 * t80 * t16 / 0.12e2_dp - t84 * t87 * t96 / 0.4e1_dp) * t101 * t103
      t105 = t5 * t8
      t106 = t105 * t15
      t109 = t22 * t22
      t110 = 0.1e1_dp / t109
      t112 = t110 * t90 * t1
      t114 = 0.2016e-2_dp * t110 + 0.1e1_dp
      t115 = 0.1e1_dp / t114
      t120 = t28 * t16
      t121 = t120 * t90
      t124 = t29 * t86
      t126 = -t121 * t88 / 0.6e1_dp - t124 * t96
      t127 = 0.1e1_dp / t29
      t128 = t126 * t127
      t131 = 0.10363566666666666667e-1_dp * t104 * t106 + 0.15357238326806922974e0_dp * t112 &
         * t92 * t79 * t115 + 0.44313737677495382697e-2_dp * t128 * t15
      t132 = t131 * t55
      t133 = t7 * t7
      t134 = 0.1e1_dp / t133
      t135 = t34 * t134
      t136 = t35 - t135
      t139 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t41 * t136, t38)
      t140 = -t136
      t143 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t46 * t140, t45)
      t144 = t139 + t143
      t146 = t33 * t144 * t53
      t150 = t58 * t58
      t151 = 0.1e1_dp / t150
      t152 = t9 * t151
      t154 = -t89 - 0.1676925e1_dp * t94
      t160 = (-t4 * t80 * t59 / 0.12e2_dp - t84 * t152 * t154 / 0.4e1_dp) * t101 * t103
      t161 = t105 * t58
      t164 = t65 * t65
      t165 = 0.1e1_dp / t164
      t167 = t165 * t90 * t1
      t169 = 0.137284639e1_dp * t165 + 0.1e1_dp
      t170 = 0.1e1_dp / t169
      t175 = t70 * t59
      t176 = t175 * t90
      t179 = t71 * t151
      t181 = -t176 * t88 / 0.6e1_dp - t179 * t154
      t182 = 0.1e1_dp / t71
      t183 = t181 * t182
      t186 = 0.51817833333333333333e-2_dp * t160 * t161 + 0.12084332918108974175e0_dp * t167 &
         * t92 * t79 * t170 + 0.26673100072733151594e-2_dp * t183 * t58
      t188 = t186 * t49 * t53
      t190 = t75 * t144 * t53
      t193 = -t35 - t135
      t196 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t41 * t193, t38)
      t197 = -t193
      t200 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t46 * t197, t45)
      t201 = t196 + t200
      t203 = t33 * t201 * t53
      t205 = t75 * t201 * t53
      t208 = 0.2e1_dp * t132
      t210 = 0.2e1_dp * t188
      t213 = 0.1e1_dp / t8 / t133
      t214 = t6 * t213
      t216 = t4 * t214 * t16
      t218 = t79 * t86
      t223 = 0.1e1_dp / t85 / t15
      t224 = t9 * t223
      t225 = t96 * t96
      t229 = t4 * t214
      t230 = t229 / 0.9e1_dp
      t232 = 0.1e1_dp / t13 / t11
      t233 = t232 * t101
      t236 = t8 * t8
      t238 = 0.1e1_dp / t236 / t133
      t240 = t233 * t235 * t238
      t243 = t91 * t92 * t213
      t245 = t230 - 0.7262222222222222222e0_dp * t240 + 0.14524444444444444444e1_dp * t243
      t251 = (t216 / 0.9e1_dp + t84 * t218 * t96 / 0.6e1_dp + t84 * t224 * t225 / 0.2e1_dp - &
         t84 * t87 * t245 / 0.4e1_dp) * t101 * t103
      t255 = t5 / t236
      t256 = t255 * t15
      t259 = t105 * t96
      t262 = t109 * t22
      t263 = 0.1e1_dp / t262
      t264 = t263 * t1
      t265 = t264 * t3
      t270 = t110 * t232 * t101
      t279 = t109 * t109
      t281 = 0.1e1_dp / t279 / t22
      t282 = t281 * t1
      t283 = t282 * t3
      t284 = t114 * t114
      t285 = 0.1e1_dp / t284
      t290 = t28 * t86
      t291 = t290 * t91
      t292 = t79 * t96
      t296 = t120 * t232
      t298 = t5 * t238
      t299 = t297 * t298
      t304 = t29 * t223
      t308 = t216 / 0.72e2_dp + t291 * t92 * t292 / 0.3e1_dp - t296 * t299 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t121 * t229 + 0.2e1_dp * t304 * t225 - t124 * t245
      t309 = t308 * t127
      t313 = 0.1e1_dp / t29 / t28
      t314 = t126 * t313
      t315 = t15 * t90
      t316 = t314 * t315
      t321 = 0.10363566666666666667e-1_dp * t251 * t106 + 0.34545222222222222223e-2_dp * t104 &
         * t256 + 0.10363566666666666667e-1_dp * t104 * t259 + 0.51190794422689743247e-1_dp * &
         t265 * t214 * t115 + 0.10238158884537948649e0_dp * t270 * t235 * t238 * t115 - &
         0.20476317769075897299e0_dp * t112 * t92 * t213 * t115 - &
         0.10320064155614252239e-3_dp * t283 * t214 * t285 + 0.44313737677495382697e-2_dp * &
         t309 * t15 + 0.73856229462492304495e-3_dp * t316 * t88 + &
         0.44313737677495382697e-2_dp * t128 * t96
      t322 = t321 * t55
      t324 = t131 * t144 * t53
      t325 = 0.2e1_dp * t324
      t326 = t41 * t41
      t327 = 0.1e1_dp / t326
      t328 = t136 * t136
      t331 = t133 * t7
      t332 = 0.1e1_dp / t331
      t333 = t34 * t332
      t335 = -0.2e1_dp * t134 + 0.2e1_dp * t333
      t339 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t327 * t328 + 0.4e1_dp / 0.3e1_dp * t41 * &
         t335, t38)
      t340 = t46 * t46
      t341 = 0.1e1_dp / t340
      t342 = t140 * t140
      t345 = -t335
      t349 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t341 * t342 + 0.4e1_dp / 0.3e1_dp * t46 * &
         t345, t45)
      t350 = t339 + t349
      t352 = t33 * t350 * t53
      t354 = t4 * t214 * t59
      t356 = t79 * t151
      t361 = 0.1e1_dp / t150 / t58
      t362 = t9 * t361
      t363 = t154 * t154
      t369 = t230 - 0.111795e1_dp * t240 + 0.22359e1_dp * t243
      t375 = (t354 / 0.9e1_dp + t84 * t356 * t154 / 0.6e1_dp + t84 * t362 * t363 / 0.2e1_dp - &
         t84 * t152 * t369 / 0.4e1_dp) * t101 * t103
      t378 = t255 * t58
      t381 = t105 * t154
      t384 = t164 * t65
      t385 = 0.1e1_dp / t384
      t386 = t385 * t1
      t387 = t386 * t3
      t392 = t165 * t232 * t101
      t401 = t164 * t164
      t403 = 0.1e1_dp / t401 / t65
      t404 = t403 * t1
      t405 = t404 * t3
      t406 = t169 * t169
      t407 = 0.1e1_dp / t406
      t412 = t70 * t151
      t413 = t412 * t91
      t414 = t79 * t154
      t418 = t175 * t232
      t423 = t71 * t361
      t427 = t354 / 0.72e2_dp + t413 * t92 * t414 / 0.3e1_dp - t418 * t299 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t176 * t229 + 0.2e1_dp * t423 * t363 - t179 * t369
      t428 = t427 * t182
      t432 = 0.1e1_dp / t71 / t70
      t433 = t181 * t432
      t434 = t58 * t90
      t435 = t433 * t434
      t440 = 0.51817833333333333333e-2_dp * t375 * t161 + 0.17272611111111111111e-2_dp * t160 &
         * t378 + 0.51817833333333333333e-2_dp * t160 * t381 + 0.40281109727029913917e-1_dp * &
         t387 * t214 * t170 + 0.80562219454059827833e-1_dp * t392 * t235 * t238 * t170 - &
         0.16112443890811965567e0_dp * t167 * t92 * t213 * t170 - &
         0.55299776073946902743e-1_dp * t405 * t214 * t407 + 0.26673100072733151594e-2_dp * &
         t428 * t58 + 0.4445516678788858599e-3_dp * t435 * t88 + 0.26673100072733151594e-2_dp &
         * t183 * t154
      t442 = t440 * t49 * t53
      t444 = t186 * t144 * t53
      t445 = 0.2e1_dp * t444
      t447 = t75 * t350 * t53
      t451 = t131 * t201 * t53
      t452 = t327 * t193
      t455 = t41 * t34
      t459 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t452 * t136 + 0.8e1_dp / 0.3e1_dp * t455 * &
         t332, t38)
      t460 = t341 * t197
      t463 = t46 * t34
      t467 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t460 * t140 - 0.8e1_dp / 0.3e1_dp * t463 * &
         t332, t45)
      t468 = t459 + t467
      t470 = t33 * t468 * t53
      t472 = t186 * t201 * t53
      t474 = t75 * t468 * t53
      t479 = 0.2e1_dp * t451
      t480 = t193 * t193
      t484 = 0.2e1_dp * t134 + 0.2e1_dp * t333
      t488 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t327 * t480 + 0.4e1_dp / 0.3e1_dp * t41 * &
         t484, t38)
      t489 = t197 * t197
      t492 = -t484
      t496 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t341 * t489 + 0.4e1_dp / 0.3e1_dp * t46 * &
         t492, t45)
      t497 = t488 + t496
      t499 = t33 * t497 * t53
      t500 = 0.2e1_dp * t472
      t502 = t75 * t497 * t53
      v2rho2_aa = t208 - 0.2e1_dp * t146 + t210 + 0.2e1_dp * t190 + t7 * (t322 - t325 - t352 &
         + t442 + t445 + t447)
      v2rho2_ab = t208 - t146 + t210 + t190 - t203 + t205 + t7 * (t322 - t324 - t451 - t470 + &
         t442 + t444 + t472 + t474)
      v2rho2_bb = t208 - 0.2e1_dp * t203 + t210 + 0.2e1_dp * t205 + t7 * (t322 - t479 - t499 &
         + t442 + t500 + t502)
   end subroutine vwn_rpa_fxc_polar_impl

   pure subroutine vwn_rpa_vxc_fxc_polar_impl(rho_a, rho_b, vrho_a, vrho_b, v2rho2_aa, &
      v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb
      logical :: t38, t45
      real(dp) :: t1, t3, t5, t50, t4, t6, t84, t92
      real(dp) :: t101, t103, t234, t235, t297, t7, t8, t9
      real(dp) :: t10, t11, t12, t13, t15, t16, t20, t22
      real(dp) :: t25, t27, t28, t29, t31, t33, t34, t35
      real(dp) :: t36, t37, t39, t40, t41, t43, t44, t46
      real(dp) :: t48, t49, t53, t55, t56, t58, t59, t63
      real(dp) :: t65, t68, t70, t71, t73, t75, t77, t79
      real(dp) :: t80, t85, t86, t87, t88, t89, t90, t91
      real(dp) :: t94, t96, t104, t105, t106, t109, t110, t112
      real(dp) :: t114, t115, t120, t121, t124, t126, t127, t128
      real(dp) :: t131, t132, t133, t134, t135, t136, t139, t140
      real(dp) :: t143, t144, t146, t150, t151, t152, t154, t160
      real(dp) :: t161, t164, t165, t167, t169, t170, t175, t176
      real(dp) :: t179, t181, t182, t183, t186, t188, t190, t193
      real(dp) :: t196, t197, t200, t201, t203, t205, t208, t210
      real(dp) :: t213, t214, t216, t218, t223, t224, t225, t229
      real(dp) :: t230, t232, t233, t236, t238, t240, t243, t245
      real(dp) :: t251, t255, t256, t259, t262, t263, t264, t265
      real(dp) :: t270, t279, t281, t282, t283, t284, t285, t290
      real(dp) :: t291, t292, t296, t298, t299, t304, t308, t309
      real(dp) :: t313, t314, t315, t316, t321, t322, t324, t325
      real(dp) :: t326, t327, t328, t331, t332, t333, t335, t339
      real(dp) :: t340, t341, t342, t345, t349, t350, t352, t354
      real(dp) :: t356, t361, t362, t363, t369, t375, t378, t381
      real(dp) :: t384, t385, t386, t387, t392, t401, t403, t404
      real(dp) :: t405, t406, t407, t412, t413, t414, t418, t423
      real(dp) :: t427, t428, t432, t433, t434, t435, t440, t442
      real(dp) :: t444, t445, t447, t451, t452, t455, t459, t460
      real(dp) :: t463, t467, t468, t470, t472, t474, t479, t480
      real(dp) :: t484, t488, t489, t492, t496, t497, t499, t500
      real(dp) :: t502
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t50 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t84 = t4 * t6
      t92 = t3 * t6
      t101 = t1 * t1
      t103 = 0.1e1_dp / t3
      t234 = t3 * t3
      t235 = t234 * t5
      t297 = t101 * t234
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.6536e1_dp * t13 + 0.427198e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t22 = t13 + 0.13072e2_dp
      t25 = atan(0.44899888641287296627e-1_dp / t22)
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.409286e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t33 = 0.310907e-1_dp * t20 + 0.20521972937837502661e2_dp * t25 + &
         0.44313737677495382697e-2_dp * t31
      t34 = rho_a - rho_b
      t35 = 0.1e1_dp / t7
      t36 = t34 * t35
      t37 = 0.1e1_dp + t36
      t38 = t37 <= zeta_tol
      t39 = xc_cbrt(zeta_tol)
      t40 = t39 * zeta_tol
      t41 = xc_cbrt(t37)
      t43 = merge(t40, t41 * t37, t38)
      t44 = 0.1e1_dp - t36
      t45 = t44 <= zeta_tol
      t46 = xc_cbrt(t44)
      t48 = merge(t40, t46 * t44, t45)
      t49 = t43 + t48 - 0.2e1_dp
      t53 = 0.1e1_dp / (0.2e1_dp * t50 - 0.2e1_dp)
      t55 = -t49 * t53 + 0.1e1_dp
      t56 = t33 * t55
      t58 = t12 + 0.1006155e2_dp * t13 + 0.101578e3_dp
      t59 = 0.1e1_dp / t58
      t63 = log(t4 * t10 * t59 / 0.4e1_dp)
      t65 = t13 + 0.201231e2_dp
      t68 = atan(0.11716852777089929792e1_dp / t65)
      t70 = t27 + 0.743294e0_dp
      t71 = t70 * t70
      t73 = log(t71 * t59)
      t75 = 0.1554535e-1_dp * t63 + 0.61881802979060631482e0_dp * t68 + &
         0.26673100072733151594e-2_dp * t73
      t77 = t75 * t49 * t53
      t79 = 0.1e1_dp / t8 / t7
      t80 = t6 * t79
      t85 = t15 * t15
      t86 = 0.1e1_dp / t85
      t87 = t9 * t86
      t88 = t4 * t80
      t89 = t88 / 0.12e2_dp
      t90 = 0.1e1_dp / t13
      t91 = t90 * t1
      t94 = t91 * t92 * t79
      t96 = -t89 - 0.10893333333333333333e1_dp * t94
      t104 = (-t4 * t80 * t16 / 0.12e2_dp - t84 * t87 * t96 / 0.4e1_dp) * t101 * t103
      t105 = t5 * t8
      t106 = t105 * t15
      t109 = t22 * t22
      t110 = 0.1e1_dp / t109
      t112 = t110 * t90 * t1
      t114 = 0.2016e-2_dp * t110 + 0.1e1_dp
      t115 = 0.1e1_dp / t114
      t120 = t28 * t16
      t121 = t120 * t90
      t124 = t29 * t86
      t126 = -t121 * t88 / 0.6e1_dp - t124 * t96
      t127 = 0.1e1_dp / t29
      t128 = t126 * t127
      t131 = 0.10363566666666666667e-1_dp * t104 * t106 + 0.15357238326806922974e0_dp * t112 &
         * t92 * t79 * t115 + 0.44313737677495382697e-2_dp * t128 * t15
      t132 = t131 * t55
      t133 = t7 * t7
      t134 = 0.1e1_dp / t133
      t135 = t34 * t134
      t136 = t35 - t135
      t139 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t41 * t136, t38)
      t140 = -t136
      t143 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t46 * t140, t45)
      t144 = t139 + t143
      t146 = t33 * t144 * t53
      t150 = t58 * t58
      t151 = 0.1e1_dp / t150
      t152 = t9 * t151
      t154 = -t89 - 0.1676925e1_dp * t94
      t160 = (-t4 * t80 * t59 / 0.12e2_dp - t84 * t152 * t154 / 0.4e1_dp) * t101 * t103
      t161 = t105 * t58
      t164 = t65 * t65
      t165 = 0.1e1_dp / t164
      t167 = t165 * t90 * t1
      t169 = 0.137284639e1_dp * t165 + 0.1e1_dp
      t170 = 0.1e1_dp / t169
      t175 = t70 * t59
      t176 = t175 * t90
      t179 = t71 * t151
      t181 = -t176 * t88 / 0.6e1_dp - t179 * t154
      t182 = 0.1e1_dp / t71
      t183 = t181 * t182
      t186 = 0.51817833333333333333e-2_dp * t160 * t161 + 0.12084332918108974175e0_dp * t167 &
         * t92 * t79 * t170 + 0.26673100072733151594e-2_dp * t183 * t58
      t188 = t186 * t49 * t53
      t190 = t75 * t144 * t53
      t193 = -t35 - t135
      t196 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t41 * t193, t38)
      t197 = -t193
      t200 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t46 * t197, t45)
      t201 = t196 + t200
      t203 = t33 * t201 * t53
      t205 = t75 * t201 * t53
      t208 = 0.2e1_dp * t132
      t210 = 0.2e1_dp * t188
      t213 = 0.1e1_dp / t8 / t133
      t214 = t6 * t213
      t216 = t4 * t214 * t16
      t218 = t79 * t86
      t223 = 0.1e1_dp / t85 / t15
      t224 = t9 * t223
      t225 = t96 * t96
      t229 = t4 * t214
      t230 = t229 / 0.9e1_dp
      t232 = 0.1e1_dp / t13 / t11
      t233 = t232 * t101
      t236 = t8 * t8
      t238 = 0.1e1_dp / t236 / t133
      t240 = t233 * t235 * t238
      t243 = t91 * t92 * t213
      t245 = t230 - 0.7262222222222222222e0_dp * t240 + 0.14524444444444444444e1_dp * t243
      t251 = (t216 / 0.9e1_dp + t84 * t218 * t96 / 0.6e1_dp + t84 * t224 * t225 / 0.2e1_dp - &
         t84 * t87 * t245 / 0.4e1_dp) * t101 * t103
      t255 = t5 / t236
      t256 = t255 * t15
      t259 = t105 * t96
      t262 = t109 * t22
      t263 = 0.1e1_dp / t262
      t264 = t263 * t1
      t265 = t264 * t3
      t270 = t110 * t232 * t101
      t279 = t109 * t109
      t281 = 0.1e1_dp / t279 / t22
      t282 = t281 * t1
      t283 = t282 * t3
      t284 = t114 * t114
      t285 = 0.1e1_dp / t284
      t290 = t28 * t86
      t291 = t290 * t91
      t292 = t79 * t96
      t296 = t120 * t232
      t298 = t5 * t238
      t299 = t297 * t298
      t304 = t29 * t223
      t308 = t216 / 0.72e2_dp + t291 * t92 * t292 / 0.3e1_dp - t296 * t299 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t121 * t229 + 0.2e1_dp * t304 * t225 - t124 * t245
      t309 = t308 * t127
      t313 = 0.1e1_dp / t29 / t28
      t314 = t126 * t313
      t315 = t15 * t90
      t316 = t314 * t315
      t321 = 0.10363566666666666667e-1_dp * t251 * t106 + 0.34545222222222222223e-2_dp * t104 &
         * t256 + 0.10363566666666666667e-1_dp * t104 * t259 + 0.51190794422689743247e-1_dp * &
         t265 * t214 * t115 + 0.10238158884537948649e0_dp * t270 * t235 * t238 * t115 - &
         0.20476317769075897299e0_dp * t112 * t92 * t213 * t115 - &
         0.10320064155614252239e-3_dp * t283 * t214 * t285 + 0.44313737677495382697e-2_dp * &
         t309 * t15 + 0.73856229462492304495e-3_dp * t316 * t88 + &
         0.44313737677495382697e-2_dp * t128 * t96
      t322 = t321 * t55
      t324 = t131 * t144 * t53
      t325 = 0.2e1_dp * t324
      t326 = t41 * t41
      t327 = 0.1e1_dp / t326
      t328 = t136 * t136
      t331 = t133 * t7
      t332 = 0.1e1_dp / t331
      t333 = t34 * t332
      t335 = -0.2e1_dp * t134 + 0.2e1_dp * t333
      t339 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t327 * t328 + 0.4e1_dp / 0.3e1_dp * t41 * &
         t335, t38)
      t340 = t46 * t46
      t341 = 0.1e1_dp / t340
      t342 = t140 * t140
      t345 = -t335
      t349 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t341 * t342 + 0.4e1_dp / 0.3e1_dp * t46 * &
         t345, t45)
      t350 = t339 + t349
      t352 = t33 * t350 * t53
      t354 = t4 * t214 * t59
      t356 = t79 * t151
      t361 = 0.1e1_dp / t150 / t58
      t362 = t9 * t361
      t363 = t154 * t154
      t369 = t230 - 0.111795e1_dp * t240 + 0.22359e1_dp * t243
      t375 = (t354 / 0.9e1_dp + t84 * t356 * t154 / 0.6e1_dp + t84 * t362 * t363 / 0.2e1_dp - &
         t84 * t152 * t369 / 0.4e1_dp) * t101 * t103
      t378 = t255 * t58
      t381 = t105 * t154
      t384 = t164 * t65
      t385 = 0.1e1_dp / t384
      t386 = t385 * t1
      t387 = t386 * t3
      t392 = t165 * t232 * t101
      t401 = t164 * t164
      t403 = 0.1e1_dp / t401 / t65
      t404 = t403 * t1
      t405 = t404 * t3
      t406 = t169 * t169
      t407 = 0.1e1_dp / t406
      t412 = t70 * t151
      t413 = t412 * t91
      t414 = t79 * t154
      t418 = t175 * t232
      t423 = t71 * t361
      t427 = t354 / 0.72e2_dp + t413 * t92 * t414 / 0.3e1_dp - t418 * t299 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t176 * t229 + 0.2e1_dp * t423 * t363 - t179 * t369
      t428 = t427 * t182
      t432 = 0.1e1_dp / t71 / t70
      t433 = t181 * t432
      t434 = t58 * t90
      t435 = t433 * t434
      t440 = 0.51817833333333333333e-2_dp * t375 * t161 + 0.17272611111111111111e-2_dp * t160 &
         * t378 + 0.51817833333333333333e-2_dp * t160 * t381 + 0.40281109727029913917e-1_dp * &
         t387 * t214 * t170 + 0.80562219454059827833e-1_dp * t392 * t235 * t238 * t170 - &
         0.16112443890811965567e0_dp * t167 * t92 * t213 * t170 - &
         0.55299776073946902743e-1_dp * t405 * t214 * t407 + 0.26673100072733151594e-2_dp * &
         t428 * t58 + 0.4445516678788858599e-3_dp * t435 * t88 + 0.26673100072733151594e-2_dp &
         * t183 * t154
      t442 = t440 * t49 * t53
      t444 = t186 * t144 * t53
      t445 = 0.2e1_dp * t444
      t447 = t75 * t350 * t53
      t451 = t131 * t201 * t53
      t452 = t327 * t193
      t455 = t41 * t34
      t459 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t452 * t136 + 0.8e1_dp / 0.3e1_dp * t455 * &
         t332, t38)
      t460 = t341 * t197
      t463 = t46 * t34
      t467 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t460 * t140 - 0.8e1_dp / 0.3e1_dp * t463 * &
         t332, t45)
      t468 = t459 + t467
      t470 = t33 * t468 * t53
      t472 = t186 * t201 * t53
      t474 = t75 * t468 * t53
      t479 = 0.2e1_dp * t451
      t480 = t193 * t193
      t484 = 0.2e1_dp * t134 + 0.2e1_dp * t333
      t488 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t327 * t480 + 0.4e1_dp / 0.3e1_dp * t41 * &
         t484, t38)
      t489 = t197 * t197
      t492 = -t484
      t496 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t341 * t489 + 0.4e1_dp / 0.3e1_dp * t46 * &
         t492, t45)
      t497 = t488 + t496
      t499 = t33 * t497 * t53
      t500 = 0.2e1_dp * t472
      t502 = t75 * t497 * t53
      vrho_a = t56 + t77 + t7 * (t132 - t146 + t188 + t190)
      vrho_b = t56 + t77 + t7 * (t132 - t203 + t188 + t205)
      v2rho2_aa = t208 - 0.2e1_dp * t146 + t210 + 0.2e1_dp * t190 + t7 * (t322 - t325 - t352 &
         + t442 + t445 + t447)
      v2rho2_ab = t208 - t146 + t210 + t190 - t203 + t205 + t7 * (t322 - t324 - t451 - t470 + &
         t442 + t444 + t472 + t474)
      v2rho2_bb = t208 - 0.2e1_dp * t203 + t210 + 0.2e1_dp * t205 + t7 * (t322 - t479 - t499 &
         + t442 + t500 + t502)
   end subroutine vwn_rpa_vxc_fxc_polar_impl

end module trc_xc_vwn_rpa
