!
! VWN: LDA exchange-correlation kernel.
!
! GENERATED by tools/exchcxx_to_fortran.py from ExchCXX's
! include/exchcxx/impl/builtin/kernels/vwn.hpp -- do not edit.
!
! The arithmetic is ExchCXX's (MIT; Copyright (c) 2020-2024, The Regents
! of the University of California, through Lawrence Berkeley National
! Laboratory; portions Copyright (c) Microsoft Corporation), itself
! generated by Maple from the functional's definition. See
! https://github.com/wavefunction91/ExchCXX.
!
! Every routine is scalar, pure, and callable from `do concurrent`.
! The public `<name>_<what>_<polar>` routines apply the density and
! gradient thresholds the way ExchCXX's screening_interface.hpp does;
! the `_impl` bodies below them are the bare Maple expressions.
!
! Unpolarised routines take the TOTAL density and its gradient
! invariant; polarised ones take the two spin densities and the three
! gradient invariants. `eps` is the energy per particle, so the
! integrand is rho * eps.
!
module trc_xc_vwn
   use trc_boys, only: dp
   use trc_xc_util, only: m_cbrt_2, m_cbrt_3, m_cbrt_4, m_cbrt_one_ov_pi, m_pi_sq, xc_cbrt
   implicit none
   private

   public :: vwn_exc_unpolar
   public :: vwn_exc_vxc_unpolar
   public :: vwn_fxc_unpolar
   public :: vwn_vxc_fxc_unpolar
   public :: vwn_exc_polar
   public :: vwn_exc_vxc_polar
   public :: vwn_fxc_polar
   public :: vwn_vxc_fxc_polar

   real(dp), parameter :: dens_tol = 1e-15_dp
   real(dp), parameter :: zeta_tol = 1e-15_dp
   real(dp), parameter :: sigma_tol = 1.0000000000000027e-20_dp
   real(dp), parameter :: tau_tol = 1e-20_dp

contains

   pure subroutine vwn_exc_unpolar(rho, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps
      real(dp) :: rho_c
      eps = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_exc_unpolar_impl(rho_c, eps)
      end if
   end subroutine vwn_exc_unpolar

   pure subroutine vwn_exc_vxc_unpolar(rho, eps, vrho)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps, vrho
      real(dp) :: rho_c
      eps = 0.0_dp
      vrho = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_exc_vxc_unpolar_impl(rho_c, eps, vrho)
      end if
   end subroutine vwn_exc_vxc_unpolar

   pure subroutine vwn_fxc_unpolar(rho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: v2rho2
      real(dp) :: rho_c
      v2rho2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_fxc_unpolar_impl(rho_c, v2rho2)
      end if
   end subroutine vwn_fxc_unpolar

   pure subroutine vwn_vxc_fxc_unpolar(rho, vrho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: vrho, v2rho2
      real(dp) :: rho_c
      vrho = 0.0_dp
      v2rho2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call vwn_vxc_fxc_unpolar_impl(rho_c, vrho, v2rho2)
      end if
   end subroutine vwn_vxc_fxc_unpolar

   pure subroutine vwn_exc_polar(rho_a, rho_b, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps
      real(dp) :: rho_a_c, rho_b_c
      eps = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_exc_polar_impl(rho_a_c, rho_b_c, eps)
      end if
   end subroutine vwn_exc_polar

   pure subroutine vwn_exc_vxc_polar(rho_a, rho_b, eps, vrho_a, vrho_b)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps, vrho_a, vrho_b
      real(dp) :: rho_a_c, rho_b_c
      eps = 0.0_dp
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_exc_vxc_polar_impl(rho_a_c, rho_b_c, eps, vrho_a, vrho_b)
      end if
   end subroutine vwn_exc_vxc_polar

   pure subroutine vwn_fxc_polar(rho_a, rho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb
      real(dp) :: rho_a_c, rho_b_c
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_fxc_polar_impl(rho_a_c, rho_b_c, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      end if
   end subroutine vwn_fxc_polar

   pure subroutine vwn_vxc_fxc_polar(rho_a, rho_b, vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, &
      v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb
      real(dp) :: rho_a_c, rho_b_c
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call vwn_vxc_fxc_polar_impl(rho_a_c, rho_b_c, vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, &
            v2rho2_bb)
      end if
   end subroutine vwn_vxc_fxc_polar

   pure subroutine vwn_exc_unpolar_impl(rho, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps
      real(dp) :: t1, t3, t5, t32, t4, t6, t33, t7
      real(dp) :: t8, t9, t10, t11, t12, t14, t15, t19
      real(dp) :: t20, t21, t24, t25, t26, t27, t28, t30
      real(dp) :: t31, t35, t36, t40, t41, t44, t46, t47
      real(dp) :: t49, t54, t56, t65, t67
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t32 = m_pi_sq
      t4 = t1 * t3
      t6 = t5 * t5
      t33 = 0.1e1_dp / t32
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.186372e1_dp * t12 + 0.129352e2_dp
      t15 = 0.1e1_dp / t14
      t19 = log(t4 * t9 * t15 / 0.4e1_dp)
      t20 = 0.310907e-1_dp * t19
      t21 = t12 + 0.372744e1_dp
      t24 = atan(0.61519908197590802322e1_dp / t21)
      t25 = 0.38783294878113014393e-1_dp * t24
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.10498e0_dp
      t28 = t27 * t27
      t30 = log(t28 * t15)
      t31 = 0.96902277115443742139e-3_dp * t30
      t35 = t11 + 0.565535e0_dp * t12 + 0.130045e2_dp
      t36 = 0.1e1_dp / t35
      t40 = log(t4 * t9 * t36 / 0.4e1_dp)
      t41 = t12 + 0.113107e1_dp
      t44 = atan(0.71231089178181179908e1_dp / t41)
      t46 = t26 + 0.47584e-2_dp
      t47 = t46 * t46
      t49 = log(t47 * t36)
      t54 = xc_cbrt(zeta_tol)
      t56 = merge(t54 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t65 = 0.9e1_dp * t56 - 0.9e1_dp
      t67 = t33 * (t40 + 0.317708004743941464e0_dp * t44 + 0.41403379428206274608e-3_dp * &
         t49) * t65 / 0.24e2_dp
      eps = t20 + t25 + t31 - t67
   end subroutine vwn_exc_unpolar_impl

   pure subroutine vwn_exc_vxc_unpolar_impl(rho, eps, vrho)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps, vrho
      real(dp) :: t1, t3, t5, t32, t4, t6, t33, t74
      real(dp) :: t82, t91, t93, t7, t8, t9, t10, t11
      real(dp) :: t12, t14, t15, t19, t20, t21, t24, t25
      real(dp) :: t26, t27, t28, t30, t31, t35, t36, t40
      real(dp) :: t41, t44, t46, t47, t49, t54, t56, t65
      real(dp) :: t67, t69, t70, t75, t76, t77, t78, t79
      real(dp) :: t80, t81, t84, t86, t94, t95, t96, t97
      real(dp) :: t99, t100, t102, t104, t105, t108, t110, t111
      real(dp) :: t114, t116, t117, t118, t119, t124, t125, t126
      real(dp) :: t128, t134, t135, t138, t139, t141, t143, t144
      real(dp) :: t149, t150, t153, t155, t156, t157, t162
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t32 = m_pi_sq
      t4 = t1 * t3
      t6 = t5 * t5
      t33 = 0.1e1_dp / t32
      t74 = t4 * t6
      t82 = t3 * t6
      t91 = t1 * t1
      t93 = 0.1e1_dp / t3
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.186372e1_dp * t12 + 0.129352e2_dp
      t15 = 0.1e1_dp / t14
      t19 = log(t4 * t9 * t15 / 0.4e1_dp)
      t20 = 0.310907e-1_dp * t19
      t21 = t12 + 0.372744e1_dp
      t24 = atan(0.61519908197590802322e1_dp / t21)
      t25 = 0.38783294878113014393e-1_dp * t24
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.10498e0_dp
      t28 = t27 * t27
      t30 = log(t28 * t15)
      t31 = 0.96902277115443742139e-3_dp * t30
      t35 = t11 + 0.565535e0_dp * t12 + 0.130045e2_dp
      t36 = 0.1e1_dp / t35
      t40 = log(t4 * t9 * t36 / 0.4e1_dp)
      t41 = t12 + 0.113107e1_dp
      t44 = atan(0.71231089178181179908e1_dp / t41)
      t46 = t26 + 0.47584e-2_dp
      t47 = t46 * t46
      t49 = log(t47 * t36)
      t54 = xc_cbrt(zeta_tol)
      t56 = merge(t54 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t65 = 0.9e1_dp * t56 - 0.9e1_dp
      t67 = t33 * (t40 + 0.317708004743941464e0_dp * t44 + 0.41403379428206274608e-3_dp * &
         t49) * t65 / 0.24e2_dp
      t69 = 0.1e1_dp / t7 / rho
      t70 = t6 * t69
      t75 = t14 * t14
      t76 = 0.1e1_dp / t75
      t77 = t8 * t76
      t78 = t4 * t70
      t79 = t78 / 0.12e2_dp
      t80 = 0.1e1_dp / t12
      t81 = t80 * t1
      t84 = t81 * t82 * t69
      t86 = -t79 - 0.31062e0_dp * t84
      t94 = (-t4 * t70 * t15 / 0.12e2_dp - t74 * t77 * t86 / 0.4e1_dp) * t91 * t93
      t95 = t5 * t7
      t96 = t95 * t14
      t97 = t94 * t96
      t99 = t21 * t21
      t100 = 0.1e1_dp / t99
      t102 = t100 * t80 * t1
      t104 = 0.378469910464e2_dp * t100 + 0.1e1_dp
      t105 = 0.1e1_dp / t104
      t108 = t102 * t82 * t69 * t105
      t110 = t27 * t15
      t111 = t110 * t80
      t114 = t28 * t76
      t116 = -t111 * t78 / 0.6e1_dp - t114 * t86
      t117 = 0.1e1_dp / t28
      t118 = t116 * t117
      t119 = t118 * t14
      t124 = t35 * t35
      t125 = 0.1e1_dp / t124
      t126 = t8 * t125
      t128 = -t79 - 0.94255833333333333334e-1_dp * t84
      t134 = (-t4 * t70 * t36 / 0.12e2_dp - t74 * t126 * t128 / 0.4e1_dp) * t91 * t93
      t135 = t95 * t35
      t138 = t41 * t41
      t139 = 0.1e1_dp / t138
      t141 = t139 * t80 * t1
      t143 = 0.50738680655100000001e2_dp * t139 + 0.1e1_dp
      t144 = 0.1e1_dp / t143
      t149 = t46 * t36
      t150 = t149 * t80
      t153 = t47 * t125
      t155 = -t150 * t78 / 0.6e1_dp - t153 * t128
      t156 = 0.1e1_dp / t47
      t157 = t155 * t156
      t162 = t33 * (t134 * t135 / 0.3e1_dp + 0.37717812030896172975e0_dp * t141 * t82 * t69 * &
         t144 + 0.41403379428206274608e-3_dp * t157 * t35) * t65
      eps = t20 + t25 + t31 - t67
      vrho = t20 + t25 + t31 - t67 + rho * (0.10363566666666666667e-1_dp * t97 + &
         0.39765745675026770179e-1_dp * t108 + 0.96902277115443742139e-3_dp * t119 - t162 / &
         0.24e2_dp)
   end subroutine vwn_exc_vxc_unpolar_impl

   pure subroutine vwn_fxc_unpolar_impl(rho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: v2rho2
      real(dp) :: t1, t3, t5, t32, t4, t6, t33, t74
      real(dp) :: t82, t91, t93, t193, t194, t256, t7, t8
      real(dp) :: t9, t10, t11, t12, t14, t15, t21, t26
      real(dp) :: t27, t28, t35, t36, t41, t46, t47, t54
      real(dp) :: t56, t65, t69, t70, t75, t76, t77, t78
      real(dp) :: t79, t80, t81, t84, t86, t94, t95, t96
      real(dp) :: t97, t99, t100, t102, t104, t105, t108, t110
      real(dp) :: t111, t114, t116, t117, t118, t119, t124, t125
      real(dp) :: t126, t128, t134, t135, t138, t139, t141, t143
      real(dp) :: t144, t149, t150, t153, t155, t156, t157, t162
      real(dp) :: t170, t172, t173, t175, t177, t182, t183, t184
      real(dp) :: t188, t189, t191, t192, t195, t197, t199, t202
      real(dp) :: t204, t210, t211, t214, t215, t216, t218, t219
      real(dp) :: t221, t222, t223, t224, t226, t229, t232, t236
      real(dp) :: t238, t240, t241, t242, t243, t244, t246, t249
      real(dp) :: t250, t251, t255, t257, t258, t263, t267, t268
      real(dp) :: t269, t272, t273, t274, t275, t276, t278, t281
      real(dp) :: t283, t288, t289, t290, t296, t302, t305, t308
      real(dp) :: t311, t313, t314, t319, t328, t330, t331, t332
      real(dp) :: t333, t334, t339, t340, t341, t345, t350, t354
      real(dp) :: t355, t359, t360, t361, t362, t369, t371
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t32 = m_pi_sq
      t4 = t1 * t3
      t6 = t5 * t5
      t33 = 0.1e1_dp / t32
      t74 = t4 * t6
      t82 = t3 * t6
      t91 = t1 * t1
      t93 = 0.1e1_dp / t3
      t193 = t3 * t3
      t194 = t193 * t5
      t256 = t91 * t193
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.186372e1_dp * t12 + 0.129352e2_dp
      t15 = 0.1e1_dp / t14
      t21 = t12 + 0.372744e1_dp
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.10498e0_dp
      t28 = t27 * t27
      t35 = t11 + 0.565535e0_dp * t12 + 0.130045e2_dp
      t36 = 0.1e1_dp / t35
      t41 = t12 + 0.113107e1_dp
      t46 = t26 + 0.47584e-2_dp
      t47 = t46 * t46
      t54 = xc_cbrt(zeta_tol)
      t56 = merge(t54 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t65 = 0.9e1_dp * t56 - 0.9e1_dp
      t69 = 0.1e1_dp / t7 / rho
      t70 = t6 * t69
      t75 = t14 * t14
      t76 = 0.1e1_dp / t75
      t77 = t8 * t76
      t78 = t4 * t70
      t79 = t78 / 0.12e2_dp
      t80 = 0.1e1_dp / t12
      t81 = t80 * t1
      t84 = t81 * t82 * t69
      t86 = -t79 - 0.31062e0_dp * t84
      t94 = (-t4 * t70 * t15 / 0.12e2_dp - t74 * t77 * t86 / 0.4e1_dp) * t91 * t93
      t95 = t5 * t7
      t96 = t95 * t14
      t97 = t94 * t96
      t99 = t21 * t21
      t100 = 0.1e1_dp / t99
      t102 = t100 * t80 * t1
      t104 = 0.378469910464e2_dp * t100 + 0.1e1_dp
      t105 = 0.1e1_dp / t104
      t108 = t102 * t82 * t69 * t105
      t110 = t27 * t15
      t111 = t110 * t80
      t114 = t28 * t76
      t116 = -t111 * t78 / 0.6e1_dp - t114 * t86
      t117 = 0.1e1_dp / t28
      t118 = t116 * t117
      t119 = t118 * t14
      t124 = t35 * t35
      t125 = 0.1e1_dp / t124
      t126 = t8 * t125
      t128 = -t79 - 0.94255833333333333334e-1_dp * t84
      t134 = (-t4 * t70 * t36 / 0.12e2_dp - t74 * t126 * t128 / 0.4e1_dp) * t91 * t93
      t135 = t95 * t35
      t138 = t41 * t41
      t139 = 0.1e1_dp / t138
      t141 = t139 * t80 * t1
      t143 = 0.50738680655100000001e2_dp * t139 + 0.1e1_dp
      t144 = 0.1e1_dp / t143
      t149 = t46 * t36
      t150 = t149 * t80
      t153 = t47 * t125
      t155 = -t150 * t78 / 0.6e1_dp - t153 * t128
      t156 = 0.1e1_dp / t47
      t157 = t155 * t156
      t162 = t33 * (t134 * t135 / 0.3e1_dp + 0.37717812030896172975e0_dp * t141 * t82 * t69 * &
         t144 + 0.41403379428206274608e-3_dp * t157 * t35) * t65
      t170 = rho * rho
      t172 = 0.1e1_dp / t7 / t170
      t173 = t6 * t172
      t175 = t4 * t173 * t15
      t177 = t69 * t76
      t182 = 0.1e1_dp / t75 / t14
      t183 = t8 * t182
      t184 = t86 * t86
      t188 = t4 * t173
      t189 = t188 / 0.9e1_dp
      t191 = 0.1e1_dp / t12 / t10
      t192 = t191 * t91
      t195 = t7 * t7
      t197 = 0.1e1_dp / t195 / t170
      t199 = t192 * t194 * t197
      t202 = t81 * t82 * t172
      t204 = t189 - 0.20708e0_dp * t199 + 0.41416e0_dp * t202
      t210 = (t175 / 0.9e1_dp + t74 * t177 * t86 / 0.6e1_dp + t74 * t183 * t184 / 0.2e1_dp - &
         t74 * t77 * t204 / 0.4e1_dp) * t91 * t93
      t211 = t210 * t96
      t214 = t5 / t195
      t215 = t214 * t14
      t216 = t94 * t215
      t218 = t95 * t86
      t219 = t94 * t218
      t221 = t99 * t21
      t222 = 0.1e1_dp / t221
      t223 = t222 * t1
      t224 = t223 * t3
      t226 = t224 * t173 * t105
      t229 = t100 * t191 * t91
      t232 = t229 * t194 * t197 * t105
      t236 = t102 * t82 * t172 * t105
      t238 = t99 * t99
      t240 = 0.1e1_dp / t238 / t21
      t241 = t240 * t1
      t242 = t241 * t3
      t243 = t104 * t104
      t244 = 0.1e1_dp / t243
      t246 = t242 * t173 * t244
      t249 = t27 * t76
      t250 = t249 * t81
      t251 = t69 * t86
      t255 = t110 * t191
      t257 = t5 * t197
      t258 = t256 * t257
      t263 = t28 * t182
      t267 = t175 / 0.72e2_dp + t250 * t82 * t251 / 0.3e1_dp - t255 * t258 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t111 * t188 + 0.2e1_dp * t263 * t184 - t114 * t204
      t268 = t267 * t117
      t269 = t268 * t14
      t272 = 0.1e1_dp / t28 / t27
      t273 = t116 * t272
      t274 = t14 * t80
      t275 = t273 * t274
      t276 = t275 * t78
      t278 = t118 * t86
      t281 = t4 * t173 * t36
      t283 = t69 * t125
      t288 = 0.1e1_dp / t124 / t35
      t289 = t8 * t288
      t290 = t128 * t128
      t296 = t189 - 0.62837222222222222223e-1_dp * t199 + 0.12567444444444444445e0_dp * t202
      t302 = (t281 / 0.9e1_dp + t74 * t283 * t128 / 0.6e1_dp + t74 * t289 * t290 / 0.2e1_dp - &
         t74 * t126 * t296 / 0.4e1_dp) * t91 * t93
      t305 = t214 * t35
      t308 = t95 * t128
      t311 = t138 * t41
      t313 = 0.1e1_dp / t311 * t1
      t314 = t313 * t3
      t319 = t139 * t191 * t91
      t328 = t138 * t138
      t330 = 0.1e1_dp / t328 / t41
      t331 = t330 * t1
      t332 = t331 * t3
      t333 = t143 * t143
      t334 = 0.1e1_dp / t333
      t339 = t46 * t125
      t340 = t339 * t81
      t341 = t69 * t128
      t345 = t149 * t191
      t350 = t47 * t288
      t354 = t281 / 0.72e2_dp + t340 * t82 * t341 / 0.3e1_dp - t345 * t258 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t150 * t188 + 0.2e1_dp * t350 * t290 - t153 * t296
      t355 = t354 * t156
      t359 = 0.1e1_dp / t47 / t46
      t360 = t155 * t359
      t361 = t35 * t80
      t362 = t360 * t361
      t369 = t33 * (t302 * t135 / 0.3e1_dp + t134 * t305 / 0.9e1_dp + t134 * t308 / 0.3e1_dp &
         + 0.12572604010298724325e0_dp * t314 * t173 * t144 + 0.2514520802059744865e0_dp * &
         t319 * t194 * t197 * t144 - 0.502904160411948973e0_dp * t141 * t82 * t172 * t144 - &
         0.63791733988157656508e1_dp * t332 * t173 * t334 + 0.41403379428206274608e-3_dp * &
         t355 * t35 + 0.69005632380343791013e-4_dp * t362 * t78 + &
         0.41403379428206274608e-3_dp * t157 * t128) * t65
      t371 = 0.10363566666666666667e-1_dp * t211 + 0.34545222222222222223e-2_dp * t216 + &
         0.10363566666666666667e-1_dp * t219 + 0.13255248558342256726e-1_dp * t226 + &
         0.26510497116684513453e-1_dp * t232 - 0.53020994233369026905e-1_dp * t236 - &
         0.50167127350538589834e0_dp * t246 + 0.96902277115443742139e-3_dp * t269 + &
         0.1615037951924062369e-3_dp * t276 + 0.96902277115443742139e-3_dp * t278 - t369 / &
         0.24e2_dp
      v2rho2 = 0.20727133333333333334e-1_dp * t97 + 0.79531491350053540358e-1_dp * t108 + &
         0.19380455423088748428e-2_dp * t119 - t162 / 0.12e2_dp + rho * t371
   end subroutine vwn_fxc_unpolar_impl

   pure subroutine vwn_vxc_fxc_unpolar_impl(rho, vrho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: vrho, v2rho2
      real(dp) :: t1, t3, t5, t32, t4, t6, t33, t74
      real(dp) :: t82, t91, t93, t193, t194, t256, t7, t8
      real(dp) :: t9, t10, t11, t12, t14, t15, t19, t20
      real(dp) :: t21, t24, t25, t26, t27, t28, t30, t31
      real(dp) :: t35, t36, t40, t41, t44, t46, t47, t49
      real(dp) :: t54, t56, t65, t67, t69, t70, t75, t76
      real(dp) :: t77, t78, t79, t80, t81, t84, t86, t94
      real(dp) :: t95, t96, t97, t99, t100, t102, t104, t105
      real(dp) :: t108, t110, t111, t114, t116, t117, t118, t119
      real(dp) :: t124, t125, t126, t128, t134, t135, t138, t139
      real(dp) :: t141, t143, t144, t149, t150, t153, t155, t156
      real(dp) :: t157, t162, t170, t172, t173, t175, t177, t182
      real(dp) :: t183, t184, t188, t189, t191, t192, t195, t197
      real(dp) :: t199, t202, t204, t210, t211, t214, t215, t216
      real(dp) :: t218, t219, t221, t222, t223, t224, t226, t229
      real(dp) :: t232, t236, t238, t240, t241, t242, t243, t244
      real(dp) :: t246, t249, t250, t251, t255, t257, t258, t263
      real(dp) :: t267, t268, t269, t272, t273, t274, t275, t276
      real(dp) :: t278, t281, t283, t288, t289, t290, t296, t302
      real(dp) :: t305, t308, t311, t313, t314, t319, t328, t330
      real(dp) :: t331, t332, t333, t334, t339, t340, t341, t345
      real(dp) :: t350, t354, t355, t359, t360, t361, t362, t369
      real(dp) :: t371
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t32 = m_pi_sq
      t4 = t1 * t3
      t6 = t5 * t5
      t33 = 0.1e1_dp / t32
      t74 = t4 * t6
      t82 = t3 * t6
      t91 = t1 * t1
      t93 = 0.1e1_dp / t3
      t193 = t3 * t3
      t194 = t193 * t5
      t256 = t91 * t193
      t7 = xc_cbrt(rho)
      t8 = 0.1e1_dp / t7
      t9 = t6 * t8
      t10 = t4 * t9
      t11 = t10 / 0.4e1_dp
      t12 = sqrt(t10)
      t14 = t11 + 0.186372e1_dp * t12 + 0.129352e2_dp
      t15 = 0.1e1_dp / t14
      t19 = log(t4 * t9 * t15 / 0.4e1_dp)
      t20 = 0.310907e-1_dp * t19
      t21 = t12 + 0.372744e1_dp
      t24 = atan(0.61519908197590802322e1_dp / t21)
      t25 = 0.38783294878113014393e-1_dp * t24
      t26 = t12 / 0.2e1_dp
      t27 = t26 + 0.10498e0_dp
      t28 = t27 * t27
      t30 = log(t28 * t15)
      t31 = 0.96902277115443742139e-3_dp * t30
      t35 = t11 + 0.565535e0_dp * t12 + 0.130045e2_dp
      t36 = 0.1e1_dp / t35
      t40 = log(t4 * t9 * t36 / 0.4e1_dp)
      t41 = t12 + 0.113107e1_dp
      t44 = atan(0.71231089178181179908e1_dp / t41)
      t46 = t26 + 0.47584e-2_dp
      t47 = t46 * t46
      t49 = log(t47 * t36)
      t54 = xc_cbrt(zeta_tol)
      t56 = merge(t54 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t65 = 0.9e1_dp * t56 - 0.9e1_dp
      t67 = t33 * (t40 + 0.317708004743941464e0_dp * t44 + 0.41403379428206274608e-3_dp * &
         t49) * t65 / 0.24e2_dp
      t69 = 0.1e1_dp / t7 / rho
      t70 = t6 * t69
      t75 = t14 * t14
      t76 = 0.1e1_dp / t75
      t77 = t8 * t76
      t78 = t4 * t70
      t79 = t78 / 0.12e2_dp
      t80 = 0.1e1_dp / t12
      t81 = t80 * t1
      t84 = t81 * t82 * t69
      t86 = -t79 - 0.31062e0_dp * t84
      t94 = (-t4 * t70 * t15 / 0.12e2_dp - t74 * t77 * t86 / 0.4e1_dp) * t91 * t93
      t95 = t5 * t7
      t96 = t95 * t14
      t97 = t94 * t96
      t99 = t21 * t21
      t100 = 0.1e1_dp / t99
      t102 = t100 * t80 * t1
      t104 = 0.378469910464e2_dp * t100 + 0.1e1_dp
      t105 = 0.1e1_dp / t104
      t108 = t102 * t82 * t69 * t105
      t110 = t27 * t15
      t111 = t110 * t80
      t114 = t28 * t76
      t116 = -t111 * t78 / 0.6e1_dp - t114 * t86
      t117 = 0.1e1_dp / t28
      t118 = t116 * t117
      t119 = t118 * t14
      t124 = t35 * t35
      t125 = 0.1e1_dp / t124
      t126 = t8 * t125
      t128 = -t79 - 0.94255833333333333334e-1_dp * t84
      t134 = (-t4 * t70 * t36 / 0.12e2_dp - t74 * t126 * t128 / 0.4e1_dp) * t91 * t93
      t135 = t95 * t35
      t138 = t41 * t41
      t139 = 0.1e1_dp / t138
      t141 = t139 * t80 * t1
      t143 = 0.50738680655100000001e2_dp * t139 + 0.1e1_dp
      t144 = 0.1e1_dp / t143
      t149 = t46 * t36
      t150 = t149 * t80
      t153 = t47 * t125
      t155 = -t150 * t78 / 0.6e1_dp - t153 * t128
      t156 = 0.1e1_dp / t47
      t157 = t155 * t156
      t162 = t33 * (t134 * t135 / 0.3e1_dp + 0.37717812030896172975e0_dp * t141 * t82 * t69 * &
         t144 + 0.41403379428206274608e-3_dp * t157 * t35) * t65
      t170 = rho * rho
      t172 = 0.1e1_dp / t7 / t170
      t173 = t6 * t172
      t175 = t4 * t173 * t15
      t177 = t69 * t76
      t182 = 0.1e1_dp / t75 / t14
      t183 = t8 * t182
      t184 = t86 * t86
      t188 = t4 * t173
      t189 = t188 / 0.9e1_dp
      t191 = 0.1e1_dp / t12 / t10
      t192 = t191 * t91
      t195 = t7 * t7
      t197 = 0.1e1_dp / t195 / t170
      t199 = t192 * t194 * t197
      t202 = t81 * t82 * t172
      t204 = t189 - 0.20708e0_dp * t199 + 0.41416e0_dp * t202
      t210 = (t175 / 0.9e1_dp + t74 * t177 * t86 / 0.6e1_dp + t74 * t183 * t184 / 0.2e1_dp - &
         t74 * t77 * t204 / 0.4e1_dp) * t91 * t93
      t211 = t210 * t96
      t214 = t5 / t195
      t215 = t214 * t14
      t216 = t94 * t215
      t218 = t95 * t86
      t219 = t94 * t218
      t221 = t99 * t21
      t222 = 0.1e1_dp / t221
      t223 = t222 * t1
      t224 = t223 * t3
      t226 = t224 * t173 * t105
      t229 = t100 * t191 * t91
      t232 = t229 * t194 * t197 * t105
      t236 = t102 * t82 * t172 * t105
      t238 = t99 * t99
      t240 = 0.1e1_dp / t238 / t21
      t241 = t240 * t1
      t242 = t241 * t3
      t243 = t104 * t104
      t244 = 0.1e1_dp / t243
      t246 = t242 * t173 * t244
      t249 = t27 * t76
      t250 = t249 * t81
      t251 = t69 * t86
      t255 = t110 * t191
      t257 = t5 * t197
      t258 = t256 * t257
      t263 = t28 * t182
      t267 = t175 / 0.72e2_dp + t250 * t82 * t251 / 0.3e1_dp - t255 * t258 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t111 * t188 + 0.2e1_dp * t263 * t184 - t114 * t204
      t268 = t267 * t117
      t269 = t268 * t14
      t272 = 0.1e1_dp / t28 / t27
      t273 = t116 * t272
      t274 = t14 * t80
      t275 = t273 * t274
      t276 = t275 * t78
      t278 = t118 * t86
      t281 = t4 * t173 * t36
      t283 = t69 * t125
      t288 = 0.1e1_dp / t124 / t35
      t289 = t8 * t288
      t290 = t128 * t128
      t296 = t189 - 0.62837222222222222223e-1_dp * t199 + 0.12567444444444444445e0_dp * t202
      t302 = (t281 / 0.9e1_dp + t74 * t283 * t128 / 0.6e1_dp + t74 * t289 * t290 / 0.2e1_dp - &
         t74 * t126 * t296 / 0.4e1_dp) * t91 * t93
      t305 = t214 * t35
      t308 = t95 * t128
      t311 = t138 * t41
      t313 = 0.1e1_dp / t311 * t1
      t314 = t313 * t3
      t319 = t139 * t191 * t91
      t328 = t138 * t138
      t330 = 0.1e1_dp / t328 / t41
      t331 = t330 * t1
      t332 = t331 * t3
      t333 = t143 * t143
      t334 = 0.1e1_dp / t333
      t339 = t46 * t125
      t340 = t339 * t81
      t341 = t69 * t128
      t345 = t149 * t191
      t350 = t47 * t288
      t354 = t281 / 0.72e2_dp + t340 * t82 * t341 / 0.3e1_dp - t345 * t258 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t150 * t188 + 0.2e1_dp * t350 * t290 - t153 * t296
      t355 = t354 * t156
      t359 = 0.1e1_dp / t47 / t46
      t360 = t155 * t359
      t361 = t35 * t80
      t362 = t360 * t361
      t369 = t33 * (t302 * t135 / 0.3e1_dp + t134 * t305 / 0.9e1_dp + t134 * t308 / 0.3e1_dp &
         + 0.12572604010298724325e0_dp * t314 * t173 * t144 + 0.2514520802059744865e0_dp * &
         t319 * t194 * t197 * t144 - 0.502904160411948973e0_dp * t141 * t82 * t172 * t144 - &
         0.63791733988157656508e1_dp * t332 * t173 * t334 + 0.41403379428206274608e-3_dp * &
         t355 * t35 + 0.69005632380343791013e-4_dp * t362 * t78 + &
         0.41403379428206274608e-3_dp * t157 * t128) * t65
      t371 = 0.10363566666666666667e-1_dp * t211 + 0.34545222222222222223e-2_dp * t216 + &
         0.10363566666666666667e-1_dp * t219 + 0.13255248558342256726e-1_dp * t226 + &
         0.26510497116684513453e-1_dp * t232 - 0.53020994233369026905e-1_dp * t236 - &
         0.50167127350538589834e0_dp * t246 + 0.96902277115443742139e-3_dp * t269 + &
         0.1615037951924062369e-3_dp * t276 + 0.96902277115443742139e-3_dp * t278 - t369 / &
         0.24e2_dp
      vrho = t20 + t25 + t31 - t67 + rho * (0.10363566666666666667e-1_dp * t97 + &
         0.39765745675026770179e-1_dp * t108 + 0.96902277115443742139e-3_dp * t119 - t162 / &
         0.24e2_dp)
      v2rho2 = 0.20727133333333333334e-1_dp * t97 + 0.79531491350053540358e-1_dp * t108 + &
         0.19380455423088748428e-2_dp * t119 - t162 / 0.12e2_dp + rho * t371
   end subroutine vwn_vxc_fxc_unpolar_impl

   pure subroutine vwn_exc_polar_impl(rho_a, rho_b, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps
      logical :: t58, t65
      real(dp) :: t1, t3, t5, t33, t71, t4, t6, t34
      real(dp) :: t72, t74, t83, t7, t8, t9, t10, t11
      real(dp) :: t12, t13, t15, t16, t20, t21, t22, t25
      real(dp) :: t26, t27, t28, t29, t31, t32, t36, t37
      real(dp) :: t41, t42, t45, t47, t48, t50, t53, t54
      real(dp) :: t55, t56, t57, t59, t60, t61, t63, t64
      real(dp) :: t66, t68, t69, t70, t75, t76, t77, t78
      real(dp) :: t79, t84, t86, t88, t89, t93, t95, t98
      real(dp) :: t100, t101, t103, t105, t106, t107, t108, t109
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t33 = m_pi_sq
      t71 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t34 = 0.1e1_dp / t33
      t72 = t71 - 0.1e1_dp
      t74 = 0.1e1_dp / t72 / 0.2e1_dp
      t83 = 0.9e1_dp * t72
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.186372e1_dp * t13 + 0.129352e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t21 = 0.310907e-1_dp * t20
      t22 = t13 + 0.372744e1_dp
      t25 = atan(0.61519908197590802322e1_dp / t22)
      t26 = 0.38783294878113014393e-1_dp * t25
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.10498e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t32 = 0.96902277115443742139e-3_dp * t31
      t36 = t12 + 0.565535e0_dp * t13 + 0.130045e2_dp
      t37 = 0.1e1_dp / t36
      t41 = log(t4 * t10 * t37 / 0.4e1_dp)
      t42 = t13 + 0.113107e1_dp
      t45 = atan(0.71231089178181179908e1_dp / t42)
      t47 = t27 + 0.47584e-2_dp
      t48 = t47 * t47
      t50 = log(t48 * t37)
      t53 = t34 * (t41 + 0.317708004743941464e0_dp * t45 + 0.41403379428206274608e-3_dp * t50)
      t54 = rho_a - rho_b
      t55 = 0.1e1_dp / t7
      t56 = t54 * t55
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(zeta_tol)
      t60 = t59 * zeta_tol
      t61 = xc_cbrt(t57)
      t63 = merge(t60, t61 * t57, t58)
      t64 = 0.1e1_dp - t56
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t60, t66 * t64, t65)
      t69 = t63 + t68 - 0.2e1_dp
      t70 = t53 * t69
      t75 = t54 * t54
      t76 = t75 * t75
      t77 = t7 * t7
      t78 = t77 * t77
      t79 = 0.1e1_dp / t78
      t84 = t74 * (-t76 * t79 + 0.1e1_dp) * t83
      t86 = t70 * t84 / 0.24e2_dp
      t88 = t12 + 0.353021e1_dp * t13 + 0.180578e2_dp
      t89 = 0.1e1_dp / t88
      t93 = log(t4 * t10 * t89 / 0.4e1_dp)
      t95 = t13 + 0.706042e1_dp
      t98 = atan(0.473092690956011283e1_dp / t95)
      t100 = t27 + 0.325e0_dp
      t101 = t100 * t100
      t103 = log(t101 * t89)
      t105 = 0.1554535e-1_dp * t93 + 0.52491393169780936218e-1_dp * t98 + &
         0.22478670955426118383e-2_dp * t103 - t21 - t26 - t32
      t106 = t105 * t69
      t107 = t74 * t76
      t108 = t107 * t79
      t109 = t106 * t108
      eps = t21 + t26 + t32 - t86 + t109
   end subroutine vwn_exc_polar_impl

   pure subroutine vwn_exc_vxc_polar_impl(rho_a, rho_b, eps, vrho_a, vrho_b)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps, vrho_a, vrho_b
      logical :: t58, t65
      real(dp) :: t1, t3, t5, t33, t71, t4, t6, t34
      real(dp) :: t72, t74, t83, t116, t124, t133, t135, t7
      real(dp) :: t8, t9, t10, t11, t12, t13, t15, t16
      real(dp) :: t20, t21, t22, t25, t26, t27, t28, t29
      real(dp) :: t31, t32, t36, t37, t41, t42, t45, t47
      real(dp) :: t48, t50, t53, t54, t55, t56, t57, t59
      real(dp) :: t60, t61, t63, t64, t66, t68, t69, t70
      real(dp) :: t75, t76, t77, t78, t79, t84, t86, t88
      real(dp) :: t89, t93, t95, t98, t100, t101, t103, t105
      real(dp) :: t106, t107, t108, t109, t111, t112, t117, t118
      real(dp) :: t119, t120, t121, t122, t123, t126, t128, t136
      real(dp) :: t137, t138, t139, t140, t141, t142, t144, t146
      real(dp) :: t147, t150, t151, t152, t153, t156, t158, t159
      real(dp) :: t160, t161, t162, t166, t167, t168, t170, t176
      real(dp) :: t177, t180, t181, t183, t185, t186, t191, t192
      real(dp) :: t195, t197, t198, t199, t203, t204, t205, t206
      real(dp) :: t207, t208, t209, t212, t213, t216, t217, t218
      real(dp) :: t219, t220, t221, t222, t223, t224, t225, t229
      real(dp) :: t230, t231, t235, t236, t237, t239, t245, t246
      real(dp) :: t249, t250, t252, t254, t255, t260, t261, t264
      real(dp) :: t266, t267, t268, t271, t272, t273, t274, t275
      real(dp) :: t276, t277, t278, t279, t280, t281, t282, t285
      real(dp) :: t288, t289, t292, t293, t294, t295, t296, t300
      real(dp) :: t301, t302, t303, t304
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t33 = m_pi_sq
      t71 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t34 = 0.1e1_dp / t33
      t72 = t71 - 0.1e1_dp
      t74 = 0.1e1_dp / t72 / 0.2e1_dp
      t83 = 0.9e1_dp * t72
      t116 = t4 * t6
      t124 = t3 * t6
      t133 = t1 * t1
      t135 = 0.1e1_dp / t3
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.186372e1_dp * t13 + 0.129352e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t21 = 0.310907e-1_dp * t20
      t22 = t13 + 0.372744e1_dp
      t25 = atan(0.61519908197590802322e1_dp / t22)
      t26 = 0.38783294878113014393e-1_dp * t25
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.10498e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t32 = 0.96902277115443742139e-3_dp * t31
      t36 = t12 + 0.565535e0_dp * t13 + 0.130045e2_dp
      t37 = 0.1e1_dp / t36
      t41 = log(t4 * t10 * t37 / 0.4e1_dp)
      t42 = t13 + 0.113107e1_dp
      t45 = atan(0.71231089178181179908e1_dp / t42)
      t47 = t27 + 0.47584e-2_dp
      t48 = t47 * t47
      t50 = log(t48 * t37)
      t53 = t34 * (t41 + 0.317708004743941464e0_dp * t45 + 0.41403379428206274608e-3_dp * t50)
      t54 = rho_a - rho_b
      t55 = 0.1e1_dp / t7
      t56 = t54 * t55
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(zeta_tol)
      t60 = t59 * zeta_tol
      t61 = xc_cbrt(t57)
      t63 = merge(t60, t61 * t57, t58)
      t64 = 0.1e1_dp - t56
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t60, t66 * t64, t65)
      t69 = t63 + t68 - 0.2e1_dp
      t70 = t53 * t69
      t75 = t54 * t54
      t76 = t75 * t75
      t77 = t7 * t7
      t78 = t77 * t77
      t79 = 0.1e1_dp / t78
      t84 = t74 * (-t76 * t79 + 0.1e1_dp) * t83
      t86 = t70 * t84 / 0.24e2_dp
      t88 = t12 + 0.353021e1_dp * t13 + 0.180578e2_dp
      t89 = 0.1e1_dp / t88
      t93 = log(t4 * t10 * t89 / 0.4e1_dp)
      t95 = t13 + 0.706042e1_dp
      t98 = atan(0.473092690956011283e1_dp / t95)
      t100 = t27 + 0.325e0_dp
      t101 = t100 * t100
      t103 = log(t101 * t89)
      t105 = 0.1554535e-1_dp * t93 + 0.52491393169780936218e-1_dp * t98 + &
         0.22478670955426118383e-2_dp * t103 - t21 - t26 - t32
      t106 = t105 * t69
      t107 = t74 * t76
      t108 = t107 * t79
      t109 = t106 * t108
      t111 = 0.1e1_dp / t8 / t7
      t112 = t6 * t111
      t117 = t15 * t15
      t118 = 0.1e1_dp / t117
      t119 = t9 * t118
      t120 = t4 * t112
      t121 = t120 / 0.12e2_dp
      t122 = 0.1e1_dp / t13
      t123 = t122 * t1
      t126 = t123 * t124 * t111
      t128 = -t121 - 0.31062e0_dp * t126
      t136 = (-t4 * t112 * t16 / 0.12e2_dp - t116 * t119 * t128 / 0.4e1_dp) * t133 * t135
      t137 = t5 * t8
      t138 = t137 * t15
      t139 = t136 * t138
      t140 = 0.10363566666666666667e-1_dp * t139
      t141 = t22 * t22
      t142 = 0.1e1_dp / t141
      t144 = t142 * t122 * t1
      t146 = 0.378469910464e2_dp * t142 + 0.1e1_dp
      t147 = 0.1e1_dp / t146
      t150 = t144 * t124 * t111 * t147
      t151 = 0.39765745675026770179e-1_dp * t150
      t152 = t28 * t16
      t153 = t152 * t122
      t156 = t29 * t118
      t158 = -t153 * t120 / 0.6e1_dp - t156 * t128
      t159 = 0.1e1_dp / t29
      t160 = t158 * t159
      t161 = t160 * t15
      t162 = 0.96902277115443742139e-3_dp * t161
      t166 = t36 * t36
      t167 = 0.1e1_dp / t166
      t168 = t9 * t167
      t170 = -t121 - 0.94255833333333333334e-1_dp * t126
      t176 = (-t4 * t112 * t37 / 0.12e2_dp - t116 * t168 * t170 / 0.4e1_dp) * t133 * t135
      t177 = t137 * t36
      t180 = t42 * t42
      t181 = 0.1e1_dp / t180
      t183 = t181 * t122 * t1
      t185 = 0.50738680655100000001e2_dp * t181 + 0.1e1_dp
      t186 = 0.1e1_dp / t185
      t191 = t47 * t37
      t192 = t191 * t122
      t195 = t48 * t167
      t197 = -t192 * t120 / 0.6e1_dp - t195 * t170
      t198 = 0.1e1_dp / t48
      t199 = t197 * t198
      t203 = t34 * (t176 * t177 / 0.3e1_dp + 0.37717812030896172975e0_dp * t183 * t124 * t111 &
         * t186 + 0.41403379428206274608e-3_dp * t199 * t36)
      t204 = t203 * t69
      t205 = t204 * t84
      t206 = t205 / 0.24e2_dp
      t207 = 0.1e1_dp / t77
      t208 = t54 * t207
      t209 = t55 - t208
      t212 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t61 * t209, t58)
      t213 = -t209
      t216 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t213, t65)
      t217 = t212 + t216
      t218 = t53 * t217
      t219 = t218 * t84
      t220 = t219 / 0.24e2_dp
      t221 = t75 * t54
      t222 = t221 * t79
      t223 = t78 * t7
      t224 = 0.1e1_dp / t223
      t225 = t76 * t224
      t229 = t74 * (-0.4e1_dp * t222 + 0.4e1_dp * t225) * t83
      t230 = t70 * t229
      t231 = t230 / 0.24e2_dp
      t235 = t88 * t88
      t236 = 0.1e1_dp / t235
      t237 = t9 * t236
      t239 = -t121 - 0.58836833333333333333e0_dp * t126
      t245 = (-t4 * t112 * t89 / 0.12e2_dp - t116 * t237 * t239 / 0.4e1_dp) * t133 * t135
      t246 = t137 * t88
      t249 = t95 * t95
      t250 = 0.1e1_dp / t249
      t252 = t250 * t122 * t1
      t254 = 0.223816694236e2_dp * t250 + 0.1e1_dp
      t255 = 0.1e1_dp / t254
      t260 = t100 * t89
      t261 = t260 * t122
      t264 = t101 * t236
      t266 = -t261 * t120 / 0.6e1_dp - t264 * t239
      t267 = 0.1e1_dp / t101
      t268 = t266 * t267
      t271 = 0.51817833333333333333e-2_dp * t245 * t246 + 0.41388824077869423261e-1_dp * t252 &
         * t124 * t111 * t255 + 0.22478670955426118383e-2_dp * t268 * t88 - t140 - t151 - t162
      t272 = t271 * t69
      t273 = t272 * t108
      t274 = t105 * t217
      t275 = t274 * t108
      t276 = t74 * t221
      t277 = t276 * t79
      t278 = t106 * t277
      t279 = 0.4e1_dp * t278
      t280 = t107 * t224
      t281 = t106 * t280
      t282 = 0.4e1_dp * t281
      t285 = -t55 - t208
      t288 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t61 * t285, t58)
      t289 = -t285
      t292 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t289, t65)
      t293 = t288 + t292
      t294 = t53 * t293
      t295 = t294 * t84
      t296 = t295 / 0.24e2_dp
      t300 = t74 * (0.4e1_dp * t222 + 0.4e1_dp * t225) * t83
      t301 = t70 * t300
      t302 = t301 / 0.24e2_dp
      t303 = t105 * t293
      t304 = t303 * t108
      eps = t21 + t26 + t32 - t86 + t109
      vrho_a = t21 + t26 + t32 - t86 + t109 + t7 * (t140 + t151 + t162 - t206 - t220 - t231 + &
         t273 + t275 + t279 - t282)
      vrho_b = t21 + t26 + t32 - t86 + t109 + t7 * (t140 + t151 + t162 - t206 - t296 - t302 + &
         t273 + t304 - t279 - t282)
   end subroutine vwn_exc_vxc_polar_impl

   pure subroutine vwn_fxc_polar_impl(rho_a, rho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb
      logical :: t58, t65
      real(dp) :: t1, t3, t5, t33, t71, t4, t6, t34
      real(dp) :: t72, t74, t83, t116, t124, t133, t135, t339
      real(dp) :: t340, t402, t7, t8, t9, t10, t11, t12
      real(dp) :: t13, t15, t16, t20, t21, t22, t25, t26
      real(dp) :: t27, t28, t29, t31, t32, t36, t37, t41
      real(dp) :: t42, t45, t47, t48, t50, t53, t54, t55
      real(dp) :: t56, t57, t59, t60, t61, t63, t64, t66
      real(dp) :: t68, t69, t70, t75, t76, t77, t78, t79
      real(dp) :: t84, t88, t89, t93, t95, t98, t100, t101
      real(dp) :: t103, t105, t106, t107, t108, t111, t112, t117
      real(dp) :: t118, t119, t120, t121, t122, t123, t126, t128
      real(dp) :: t136, t137, t138, t139, t140, t141, t142, t144
      real(dp) :: t146, t147, t150, t151, t152, t153, t156, t158
      real(dp) :: t159, t160, t161, t162, t166, t167, t168, t170
      real(dp) :: t176, t177, t180, t181, t183, t185, t186, t191
      real(dp) :: t192, t195, t197, t198, t199, t203, t204, t205
      real(dp) :: t207, t208, t209, t212, t213, t216, t217, t218
      real(dp) :: t219, t220, t221, t222, t223, t224, t225, t229
      real(dp) :: t230, t231, t235, t236, t237, t239, t245, t246
      real(dp) :: t249, t250, t252, t254, t255, t260, t261, t264
      real(dp) :: t266, t267, t268, t271, t272, t273, t274, t275
      real(dp) :: t276, t277, t278, t280, t281, t285, t288, t289
      real(dp) :: t292, t293, t294, t295, t296, t300, t301, t302
      real(dp) :: t303, t304, t307, t308, t309, t310, t313, t315
      real(dp) :: t316, t318, t319, t321, t323, t328, t329, t330
      real(dp) :: t334, t335, t337, t338, t341, t343, t345, t348
      real(dp) :: t350, t356, t360, t361, t364, t367, t368, t369
      real(dp) :: t370, t375, t384, t386, t387, t388, t389, t390
      real(dp) :: t395, t396, t397, t401, t403, t404, t409, t413
      real(dp) :: t414, t418, t419, t420, t421, t427, t429, t434
      real(dp) :: t435, t436, t442, t448, t449, t450, t451, t452
      real(dp) :: t453, t454, t455, t456, t457, t458, t459, t460
      real(dp) :: t462, t463, t465, t468, t469, t472, t473, t474
      real(dp) :: t476, t477, t478, t479, t480, t482, t483, t485
      real(dp) :: t486, t487, t491, t496, t500, t501, t502, t503
      real(dp) :: t505, t506, t507, t508, t509, t510, t511, t512
      real(dp) :: t513, t514, t515, t516, t517, t518, t521, t522
      real(dp) :: t523, t525, t529, t530, t531, t532, t535, t539
      real(dp) :: t540, t541, t542, t543, t544, t545, t546, t547
      real(dp) :: t549, t551, t553, t555, t558, t559, t560, t561
      real(dp) :: t562, t564, t566, t571, t572, t573, t579, t585
      real(dp) :: t588, t591, t594, t596, t597, t602, t611, t613
      real(dp) :: t614, t615, t616, t617, t622, t623, t624, t628
      real(dp) :: t633, t637, t638, t642, t643, t644, t645, t651
      real(dp) :: t652, t653, t654, t655, t656, t657, t658, t659
      real(dp) :: t660, t661, t662, t663, t664, t665, t666, t667
      real(dp) :: t668, t669, t670, t671, t672, t673, t674, t675
      real(dp) :: t676, t677, t678, t679, t680, t683, t684, t686
      real(dp) :: t689, t693, t694, t697, t701, t702, t703, t704
      real(dp) :: t706, t708, t710, t714, t715, t719, t720, t722
      real(dp) :: t724, t725, t726, t727, t730, t738, t739, t740
      real(dp) :: t741, t745, t749, t750, t753, t757, t758, t759
      real(dp) :: t760, t761, t762, t763, t764, t765, t766, t767
      real(dp) :: t768, t769, t770, t771, t772
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t33 = m_pi_sq
      t71 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t34 = 0.1e1_dp / t33
      t72 = t71 - 0.1e1_dp
      t74 = 0.1e1_dp / t72 / 0.2e1_dp
      t83 = 0.9e1_dp * t72
      t116 = t4 * t6
      t124 = t3 * t6
      t133 = t1 * t1
      t135 = 0.1e1_dp / t3
      t339 = t3 * t3
      t340 = t339 * t5
      t402 = t133 * t339
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.186372e1_dp * t13 + 0.129352e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t21 = 0.310907e-1_dp * t20
      t22 = t13 + 0.372744e1_dp
      t25 = atan(0.61519908197590802322e1_dp / t22)
      t26 = 0.38783294878113014393e-1_dp * t25
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.10498e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t32 = 0.96902277115443742139e-3_dp * t31
      t36 = t12 + 0.565535e0_dp * t13 + 0.130045e2_dp
      t37 = 0.1e1_dp / t36
      t41 = log(t4 * t10 * t37 / 0.4e1_dp)
      t42 = t13 + 0.113107e1_dp
      t45 = atan(0.71231089178181179908e1_dp / t42)
      t47 = t27 + 0.47584e-2_dp
      t48 = t47 * t47
      t50 = log(t48 * t37)
      t53 = t34 * (t41 + 0.317708004743941464e0_dp * t45 + 0.41403379428206274608e-3_dp * t50)
      t54 = rho_a - rho_b
      t55 = 0.1e1_dp / t7
      t56 = t54 * t55
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(zeta_tol)
      t60 = t59 * zeta_tol
      t61 = xc_cbrt(t57)
      t63 = merge(t60, t61 * t57, t58)
      t64 = 0.1e1_dp - t56
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t60, t66 * t64, t65)
      t69 = t63 + t68 - 0.2e1_dp
      t70 = t53 * t69
      t75 = t54 * t54
      t76 = t75 * t75
      t77 = t7 * t7
      t78 = t77 * t77
      t79 = 0.1e1_dp / t78
      t84 = t74 * (-t76 * t79 + 0.1e1_dp) * t83
      t88 = t12 + 0.353021e1_dp * t13 + 0.180578e2_dp
      t89 = 0.1e1_dp / t88
      t93 = log(t4 * t10 * t89 / 0.4e1_dp)
      t95 = t13 + 0.706042e1_dp
      t98 = atan(0.473092690956011283e1_dp / t95)
      t100 = t27 + 0.325e0_dp
      t101 = t100 * t100
      t103 = log(t101 * t89)
      t105 = 0.1554535e-1_dp * t93 + 0.52491393169780936218e-1_dp * t98 + &
         0.22478670955426118383e-2_dp * t103 - t21 - t26 - t32
      t106 = t105 * t69
      t107 = t74 * t76
      t108 = t107 * t79
      t111 = 0.1e1_dp / t8 / t7
      t112 = t6 * t111
      t117 = t15 * t15
      t118 = 0.1e1_dp / t117
      t119 = t9 * t118
      t120 = t4 * t112
      t121 = t120 / 0.12e2_dp
      t122 = 0.1e1_dp / t13
      t123 = t122 * t1
      t126 = t123 * t124 * t111
      t128 = -t121 - 0.31062e0_dp * t126
      t136 = (-t4 * t112 * t16 / 0.12e2_dp - t116 * t119 * t128 / 0.4e1_dp) * t133 * t135
      t137 = t5 * t8
      t138 = t137 * t15
      t139 = t136 * t138
      t140 = 0.10363566666666666667e-1_dp * t139
      t141 = t22 * t22
      t142 = 0.1e1_dp / t141
      t144 = t142 * t122 * t1
      t146 = 0.378469910464e2_dp * t142 + 0.1e1_dp
      t147 = 0.1e1_dp / t146
      t150 = t144 * t124 * t111 * t147
      t151 = 0.39765745675026770179e-1_dp * t150
      t152 = t28 * t16
      t153 = t152 * t122
      t156 = t29 * t118
      t158 = -t153 * t120 / 0.6e1_dp - t156 * t128
      t159 = 0.1e1_dp / t29
      t160 = t158 * t159
      t161 = t160 * t15
      t162 = 0.96902277115443742139e-3_dp * t161
      t166 = t36 * t36
      t167 = 0.1e1_dp / t166
      t168 = t9 * t167
      t170 = -t121 - 0.94255833333333333334e-1_dp * t126
      t176 = (-t4 * t112 * t37 / 0.12e2_dp - t116 * t168 * t170 / 0.4e1_dp) * t133 * t135
      t177 = t137 * t36
      t180 = t42 * t42
      t181 = 0.1e1_dp / t180
      t183 = t181 * t122 * t1
      t185 = 0.50738680655100000001e2_dp * t181 + 0.1e1_dp
      t186 = 0.1e1_dp / t185
      t191 = t47 * t37
      t192 = t191 * t122
      t195 = t48 * t167
      t197 = -t192 * t120 / 0.6e1_dp - t195 * t170
      t198 = 0.1e1_dp / t48
      t199 = t197 * t198
      t203 = t34 * (t176 * t177 / 0.3e1_dp + 0.37717812030896172975e0_dp * t183 * t124 * t111 &
         * t186 + 0.41403379428206274608e-3_dp * t199 * t36)
      t204 = t203 * t69
      t205 = t204 * t84
      t207 = 0.1e1_dp / t77
      t208 = t54 * t207
      t209 = t55 - t208
      t212 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t61 * t209, t58)
      t213 = -t209
      t216 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t213, t65)
      t217 = t212 + t216
      t218 = t53 * t217
      t219 = t218 * t84
      t220 = t219 / 0.24e2_dp
      t221 = t75 * t54
      t222 = t221 * t79
      t223 = t78 * t7
      t224 = 0.1e1_dp / t223
      t225 = t76 * t224
      t229 = t74 * (-0.4e1_dp * t222 + 0.4e1_dp * t225) * t83
      t230 = t70 * t229
      t231 = t230 / 0.24e2_dp
      t235 = t88 * t88
      t236 = 0.1e1_dp / t235
      t237 = t9 * t236
      t239 = -t121 - 0.58836833333333333333e0_dp * t126
      t245 = (-t4 * t112 * t89 / 0.12e2_dp - t116 * t237 * t239 / 0.4e1_dp) * t133 * t135
      t246 = t137 * t88
      t249 = t95 * t95
      t250 = 0.1e1_dp / t249
      t252 = t250 * t122 * t1
      t254 = 0.223816694236e2_dp * t250 + 0.1e1_dp
      t255 = 0.1e1_dp / t254
      t260 = t100 * t89
      t261 = t260 * t122
      t264 = t101 * t236
      t266 = -t261 * t120 / 0.6e1_dp - t264 * t239
      t267 = 0.1e1_dp / t101
      t268 = t266 * t267
      t271 = 0.51817833333333333333e-2_dp * t245 * t246 + 0.41388824077869423261e-1_dp * t252 &
         * t124 * t111 * t255 + 0.22478670955426118383e-2_dp * t268 * t88 - t140 - t151 - t162
      t272 = t271 * t69
      t273 = t272 * t108
      t274 = t105 * t217
      t275 = t274 * t108
      t276 = t74 * t221
      t277 = t276 * t79
      t278 = t106 * t277
      t280 = t107 * t224
      t281 = t106 * t280
      t285 = -t55 - t208
      t288 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t61 * t285, t58)
      t289 = -t285
      t292 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t289, t65)
      t293 = t288 + t292
      t294 = t53 * t293
      t295 = t294 * t84
      t296 = t295 / 0.24e2_dp
      t300 = t74 * (0.4e1_dp * t222 + 0.4e1_dp * t225) * t83
      t301 = t70 * t300
      t302 = t301 / 0.24e2_dp
      t303 = t105 * t293
      t304 = t303 * t108
      t307 = 0.20727133333333333334e-1_dp * t139
      t308 = 0.79531491350053540358e-1_dp * t150
      t309 = 0.19380455423088748428e-2_dp * t161
      t310 = t205 / 0.12e2_dp
      t313 = 0.2e1_dp * t273
      t315 = 0.8e1_dp * t278
      t316 = 0.8e1_dp * t281
      t318 = 0.1e1_dp / t8 / t77
      t319 = t6 * t318
      t321 = t4 * t319 * t89
      t323 = t111 * t236
      t328 = 0.1e1_dp / t235 / t88
      t329 = t9 * t328
      t330 = t239 * t239
      t334 = t4 * t319
      t335 = t334 / 0.9e1_dp
      t337 = 0.1e1_dp / t13 / t11
      t338 = t337 * t133
      t341 = t8 * t8
      t343 = 0.1e1_dp / t341 / t77
      t345 = t338 * t340 * t343
      t348 = t123 * t124 * t318
      t350 = t335 - 0.39224555555555555555e0_dp * t345 + 0.7844911111111111111e0_dp * t348
      t356 = (t321 / 0.9e1_dp + t116 * t323 * t239 / 0.6e1_dp + t116 * t329 * t330 / 0.2e1_dp &
         - t116 * t237 * t350 / 0.4e1_dp) * t133 * t135
      t360 = t5 / t341
      t361 = t360 * t88
      t364 = t137 * t239
      t367 = t249 * t95
      t368 = 0.1e1_dp / t367
      t369 = t368 * t1
      t370 = t369 * t3
      t375 = t250 * t337 * t133
      t384 = t249 * t249
      t386 = 0.1e1_dp / t384 / t95
      t387 = t386 * t1
      t388 = t387 * t3
      t389 = t254 * t254
      t390 = 0.1e1_dp / t389
      t395 = t100 * t236
      t396 = t395 * t123
      t397 = t111 * t239
      t401 = t260 * t337
      t403 = t5 * t343
      t404 = t402 * t403
      t409 = t101 * t328
      t413 = t321 / 0.72e2_dp + t396 * t124 * t397 / 0.3e1_dp - t401 * t404 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t261 * t334 + 0.2e1_dp * t409 * t330 - t264 * t350
      t414 = t413 * t267
      t418 = 0.1e1_dp / t101 / t100
      t419 = t266 * t418
      t420 = t88 * t122
      t421 = t419 * t420
      t427 = t4 * t319 * t16
      t429 = t111 * t118
      t434 = 0.1e1_dp / t117 / t15
      t435 = t9 * t434
      t436 = t128 * t128
      t442 = t335 - 0.20708e0_dp * t345 + 0.41416e0_dp * t348
      t448 = (t427 / 0.9e1_dp + t116 * t429 * t128 / 0.6e1_dp + t116 * t435 * t436 / 0.2e1_dp &
         - t116 * t119 * t442 / 0.4e1_dp) * t133 * t135
      t449 = t448 * t138
      t450 = 0.10363566666666666667e-1_dp * t449
      t451 = t360 * t15
      t452 = t136 * t451
      t453 = 0.34545222222222222223e-2_dp * t452
      t454 = t137 * t128
      t455 = t136 * t454
      t456 = 0.10363566666666666667e-1_dp * t455
      t457 = t141 * t22
      t458 = 0.1e1_dp / t457
      t459 = t458 * t1
      t460 = t459 * t3
      t462 = t460 * t319 * t147
      t463 = 0.13255248558342256726e-1_dp * t462
      t465 = t142 * t337 * t133
      t468 = t465 * t340 * t343 * t147
      t469 = 0.26510497116684513453e-1_dp * t468
      t472 = t144 * t124 * t318 * t147
      t473 = 0.53020994233369026905e-1_dp * t472
      t474 = t141 * t141
      t476 = 0.1e1_dp / t474 / t22
      t477 = t476 * t1
      t478 = t477 * t3
      t479 = t146 * t146
      t480 = 0.1e1_dp / t479
      t482 = t478 * t319 * t480
      t483 = 0.50167127350538589834e0_dp * t482
      t485 = t28 * t118
      t486 = t485 * t123
      t487 = t111 * t128
      t491 = t152 * t337
      t496 = t29 * t434
      t500 = t427 / 0.72e2_dp + t486 * t124 * t487 / 0.3e1_dp - t491 * t404 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t153 * t334 + 0.2e1_dp * t496 * t436 - t156 * t442
      t501 = t500 * t159
      t502 = t501 * t15
      t503 = 0.96902277115443742139e-3_dp * t502
      t505 = 0.1e1_dp / t29 / t28
      t506 = t158 * t505
      t507 = t15 * t122
      t508 = t506 * t507
      t509 = t508 * t120
      t510 = 0.1615037951924062369e-3_dp * t509
      t511 = t160 * t128
      t512 = 0.96902277115443742139e-3_dp * t511
      t513 = 0.51817833333333333333e-2_dp * t356 * t246 + 0.17272611111111111111e-2_dp * t245 &
         * t361 + 0.51817833333333333333e-2_dp * t245 * t364 + 0.13796274692623141087e-1_dp * &
         t370 * t319 * t255 + 0.27592549385246282174e-1_dp * t375 * t340 * t343 * t255 - &
         0.55185098770492564348e-1_dp * t252 * t124 * t318 * t255 - &
         0.30878365944746984535e0_dp * t388 * t319 * t390 + 0.22478670955426118383e-2_dp * &
         t414 * t88 + 0.37464451592376863972e-3_dp * t421 * t120 + &
         0.22478670955426118383e-2_dp * t268 * t239 - t450 - t453 - t456 - t463 - t469 + t473 &
         + t483 - t503 - t510 - t512
      t514 = t513 * t69
      t515 = t514 * t108
      t516 = t61 * t61
      t517 = 0.1e1_dp / t516
      t518 = t209 * t209
      t521 = t77 * t7
      t522 = 0.1e1_dp / t521
      t523 = t54 * t522
      t525 = -0.2e1_dp * t207 + 0.2e1_dp * t523
      t529 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t517 * t518 + 0.4e1_dp / 0.3e1_dp * t61 * &
         t525, t58)
      t530 = t66 * t66
      t531 = 0.1e1_dp / t530
      t532 = t213 * t213
      t535 = -t525
      t539 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t531 * t532 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t535, t65)
      t540 = t529 + t539
      t541 = t105 * t540
      t542 = t541 * t108
      t543 = t53 * t540
      t544 = t543 * t84
      t545 = t544 / 0.24e2_dp
      t546 = t218 * t229
      t547 = t546 / 0.12e2_dp
      t549 = 0.12e2_dp * t75 * t79
      t551 = 0.32e2_dp * t221 * t224
      t553 = 0.1e1_dp / t78 / t77
      t555 = 0.2e2_dp * t76 * t553
      t558 = t74 * (-t549 + t551 - t555) * t83
      t559 = t70 * t558
      t560 = t559 / 0.24e2_dp
      t561 = t204 * t229
      t562 = t561 / 0.12e2_dp
      t564 = t4 * t319 * t37
      t566 = t111 * t167
      t571 = 0.1e1_dp / t166 / t36
      t572 = t9 * t571
      t573 = t170 * t170
      t579 = t335 - 0.62837222222222222223e-1_dp * t345 + 0.12567444444444444445e0_dp * t348
      t585 = (t564 / 0.9e1_dp + t116 * t566 * t170 / 0.6e1_dp + t116 * t572 * t573 / 0.2e1_dp &
         - t116 * t168 * t579 / 0.4e1_dp) * t133 * t135
      t588 = t360 * t36
      t591 = t137 * t170
      t594 = t180 * t42
      t596 = 0.1e1_dp / t594 * t1
      t597 = t596 * t3
      t602 = t181 * t337 * t133
      t611 = t180 * t180
      t613 = 0.1e1_dp / t611 / t42
      t614 = t613 * t1
      t615 = t614 * t3
      t616 = t185 * t185
      t617 = 0.1e1_dp / t616
      t622 = t47 * t167
      t623 = t622 * t123
      t624 = t111 * t170
      t628 = t191 * t337
      t633 = t48 * t571
      t637 = t564 / 0.72e2_dp + t623 * t124 * t624 / 0.3e1_dp - t628 * t404 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t192 * t334 + 0.2e1_dp * t633 * t573 - t195 * t579
      t638 = t637 * t198
      t642 = 0.1e1_dp / t48 / t47
      t643 = t197 * t642
      t644 = t36 * t122
      t645 = t643 * t644
      t651 = t34 * (t585 * t177 / 0.3e1_dp + t176 * t588 / 0.9e1_dp + t176 * t591 / 0.3e1_dp &
         + 0.12572604010298724325e0_dp * t597 * t319 * t186 + 0.2514520802059744865e0_dp * &
         t602 * t340 * t343 * t186 - 0.502904160411948973e0_dp * t183 * t124 * t318 * t186 - &
         0.63791733988157656508e1_dp * t615 * t319 * t617 + 0.41403379428206274608e-3_dp * &
         t638 * t36 + 0.69005632380343791013e-4_dp * t645 * t120 + &
         0.41403379428206274608e-3_dp * t199 * t170)
      t652 = t651 * t69
      t653 = t652 * t84
      t654 = t653 / 0.24e2_dp
      t655 = t203 * t217
      t656 = t655 * t84
      t657 = t656 / 0.12e2_dp
      t658 = t515 + t542 - t545 - t547 - t560 - t562 + t453 - t483 - t654 - t657 + t450 + &
         t456 + t463
      t659 = t272 * t277
      t660 = 0.8e1_dp * t659
      t661 = t272 * t280
      t662 = 0.8e1_dp * t661
      t663 = t274 * t277
      t664 = 0.8e1_dp * t663
      t665 = t274 * t280
      t666 = 0.8e1_dp * t665
      t667 = t74 * t75
      t668 = t667 * t79
      t669 = t106 * t668
      t670 = 0.12e2_dp * t669
      t671 = t276 * t224
      t672 = t106 * t671
      t673 = 0.32e2_dp * t672
      t674 = t107 * t553
      t675 = t106 * t674
      t676 = 0.2e2_dp * t675
      t677 = t271 * t217
      t678 = t677 * t108
      t679 = 0.2e1_dp * t678
      t680 = t503 + t512 + t510 + t469 - t473 + t660 - t662 + t664 - t666 + t670 - t673 + &
         t676 + t679
      t683 = t203 * t293
      t684 = t683 * t84
      t686 = t517 * t285
      t689 = t61 * t54
      t693 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t686 * t209 + 0.8e1_dp / 0.3e1_dp * t689 * &
         t522, t58)
      t694 = t531 * t289
      t697 = t66 * t54
      t701 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t694 * t213 - 0.8e1_dp / 0.3e1_dp * t697 * &
         t522, t65)
      t702 = t693 + t701
      t703 = t53 * t702
      t704 = t703 * t84
      t706 = t294 * t229
      t708 = t204 * t300
      t710 = t218 * t300
      t714 = t74 * (t549 - t555) * t83
      t715 = t70 * t714
      t719 = t515 - t684 / 0.24e2_dp - t704 / 0.24e2_dp - t706 / 0.24e2_dp - t708 / 0.24e2_dp &
         - t710 / 0.24e2_dp - t715 / 0.24e2_dp - t561 / 0.24e2_dp + t453 - t483 - t654 - t656 &
         / 0.24e2_dp + t450 + t456 + t463
      t720 = t303 * t277
      t722 = t303 * t280
      t724 = t105 * t702
      t725 = t724 * t108
      t726 = t271 * t293
      t727 = t726 * t108
      t730 = t503 + t512 + t510 + 0.4e1_dp * t720 - 0.4e1_dp * t722 + t469 - t473 + t725 + &
         t727 - t662 - 0.4e1_dp * t663 - 0.4e1_dp * t665 - t670 + t676 + t678
      t738 = t74 * (-t549 - t551 - t555) * t83
      t739 = t70 * t738
      t740 = t739 / 0.24e2_dp
      t741 = t285 * t285
      t745 = 0.2e1_dp * t207 + 0.2e1_dp * t523
      t749 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t517 * t741 + 0.4e1_dp / 0.3e1_dp * t61 * &
         t745, t58)
      t750 = t289 * t289
      t753 = -t745
      t757 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t531 * t750 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t753, t65)
      t758 = t749 + t757
      t759 = t53 * t758
      t760 = t759 * t84
      t761 = t760 / 0.24e2_dp
      t762 = t294 * t300
      t763 = t762 / 0.12e2_dp
      t764 = t684 / 0.12e2_dp
      t765 = t708 / 0.12e2_dp
      t766 = t515 - t740 - t761 - t763 - t764 - t765 + t453 - t483 - t654 + t450 + t456 + &
         t463 + t503
      t767 = t105 * t758
      t768 = t767 * t108
      t769 = 0.8e1_dp * t720
      t770 = 0.8e1_dp * t722
      t771 = 0.2e1_dp * t727
      t772 = t512 + t510 + t768 - t769 - t770 + t469 - t473 + t771 - t660 - t662 + t670 + &
         t673 + t676
      v2rho2_aa = t307 + t308 + t309 - t310 - t219 / 0.12e2_dp - t230 / 0.12e2_dp + t313 + &
         0.2e1_dp * t275 + t315 - t316 + t7 * (t658 + t680)
      v2rho2_ab = t307 + t308 + t309 - t310 - t220 - t231 + t313 + t275 - t316 - t296 - t302 &
         + t304 + t7 * (t719 + t730)
      v2rho2_bb = t307 + t308 + t309 - t310 - t295 / 0.12e2_dp - t301 / 0.12e2_dp + t313 + &
         0.2e1_dp * t304 - t315 - t316 + t7 * (t766 + t772)
   end subroutine vwn_fxc_polar_impl

   pure subroutine vwn_vxc_fxc_polar_impl(rho_a, rho_b, vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, &
      v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb
      logical :: t58, t65
      real(dp) :: t1, t3, t5, t33, t71, t4, t6, t34
      real(dp) :: t72, t74, t83, t116, t124, t133, t135, t339
      real(dp) :: t340, t402, t7, t8, t9, t10, t11, t12
      real(dp) :: t13, t15, t16, t20, t21, t22, t25, t26
      real(dp) :: t27, t28, t29, t31, t32, t36, t37, t41
      real(dp) :: t42, t45, t47, t48, t50, t53, t54, t55
      real(dp) :: t56, t57, t59, t60, t61, t63, t64, t66
      real(dp) :: t68, t69, t70, t75, t76, t77, t78, t79
      real(dp) :: t84, t86, t88, t89, t93, t95, t98, t100
      real(dp) :: t101, t103, t105, t106, t107, t108, t109, t111
      real(dp) :: t112, t117, t118, t119, t120, t121, t122, t123
      real(dp) :: t126, t128, t136, t137, t138, t139, t140, t141
      real(dp) :: t142, t144, t146, t147, t150, t151, t152, t153
      real(dp) :: t156, t158, t159, t160, t161, t162, t166, t167
      real(dp) :: t168, t170, t176, t177, t180, t181, t183, t185
      real(dp) :: t186, t191, t192, t195, t197, t198, t199, t203
      real(dp) :: t204, t205, t206, t207, t208, t209, t212, t213
      real(dp) :: t216, t217, t218, t219, t220, t221, t222, t223
      real(dp) :: t224, t225, t229, t230, t231, t235, t236, t237
      real(dp) :: t239, t245, t246, t249, t250, t252, t254, t255
      real(dp) :: t260, t261, t264, t266, t267, t268, t271, t272
      real(dp) :: t273, t274, t275, t276, t277, t278, t279, t280
      real(dp) :: t281, t282, t285, t288, t289, t292, t293, t294
      real(dp) :: t295, t296, t300, t301, t302, t303, t304, t307
      real(dp) :: t308, t309, t310, t313, t315, t316, t318, t319
      real(dp) :: t321, t323, t328, t329, t330, t334, t335, t337
      real(dp) :: t338, t341, t343, t345, t348, t350, t356, t360
      real(dp) :: t361, t364, t367, t368, t369, t370, t375, t384
      real(dp) :: t386, t387, t388, t389, t390, t395, t396, t397
      real(dp) :: t401, t403, t404, t409, t413, t414, t418, t419
      real(dp) :: t420, t421, t427, t429, t434, t435, t436, t442
      real(dp) :: t448, t449, t450, t451, t452, t453, t454, t455
      real(dp) :: t456, t457, t458, t459, t460, t462, t463, t465
      real(dp) :: t468, t469, t472, t473, t474, t476, t477, t478
      real(dp) :: t479, t480, t482, t483, t485, t486, t487, t491
      real(dp) :: t496, t500, t501, t502, t503, t505, t506, t507
      real(dp) :: t508, t509, t510, t511, t512, t513, t514, t515
      real(dp) :: t516, t517, t518, t521, t522, t523, t525, t529
      real(dp) :: t530, t531, t532, t535, t539, t540, t541, t542
      real(dp) :: t543, t544, t545, t546, t547, t549, t551, t553
      real(dp) :: t555, t558, t559, t560, t561, t562, t564, t566
      real(dp) :: t571, t572, t573, t579, t585, t588, t591, t594
      real(dp) :: t596, t597, t602, t611, t613, t614, t615, t616
      real(dp) :: t617, t622, t623, t624, t628, t633, t637, t638
      real(dp) :: t642, t643, t644, t645, t651, t652, t653, t654
      real(dp) :: t655, t656, t657, t658, t659, t660, t661, t662
      real(dp) :: t663, t664, t665, t666, t667, t668, t669, t670
      real(dp) :: t671, t672, t673, t674, t675, t676, t677, t678
      real(dp) :: t679, t680, t683, t684, t686, t689, t693, t694
      real(dp) :: t697, t701, t702, t703, t704, t706, t708, t710
      real(dp) :: t714, t715, t719, t720, t722, t724, t725, t726
      real(dp) :: t727, t730, t738, t739, t740, t741, t745, t749
      real(dp) :: t750, t753, t757, t758, t759, t760, t761, t762
      real(dp) :: t763, t764, t765, t766, t767, t768, t769, t770
      real(dp) :: t771, t772
      t1 = m_cbrt_3
      t3 = m_cbrt_one_ov_pi
      t5 = m_cbrt_4
      t33 = m_pi_sq
      t71 = m_cbrt_2
      t4 = t1 * t3
      t6 = t5 * t5
      t34 = 0.1e1_dp / t33
      t72 = t71 - 0.1e1_dp
      t74 = 0.1e1_dp / t72 / 0.2e1_dp
      t83 = 0.9e1_dp * t72
      t116 = t4 * t6
      t124 = t3 * t6
      t133 = t1 * t1
      t135 = 0.1e1_dp / t3
      t339 = t3 * t3
      t340 = t339 * t5
      t402 = t133 * t339
      t7 = rho_a + rho_b
      t8 = xc_cbrt(t7)
      t9 = 0.1e1_dp / t8
      t10 = t6 * t9
      t11 = t4 * t10
      t12 = t11 / 0.4e1_dp
      t13 = sqrt(t11)
      t15 = t12 + 0.186372e1_dp * t13 + 0.129352e2_dp
      t16 = 0.1e1_dp / t15
      t20 = log(t4 * t10 * t16 / 0.4e1_dp)
      t21 = 0.310907e-1_dp * t20
      t22 = t13 + 0.372744e1_dp
      t25 = atan(0.61519908197590802322e1_dp / t22)
      t26 = 0.38783294878113014393e-1_dp * t25
      t27 = t13 / 0.2e1_dp
      t28 = t27 + 0.10498e0_dp
      t29 = t28 * t28
      t31 = log(t29 * t16)
      t32 = 0.96902277115443742139e-3_dp * t31
      t36 = t12 + 0.565535e0_dp * t13 + 0.130045e2_dp
      t37 = 0.1e1_dp / t36
      t41 = log(t4 * t10 * t37 / 0.4e1_dp)
      t42 = t13 + 0.113107e1_dp
      t45 = atan(0.71231089178181179908e1_dp / t42)
      t47 = t27 + 0.47584e-2_dp
      t48 = t47 * t47
      t50 = log(t48 * t37)
      t53 = t34 * (t41 + 0.317708004743941464e0_dp * t45 + 0.41403379428206274608e-3_dp * t50)
      t54 = rho_a - rho_b
      t55 = 0.1e1_dp / t7
      t56 = t54 * t55
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(zeta_tol)
      t60 = t59 * zeta_tol
      t61 = xc_cbrt(t57)
      t63 = merge(t60, t61 * t57, t58)
      t64 = 0.1e1_dp - t56
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t60, t66 * t64, t65)
      t69 = t63 + t68 - 0.2e1_dp
      t70 = t53 * t69
      t75 = t54 * t54
      t76 = t75 * t75
      t77 = t7 * t7
      t78 = t77 * t77
      t79 = 0.1e1_dp / t78
      t84 = t74 * (-t76 * t79 + 0.1e1_dp) * t83
      t86 = t70 * t84 / 0.24e2_dp
      t88 = t12 + 0.353021e1_dp * t13 + 0.180578e2_dp
      t89 = 0.1e1_dp / t88
      t93 = log(t4 * t10 * t89 / 0.4e1_dp)
      t95 = t13 + 0.706042e1_dp
      t98 = atan(0.473092690956011283e1_dp / t95)
      t100 = t27 + 0.325e0_dp
      t101 = t100 * t100
      t103 = log(t101 * t89)
      t105 = 0.1554535e-1_dp * t93 + 0.52491393169780936218e-1_dp * t98 + &
         0.22478670955426118383e-2_dp * t103 - t21 - t26 - t32
      t106 = t105 * t69
      t107 = t74 * t76
      t108 = t107 * t79
      t109 = t106 * t108
      t111 = 0.1e1_dp / t8 / t7
      t112 = t6 * t111
      t117 = t15 * t15
      t118 = 0.1e1_dp / t117
      t119 = t9 * t118
      t120 = t4 * t112
      t121 = t120 / 0.12e2_dp
      t122 = 0.1e1_dp / t13
      t123 = t122 * t1
      t126 = t123 * t124 * t111
      t128 = -t121 - 0.31062e0_dp * t126
      t136 = (-t4 * t112 * t16 / 0.12e2_dp - t116 * t119 * t128 / 0.4e1_dp) * t133 * t135
      t137 = t5 * t8
      t138 = t137 * t15
      t139 = t136 * t138
      t140 = 0.10363566666666666667e-1_dp * t139
      t141 = t22 * t22
      t142 = 0.1e1_dp / t141
      t144 = t142 * t122 * t1
      t146 = 0.378469910464e2_dp * t142 + 0.1e1_dp
      t147 = 0.1e1_dp / t146
      t150 = t144 * t124 * t111 * t147
      t151 = 0.39765745675026770179e-1_dp * t150
      t152 = t28 * t16
      t153 = t152 * t122
      t156 = t29 * t118
      t158 = -t153 * t120 / 0.6e1_dp - t156 * t128
      t159 = 0.1e1_dp / t29
      t160 = t158 * t159
      t161 = t160 * t15
      t162 = 0.96902277115443742139e-3_dp * t161
      t166 = t36 * t36
      t167 = 0.1e1_dp / t166
      t168 = t9 * t167
      t170 = -t121 - 0.94255833333333333334e-1_dp * t126
      t176 = (-t4 * t112 * t37 / 0.12e2_dp - t116 * t168 * t170 / 0.4e1_dp) * t133 * t135
      t177 = t137 * t36
      t180 = t42 * t42
      t181 = 0.1e1_dp / t180
      t183 = t181 * t122 * t1
      t185 = 0.50738680655100000001e2_dp * t181 + 0.1e1_dp
      t186 = 0.1e1_dp / t185
      t191 = t47 * t37
      t192 = t191 * t122
      t195 = t48 * t167
      t197 = -t192 * t120 / 0.6e1_dp - t195 * t170
      t198 = 0.1e1_dp / t48
      t199 = t197 * t198
      t203 = t34 * (t176 * t177 / 0.3e1_dp + 0.37717812030896172975e0_dp * t183 * t124 * t111 &
         * t186 + 0.41403379428206274608e-3_dp * t199 * t36)
      t204 = t203 * t69
      t205 = t204 * t84
      t206 = t205 / 0.24e2_dp
      t207 = 0.1e1_dp / t77
      t208 = t54 * t207
      t209 = t55 - t208
      t212 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t61 * t209, t58)
      t213 = -t209
      t216 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t213, t65)
      t217 = t212 + t216
      t218 = t53 * t217
      t219 = t218 * t84
      t220 = t219 / 0.24e2_dp
      t221 = t75 * t54
      t222 = t221 * t79
      t223 = t78 * t7
      t224 = 0.1e1_dp / t223
      t225 = t76 * t224
      t229 = t74 * (-0.4e1_dp * t222 + 0.4e1_dp * t225) * t83
      t230 = t70 * t229
      t231 = t230 / 0.24e2_dp
      t235 = t88 * t88
      t236 = 0.1e1_dp / t235
      t237 = t9 * t236
      t239 = -t121 - 0.58836833333333333333e0_dp * t126
      t245 = (-t4 * t112 * t89 / 0.12e2_dp - t116 * t237 * t239 / 0.4e1_dp) * t133 * t135
      t246 = t137 * t88
      t249 = t95 * t95
      t250 = 0.1e1_dp / t249
      t252 = t250 * t122 * t1
      t254 = 0.223816694236e2_dp * t250 + 0.1e1_dp
      t255 = 0.1e1_dp / t254
      t260 = t100 * t89
      t261 = t260 * t122
      t264 = t101 * t236
      t266 = -t261 * t120 / 0.6e1_dp - t264 * t239
      t267 = 0.1e1_dp / t101
      t268 = t266 * t267
      t271 = 0.51817833333333333333e-2_dp * t245 * t246 + 0.41388824077869423261e-1_dp * t252 &
         * t124 * t111 * t255 + 0.22478670955426118383e-2_dp * t268 * t88 - t140 - t151 - t162
      t272 = t271 * t69
      t273 = t272 * t108
      t274 = t105 * t217
      t275 = t274 * t108
      t276 = t74 * t221
      t277 = t276 * t79
      t278 = t106 * t277
      t279 = 0.4e1_dp * t278
      t280 = t107 * t224
      t281 = t106 * t280
      t282 = 0.4e1_dp * t281
      t285 = -t55 - t208
      t288 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t61 * t285, t58)
      t289 = -t285
      t292 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t289, t65)
      t293 = t288 + t292
      t294 = t53 * t293
      t295 = t294 * t84
      t296 = t295 / 0.24e2_dp
      t300 = t74 * (0.4e1_dp * t222 + 0.4e1_dp * t225) * t83
      t301 = t70 * t300
      t302 = t301 / 0.24e2_dp
      t303 = t105 * t293
      t304 = t303 * t108
      t307 = 0.20727133333333333334e-1_dp * t139
      t308 = 0.79531491350053540358e-1_dp * t150
      t309 = 0.19380455423088748428e-2_dp * t161
      t310 = t205 / 0.12e2_dp
      t313 = 0.2e1_dp * t273
      t315 = 0.8e1_dp * t278
      t316 = 0.8e1_dp * t281
      t318 = 0.1e1_dp / t8 / t77
      t319 = t6 * t318
      t321 = t4 * t319 * t89
      t323 = t111 * t236
      t328 = 0.1e1_dp / t235 / t88
      t329 = t9 * t328
      t330 = t239 * t239
      t334 = t4 * t319
      t335 = t334 / 0.9e1_dp
      t337 = 0.1e1_dp / t13 / t11
      t338 = t337 * t133
      t341 = t8 * t8
      t343 = 0.1e1_dp / t341 / t77
      t345 = t338 * t340 * t343
      t348 = t123 * t124 * t318
      t350 = t335 - 0.39224555555555555555e0_dp * t345 + 0.7844911111111111111e0_dp * t348
      t356 = (t321 / 0.9e1_dp + t116 * t323 * t239 / 0.6e1_dp + t116 * t329 * t330 / 0.2e1_dp &
         - t116 * t237 * t350 / 0.4e1_dp) * t133 * t135
      t360 = t5 / t341
      t361 = t360 * t88
      t364 = t137 * t239
      t367 = t249 * t95
      t368 = 0.1e1_dp / t367
      t369 = t368 * t1
      t370 = t369 * t3
      t375 = t250 * t337 * t133
      t384 = t249 * t249
      t386 = 0.1e1_dp / t384 / t95
      t387 = t386 * t1
      t388 = t387 * t3
      t389 = t254 * t254
      t390 = 0.1e1_dp / t389
      t395 = t100 * t236
      t396 = t395 * t123
      t397 = t111 * t239
      t401 = t260 * t337
      t403 = t5 * t343
      t404 = t402 * t403
      t409 = t101 * t328
      t413 = t321 / 0.72e2_dp + t396 * t124 * t397 / 0.3e1_dp - t401 * t404 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t261 * t334 + 0.2e1_dp * t409 * t330 - t264 * t350
      t414 = t413 * t267
      t418 = 0.1e1_dp / t101 / t100
      t419 = t266 * t418
      t420 = t88 * t122
      t421 = t419 * t420
      t427 = t4 * t319 * t16
      t429 = t111 * t118
      t434 = 0.1e1_dp / t117 / t15
      t435 = t9 * t434
      t436 = t128 * t128
      t442 = t335 - 0.20708e0_dp * t345 + 0.41416e0_dp * t348
      t448 = (t427 / 0.9e1_dp + t116 * t429 * t128 / 0.6e1_dp + t116 * t435 * t436 / 0.2e1_dp &
         - t116 * t119 * t442 / 0.4e1_dp) * t133 * t135
      t449 = t448 * t138
      t450 = 0.10363566666666666667e-1_dp * t449
      t451 = t360 * t15
      t452 = t136 * t451
      t453 = 0.34545222222222222223e-2_dp * t452
      t454 = t137 * t128
      t455 = t136 * t454
      t456 = 0.10363566666666666667e-1_dp * t455
      t457 = t141 * t22
      t458 = 0.1e1_dp / t457
      t459 = t458 * t1
      t460 = t459 * t3
      t462 = t460 * t319 * t147
      t463 = 0.13255248558342256726e-1_dp * t462
      t465 = t142 * t337 * t133
      t468 = t465 * t340 * t343 * t147
      t469 = 0.26510497116684513453e-1_dp * t468
      t472 = t144 * t124 * t318 * t147
      t473 = 0.53020994233369026905e-1_dp * t472
      t474 = t141 * t141
      t476 = 0.1e1_dp / t474 / t22
      t477 = t476 * t1
      t478 = t477 * t3
      t479 = t146 * t146
      t480 = 0.1e1_dp / t479
      t482 = t478 * t319 * t480
      t483 = 0.50167127350538589834e0_dp * t482
      t485 = t28 * t118
      t486 = t485 * t123
      t487 = t111 * t128
      t491 = t152 * t337
      t496 = t29 * t434
      t500 = t427 / 0.72e2_dp + t486 * t124 * t487 / 0.3e1_dp - t491 * t404 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t153 * t334 + 0.2e1_dp * t496 * t436 - t156 * t442
      t501 = t500 * t159
      t502 = t501 * t15
      t503 = 0.96902277115443742139e-3_dp * t502
      t505 = 0.1e1_dp / t29 / t28
      t506 = t158 * t505
      t507 = t15 * t122
      t508 = t506 * t507
      t509 = t508 * t120
      t510 = 0.1615037951924062369e-3_dp * t509
      t511 = t160 * t128
      t512 = 0.96902277115443742139e-3_dp * t511
      t513 = 0.51817833333333333333e-2_dp * t356 * t246 + 0.17272611111111111111e-2_dp * t245 &
         * t361 + 0.51817833333333333333e-2_dp * t245 * t364 + 0.13796274692623141087e-1_dp * &
         t370 * t319 * t255 + 0.27592549385246282174e-1_dp * t375 * t340 * t343 * t255 - &
         0.55185098770492564348e-1_dp * t252 * t124 * t318 * t255 - &
         0.30878365944746984535e0_dp * t388 * t319 * t390 + 0.22478670955426118383e-2_dp * &
         t414 * t88 + 0.37464451592376863972e-3_dp * t421 * t120 + &
         0.22478670955426118383e-2_dp * t268 * t239 - t450 - t453 - t456 - t463 - t469 + t473 &
         + t483 - t503 - t510 - t512
      t514 = t513 * t69
      t515 = t514 * t108
      t516 = t61 * t61
      t517 = 0.1e1_dp / t516
      t518 = t209 * t209
      t521 = t77 * t7
      t522 = 0.1e1_dp / t521
      t523 = t54 * t522
      t525 = -0.2e1_dp * t207 + 0.2e1_dp * t523
      t529 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t517 * t518 + 0.4e1_dp / 0.3e1_dp * t61 * &
         t525, t58)
      t530 = t66 * t66
      t531 = 0.1e1_dp / t530
      t532 = t213 * t213
      t535 = -t525
      t539 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t531 * t532 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t535, t65)
      t540 = t529 + t539
      t541 = t105 * t540
      t542 = t541 * t108
      t543 = t53 * t540
      t544 = t543 * t84
      t545 = t544 / 0.24e2_dp
      t546 = t218 * t229
      t547 = t546 / 0.12e2_dp
      t549 = 0.12e2_dp * t75 * t79
      t551 = 0.32e2_dp * t221 * t224
      t553 = 0.1e1_dp / t78 / t77
      t555 = 0.2e2_dp * t76 * t553
      t558 = t74 * (-t549 + t551 - t555) * t83
      t559 = t70 * t558
      t560 = t559 / 0.24e2_dp
      t561 = t204 * t229
      t562 = t561 / 0.12e2_dp
      t564 = t4 * t319 * t37
      t566 = t111 * t167
      t571 = 0.1e1_dp / t166 / t36
      t572 = t9 * t571
      t573 = t170 * t170
      t579 = t335 - 0.62837222222222222223e-1_dp * t345 + 0.12567444444444444445e0_dp * t348
      t585 = (t564 / 0.9e1_dp + t116 * t566 * t170 / 0.6e1_dp + t116 * t572 * t573 / 0.2e1_dp &
         - t116 * t168 * t579 / 0.4e1_dp) * t133 * t135
      t588 = t360 * t36
      t591 = t137 * t170
      t594 = t180 * t42
      t596 = 0.1e1_dp / t594 * t1
      t597 = t596 * t3
      t602 = t181 * t337 * t133
      t611 = t180 * t180
      t613 = 0.1e1_dp / t611 / t42
      t614 = t613 * t1
      t615 = t614 * t3
      t616 = t185 * t185
      t617 = 0.1e1_dp / t616
      t622 = t47 * t167
      t623 = t622 * t123
      t624 = t111 * t170
      t628 = t191 * t337
      t633 = t48 * t571
      t637 = t564 / 0.72e2_dp + t623 * t124 * t624 / 0.3e1_dp - t628 * t404 / 0.9e1_dp + &
         0.2e1_dp / 0.9e1_dp * t192 * t334 + 0.2e1_dp * t633 * t573 - t195 * t579
      t638 = t637 * t198
      t642 = 0.1e1_dp / t48 / t47
      t643 = t197 * t642
      t644 = t36 * t122
      t645 = t643 * t644
      t651 = t34 * (t585 * t177 / 0.3e1_dp + t176 * t588 / 0.9e1_dp + t176 * t591 / 0.3e1_dp &
         + 0.12572604010298724325e0_dp * t597 * t319 * t186 + 0.2514520802059744865e0_dp * &
         t602 * t340 * t343 * t186 - 0.502904160411948973e0_dp * t183 * t124 * t318 * t186 - &
         0.63791733988157656508e1_dp * t615 * t319 * t617 + 0.41403379428206274608e-3_dp * &
         t638 * t36 + 0.69005632380343791013e-4_dp * t645 * t120 + &
         0.41403379428206274608e-3_dp * t199 * t170)
      t652 = t651 * t69
      t653 = t652 * t84
      t654 = t653 / 0.24e2_dp
      t655 = t203 * t217
      t656 = t655 * t84
      t657 = t656 / 0.12e2_dp
      t658 = t515 + t542 - t545 - t547 - t560 - t562 + t453 - t483 - t654 - t657 + t450 + &
         t456 + t463
      t659 = t272 * t277
      t660 = 0.8e1_dp * t659
      t661 = t272 * t280
      t662 = 0.8e1_dp * t661
      t663 = t274 * t277
      t664 = 0.8e1_dp * t663
      t665 = t274 * t280
      t666 = 0.8e1_dp * t665
      t667 = t74 * t75
      t668 = t667 * t79
      t669 = t106 * t668
      t670 = 0.12e2_dp * t669
      t671 = t276 * t224
      t672 = t106 * t671
      t673 = 0.32e2_dp * t672
      t674 = t107 * t553
      t675 = t106 * t674
      t676 = 0.2e2_dp * t675
      t677 = t271 * t217
      t678 = t677 * t108
      t679 = 0.2e1_dp * t678
      t680 = t503 + t512 + t510 + t469 - t473 + t660 - t662 + t664 - t666 + t670 - t673 + &
         t676 + t679
      t683 = t203 * t293
      t684 = t683 * t84
      t686 = t517 * t285
      t689 = t61 * t54
      t693 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t686 * t209 + 0.8e1_dp / 0.3e1_dp * t689 * &
         t522, t58)
      t694 = t531 * t289
      t697 = t66 * t54
      t701 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t694 * t213 - 0.8e1_dp / 0.3e1_dp * t697 * &
         t522, t65)
      t702 = t693 + t701
      t703 = t53 * t702
      t704 = t703 * t84
      t706 = t294 * t229
      t708 = t204 * t300
      t710 = t218 * t300
      t714 = t74 * (t549 - t555) * t83
      t715 = t70 * t714
      t719 = t515 - t684 / 0.24e2_dp - t704 / 0.24e2_dp - t706 / 0.24e2_dp - t708 / 0.24e2_dp &
         - t710 / 0.24e2_dp - t715 / 0.24e2_dp - t561 / 0.24e2_dp + t453 - t483 - t654 - t656 &
         / 0.24e2_dp + t450 + t456 + t463
      t720 = t303 * t277
      t722 = t303 * t280
      t724 = t105 * t702
      t725 = t724 * t108
      t726 = t271 * t293
      t727 = t726 * t108
      t730 = t503 + t512 + t510 + 0.4e1_dp * t720 - 0.4e1_dp * t722 + t469 - t473 + t725 + &
         t727 - t662 - 0.4e1_dp * t663 - 0.4e1_dp * t665 - t670 + t676 + t678
      t738 = t74 * (-t549 - t551 - t555) * t83
      t739 = t70 * t738
      t740 = t739 / 0.24e2_dp
      t741 = t285 * t285
      t745 = 0.2e1_dp * t207 + 0.2e1_dp * t523
      t749 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t517 * t741 + 0.4e1_dp / 0.3e1_dp * t61 * &
         t745, t58)
      t750 = t289 * t289
      t753 = -t745
      t757 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t531 * t750 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t753, t65)
      t758 = t749 + t757
      t759 = t53 * t758
      t760 = t759 * t84
      t761 = t760 / 0.24e2_dp
      t762 = t294 * t300
      t763 = t762 / 0.12e2_dp
      t764 = t684 / 0.12e2_dp
      t765 = t708 / 0.12e2_dp
      t766 = t515 - t740 - t761 - t763 - t764 - t765 + t453 - t483 - t654 + t450 + t456 + &
         t463 + t503
      t767 = t105 * t758
      t768 = t767 * t108
      t769 = 0.8e1_dp * t720
      t770 = 0.8e1_dp * t722
      t771 = 0.2e1_dp * t727
      t772 = t512 + t510 + t768 - t769 - t770 + t469 - t473 + t771 - t660 - t662 + t670 + &
         t673 + t676
      vrho_a = t21 + t26 + t32 - t86 + t109 + t7 * (t140 + t151 + t162 - t206 - t220 - t231 + &
         t273 + t275 + t279 - t282)
      vrho_b = t21 + t26 + t32 - t86 + t109 + t7 * (t140 + t151 + t162 - t206 - t296 - t302 + &
         t273 + t304 - t279 - t282)
      v2rho2_aa = t307 + t308 + t309 - t310 - t219 / 0.12e2_dp - t230 / 0.12e2_dp + t313 + &
         0.2e1_dp * t275 + t315 - t316 + t7 * (t658 + t680)
      v2rho2_ab = t307 + t308 + t309 - t310 - t220 - t231 + t313 + t275 - t316 - t296 - t302 &
         + t304 + t7 * (t719 + t730)
      v2rho2_bb = t307 + t308 + t309 - t310 - t295 / 0.12e2_dp - t301 / 0.12e2_dp + t313 + &
         0.2e1_dp * t304 - t315 - t316 + t7 * (t766 + t772)
   end subroutine vwn_vxc_fxc_polar_impl

end module trc_xc_vwn
