!
! LYP: GGA exchange-correlation kernel.
!
! GENERATED by tools/exchcxx_to_fortran.py from ExchCXX's
! include/exchcxx/impl/builtin/kernels/lyp.hpp -- do not edit.
!
! The arithmetic is ExchCXX's (MIT; Copyright (c) 2020-2024, The Regents
! of the University of California, through Lawrence Berkeley National
! Laboratory; portions Copyright (c) Microsoft Corporation), itself
! generated by Maple from the functional's definition. See
! https://github.com/wavefunction91/ExchCXX.
!
! Every routine is scalar, pure, and callable from `do concurrent`.
! The public `<name>_<what>_<polar>` routines apply the density and
! gradient thresholds the way ExchCXX's screening_interface.hpp does;
! the `_impl` bodies below them are the bare Maple expressions.
!
! Unpolarised routines take the TOTAL density and its gradient
! invariant; polarised ones take the two spin densities and the three
! gradient invariants. `eps` is the energy per particle, so the
! integrand is rho * eps.
!
module trc_xc_lyp
   use trc_boys, only: dp
   use trc_xc_util, only: enforce_polar_sigma_constraints, m_cbrt_2, m_cbrt_3, m_cbrt_pi_sq, &
      xc_cbrt
   implicit none
   private

   public :: lyp_exc_unpolar
   public :: lyp_exc_vxc_unpolar
   public :: lyp_fxc_unpolar
   public :: lyp_vxc_fxc_unpolar
   public :: lyp_exc_polar
   public :: lyp_exc_vxc_polar
   public :: lyp_fxc_polar
   public :: lyp_vxc_fxc_polar

   real(dp), parameter :: dens_tol = 1e-32_dp
   real(dp), parameter :: zeta_tol = 1e-15_dp
   real(dp), parameter :: sigma_tol = 2.1544346900318956e-43_dp
   real(dp), parameter :: tau_tol = 1e-20_dp
   real(dp), parameter :: a = 0.04918_dp
   real(dp), parameter :: b = 0.132_dp
   real(dp), parameter :: c = 0.2533_dp
   real(dp), parameter :: d = 0.349_dp

contains

   pure subroutine lyp_exc_unpolar(rho, sigma, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps
      real(dp) :: rho_c, sigma_c
      eps = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call lyp_exc_unpolar_impl(rho_c, sigma_c, eps)
      end if
   end subroutine lyp_exc_unpolar

   pure subroutine lyp_exc_vxc_unpolar(rho, sigma, eps, vrho, vsigma)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps, vrho, vsigma
      real(dp) :: rho_c, sigma_c
      eps = 0.0_dp
      vrho = 0.0_dp
      vsigma = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call lyp_exc_vxc_unpolar_impl(rho_c, sigma_c, eps, vrho, vsigma)
      end if
   end subroutine lyp_exc_vxc_unpolar

   pure subroutine lyp_fxc_unpolar(rho, sigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: v2rho2, v2rhosigma, v2sigma2
      real(dp) :: rho_c, sigma_c
      v2rho2 = 0.0_dp
      v2rhosigma = 0.0_dp
      v2sigma2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call lyp_fxc_unpolar_impl(rho_c, sigma_c, v2rho2, v2rhosigma, v2sigma2)
      end if
   end subroutine lyp_fxc_unpolar

   pure subroutine lyp_vxc_fxc_unpolar(rho, sigma, vrho, vsigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: vrho, vsigma, v2rho2, v2rhosigma, v2sigma2
      real(dp) :: rho_c, sigma_c
      vrho = 0.0_dp
      vsigma = 0.0_dp
      v2rho2 = 0.0_dp
      v2rhosigma = 0.0_dp
      v2sigma2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call lyp_vxc_fxc_unpolar_impl(rho_c, sigma_c, vrho, vsigma, v2rho2, v2rhosigma, &
            v2sigma2)
      end if
   end subroutine lyp_vxc_fxc_unpolar

   pure subroutine lyp_exc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      eps = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call lyp_exc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, eps)
      end if
   end subroutine lyp_exc_polar

   pure subroutine lyp_exc_vxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps, vrho_a, &
      vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      eps = 0.0_dp
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      vsigma_aa = 0.0_dp
      vsigma_ab = 0.0_dp
      vsigma_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call lyp_exc_vxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      end if
   end subroutine lyp_exc_vxc_polar

   pure subroutine lyp_fxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, v2rho2_aa, &
      v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
      v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
      v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, &
         v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
         v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
         v2sigma2_bb_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      v2rhosigma_a_aa = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2rhosigma_b_bb = 0.0_dp
      v2sigma2_aa_aa = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
      v2sigma2_bb_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call lyp_fxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, &
            v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
            v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
            v2sigma2_bb_bb)
      end if
   end subroutine lyp_fxc_polar

   pure subroutine lyp_vxc_fxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, vrho_a, &
      vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
      v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, &
      v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, &
      v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, &
         v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
         v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
         v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      vsigma_aa = 0.0_dp
      vsigma_ab = 0.0_dp
      vsigma_bb = 0.0_dp
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      v2rhosigma_a_aa = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2rhosigma_b_bb = 0.0_dp
      v2sigma2_aa_aa = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
      v2sigma2_bb_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call lyp_vxc_fxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
            v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, &
            v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, &
            v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      end if
   end subroutine lyp_vxc_fxc_polar

   pure subroutine lyp_exc_unpolar_impl(rho, sigma, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps
      logical :: t26
      real(dp) :: t20, t23, t48, t21, t24, t49, t1, t2
      real(dp) :: t4, t5, t7, t8, t9, t10, t12, t13
      real(dp) :: t15, t16, t18, t27, t28, t29, t31, t35
      real(dp) :: t36, t37, t40, t41, t44, t45, t50, t53
      real(dp) :: t54, t56, t62
      t20 = m_cbrt_3
      t23 = m_cbrt_pi_sq
      t48 = m_cbrt_2
      t21 = t20 * t20
      t24 = t23 * t23
      t49 = t48 * t48
      t1 = xc_cbrt(rho)
      t2 = 0.1e1_dp / t1
      t4 = d * t2 + 0.1e1_dp
      t5 = 0.1e1_dp / t4
      t7 = exp(-c * t2)
      t8 = b * t7
      t9 = rho * rho
      t10 = t1 * t1
      t12 = 0.1e1_dp / t10 / t9
      t13 = sigma * t12
      t15 = d * t5 + c
      t16 = t15 * t2
      t18 = -0.1e1_dp / 0.72e2_dp - 0.7e1_dp / 0.72e2_dp * t16
      t26 = 0.1e1_dp <= zeta_tol
      t27 = zeta_tol * zeta_tol
      t28 = xc_cbrt(zeta_tol)
      t29 = t28 * t28
      t31 = merge(t29 * t27, 1.0_dp, t26)
      t35 = 0.5e1_dp / 0.2e1_dp - t16 / 0.18e2_dp
      t36 = t35 * sigma
      t37 = t12 * t31
      t40 = t16 - 0.11e2_dp
      t41 = t40 * sigma
      t44 = merge(t29 * t27 * zeta_tol, 1.0_dp, t26)
      t45 = t12 * t44
      t50 = sigma * t49
      t53 = merge(t27, 1.0_dp, t26)
      t54 = t53 * sigma
      t56 = t49 * t12 * t31
      t62 = -t13 * t18 - 0.3e1_dp / 0.1e2_dp * t21 * t24 * t31 + t36 * t37 / 0.8e1_dp + t41 * &
         t45 / 0.144e3_dp - t48 * (0.4e1_dp / 0.3e1_dp * t50 * t37 - t54 * t56 / 0.2e1_dp) / &
         0.8e1_dp
      eps = a * (t8 * t5 * t62 - t5)
   end subroutine lyp_exc_unpolar_impl

   pure subroutine lyp_exc_vxc_unpolar_impl(rho, sigma, eps, vrho, vsigma)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps, vrho, vsigma
      logical :: t26
      real(dp) :: t20, t23, t48, t21, t24, t49, t74, t91
      real(dp) :: t1, t2, t4, t5, t7, t8, t9, t10
      real(dp) :: t12, t13, t15, t16, t18, t27, t28, t29
      real(dp) :: t31, t35, t36, t37, t40, t41, t44, t45
      real(dp) :: t50, t53, t54, t56, t62, t66, t67, t68
      real(dp) :: t69, t71, t75, t76, t77, t80, t81, t85
      real(dp) :: t87, t88, t92, t94, t97, t98, t100, t101
      real(dp) :: t104, t108, t109, t112, t118, t124, t127, t129
      real(dp) :: t138, t144, t145
      t20 = m_cbrt_3
      t23 = m_cbrt_pi_sq
      t48 = m_cbrt_2
      t21 = t20 * t20
      t24 = t23 * t23
      t49 = t48 * t48
      t74 = b * c
      t91 = d * d
      t1 = xc_cbrt(rho)
      t2 = 0.1e1_dp / t1
      t4 = d * t2 + 0.1e1_dp
      t5 = 0.1e1_dp / t4
      t7 = exp(-c * t2)
      t8 = b * t7
      t9 = rho * rho
      t10 = t1 * t1
      t12 = 0.1e1_dp / t10 / t9
      t13 = sigma * t12
      t15 = d * t5 + c
      t16 = t15 * t2
      t18 = -0.1e1_dp / 0.72e2_dp - 0.7e1_dp / 0.72e2_dp * t16
      t26 = 0.1e1_dp <= zeta_tol
      t27 = zeta_tol * zeta_tol
      t28 = xc_cbrt(zeta_tol)
      t29 = t28 * t28
      t31 = merge(t29 * t27, 1.0_dp, t26)
      t35 = 0.5e1_dp / 0.2e1_dp - t16 / 0.18e2_dp
      t36 = t35 * sigma
      t37 = t12 * t31
      t40 = t16 - 0.11e2_dp
      t41 = t40 * sigma
      t44 = merge(t29 * t27 * zeta_tol, 1.0_dp, t26)
      t45 = t12 * t44
      t50 = sigma * t49
      t53 = merge(t27, 1.0_dp, t26)
      t54 = t53 * sigma
      t56 = t49 * t12 * t31
      t62 = -t13 * t18 - 0.3e1_dp / 0.1e2_dp * t21 * t24 * t31 + t36 * t37 / 0.8e1_dp + t41 * &
         t45 / 0.144e3_dp - t48 * (0.4e1_dp / 0.3e1_dp * t50 * t37 - t54 * t56 / 0.2e1_dp) / &
         0.8e1_dp
      t66 = rho * a
      t67 = t4 * t4
      t68 = 0.1e1_dp / t67
      t69 = t68 * d
      t71 = 0.1e1_dp / t1 / rho
      t75 = t74 * t71
      t76 = t7 * t5
      t77 = t76 * t62
      t80 = t8 * t68
      t81 = t62 * d
      t85 = t9 * rho
      t87 = 0.1e1_dp / t10 / t85
      t88 = sigma * t87
      t92 = t91 * t68
      t94 = 0.1e1_dp / t10 / rho
      t97 = t15 * t71 - t92 * t94
      t98 = 0.7e1_dp / 0.216e3_dp * t97
      t100 = t97 / 0.54e2_dp
      t101 = t100 * sigma
      t104 = t87 * t31
      t108 = -t97 / 0.3e1_dp
      t109 = t108 * sigma
      t112 = t87 * t44
      t118 = t49 * t87 * t31
      t124 = 0.8e1_dp / 0.3e1_dp * t88 * t18 - t13 * t98 + t101 * t37 / 0.8e1_dp - t36 * t104 &
         / 0.3e1_dp + t109 * t45 / 0.144e3_dp - t41 * t112 / 0.54e2_dp - t48 * (-0.32e2_dp / &
         0.9e1_dp * t50 * t104 + 0.4e1_dp / 0.3e1_dp * t54 * t118) / 0.8e1_dp
      t127 = -t69 * t71 / 0.3e1_dp + t75 * t77 / 0.3e1_dp + t80 * t81 * t71 / 0.3e1_dp + t8 * &
         t5 * t124
      t129 = t66 * b
      t138 = t53 * t49
      t144 = -t12 * t18 + t35 * t12 * t31 / 0.8e1_dp + t40 * t12 * t44 / 0.144e3_dp - t48 * &
         (0.4e1_dp / 0.3e1_dp * t56 - t138 * t37 / 0.2e1_dp) / 0.8e1_dp
      t145 = t76 * t144
      eps = a * (t8 * t5 * t62 - t5)
      vrho = t66 * t127 + eps
      vsigma = t129 * t145
   end subroutine lyp_exc_vxc_unpolar_impl

   pure subroutine lyp_fxc_unpolar_impl(rho, sigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: v2rho2, v2rhosigma, v2sigma2
      logical :: t26
      real(dp) :: t20, t23, t48, t21, t24, t49, t74, t91
      real(dp) :: t160, t161, t193, t242, t1, t2, t4, t5
      real(dp) :: t7, t8, t9, t10, t12, t13, t15, t16
      real(dp) :: t18, t27, t28, t29, t31, t35, t36, t37
      real(dp) :: t40, t41, t44, t45, t50, t53, t54, t56
      real(dp) :: t62, t66, t67, t68, t69, t71, t75, t76
      real(dp) :: t77, t80, t81, t85, t87, t88, t92, t94
      real(dp) :: t97, t98, t100, t101, t104, t108, t109, t112
      real(dp) :: t118, t124, t127, t129, t138, t144, t145, t149
      real(dp) :: t150, t154, t157, t162, t165, t166, t167, t170
      real(dp) :: t173, t174, t178, t185, t187, t188, t194, t195
      real(dp) :: t196, t198, t200, t202, t207, t208, t213, t219
      real(dp) :: t220, t225, t231, t237, t240, t245, t246, t247
      real(dp) :: t252, t276, t277
      t20 = m_cbrt_3
      t23 = m_cbrt_pi_sq
      t48 = m_cbrt_2
      t21 = t20 * t20
      t24 = t23 * t23
      t49 = t48 * t48
      t74 = b * c
      t91 = d * d
      t160 = c * c
      t161 = b * t160
      t193 = t91 * d
      t242 = a * b
      t1 = xc_cbrt(rho)
      t2 = 0.1e1_dp / t1
      t4 = d * t2 + 0.1e1_dp
      t5 = 0.1e1_dp / t4
      t7 = exp(-c * t2)
      t8 = b * t7
      t9 = rho * rho
      t10 = t1 * t1
      t12 = 0.1e1_dp / t10 / t9
      t13 = sigma * t12
      t15 = d * t5 + c
      t16 = t15 * t2
      t18 = -0.1e1_dp / 0.72e2_dp - 0.7e1_dp / 0.72e2_dp * t16
      t26 = 0.1e1_dp <= zeta_tol
      t27 = zeta_tol * zeta_tol
      t28 = xc_cbrt(zeta_tol)
      t29 = t28 * t28
      t31 = merge(t29 * t27, 1.0_dp, t26)
      t35 = 0.5e1_dp / 0.2e1_dp - t16 / 0.18e2_dp
      t36 = t35 * sigma
      t37 = t12 * t31
      t40 = t16 - 0.11e2_dp
      t41 = t40 * sigma
      t44 = merge(t29 * t27 * zeta_tol, 1.0_dp, t26)
      t45 = t12 * t44
      t50 = sigma * t49
      t53 = merge(t27, 1.0_dp, t26)
      t54 = t53 * sigma
      t56 = t49 * t12 * t31
      t62 = -t13 * t18 - 0.3e1_dp / 0.1e2_dp * t21 * t24 * t31 + t36 * t37 / 0.8e1_dp + t41 * &
         t45 / 0.144e3_dp - t48 * (0.4e1_dp / 0.3e1_dp * t50 * t37 - t54 * t56 / 0.2e1_dp) / &
         0.8e1_dp
      t66 = rho * a
      t67 = t4 * t4
      t68 = 0.1e1_dp / t67
      t69 = t68 * d
      t71 = 0.1e1_dp / t1 / rho
      t75 = t74 * t71
      t76 = t7 * t5
      t77 = t76 * t62
      t80 = t8 * t68
      t81 = t62 * d
      t85 = t9 * rho
      t87 = 0.1e1_dp / t10 / t85
      t88 = sigma * t87
      t92 = t91 * t68
      t94 = 0.1e1_dp / t10 / rho
      t97 = t15 * t71 - t92 * t94
      t98 = 0.7e1_dp / 0.216e3_dp * t97
      t100 = t97 / 0.54e2_dp
      t101 = t100 * sigma
      t104 = t87 * t31
      t108 = -t97 / 0.3e1_dp
      t109 = t108 * sigma
      t112 = t87 * t44
      t118 = t49 * t87 * t31
      t124 = 0.8e1_dp / 0.3e1_dp * t88 * t18 - t13 * t98 + t101 * t37 / 0.8e1_dp - t36 * t104 &
         / 0.3e1_dp + t109 * t45 / 0.144e3_dp - t41 * t112 / 0.54e2_dp - t48 * (-0.32e2_dp / &
         0.9e1_dp * t50 * t104 + 0.4e1_dp / 0.3e1_dp * t54 * t118) / 0.8e1_dp
      t127 = -t69 * t71 / 0.3e1_dp + t75 * t77 / 0.3e1_dp + t80 * t81 * t71 / 0.3e1_dp + t8 * &
         t5 * t124
      t129 = t66 * b
      t138 = t53 * t49
      t144 = -t12 * t18 + t35 * t12 * t31 / 0.8e1_dp + t40 * t12 * t44 / 0.144e3_dp - t48 * &
         (0.4e1_dp / 0.3e1_dp * t56 - t138 * t37 / 0.2e1_dp) / 0.8e1_dp
      t145 = t76 * t144
      t149 = 0.1e1_dp / t67 / t4
      t150 = t149 * t91
      t154 = 0.1e1_dp / t1 / t9
      t157 = t74 * t154
      t162 = t161 * t12
      t165 = t74 * t12
      t166 = t7 * t68
      t167 = t166 * t81
      t170 = t76 * t124
      t173 = t8 * t149
      t174 = t62 * t91
      t178 = t124 * d
      t185 = t9 * t9
      t187 = 0.1e1_dp / t10 / t185
      t188 = sigma * t187
      t194 = t193 * t149
      t195 = 0.1e1_dp / t85
      t196 = t194 * t195
      t198 = t92 * t12
      t200 = t15 * t154
      t202 = -0.7e1_dp / 0.324e3_dp * t196 + 0.7e1_dp / 0.108e3_dp * t198 - 0.7e1_dp / &
         0.162e3_dp * t200
      t207 = -t196 / 0.81e2_dp + t198 / 0.27e2_dp - 0.2e1_dp / 0.81e2_dp * t200
      t208 = t207 * sigma
      t213 = t187 * t31
      t219 = 0.2e1_dp / 0.9e1_dp * t196 - 0.2e1_dp / 0.3e1_dp * t198 + 0.4e1_dp / 0.9e1_dp * &
         t200
      t220 = t219 * sigma
      t225 = t187 * t44
      t231 = t49 * t187 * t31
      t237 = -0.88e2_dp / 0.9e1_dp * t188 * t18 + 0.16e2_dp / 0.3e1_dp * t88 * t98 - t13 * &
         t202 + t208 * t37 / 0.8e1_dp - 0.2e1_dp / 0.3e1_dp * t101 * t104 + 0.11e2_dp / &
         0.9e1_dp * t36 * t213 + t220 * t45 / 0.144e3_dp - t109 * t112 / 0.27e2_dp + &
         0.11e2_dp / 0.162e3_dp * t41 * t225 - t48 * (0.352e3_dp / 0.27e2_dp * t50 * t213 - &
         0.44e2_dp / 0.9e1_dp * t54 * t231) / 0.8e1_dp
      t240 = -0.2e1_dp / 0.9e1_dp * t150 * t12 + 0.4e1_dp / 0.9e1_dp * t69 * t154 - 0.4e1_dp &
         / 0.9e1_dp * t157 * t77 + t162 * t77 / 0.9e1_dp + 0.2e1_dp / 0.9e1_dp * t165 * t167 &
         + 0.2e1_dp / 0.3e1_dp * t75 * t170 + 0.2e1_dp / 0.9e1_dp * t173 * t174 * t12 + &
         0.2e1_dp / 0.3e1_dp * t80 * t178 * t71 - 0.4e1_dp / 0.9e1_dp * t80 * t81 * t154 + t8 &
         * t5 * t237
      t245 = t2 * a * b
      t246 = c * t7
      t247 = t5 * t144
      t252 = t166 * t144 * d
      t276 = 0.8e1_dp / 0.3e1_dp * t87 * t18 - t12 * t98 + t100 * t12 * t31 / 0.8e1_dp - t35 &
         * t87 * t31 / 0.3e1_dp + t108 * t12 * t44 / 0.144e3_dp - t40 * t87 * t44 / 0.54e2_dp &
         - t48 * (-0.32e2_dp / 0.9e1_dp * t118 + 0.4e1_dp / 0.3e1_dp * t138 * t104) / 0.8e1_dp
      t277 = t76 * t276
      v2rho2 = 0.2e1_dp * a * t127 + t66 * t240
      v2rhosigma = t242 * t145 + t245 * t246 * t247 / 0.3e1_dp + t245 * t252 / 0.3e1_dp + &
         t129 * t277
      v2sigma2 = 0.e0_dp
   end subroutine lyp_fxc_unpolar_impl

   pure subroutine lyp_vxc_fxc_unpolar_impl(rho, sigma, vrho, vsigma, v2rho2, v2rhosigma, &
      v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: vrho, vsigma, v2rho2, v2rhosigma, v2sigma2
      logical :: t26
      real(dp) :: t20, t23, t48, t21, t24, t49, t74, t91
      real(dp) :: t160, t161, t193, t242, t1, t2, t4, t5
      real(dp) :: t7, t8, t9, t10, t12, t13, t15, t16
      real(dp) :: t18, t27, t28, t29, t31, t35, t36, t37
      real(dp) :: t40, t41, t44, t45, t50, t53, t54, t56
      real(dp) :: t62, tzk0, t66, t67, t68, t69, t71, t75
      real(dp) :: t76, t77, t80, t81, t85, t87, t88, t92
      real(dp) :: t94, t97, t98, t100, t101, t104, t108, t109
      real(dp) :: t112, t118, t124, t127, t129, t138, t144, t145
      real(dp) :: t149, t150, t154, t157, t162, t165, t166, t167
      real(dp) :: t170, t173, t174, t178, t185, t187, t188, t194
      real(dp) :: t195, t196, t198, t200, t202, t207, t208, t213
      real(dp) :: t219, t220, t225, t231, t237, t240, t245, t246
      real(dp) :: t247, t252, t276, t277
      t20 = m_cbrt_3
      t23 = m_cbrt_pi_sq
      t48 = m_cbrt_2
      t21 = t20 * t20
      t24 = t23 * t23
      t49 = t48 * t48
      t74 = b * c
      t91 = d * d
      t160 = c * c
      t161 = b * t160
      t193 = t91 * d
      t242 = a * b
      t1 = xc_cbrt(rho)
      t2 = 0.1e1_dp / t1
      t4 = d * t2 + 0.1e1_dp
      t5 = 0.1e1_dp / t4
      t7 = exp(-c * t2)
      t8 = b * t7
      t9 = rho * rho
      t10 = t1 * t1
      t12 = 0.1e1_dp / t10 / t9
      t13 = sigma * t12
      t15 = d * t5 + c
      t16 = t15 * t2
      t18 = -0.1e1_dp / 0.72e2_dp - 0.7e1_dp / 0.72e2_dp * t16
      t26 = 0.1e1_dp <= zeta_tol
      t27 = zeta_tol * zeta_tol
      t28 = xc_cbrt(zeta_tol)
      t29 = t28 * t28
      t31 = merge(t29 * t27, 1.0_dp, t26)
      t35 = 0.5e1_dp / 0.2e1_dp - t16 / 0.18e2_dp
      t36 = t35 * sigma
      t37 = t12 * t31
      t40 = t16 - 0.11e2_dp
      t41 = t40 * sigma
      t44 = merge(t29 * t27 * zeta_tol, 1.0_dp, t26)
      t45 = t12 * t44
      t50 = sigma * t49
      t53 = merge(t27, 1.0_dp, t26)
      t54 = t53 * sigma
      t56 = t49 * t12 * t31
      t62 = -t13 * t18 - 0.3e1_dp / 0.1e2_dp * t21 * t24 * t31 + t36 * t37 / 0.8e1_dp + t41 * &
         t45 / 0.144e3_dp - t48 * (0.4e1_dp / 0.3e1_dp * t50 * t37 - t54 * t56 / 0.2e1_dp) / &
         0.8e1_dp
      tzk0 = a * (t8 * t5 * t62 - t5)
      t66 = rho * a
      t67 = t4 * t4
      t68 = 0.1e1_dp / t67
      t69 = t68 * d
      t71 = 0.1e1_dp / t1 / rho
      t75 = t74 * t71
      t76 = t7 * t5
      t77 = t76 * t62
      t80 = t8 * t68
      t81 = t62 * d
      t85 = t9 * rho
      t87 = 0.1e1_dp / t10 / t85
      t88 = sigma * t87
      t92 = t91 * t68
      t94 = 0.1e1_dp / t10 / rho
      t97 = t15 * t71 - t92 * t94
      t98 = 0.7e1_dp / 0.216e3_dp * t97
      t100 = t97 / 0.54e2_dp
      t101 = t100 * sigma
      t104 = t87 * t31
      t108 = -t97 / 0.3e1_dp
      t109 = t108 * sigma
      t112 = t87 * t44
      t118 = t49 * t87 * t31
      t124 = 0.8e1_dp / 0.3e1_dp * t88 * t18 - t13 * t98 + t101 * t37 / 0.8e1_dp - t36 * t104 &
         / 0.3e1_dp + t109 * t45 / 0.144e3_dp - t41 * t112 / 0.54e2_dp - t48 * (-0.32e2_dp / &
         0.9e1_dp * t50 * t104 + 0.4e1_dp / 0.3e1_dp * t54 * t118) / 0.8e1_dp
      t127 = -t69 * t71 / 0.3e1_dp + t75 * t77 / 0.3e1_dp + t80 * t81 * t71 / 0.3e1_dp + t8 * &
         t5 * t124
      t129 = t66 * b
      t138 = t53 * t49
      t144 = -t12 * t18 + t35 * t12 * t31 / 0.8e1_dp + t40 * t12 * t44 / 0.144e3_dp - t48 * &
         (0.4e1_dp / 0.3e1_dp * t56 - t138 * t37 / 0.2e1_dp) / 0.8e1_dp
      t145 = t76 * t144
      t149 = 0.1e1_dp / t67 / t4
      t150 = t149 * t91
      t154 = 0.1e1_dp / t1 / t9
      t157 = t74 * t154
      t162 = t161 * t12
      t165 = t74 * t12
      t166 = t7 * t68
      t167 = t166 * t81
      t170 = t76 * t124
      t173 = t8 * t149
      t174 = t62 * t91
      t178 = t124 * d
      t185 = t9 * t9
      t187 = 0.1e1_dp / t10 / t185
      t188 = sigma * t187
      t194 = t193 * t149
      t195 = 0.1e1_dp / t85
      t196 = t194 * t195
      t198 = t92 * t12
      t200 = t15 * t154
      t202 = -0.7e1_dp / 0.324e3_dp * t196 + 0.7e1_dp / 0.108e3_dp * t198 - 0.7e1_dp / &
         0.162e3_dp * t200
      t207 = -t196 / 0.81e2_dp + t198 / 0.27e2_dp - 0.2e1_dp / 0.81e2_dp * t200
      t208 = t207 * sigma
      t213 = t187 * t31
      t219 = 0.2e1_dp / 0.9e1_dp * t196 - 0.2e1_dp / 0.3e1_dp * t198 + 0.4e1_dp / 0.9e1_dp * &
         t200
      t220 = t219 * sigma
      t225 = t187 * t44
      t231 = t49 * t187 * t31
      t237 = -0.88e2_dp / 0.9e1_dp * t188 * t18 + 0.16e2_dp / 0.3e1_dp * t88 * t98 - t13 * &
         t202 + t208 * t37 / 0.8e1_dp - 0.2e1_dp / 0.3e1_dp * t101 * t104 + 0.11e2_dp / &
         0.9e1_dp * t36 * t213 + t220 * t45 / 0.144e3_dp - t109 * t112 / 0.27e2_dp + &
         0.11e2_dp / 0.162e3_dp * t41 * t225 - t48 * (0.352e3_dp / 0.27e2_dp * t50 * t213 - &
         0.44e2_dp / 0.9e1_dp * t54 * t231) / 0.8e1_dp
      t240 = -0.2e1_dp / 0.9e1_dp * t150 * t12 + 0.4e1_dp / 0.9e1_dp * t69 * t154 - 0.4e1_dp &
         / 0.9e1_dp * t157 * t77 + t162 * t77 / 0.9e1_dp + 0.2e1_dp / 0.9e1_dp * t165 * t167 &
         + 0.2e1_dp / 0.3e1_dp * t75 * t170 + 0.2e1_dp / 0.9e1_dp * t173 * t174 * t12 + &
         0.2e1_dp / 0.3e1_dp * t80 * t178 * t71 - 0.4e1_dp / 0.9e1_dp * t80 * t81 * t154 + t8 &
         * t5 * t237
      t245 = t2 * a * b
      t246 = c * t7
      t247 = t5 * t144
      t252 = t166 * t144 * d
      t276 = 0.8e1_dp / 0.3e1_dp * t87 * t18 - t12 * t98 + t100 * t12 * t31 / 0.8e1_dp - t35 &
         * t87 * t31 / 0.3e1_dp + t108 * t12 * t44 / 0.144e3_dp - t40 * t87 * t44 / 0.54e2_dp &
         - t48 * (-0.32e2_dp / 0.9e1_dp * t118 + 0.4e1_dp / 0.3e1_dp * t138 * t104) / 0.8e1_dp
      t277 = t76 * t276
      vrho = t66 * t127 + tzk0
      vsigma = t129 * t145
      v2rho2 = 0.2e1_dp * a * t127 + t66 * t240
      v2rhosigma = t242 * t145 + t245 * t246 * t247 / 0.3e1_dp + t245 * t252 / 0.3e1_dp + &
         t129 * t277
      v2sigma2 = 0.e0_dp
   end subroutine lyp_vxc_fxc_unpolar_impl

   pure subroutine lyp_exc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps
      logical :: t41, t52
      real(dp) :: t32, t35, t62, t33, t36, t37, t1, t2
      real(dp) :: t3, t4, t5, t7, t8, t9, t11, t12
      real(dp) :: t15, t16, t18, t19, t21, t22, t24, t25
      real(dp) :: t27, t30, t38, t39, t40, t42, t43, t44
      real(dp) :: t45, t46, t47, t48, t49, t50, t51, t53
      real(dp) :: t54, t55, t56, t57, t58, t63, t65, t66
      real(dp) :: t67, t68, t70, t71, t72, t73, t74, t75
      real(dp) :: t77, t78, t79, t80, t81, t84, t86, t89
      real(dp) :: t93, t95, t96, t101, t102, t103, t106, t107
      real(dp) :: t108, t114
      t32 = m_cbrt_3
      t35 = m_cbrt_pi_sq
      t62 = m_cbrt_2
      t33 = t32 * t32
      t36 = t35 * t35
      t37 = t33 * t36
      t1 = rho_a - rho_b
      t2 = t1 * t1
      t3 = rho_a + rho_b
      t4 = t3 * t3
      t5 = 0.1e1_dp / t4
      t7 = -t2 * t5 + 0.1e1_dp
      t8 = xc_cbrt(t3)
      t9 = 0.1e1_dp / t8
      t11 = d * t9 + 0.1e1_dp
      t12 = 0.1e1_dp / t11
      t15 = exp(-c * t9)
      t16 = b * t15
      t18 = sigma_aa + 0.2e1_dp * sigma_ab + sigma_bb
      t19 = t8 * t8
      t21 = 0.1e1_dp / t19 / t4
      t22 = t18 * t21
      t24 = d * t12 + c
      t25 = t24 * t9
      t27 = 0.47e2_dp - 0.7e1_dp * t25
      t30 = t7 * t27 / 0.72e2_dp - 0.2e1_dp / 0.3e1_dp
      t38 = 0.1e1_dp / t3
      t39 = t1 * t38
      t40 = 0.1e1_dp + t39
      t41 = t40 <= zeta_tol
      t42 = zeta_tol * zeta_tol
      t43 = xc_cbrt(zeta_tol)
      t44 = t43 * t43
      t45 = t44 * t42
      t46 = t40 * t40
      t47 = xc_cbrt(t40)
      t48 = t47 * t47
      t49 = t48 * t46
      t50 = merge(t45, t49, t41)
      t51 = 0.1e1_dp - t39
      t52 = t51 <= zeta_tol
      t53 = t51 * t51
      t54 = xc_cbrt(t51)
      t55 = t54 * t54
      t56 = t55 * t53
      t57 = merge(t45, t56, t52)
      t58 = t50 + t57
      t63 = t62 * t7
      t65 = 0.5e1_dp / 0.2e1_dp - t25 / 0.18e2_dp
      t66 = rho_a * rho_a
      t67 = xc_cbrt(rho_a)
      t68 = t67 * t67
      t70 = 0.1e1_dp / t68 / t66
      t71 = sigma_aa * t70
      t72 = t71 * t50
      t73 = rho_b * rho_b
      t74 = xc_cbrt(rho_b)
      t75 = t74 * t74
      t77 = 0.1e1_dp / t75 / t73
      t78 = sigma_bb * t77
      t79 = t78 * t57
      t80 = t72 + t79
      t81 = t65 * t80
      t84 = t25 - 0.11e2_dp
      t86 = t44 * t42 * zeta_tol
      t89 = merge(t86, t48 * t46 * t40, t41)
      t93 = merge(t86, t55 * t53 * t51, t52)
      t95 = t71 * t89 + t78 * t93
      t96 = t84 * t95
      t101 = merge(t42, t46, t41)
      t102 = t101 * sigma_bb
      t103 = t77 * t57
      t106 = merge(t42, t53, t52)
      t107 = t106 * sigma_aa
      t108 = t70 * t50
      t114 = -t22 * t30 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t58 + t63 * t81 / 0.32e2_dp + t63 &
         * t96 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * t72 + 0.2e1_dp / 0.3e1_dp * t79 - &
         t102 * t103 / 0.4e1_dp - t107 * t108 / 0.4e1_dp) / 0.8e1_dp
      eps = a * (t16 * t12 * t114 - t7 * t12)
   end subroutine lyp_exc_polar_impl

   pure subroutine lyp_exc_vxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps, &
      vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb
      logical :: t41, t52
      real(dp) :: t32, t35, t62, t33, t36, t37, t134, t151
      real(dp) :: t1, t2, t3, t4, t5, t7, t8, t9
      real(dp) :: t11, t12, t15, t16, t18, t19, t21, t22
      real(dp) :: t24, t25, t27, t30, t38, t39, t40, t42
      real(dp) :: t43, t44, t45, t46, t47, t48, t49, t50
      real(dp) :: t51, t53, t54, t55, t56, t57, t58, t63
      real(dp) :: t65, t66, t67, t68, t70, t71, t72, t73
      real(dp) :: t74, t75, t77, t78, t79, t80, t81, t84
      real(dp) :: t86, t89, t93, t95, t96, t101, t102, t103
      real(dp) :: t106, t107, t108, t114, t118, t119, t120, t121
      real(dp) :: t122, t124, t126, t127, t128, t130, t131, t133
      real(dp) :: t135, t136, t137, t139, t140, t141, t144, t146
      real(dp) :: t147, t149, t152, t154, t157, t158, t159, t161
      real(dp) :: t166, t167, t168, t170, t171, t172, t173, t175
      real(dp) :: t176, t180, t183, t184, t186, t189, t190, t191
      real(dp) :: t193, t194, t195, t196, t202, t203, t205, t210
      real(dp) :: t214, t216, t217, t225, t226, t229, t234, t235
      real(dp) :: t238, t241, t247, t250, t253, t257, t262, t263
      real(dp) :: t265, t266, t267, t269, t270, t274, t277, t280
      real(dp) :: t281, t282, t284, t285, t286, t293, t299, t301
      real(dp) :: t302, t310, t311, t314, t317, t322, t323, t326
      real(dp) :: t332, t335, t337, t338, t339, t340, t343, t344
      real(dp) :: t348, t354, t355, t356, t357, t358, t361, t362
      real(dp) :: t365, t366, t370, t376, t377
      t32 = m_cbrt_3
      t35 = m_cbrt_pi_sq
      t62 = m_cbrt_2
      t33 = t32 * t32
      t36 = t35 * t35
      t37 = t33 * t36
      t134 = b * c
      t151 = d * d
      t1 = rho_a - rho_b
      t2 = t1 * t1
      t3 = rho_a + rho_b
      t4 = t3 * t3
      t5 = 0.1e1_dp / t4
      t7 = -t2 * t5 + 0.1e1_dp
      t8 = xc_cbrt(t3)
      t9 = 0.1e1_dp / t8
      t11 = d * t9 + 0.1e1_dp
      t12 = 0.1e1_dp / t11
      t15 = exp(-c * t9)
      t16 = b * t15
      t18 = sigma_aa + 0.2e1_dp * sigma_ab + sigma_bb
      t19 = t8 * t8
      t21 = 0.1e1_dp / t19 / t4
      t22 = t18 * t21
      t24 = d * t12 + c
      t25 = t24 * t9
      t27 = 0.47e2_dp - 0.7e1_dp * t25
      t30 = t7 * t27 / 0.72e2_dp - 0.2e1_dp / 0.3e1_dp
      t38 = 0.1e1_dp / t3
      t39 = t1 * t38
      t40 = 0.1e1_dp + t39
      t41 = t40 <= zeta_tol
      t42 = zeta_tol * zeta_tol
      t43 = xc_cbrt(zeta_tol)
      t44 = t43 * t43
      t45 = t44 * t42
      t46 = t40 * t40
      t47 = xc_cbrt(t40)
      t48 = t47 * t47
      t49 = t48 * t46
      t50 = merge(t45, t49, t41)
      t51 = 0.1e1_dp - t39
      t52 = t51 <= zeta_tol
      t53 = t51 * t51
      t54 = xc_cbrt(t51)
      t55 = t54 * t54
      t56 = t55 * t53
      t57 = merge(t45, t56, t52)
      t58 = t50 + t57
      t63 = t62 * t7
      t65 = 0.5e1_dp / 0.2e1_dp - t25 / 0.18e2_dp
      t66 = rho_a * rho_a
      t67 = xc_cbrt(rho_a)
      t68 = t67 * t67
      t70 = 0.1e1_dp / t68 / t66
      t71 = sigma_aa * t70
      t72 = t71 * t50
      t73 = rho_b * rho_b
      t74 = xc_cbrt(rho_b)
      t75 = t74 * t74
      t77 = 0.1e1_dp / t75 / t73
      t78 = sigma_bb * t77
      t79 = t78 * t57
      t80 = t72 + t79
      t81 = t65 * t80
      t84 = t25 - 0.11e2_dp
      t86 = t44 * t42 * zeta_tol
      t89 = merge(t86, t48 * t46 * t40, t41)
      t93 = merge(t86, t55 * t53 * t51, t52)
      t95 = t71 * t89 + t78 * t93
      t96 = t84 * t95
      t101 = merge(t42, t46, t41)
      t102 = t101 * sigma_bb
      t103 = t77 * t57
      t106 = merge(t42, t53, t52)
      t107 = t106 * sigma_aa
      t108 = t70 * t50
      t114 = -t22 * t30 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t58 + t63 * t81 / 0.32e2_dp + t63 &
         * t96 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * t72 + 0.2e1_dp / 0.3e1_dp * t79 - &
         t102 * t103 / 0.4e1_dp - t107 * t108 / 0.4e1_dp) / 0.8e1_dp
      t118 = t3 * a
      t119 = t1 * t5
      t120 = t4 * t3
      t121 = 0.1e1_dp / t120
      t122 = t2 * t121
      t124 = -0.2e1_dp * t119 + 0.2e1_dp * t122
      t126 = t11 * t11
      t127 = 0.1e1_dp / t126
      t128 = t7 * t127
      t130 = 0.1e1_dp / t8 / t3
      t131 = d * t130
      t133 = t128 * t131 / 0.3e1_dp
      t135 = t134 * t130
      t136 = t15 * t12
      t137 = t136 * t114
      t139 = t135 * t137 / 0.3e1_dp
      t140 = t16 * t127
      t141 = t114 * d
      t144 = t140 * t141 * t130 / 0.3e1_dp
      t146 = 0.1e1_dp / t19 / t120
      t147 = t18 * t146
      t149 = 0.8e1_dp / 0.3e1_dp * t147 * t30
      t152 = t151 * t127
      t154 = 0.1e1_dp / t19 / t3
      t157 = t24 * t130 - t152 * t154
      t158 = 0.7e1_dp / 0.3e1_dp * t157
      t159 = t7 * t158
      t161 = t124 * t27 / 0.72e2_dp + t159 / 0.72e2_dp
      t166 = t48 * t40
      t167 = t38 - t119
      t168 = t166 * t167
      t170 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t168, t41)
      t171 = t55 * t51
      t172 = -t167
      t173 = t171 * t172
      t175 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t173, t52)
      t176 = t170 + t175
      t180 = t62 * t124
      t183 = t157 / 0.54e2_dp
      t184 = t183 * t80
      t186 = t63 * t184 / 0.32e2_dp
      t189 = 0.1e1_dp / t68 / t66 / rho_a
      t190 = sigma_aa * t189
      t191 = t190 * t50
      t193 = t71 * t170
      t194 = t78 * t175
      t195 = -0.8e1_dp / 0.3e1_dp * t191 + t193 + t194
      t196 = t65 * t195
      t202 = -t157 / 0.3e1_dp
      t203 = t202 * t95
      t205 = t63 * t203 / 0.576e3_dp
      t210 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t49 * t167, t41)
      t214 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t56 * t172, t52)
      t216 = -0.8e1_dp / 0.3e1_dp * t190 * t89 + t71 * t210 + t78 * t214
      t217 = t84 * t216
      t225 = merge(0.0_dp, 0.2e1_dp * t40 * t167, t41)
      t226 = t225 * sigma_bb
      t229 = t77 * t175
      t234 = merge(0.0_dp, 0.2e1_dp * t51 * t172, t52)
      t235 = t234 * sigma_aa
      t238 = t189 * t50
      t241 = t70 * t170
      t247 = t149 - t22 * t161 - 0.3e1_dp / 0.2e2_dp * t37 * t124 * t58 - 0.3e1_dp / 0.2e2_dp &
         * t37 * t7 * t176 + t180 * t81 / 0.32e2_dp + t186 + t63 * t196 / 0.32e2_dp + t180 * &
         t96 / 0.576e3_dp + t205 + t63 * t217 / 0.576e3_dp - t62 * (-0.16e2_dp / 0.9e1_dp * &
         t191 + 0.2e1_dp / 0.3e1_dp * t193 + 0.2e1_dp / 0.3e1_dp * t194 - t226 * t103 / &
         0.4e1_dp - t102 * t229 / 0.4e1_dp - t235 * t108 / 0.4e1_dp + 0.2e1_dp / 0.3e1_dp * &
         t107 * t238 - t107 * t241 / 0.4e1_dp) / 0.8e1_dp
      t250 = t16 * t12 * t247 - t124 * t12 - t133 + t139 + t144
      t253 = 0.2e1_dp * t119 + 0.2e1_dp * t122
      t257 = t253 * t27 / 0.72e2_dp + t159 / 0.72e2_dp
      t262 = -t38 - t119
      t263 = t166 * t262
      t265 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t263, t41)
      t266 = -t262
      t267 = t171 * t266
      t269 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t267, t52)
      t270 = t265 + t269
      t274 = t62 * t253
      t277 = t71 * t265
      t280 = 0.1e1_dp / t75 / t73 / rho_b
      t281 = sigma_bb * t280
      t282 = t281 * t57
      t284 = t78 * t269
      t285 = t277 - 0.8e1_dp / 0.3e1_dp * t282 + t284
      t286 = t65 * t285
      t293 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t49 * t262, t41)
      t299 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t56 * t266, t52)
      t301 = t71 * t293 - 0.8e1_dp / 0.3e1_dp * t281 * t93 + t78 * t299
      t302 = t84 * t301
      t310 = merge(0.0_dp, 0.2e1_dp * t40 * t262, t41)
      t311 = t310 * sigma_bb
      t314 = t280 * t57
      t317 = t77 * t269
      t322 = merge(0.0_dp, 0.2e1_dp * t51 * t266, t52)
      t323 = t322 * sigma_aa
      t326 = t70 * t265
      t332 = t149 - t22 * t257 - 0.3e1_dp / 0.2e2_dp * t37 * t253 * t58 - 0.3e1_dp / 0.2e2_dp &
         * t37 * t7 * t270 + t274 * t81 / 0.32e2_dp + t186 + t63 * t286 / 0.32e2_dp + t274 * &
         t96 / 0.576e3_dp + t205 + t63 * t302 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * &
         t277 - 0.16e2_dp / 0.9e1_dp * t282 + 0.2e1_dp / 0.3e1_dp * t284 - t311 * t103 / &
         0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t102 * t314 - t102 * t317 / 0.4e1_dp - t323 * t108 &
         / 0.4e1_dp - t107 * t326 / 0.4e1_dp) / 0.8e1_dp
      t335 = t16 * t12 * t332 - t253 * t12 - t133 + t139 + t144
      t337 = t118 * b
      t338 = t21 * t30
      t339 = t65 * t70
      t340 = t339 * t50
      t343 = t84 * t70
      t344 = t343 * t89
      t348 = t106 * t70
      t354 = -t338 + t63 * t340 / 0.32e2_dp + t63 * t344 / 0.576e3_dp - t62 * (0.2e1_dp / &
         0.3e1_dp * t108 - t348 * t50 / 0.4e1_dp) / 0.8e1_dp
      t355 = t136 * t354
      t356 = t154 * a
      t357 = t356 * b
      t358 = t136 * t30
      t361 = t65 * t77
      t362 = t361 * t57
      t365 = t84 * t77
      t366 = t365 * t93
      t370 = t101 * t77
      t376 = -t338 + t63 * t362 / 0.32e2_dp + t63 * t366 / 0.576e3_dp - t62 * (0.2e1_dp / &
         0.3e1_dp * t103 - t370 * t57 / 0.4e1_dp) / 0.8e1_dp
      t377 = t136 * t376
      eps = a * (t16 * t12 * t114 - t7 * t12)
      vrho_a = t118 * t250 + eps
      vrho_b = t118 * t335 + eps
      vsigma_aa = t337 * t355
      vsigma_ab = -0.2e1_dp * t357 * t358
      vsigma_bb = t337 * t377
   end subroutine lyp_exc_vxc_polar_impl

   pure subroutine lyp_fxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, v2rho2_aa, &
      v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
      v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
      v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, &
         v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
         v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
         v2sigma2_bb_bb
      logical :: t41, t52
      real(dp) :: t32, t35, t62, t33, t36, t37, t134, t151
      real(dp) :: t406, t407, t470, t899, t1, t2, t3, t4
      real(dp) :: t5, t7, t8, t9, t11, t12, t15, t16
      real(dp) :: t18, t19, t21, t22, t24, t25, t27, t30
      real(dp) :: t38, t39, t40, t42, t43, t44, t45, t46
      real(dp) :: t47, t48, t49, t50, t51, t53, t54, t55
      real(dp) :: t56, t57, t58, t63, t65, t66, t67, t68
      real(dp) :: t70, t71, t72, t73, t74, t75, t77, t78
      real(dp) :: t79, t80, t81, t84, t86, t89, t93, t95
      real(dp) :: t96, t101, t102, t103, t106, t107, t108, t114
      real(dp) :: t118, t119, t120, t121, t122, t124, t126, t127
      real(dp) :: t128, t130, t131, t133, t135, t136, t137, t139
      real(dp) :: t140, t141, t144, t146, t147, t149, t152, t154
      real(dp) :: t157, t158, t159, t161, t166, t167, t168, t170
      real(dp) :: t171, t172, t173, t175, t176, t180, t183, t184
      real(dp) :: t186, t189, t190, t191, t193, t194, t195, t196
      real(dp) :: t202, t203, t205, t210, t214, t216, t217, t225
      real(dp) :: t226, t229, t234, t235, t238, t241, t247, t250
      real(dp) :: t253, t257, t262, t263, t265, t266, t267, t269
      real(dp) :: t270, t274, t277, t280, t281, t282, t284, t285
      real(dp) :: t286, t293, t299, t301, t302, t310, t311, t314
      real(dp) :: t317, t322, t323, t326, t332, t335, t337, t338
      real(dp) :: t339, t340, t343, t344, t348, t354, t355, t356
      real(dp) :: t357, t358, t361, t362, t365, t366, t370, t376
      real(dp) :: t377, t378, t380, t381, t382, t383, t384, t386
      real(dp) :: t387, t389, t390, t393, t394, t395, t397, t399
      real(dp) :: t400, t402, t403, t405, t408, t410, t411, t412
      real(dp) :: t413, t415, t416, t417, t419, t420, t423, t424
      real(dp) :: t426, t430, t432, t433, t435, t442, t443, t446
      real(dp) :: t450, t451, t452, t454, t458, t459, t463, t466
      real(dp) :: t471, t472, t474, t476, t478, t479, t481, t482
      real(dp) :: t483, t485, t487, t488, t489, t491, t493, t494
      real(dp) :: t495, t496, t501, t508, t509, t511, t512, t513
      real(dp) :: t524, t531, t533, t534, t537, t541, t546, t547
      real(dp) :: t548, t549, t558, t559, t564, t570, t571, t578
      real(dp) :: t581, t584, t587, t590, t593, t595, t596, t598
      real(dp) :: t599, t604, t605, t607, t609, t611, t613, t616
      real(dp) :: t620, t621, t623, t625, t628, t632, t633, t637
      real(dp) :: t641, t642, t649, t654, t659, t663, t664, t673
      real(dp) :: t676, t679, t683, t685, t687, t690, t694, t697
      real(dp) :: t703, t704, t708, t709, t714, t715, t721, t722
      real(dp) :: t728, t732, t738, t742, t744, t745, t761, t762
      real(dp) :: t765, t768, t784, t785, t788, t789, t792, t793
      real(dp) :: t794, t796, t797, t800, t801, t805, t810, t811
      real(dp) :: t813, t814, t815, t817, t819, t820, t821, t833
      real(dp) :: t844, t846, t847, t853, t862, t863, t870, t873
      real(dp) :: t876, t882, t883, t888, t891, t894, t897, t900
      real(dp) :: t902, t903, t904, t907, t909, t911, t913, t914
      real(dp) :: t917, t918, t920, t921, t922, t925, t930, t931
      real(dp) :: t933, t934, t935, t938, t943, t946, t954, t955
      real(dp) :: t958, t960, t961, t962, t963, t964, t966, t968
      real(dp) :: t970, t971, t974, t975, t978, t980, t982, t985
      real(dp) :: t986, t988, t989, t994, t995, t997, t998, t1002
      real(dp) :: t1010, t1011, t1013, t1016, t1021, t1025, t1033, t1034
      real(dp) :: t1036, t1041, t1042, t1045, t1050, t1051, t1054, t1059
      real(dp) :: t1062, t1070, t1071
      t32 = m_cbrt_3
      t35 = m_cbrt_pi_sq
      t62 = m_cbrt_2
      t33 = t32 * t32
      t36 = t35 * t35
      t37 = t33 * t36
      t134 = b * c
      t151 = d * d
      t406 = c * c
      t407 = b * t406
      t470 = t151 * d
      t899 = a * b
      t1 = rho_a - rho_b
      t2 = t1 * t1
      t3 = rho_a + rho_b
      t4 = t3 * t3
      t5 = 0.1e1_dp / t4
      t7 = -t2 * t5 + 0.1e1_dp
      t8 = xc_cbrt(t3)
      t9 = 0.1e1_dp / t8
      t11 = d * t9 + 0.1e1_dp
      t12 = 0.1e1_dp / t11
      t15 = exp(-c * t9)
      t16 = b * t15
      t18 = sigma_aa + 0.2e1_dp * sigma_ab + sigma_bb
      t19 = t8 * t8
      t21 = 0.1e1_dp / t19 / t4
      t22 = t18 * t21
      t24 = d * t12 + c
      t25 = t24 * t9
      t27 = 0.47e2_dp - 0.7e1_dp * t25
      t30 = t7 * t27 / 0.72e2_dp - 0.2e1_dp / 0.3e1_dp
      t38 = 0.1e1_dp / t3
      t39 = t1 * t38
      t40 = 0.1e1_dp + t39
      t41 = t40 <= zeta_tol
      t42 = zeta_tol * zeta_tol
      t43 = xc_cbrt(zeta_tol)
      t44 = t43 * t43
      t45 = t44 * t42
      t46 = t40 * t40
      t47 = xc_cbrt(t40)
      t48 = t47 * t47
      t49 = t48 * t46
      t50 = merge(t45, t49, t41)
      t51 = 0.1e1_dp - t39
      t52 = t51 <= zeta_tol
      t53 = t51 * t51
      t54 = xc_cbrt(t51)
      t55 = t54 * t54
      t56 = t55 * t53
      t57 = merge(t45, t56, t52)
      t58 = t50 + t57
      t63 = t62 * t7
      t65 = 0.5e1_dp / 0.2e1_dp - t25 / 0.18e2_dp
      t66 = rho_a * rho_a
      t67 = xc_cbrt(rho_a)
      t68 = t67 * t67
      t70 = 0.1e1_dp / t68 / t66
      t71 = sigma_aa * t70
      t72 = t71 * t50
      t73 = rho_b * rho_b
      t74 = xc_cbrt(rho_b)
      t75 = t74 * t74
      t77 = 0.1e1_dp / t75 / t73
      t78 = sigma_bb * t77
      t79 = t78 * t57
      t80 = t72 + t79
      t81 = t65 * t80
      t84 = t25 - 0.11e2_dp
      t86 = t44 * t42 * zeta_tol
      t89 = merge(t86, t48 * t46 * t40, t41)
      t93 = merge(t86, t55 * t53 * t51, t52)
      t95 = t71 * t89 + t78 * t93
      t96 = t84 * t95
      t101 = merge(t42, t46, t41)
      t102 = t101 * sigma_bb
      t103 = t77 * t57
      t106 = merge(t42, t53, t52)
      t107 = t106 * sigma_aa
      t108 = t70 * t50
      t114 = -t22 * t30 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t58 + t63 * t81 / 0.32e2_dp + t63 &
         * t96 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * t72 + 0.2e1_dp / 0.3e1_dp * t79 - &
         t102 * t103 / 0.4e1_dp - t107 * t108 / 0.4e1_dp) / 0.8e1_dp
      t118 = t3 * a
      t119 = t1 * t5
      t120 = t4 * t3
      t121 = 0.1e1_dp / t120
      t122 = t2 * t121
      t124 = -0.2e1_dp * t119 + 0.2e1_dp * t122
      t126 = t11 * t11
      t127 = 0.1e1_dp / t126
      t128 = t7 * t127
      t130 = 0.1e1_dp / t8 / t3
      t131 = d * t130
      t133 = t128 * t131 / 0.3e1_dp
      t135 = t134 * t130
      t136 = t15 * t12
      t137 = t136 * t114
      t139 = t135 * t137 / 0.3e1_dp
      t140 = t16 * t127
      t141 = t114 * d
      t144 = t140 * t141 * t130 / 0.3e1_dp
      t146 = 0.1e1_dp / t19 / t120
      t147 = t18 * t146
      t149 = 0.8e1_dp / 0.3e1_dp * t147 * t30
      t152 = t151 * t127
      t154 = 0.1e1_dp / t19 / t3
      t157 = t24 * t130 - t152 * t154
      t158 = 0.7e1_dp / 0.3e1_dp * t157
      t159 = t7 * t158
      t161 = t124 * t27 / 0.72e2_dp + t159 / 0.72e2_dp
      t166 = t48 * t40
      t167 = t38 - t119
      t168 = t166 * t167
      t170 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t168, t41)
      t171 = t55 * t51
      t172 = -t167
      t173 = t171 * t172
      t175 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t173, t52)
      t176 = t170 + t175
      t180 = t62 * t124
      t183 = t157 / 0.54e2_dp
      t184 = t183 * t80
      t186 = t63 * t184 / 0.32e2_dp
      t189 = 0.1e1_dp / t68 / t66 / rho_a
      t190 = sigma_aa * t189
      t191 = t190 * t50
      t193 = t71 * t170
      t194 = t78 * t175
      t195 = -0.8e1_dp / 0.3e1_dp * t191 + t193 + t194
      t196 = t65 * t195
      t202 = -t157 / 0.3e1_dp
      t203 = t202 * t95
      t205 = t63 * t203 / 0.576e3_dp
      t210 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t49 * t167, t41)
      t214 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t56 * t172, t52)
      t216 = -0.8e1_dp / 0.3e1_dp * t190 * t89 + t71 * t210 + t78 * t214
      t217 = t84 * t216
      t225 = merge(0.0_dp, 0.2e1_dp * t40 * t167, t41)
      t226 = t225 * sigma_bb
      t229 = t77 * t175
      t234 = merge(0.0_dp, 0.2e1_dp * t51 * t172, t52)
      t235 = t234 * sigma_aa
      t238 = t189 * t50
      t241 = t70 * t170
      t247 = t149 - t22 * t161 - 0.3e1_dp / 0.2e2_dp * t37 * t124 * t58 - 0.3e1_dp / 0.2e2_dp &
         * t37 * t7 * t176 + t180 * t81 / 0.32e2_dp + t186 + t63 * t196 / 0.32e2_dp + t180 * &
         t96 / 0.576e3_dp + t205 + t63 * t217 / 0.576e3_dp - t62 * (-0.16e2_dp / 0.9e1_dp * &
         t191 + 0.2e1_dp / 0.3e1_dp * t193 + 0.2e1_dp / 0.3e1_dp * t194 - t226 * t103 / &
         0.4e1_dp - t102 * t229 / 0.4e1_dp - t235 * t108 / 0.4e1_dp + 0.2e1_dp / 0.3e1_dp * &
         t107 * t238 - t107 * t241 / 0.4e1_dp) / 0.8e1_dp
      t250 = t16 * t12 * t247 - t124 * t12 - t133 + t139 + t144
      t253 = 0.2e1_dp * t119 + 0.2e1_dp * t122
      t257 = t253 * t27 / 0.72e2_dp + t159 / 0.72e2_dp
      t262 = -t38 - t119
      t263 = t166 * t262
      t265 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t263, t41)
      t266 = -t262
      t267 = t171 * t266
      t269 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t267, t52)
      t270 = t265 + t269
      t274 = t62 * t253
      t277 = t71 * t265
      t280 = 0.1e1_dp / t75 / t73 / rho_b
      t281 = sigma_bb * t280
      t282 = t281 * t57
      t284 = t78 * t269
      t285 = t277 - 0.8e1_dp / 0.3e1_dp * t282 + t284
      t286 = t65 * t285
      t293 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t49 * t262, t41)
      t299 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t56 * t266, t52)
      t301 = t71 * t293 - 0.8e1_dp / 0.3e1_dp * t281 * t93 + t78 * t299
      t302 = t84 * t301
      t310 = merge(0.0_dp, 0.2e1_dp * t40 * t262, t41)
      t311 = t310 * sigma_bb
      t314 = t280 * t57
      t317 = t77 * t269
      t322 = merge(0.0_dp, 0.2e1_dp * t51 * t266, t52)
      t323 = t322 * sigma_aa
      t326 = t70 * t265
      t332 = t149 - t22 * t257 - 0.3e1_dp / 0.2e2_dp * t37 * t253 * t58 - 0.3e1_dp / 0.2e2_dp &
         * t37 * t7 * t270 + t274 * t81 / 0.32e2_dp + t186 + t63 * t286 / 0.32e2_dp + t274 * &
         t96 / 0.576e3_dp + t205 + t63 * t302 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * &
         t277 - 0.16e2_dp / 0.9e1_dp * t282 + 0.2e1_dp / 0.3e1_dp * t284 - t311 * t103 / &
         0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t102 * t314 - t102 * t317 / 0.4e1_dp - t323 * t108 &
         / 0.4e1_dp - t107 * t326 / 0.4e1_dp) / 0.8e1_dp
      t335 = t16 * t12 * t332 - t253 * t12 - t133 + t139 + t144
      t337 = t118 * b
      t338 = t21 * t30
      t339 = t65 * t70
      t340 = t339 * t50
      t343 = t84 * t70
      t344 = t343 * t89
      t348 = t106 * t70
      t354 = -t338 + t63 * t340 / 0.32e2_dp + t63 * t344 / 0.576e3_dp - t62 * (0.2e1_dp / &
         0.3e1_dp * t108 - t348 * t50 / 0.4e1_dp) / 0.8e1_dp
      t355 = t136 * t354
      t356 = t154 * a
      t357 = t356 * b
      t358 = t136 * t30
      t361 = t65 * t77
      t362 = t361 * t57
      t365 = t84 * t77
      t366 = t365 * t93
      t370 = t101 * t77
      t376 = -t338 + t63 * t362 / 0.32e2_dp + t63 * t366 / 0.576e3_dp - t62 * (0.2e1_dp / &
         0.3e1_dp * t103 - t370 * t57 / 0.4e1_dp) / 0.8e1_dp
      t377 = t136 * t376
      t378 = a * t250
      t380 = 0.2e1_dp * t5
      t381 = t1 * t121
      t382 = 0.8e1_dp * t381
      t383 = t4 * t4
      t384 = 0.1e1_dp / t383
      t386 = 0.6e1_dp * t2 * t384
      t387 = -t380 + t382 - t386
      t389 = t124 * t127
      t390 = t389 * t131
      t393 = 0.1e1_dp / t126 / t11
      t394 = t7 * t393
      t395 = t151 * t21
      t397 = 0.2e1_dp / 0.9e1_dp * t394 * t395
      t399 = 0.1e1_dp / t8 / t4
      t400 = d * t399
      t402 = 0.4e1_dp / 0.9e1_dp * t128 * t400
      t403 = t134 * t399
      t405 = 0.4e1_dp / 0.9e1_dp * t403 * t137
      t408 = t407 * t21
      t410 = t408 * t137 / 0.9e1_dp
      t411 = t134 * t21
      t412 = t15 * t127
      t413 = t412 * t141
      t415 = 0.2e1_dp / 0.9e1_dp * t411 * t413
      t416 = t136 * t247
      t417 = t135 * t416
      t419 = t16 * t393
      t420 = t114 * t151
      t423 = 0.2e1_dp / 0.9e1_dp * t419 * t420 * t21
      t424 = t247 * d
      t426 = t140 * t424 * t130
      t430 = 0.4e1_dp / 0.9e1_dp * t140 * t141 * t399
      t432 = 0.1e1_dp / t19 / t383
      t433 = t18 * t432
      t435 = 0.88e2_dp / 0.9e1_dp * t433 * t30
      t442 = t167 * t167
      t443 = t48 * t442
      t446 = -0.2e1_dp * t5 + 0.2e1_dp * t381
      t450 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t443 + 0.8e1_dp / 0.3e1_dp * t166 * t446, t41)
      t451 = t172 * t172
      t452 = t55 * t451
      t454 = -t446
      t458 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t452 + 0.8e1_dp / 0.3e1_dp * t171 * t454, t52)
      t459 = t450 + t458
      t463 = t62 * t387
      t466 = t180 * t184
      t471 = t470 * t393
      t472 = t471 * t121
      t474 = t152 * t21
      t476 = t24 * t399
      t478 = -t472 / 0.81e2_dp + t474 / 0.27e2_dp - 0.2e1_dp / 0.81e2_dp * t476
      t479 = t478 * t80
      t481 = t63 * t479 / 0.32e2_dp
      t482 = t183 * t195
      t483 = t63 * t482
      t485 = t66 * t66
      t487 = 0.1e1_dp / t68 / t485
      t488 = sigma_aa * t487
      t489 = t488 * t50
      t491 = t190 * t170
      t493 = t71 * t450
      t494 = t78 * t458
      t495 = 0.88e2_dp / 0.9e1_dp * t489 - 0.16e2_dp / 0.3e1_dp * t491 + t493 + t494
      t496 = t65 * t495
      t501 = t180 * t203
      t508 = 0.2e1_dp / 0.9e1_dp * t472 - 0.2e1_dp / 0.3e1_dp * t474 + 0.4e1_dp / 0.9e1_dp * &
         t476
      t509 = t508 * t95
      t511 = t63 * t509 / 0.576e3_dp
      t512 = t202 * t216
      t513 = t63 * t512
      t524 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t166 * t442 + 0.11e2_dp / 0.3e1_dp * t49 * &
         t446, t41)
      t531 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t171 * t451 + 0.11e2_dp / 0.3e1_dp * t56 * &
         t454, t52)
      t533 = 0.88e2_dp / 0.9e1_dp * t488 * t89 - 0.16e2_dp / 0.3e1_dp * t190 * t210 + t71 * &
         t524 + t78 * t531
      t534 = t84 * t533
      t537 = t147 * t161
      t541 = t124 * t158
      t546 = -0.14e2_dp / 0.9e1_dp * t472 + 0.14e2_dp / 0.3e1_dp * t474 - 0.28e2_dp / &
         0.9e1_dp * t476
      t547 = t7 * t546
      t548 = t547 / 0.72e2_dp
      t549 = t387 * t27 / 0.72e2_dp + t541 / 0.36e2_dp + t548
      t558 = merge(0.0_dp, 0.2e1_dp * t40 * t446 + 0.2e1_dp * t442, t41)
      t559 = t558 * sigma_bb
      t564 = t77 * t458
      t570 = merge(0.0_dp, 0.2e1_dp * t51 * t454 + 0.2e1_dp * t451, t52)
      t571 = t570 * sigma_aa
      t578 = t487 * t50
      t581 = t189 * t170
      t584 = t70 * t450
      t587 = 0.176e3_dp / 0.27e2_dp * t489 - 0.32e2_dp / 0.9e1_dp * t491 + 0.2e1_dp / &
         0.3e1_dp * t493 + 0.2e1_dp / 0.3e1_dp * t494 - t559 * t103 / 0.4e1_dp - t226 * t229 &
         / 0.2e1_dp - t102 * t564 / 0.4e1_dp - t571 * t108 / 0.4e1_dp + 0.4e1_dp / 0.3e1_dp * &
         t235 * t238 - t235 * t241 / 0.2e1_dp - 0.22e2_dp / 0.9e1_dp * t107 * t578 + 0.4e1_dp &
         / 0.3e1_dp * t107 * t581 - t107 * t584 / 0.4e1_dp
      t590 = -t435 - 0.3e1_dp / 0.2e2_dp * t37 * t387 * t58 - 0.3e1_dp / 0.1e2_dp * t37 * &
         t124 * t176 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t459 + t463 * t81 / 0.32e2_dp + t466 &
         / 0.16e2_dp + t180 * t196 / 0.16e2_dp + t481 + t483 / 0.16e2_dp + t63 * t496 / &
         0.32e2_dp + t463 * t96 / 0.576e3_dp + t501 / 0.288e3_dp + t180 * t217 / 0.288e3_dp + &
         t511 + t513 / 0.288e3_dp + t63 * t534 / 0.576e3_dp + 0.16e2_dp / 0.3e1_dp * t537 - &
         t22 * t549 - t62 * t587 / 0.8e1_dp
      t593 = -t387 * t12 - 0.2e1_dp / 0.3e1_dp * t390 - t397 + t402 - t405 + t410 + t415 + &
         0.2e1_dp / 0.3e1_dp * t417 + t423 + 0.2e1_dp / 0.3e1_dp * t426 - t430 + t16 * t12 * &
         t590
      t595 = a * t335
      t596 = t380 - t386
      t598 = t253 * t127
      t599 = t598 * t131
      t604 = t136 * t332
      t605 = t135 * t604
      t607 = t332 * d
      t609 = t140 * t607 * t130
      t611 = t190 * t265
      t613 = t48 * t262
      t616 = t166 * t1
      t620 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t613 * t167 + 0.16e2_dp / 0.3e1_dp * t616 * &
         t121, t41)
      t621 = t71 * t620
      t623 = t281 * t175
      t625 = t55 * t266
      t628 = t171 * t1
      t632 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t625 * t172 - 0.16e2_dp / 0.3e1_dp * t628 * &
         t121, t52)
      t633 = t78 * t632
      t637 = t40 * t1
      t641 = merge(0.0_dp, 0.4e1_dp * t637 * t121 + 0.2e1_dp * t167 * t262, t41)
      t642 = t641 * sigma_bb
      t649 = t280 * t175
      t654 = t77 * t632
      t659 = t51 * t1
      t663 = merge(0.0_dp, -0.4e1_dp * t659 * t121 + 0.2e1_dp * t172 * t266, t52)
      t664 = t663 * sigma_aa
      t673 = t189 * t265
      t676 = t70 * t620
      t679 = -0.16e2_dp / 0.9e1_dp * t611 + 0.2e1_dp / 0.3e1_dp * t621 - 0.16e2_dp / 0.9e1_dp &
         * t623 + 0.2e1_dp / 0.3e1_dp * t633 - t642 * t103 / 0.4e1_dp - t311 * t229 / &
         0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t226 * t314 + 0.2e1_dp / 0.3e1_dp * t102 * t649 - &
         t226 * t317 / 0.4e1_dp - t102 * t654 / 0.4e1_dp - t664 * t108 / 0.4e1_dp + 0.2e1_dp &
         / 0.3e1_dp * t323 * t238 - t323 * t241 / 0.4e1_dp - t235 * t326 / 0.4e1_dp + &
         0.2e1_dp / 0.3e1_dp * t107 * t673 - t107 * t676 / 0.4e1_dp
      t683 = t253 * t158
      t685 = t596 * t27 / 0.72e2_dp + t541 / 0.72e2_dp + t547 / 0.72e2_dp + t683 / 0.72e2_dp
      t687 = t147 * t257
      t690 = t620 + t632
      t694 = t62 * t596
      t697 = t274 * t184
      t703 = t183 * t285
      t704 = t63 * t703
      t708 = -0.8e1_dp / 0.3e1_dp * t611 + t621 - 0.8e1_dp / 0.3e1_dp * t623 + t633
      t709 = t65 * t708
      t714 = -t62 * t679 / 0.8e1_dp - t22 * t685 + 0.8e1_dp / 0.3e1_dp * t687 + 0.8e1_dp / &
         0.3e1_dp * t537 - t435 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t690 + t694 * t81 / &
         0.32e2_dp + t697 / 0.32e2_dp + t274 * t196 / 0.32e2_dp + t180 * t286 / 0.32e2_dp + &
         t704 / 0.32e2_dp + t63 * t709 / 0.32e2_dp + t694 * t96 / 0.576e3_dp
      t715 = t274 * t203
      t721 = t202 * t301
      t722 = t63 * t721
      t728 = t49 * t1
      t732 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t263 * t167 + 0.22e2_dp / 0.3e1_dp * t728 * &
         t121, t41)
      t738 = t56 * t1
      t742 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t267 * t172 - 0.22e2_dp / 0.3e1_dp * t738 * &
         t121, t52)
      t744 = -0.8e1_dp / 0.3e1_dp * t190 * t293 + t71 * t732 - 0.8e1_dp / 0.3e1_dp * t281 * &
         t214 + t78 * t742
      t745 = t84 * t744
      t761 = t715 / 0.576e3_dp + t274 * t217 / 0.576e3_dp + t180 * t302 / 0.576e3_dp + t722 / &
         0.576e3_dp + t63 * t745 / 0.576e3_dp - 0.3e1_dp / 0.2e2_dp * t37 * t596 * t58 - &
         0.3e1_dp / 0.2e2_dp * t37 * t253 * t176 - 0.3e1_dp / 0.2e2_dp * t37 * t124 * t270 + &
         t511 + t513 / 0.576e3_dp + t466 / 0.32e2_dp + t481 + t483 / 0.32e2_dp + t501 / &
         0.576e3_dp
      t762 = t714 + t761
      t765 = -t596 * t12 - t599 / 0.3e1_dp - t390 / 0.3e1_dp - t397 + t402 - t405 + t410 + &
         t415 + t417 / 0.3e1_dp + t423 + t426 / 0.3e1_dp - t430 + t605 / 0.3e1_dp + t609 / &
         0.3e1_dp + t16 * t12 * t762
      t768 = -t380 - t382 - t386
      t784 = t262 * t262
      t785 = t48 * t784
      t788 = 0.2e1_dp * t5 + 0.2e1_dp * t381
      t789 = t166 * t788
      t792 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t785 + 0.8e1_dp / 0.3e1_dp * t789, t41)
      t793 = t266 * t266
      t794 = t55 * t793
      t796 = -t788
      t797 = t171 * t796
      t800 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t794 + 0.8e1_dp / 0.3e1_dp * t797, t52)
      t801 = t792 + t800
      t805 = t62 * t768
      t810 = t71 * t792
      t811 = t73 * t73
      t813 = 0.1e1_dp / t75 / t811
      t814 = sigma_bb * t813
      t815 = t814 * t57
      t817 = t281 * t269
      t819 = t78 * t800
      t820 = t810 + 0.88e2_dp / 0.9e1_dp * t815 - 0.16e2_dp / 0.3e1_dp * t817 + t819
      t821 = t65 * t820
      t833 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t166 * t784 + 0.11e2_dp / 0.3e1_dp * t49 * &
         t788, t41)
      t844 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t171 * t793 + 0.11e2_dp / 0.3e1_dp * t56 * &
         t796, t52)
      t846 = t71 * t833 + 0.88e2_dp / 0.9e1_dp * t814 * t93 - 0.16e2_dp / 0.3e1_dp * t281 * &
         t299 + t78 * t844
      t847 = t84 * t846
      t853 = t768 * t27 / 0.72e2_dp + t683 / 0.36e2_dp + t548
      t862 = merge(0.0_dp, 0.2e1_dp * t40 * t788 + 0.2e1_dp * t784, t41)
      t863 = t862 * sigma_bb
      t870 = t813 * t57
      t873 = t280 * t269
      t876 = t77 * t800
      t882 = merge(0.0_dp, 0.2e1_dp * t51 * t796 + 0.2e1_dp * t793, t52)
      t883 = t882 * sigma_aa
      t888 = t70 * t792
      t891 = 0.2e1_dp / 0.3e1_dp * t810 + 0.176e3_dp / 0.27e2_dp * t815 - 0.32e2_dp / &
         0.9e1_dp * t817 + 0.2e1_dp / 0.3e1_dp * t819 - t863 * t103 / 0.4e1_dp + 0.4e1_dp / &
         0.3e1_dp * t311 * t314 - t311 * t317 / 0.2e1_dp - 0.22e2_dp / 0.9e1_dp * t102 * t870 &
         + 0.4e1_dp / 0.3e1_dp * t102 * t873 - t102 * t876 / 0.4e1_dp - t883 * t108 / &
         0.4e1_dp - t323 * t326 / 0.2e1_dp - t107 * t888 / 0.4e1_dp
      t894 = -t435 + t481 + t511 + 0.16e2_dp / 0.3e1_dp * t687 + t697 / 0.16e2_dp + t704 / &
         0.16e2_dp + t715 / 0.288e3_dp + t722 / 0.288e3_dp - 0.3e1_dp / 0.2e2_dp * t37 * t768 &
         * t58 - 0.3e1_dp / 0.1e2_dp * t37 * t253 * t270 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * &
         t801 + t805 * t81 / 0.32e2_dp + t274 * t286 / 0.16e2_dp + t63 * t821 / 0.32e2_dp + &
         t805 * t96 / 0.576e3_dp + t274 * t302 / 0.288e3_dp + t63 * t847 / 0.576e3_dp - t22 * &
         t853 - t62 * t891 / 0.8e1_dp
      t897 = -t768 * t12 - 0.2e1_dp / 0.3e1_dp * t599 - t397 + t402 - t405 + t410 + t415 + &
         0.2e1_dp / 0.3e1_dp * t605 + t423 + 0.2e1_dp / 0.3e1_dp * t609 - t430 + t16 * t12 * &
         t894
      t900 = t899 * t355
      t902 = t9 * a * b
      t903 = c * t15
      t904 = t12 * t354
      t907 = t902 * t903 * t904 / 0.3e1_dp
      t909 = t412 * t354 * d
      t911 = t902 * t909 / 0.3e1_dp
      t913 = 0.8e1_dp / 0.3e1_dp * t146 * t30
      t914 = t21 * t161
      t917 = t183 * t70
      t918 = t917 * t50
      t920 = t63 * t918 / 0.32e2_dp
      t921 = t65 * t189
      t922 = t921 * t50
      t925 = t339 * t170
      t930 = t202 * t70
      t931 = t930 * t89
      t933 = t63 * t931 / 0.576e3_dp
      t934 = t84 * t189
      t935 = t934 * t89
      t938 = t343 * t210
      t943 = t234 * t70
      t946 = t106 * t189
      t954 = t913 - t914 + t180 * t340 / 0.32e2_dp + t920 - t63 * t922 / 0.12e2_dp + t63 * &
         t925 / 0.32e2_dp + t180 * t344 / 0.576e3_dp + t933 - t63 * t935 / 0.216e3_dp + t63 * &
         t938 / 0.576e3_dp - t62 * (-0.16e2_dp / 0.9e1_dp * t238 + 0.2e1_dp / 0.3e1_dp * t241 &
         - t943 * t50 / 0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t946 * t50 - t348 * t170 / 0.4e1_dp) &
         / 0.8e1_dp
      t955 = t136 * t954
      t958 = t21 * a * b
      t960 = 0.1e2_dp / 0.3e1_dp * t958 * t358
      t961 = t121 * a
      t962 = t961 * b
      t963 = t12 * t30
      t964 = t903 * t963
      t966 = 0.2e1_dp / 0.3e1_dp * t962 * t964
      t968 = t412 * t30 * d
      t970 = 0.2e1_dp / 0.3e1_dp * t962 * t968
      t971 = t136 * t161
      t974 = t899 * t377
      t975 = t12 * t376
      t978 = t902 * t903 * t975 / 0.3e1_dp
      t980 = t412 * t376 * d
      t982 = t902 * t980 / 0.3e1_dp
      t985 = t183 * t77
      t986 = t985 * t57
      t988 = t63 * t986 / 0.32e2_dp
      t989 = t361 * t175
      t994 = t202 * t77
      t995 = t994 * t93
      t997 = t63 * t995 / 0.576e3_dp
      t998 = t365 * t214
      t1002 = t225 * t77
      t1010 = t913 - t914 + t180 * t362 / 0.32e2_dp + t988 + t63 * t989 / 0.32e2_dp + t180 * &
         t366 / 0.576e3_dp + t997 + t63 * t998 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * &
         t229 - t1002 * t57 / 0.4e1_dp - t370 * t175 / 0.4e1_dp) / 0.8e1_dp
      t1011 = t136 * t1010
      t1013 = t21 * t257
      t1016 = t339 * t265
      t1021 = t343 * t293
      t1025 = t322 * t70
      t1033 = t913 - t1013 + t274 * t340 / 0.32e2_dp + t920 + t63 * t1016 / 0.32e2_dp + t274 &
         * t344 / 0.576e3_dp + t933 + t63 * t1021 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * &
         t326 - t1025 * t50 / 0.4e1_dp - t348 * t265 / 0.4e1_dp) / 0.8e1_dp
      t1034 = t136 * t1033
      t1036 = t136 * t257
      t1041 = t65 * t280
      t1042 = t1041 * t57
      t1045 = t361 * t269
      t1050 = t84 * t280
      t1051 = t1050 * t93
      t1054 = t365 * t299
      t1059 = t310 * t77
      t1062 = t101 * t280
      t1070 = t913 - t1013 + t274 * t362 / 0.32e2_dp + t988 - t63 * t1042 / 0.12e2_dp + t63 * &
         t1045 / 0.32e2_dp + t274 * t366 / 0.576e3_dp + t997 - t63 * t1051 / 0.216e3_dp + t63 &
         * t1054 / 0.576e3_dp - t62 * (-0.16e2_dp / 0.9e1_dp * t314 + 0.2e1_dp / 0.3e1_dp * &
         t317 - t1059 * t57 / 0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t1062 * t57 - t370 * t269 / &
         0.4e1_dp) / 0.8e1_dp
      t1071 = t136 * t1070
      v2rho2_aa = t118 * t593 + 0.2e1_dp * t378
      v2rho2_ab = t118 * t765 + t378 + t595
      v2rho2_bb = t118 * t897 + 0.2e1_dp * t595
      v2rhosigma_a_aa = t337 * t955 + t900 + t907 + t911
      v2rhosigma_a_ab = -0.2e1_dp * t357 * t971 + t960 - t966 - t970
      v2rhosigma_a_bb = t337 * t1011 + t974 + t978 + t982
      v2rhosigma_b_aa = t337 * t1034 + t900 + t907 + t911
      v2rhosigma_b_ab = -0.2e1_dp * t357 * t1036 + t960 - t966 - t970
      v2rhosigma_b_bb = t337 * t1071 + t974 + t978 + t982
      v2sigma2_aa_aa = 0.e0_dp
      v2sigma2_aa_ab = 0.e0_dp
      v2sigma2_aa_bb = 0.e0_dp
      v2sigma2_ab_ab = 0.e0_dp
      v2sigma2_ab_bb = 0.e0_dp
      v2sigma2_bb_bb = 0.e0_dp
   end subroutine lyp_fxc_polar_impl

   pure subroutine lyp_vxc_fxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, vrho_a, &
      vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
      v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, &
      v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, &
      v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, &
         v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
         v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
         v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb
      logical :: t41, t52
      real(dp) :: t32, t35, t62, t33, t36, t37, t134, t151
      real(dp) :: t406, t407, t470, t899, t1, t2, t3, t4
      real(dp) :: t5, t7, t8, t9, t11, t12, t15, t16
      real(dp) :: t18, t19, t21, t22, t24, t25, t27, t30
      real(dp) :: t38, t39, t40, t42, t43, t44, t45, t46
      real(dp) :: t47, t48, t49, t50, t51, t53, t54, t55
      real(dp) :: t56, t57, t58, t63, t65, t66, t67, t68
      real(dp) :: t70, t71, t72, t73, t74, t75, t77, t78
      real(dp) :: t79, t80, t81, t84, t86, t89, t93, t95
      real(dp) :: t96, t101, t102, t103, t106, t107, t108, t114
      real(dp) :: tzk0, t118, t119, t120, t121, t122, t124, t126
      real(dp) :: t127, t128, t130, t131, t133, t135, t136, t137
      real(dp) :: t139, t140, t141, t144, t146, t147, t149, t152
      real(dp) :: t154, t157, t158, t159, t161, t166, t167, t168
      real(dp) :: t170, t171, t172, t173, t175, t176, t180, t183
      real(dp) :: t184, t186, t189, t190, t191, t193, t194, t195
      real(dp) :: t196, t202, t203, t205, t210, t214, t216, t217
      real(dp) :: t225, t226, t229, t234, t235, t238, t241, t247
      real(dp) :: t250, t253, t257, t262, t263, t265, t266, t267
      real(dp) :: t269, t270, t274, t277, t280, t281, t282, t284
      real(dp) :: t285, t286, t293, t299, t301, t302, t310, t311
      real(dp) :: t314, t317, t322, t323, t326, t332, t335, t337
      real(dp) :: t338, t339, t340, t343, t344, t348, t354, t355
      real(dp) :: t356, t357, t358, t361, t362, t365, t366, t370
      real(dp) :: t376, t377, t378, t380, t381, t382, t383, t384
      real(dp) :: t386, t387, t389, t390, t393, t394, t395, t397
      real(dp) :: t399, t400, t402, t403, t405, t408, t410, t411
      real(dp) :: t412, t413, t415, t416, t417, t419, t420, t423
      real(dp) :: t424, t426, t430, t432, t433, t435, t442, t443
      real(dp) :: t446, t450, t451, t452, t454, t458, t459, t463
      real(dp) :: t466, t471, t472, t474, t476, t478, t479, t481
      real(dp) :: t482, t483, t485, t487, t488, t489, t491, t493
      real(dp) :: t494, t495, t496, t501, t508, t509, t511, t512
      real(dp) :: t513, t524, t531, t533, t534, t537, t541, t546
      real(dp) :: t547, t548, t549, t558, t559, t564, t570, t571
      real(dp) :: t578, t581, t584, t587, t590, t593, t595, t596
      real(dp) :: t598, t599, t604, t605, t607, t609, t611, t613
      real(dp) :: t616, t620, t621, t623, t625, t628, t632, t633
      real(dp) :: t637, t641, t642, t649, t654, t659, t663, t664
      real(dp) :: t673, t676, t679, t683, t685, t687, t690, t694
      real(dp) :: t697, t703, t704, t708, t709, t714, t715, t721
      real(dp) :: t722, t728, t732, t738, t742, t744, t745, t761
      real(dp) :: t762, t765, t768, t784, t785, t788, t789, t792
      real(dp) :: t793, t794, t796, t797, t800, t801, t805, t810
      real(dp) :: t811, t813, t814, t815, t817, t819, t820, t821
      real(dp) :: t833, t844, t846, t847, t853, t862, t863, t870
      real(dp) :: t873, t876, t882, t883, t888, t891, t894, t897
      real(dp) :: t900, t902, t903, t904, t907, t909, t911, t913
      real(dp) :: t914, t917, t918, t920, t921, t922, t925, t930
      real(dp) :: t931, t933, t934, t935, t938, t943, t946, t954
      real(dp) :: t955, t958, t960, t961, t962, t963, t964, t966
      real(dp) :: t968, t970, t971, t974, t975, t978, t980, t982
      real(dp) :: t985, t986, t988, t989, t994, t995, t997, t998
      real(dp) :: t1002, t1010, t1011, t1013, t1016, t1021, t1025, t1033
      real(dp) :: t1034, t1036, t1041, t1042, t1045, t1050, t1051, t1054
      real(dp) :: t1059, t1062, t1070, t1071
      t32 = m_cbrt_3
      t35 = m_cbrt_pi_sq
      t62 = m_cbrt_2
      t33 = t32 * t32
      t36 = t35 * t35
      t37 = t33 * t36
      t134 = b * c
      t151 = d * d
      t406 = c * c
      t407 = b * t406
      t470 = t151 * d
      t899 = a * b
      t1 = rho_a - rho_b
      t2 = t1 * t1
      t3 = rho_a + rho_b
      t4 = t3 * t3
      t5 = 0.1e1_dp / t4
      t7 = -t2 * t5 + 0.1e1_dp
      t8 = xc_cbrt(t3)
      t9 = 0.1e1_dp / t8
      t11 = d * t9 + 0.1e1_dp
      t12 = 0.1e1_dp / t11
      t15 = exp(-c * t9)
      t16 = b * t15
      t18 = sigma_aa + 0.2e1_dp * sigma_ab + sigma_bb
      t19 = t8 * t8
      t21 = 0.1e1_dp / t19 / t4
      t22 = t18 * t21
      t24 = d * t12 + c
      t25 = t24 * t9
      t27 = 0.47e2_dp - 0.7e1_dp * t25
      t30 = t7 * t27 / 0.72e2_dp - 0.2e1_dp / 0.3e1_dp
      t38 = 0.1e1_dp / t3
      t39 = t1 * t38
      t40 = 0.1e1_dp + t39
      t41 = t40 <= zeta_tol
      t42 = zeta_tol * zeta_tol
      t43 = xc_cbrt(zeta_tol)
      t44 = t43 * t43
      t45 = t44 * t42
      t46 = t40 * t40
      t47 = xc_cbrt(t40)
      t48 = t47 * t47
      t49 = t48 * t46
      t50 = merge(t45, t49, t41)
      t51 = 0.1e1_dp - t39
      t52 = t51 <= zeta_tol
      t53 = t51 * t51
      t54 = xc_cbrt(t51)
      t55 = t54 * t54
      t56 = t55 * t53
      t57 = merge(t45, t56, t52)
      t58 = t50 + t57
      t63 = t62 * t7
      t65 = 0.5e1_dp / 0.2e1_dp - t25 / 0.18e2_dp
      t66 = rho_a * rho_a
      t67 = xc_cbrt(rho_a)
      t68 = t67 * t67
      t70 = 0.1e1_dp / t68 / t66
      t71 = sigma_aa * t70
      t72 = t71 * t50
      t73 = rho_b * rho_b
      t74 = xc_cbrt(rho_b)
      t75 = t74 * t74
      t77 = 0.1e1_dp / t75 / t73
      t78 = sigma_bb * t77
      t79 = t78 * t57
      t80 = t72 + t79
      t81 = t65 * t80
      t84 = t25 - 0.11e2_dp
      t86 = t44 * t42 * zeta_tol
      t89 = merge(t86, t48 * t46 * t40, t41)
      t93 = merge(t86, t55 * t53 * t51, t52)
      t95 = t71 * t89 + t78 * t93
      t96 = t84 * t95
      t101 = merge(t42, t46, t41)
      t102 = t101 * sigma_bb
      t103 = t77 * t57
      t106 = merge(t42, t53, t52)
      t107 = t106 * sigma_aa
      t108 = t70 * t50
      t114 = -t22 * t30 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t58 + t63 * t81 / 0.32e2_dp + t63 &
         * t96 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * t72 + 0.2e1_dp / 0.3e1_dp * t79 - &
         t102 * t103 / 0.4e1_dp - t107 * t108 / 0.4e1_dp) / 0.8e1_dp
      tzk0 = a * (t16 * t12 * t114 - t7 * t12)
      t118 = t3 * a
      t119 = t1 * t5
      t120 = t4 * t3
      t121 = 0.1e1_dp / t120
      t122 = t2 * t121
      t124 = -0.2e1_dp * t119 + 0.2e1_dp * t122
      t126 = t11 * t11
      t127 = 0.1e1_dp / t126
      t128 = t7 * t127
      t130 = 0.1e1_dp / t8 / t3
      t131 = d * t130
      t133 = t128 * t131 / 0.3e1_dp
      t135 = t134 * t130
      t136 = t15 * t12
      t137 = t136 * t114
      t139 = t135 * t137 / 0.3e1_dp
      t140 = t16 * t127
      t141 = t114 * d
      t144 = t140 * t141 * t130 / 0.3e1_dp
      t146 = 0.1e1_dp / t19 / t120
      t147 = t18 * t146
      t149 = 0.8e1_dp / 0.3e1_dp * t147 * t30
      t152 = t151 * t127
      t154 = 0.1e1_dp / t19 / t3
      t157 = t24 * t130 - t152 * t154
      t158 = 0.7e1_dp / 0.3e1_dp * t157
      t159 = t7 * t158
      t161 = t124 * t27 / 0.72e2_dp + t159 / 0.72e2_dp
      t166 = t48 * t40
      t167 = t38 - t119
      t168 = t166 * t167
      t170 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t168, t41)
      t171 = t55 * t51
      t172 = -t167
      t173 = t171 * t172
      t175 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t173, t52)
      t176 = t170 + t175
      t180 = t62 * t124
      t183 = t157 / 0.54e2_dp
      t184 = t183 * t80
      t186 = t63 * t184 / 0.32e2_dp
      t189 = 0.1e1_dp / t68 / t66 / rho_a
      t190 = sigma_aa * t189
      t191 = t190 * t50
      t193 = t71 * t170
      t194 = t78 * t175
      t195 = -0.8e1_dp / 0.3e1_dp * t191 + t193 + t194
      t196 = t65 * t195
      t202 = -t157 / 0.3e1_dp
      t203 = t202 * t95
      t205 = t63 * t203 / 0.576e3_dp
      t210 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t49 * t167, t41)
      t214 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t56 * t172, t52)
      t216 = -0.8e1_dp / 0.3e1_dp * t190 * t89 + t71 * t210 + t78 * t214
      t217 = t84 * t216
      t225 = merge(0.0_dp, 0.2e1_dp * t40 * t167, t41)
      t226 = t225 * sigma_bb
      t229 = t77 * t175
      t234 = merge(0.0_dp, 0.2e1_dp * t51 * t172, t52)
      t235 = t234 * sigma_aa
      t238 = t189 * t50
      t241 = t70 * t170
      t247 = t149 - t22 * t161 - 0.3e1_dp / 0.2e2_dp * t37 * t124 * t58 - 0.3e1_dp / 0.2e2_dp &
         * t37 * t7 * t176 + t180 * t81 / 0.32e2_dp + t186 + t63 * t196 / 0.32e2_dp + t180 * &
         t96 / 0.576e3_dp + t205 + t63 * t217 / 0.576e3_dp - t62 * (-0.16e2_dp / 0.9e1_dp * &
         t191 + 0.2e1_dp / 0.3e1_dp * t193 + 0.2e1_dp / 0.3e1_dp * t194 - t226 * t103 / &
         0.4e1_dp - t102 * t229 / 0.4e1_dp - t235 * t108 / 0.4e1_dp + 0.2e1_dp / 0.3e1_dp * &
         t107 * t238 - t107 * t241 / 0.4e1_dp) / 0.8e1_dp
      t250 = t16 * t12 * t247 - t124 * t12 - t133 + t139 + t144
      t253 = 0.2e1_dp * t119 + 0.2e1_dp * t122
      t257 = t253 * t27 / 0.72e2_dp + t159 / 0.72e2_dp
      t262 = -t38 - t119
      t263 = t166 * t262
      t265 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t263, t41)
      t266 = -t262
      t267 = t171 * t266
      t269 = merge(0.0_dp, 0.8e1_dp / 0.3e1_dp * t267, t52)
      t270 = t265 + t269
      t274 = t62 * t253
      t277 = t71 * t265
      t280 = 0.1e1_dp / t75 / t73 / rho_b
      t281 = sigma_bb * t280
      t282 = t281 * t57
      t284 = t78 * t269
      t285 = t277 - 0.8e1_dp / 0.3e1_dp * t282 + t284
      t286 = t65 * t285
      t293 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t49 * t262, t41)
      t299 = merge(0.0_dp, 0.11e2_dp / 0.3e1_dp * t56 * t266, t52)
      t301 = t71 * t293 - 0.8e1_dp / 0.3e1_dp * t281 * t93 + t78 * t299
      t302 = t84 * t301
      t310 = merge(0.0_dp, 0.2e1_dp * t40 * t262, t41)
      t311 = t310 * sigma_bb
      t314 = t280 * t57
      t317 = t77 * t269
      t322 = merge(0.0_dp, 0.2e1_dp * t51 * t266, t52)
      t323 = t322 * sigma_aa
      t326 = t70 * t265
      t332 = t149 - t22 * t257 - 0.3e1_dp / 0.2e2_dp * t37 * t253 * t58 - 0.3e1_dp / 0.2e2_dp &
         * t37 * t7 * t270 + t274 * t81 / 0.32e2_dp + t186 + t63 * t286 / 0.32e2_dp + t274 * &
         t96 / 0.576e3_dp + t205 + t63 * t302 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * &
         t277 - 0.16e2_dp / 0.9e1_dp * t282 + 0.2e1_dp / 0.3e1_dp * t284 - t311 * t103 / &
         0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t102 * t314 - t102 * t317 / 0.4e1_dp - t323 * t108 &
         / 0.4e1_dp - t107 * t326 / 0.4e1_dp) / 0.8e1_dp
      t335 = t16 * t12 * t332 - t253 * t12 - t133 + t139 + t144
      t337 = t118 * b
      t338 = t21 * t30
      t339 = t65 * t70
      t340 = t339 * t50
      t343 = t84 * t70
      t344 = t343 * t89
      t348 = t106 * t70
      t354 = -t338 + t63 * t340 / 0.32e2_dp + t63 * t344 / 0.576e3_dp - t62 * (0.2e1_dp / &
         0.3e1_dp * t108 - t348 * t50 / 0.4e1_dp) / 0.8e1_dp
      t355 = t136 * t354
      t356 = t154 * a
      t357 = t356 * b
      t358 = t136 * t30
      t361 = t65 * t77
      t362 = t361 * t57
      t365 = t84 * t77
      t366 = t365 * t93
      t370 = t101 * t77
      t376 = -t338 + t63 * t362 / 0.32e2_dp + t63 * t366 / 0.576e3_dp - t62 * (0.2e1_dp / &
         0.3e1_dp * t103 - t370 * t57 / 0.4e1_dp) / 0.8e1_dp
      t377 = t136 * t376
      t378 = a * t250
      t380 = 0.2e1_dp * t5
      t381 = t1 * t121
      t382 = 0.8e1_dp * t381
      t383 = t4 * t4
      t384 = 0.1e1_dp / t383
      t386 = 0.6e1_dp * t2 * t384
      t387 = -t380 + t382 - t386
      t389 = t124 * t127
      t390 = t389 * t131
      t393 = 0.1e1_dp / t126 / t11
      t394 = t7 * t393
      t395 = t151 * t21
      t397 = 0.2e1_dp / 0.9e1_dp * t394 * t395
      t399 = 0.1e1_dp / t8 / t4
      t400 = d * t399
      t402 = 0.4e1_dp / 0.9e1_dp * t128 * t400
      t403 = t134 * t399
      t405 = 0.4e1_dp / 0.9e1_dp * t403 * t137
      t408 = t407 * t21
      t410 = t408 * t137 / 0.9e1_dp
      t411 = t134 * t21
      t412 = t15 * t127
      t413 = t412 * t141
      t415 = 0.2e1_dp / 0.9e1_dp * t411 * t413
      t416 = t136 * t247
      t417 = t135 * t416
      t419 = t16 * t393
      t420 = t114 * t151
      t423 = 0.2e1_dp / 0.9e1_dp * t419 * t420 * t21
      t424 = t247 * d
      t426 = t140 * t424 * t130
      t430 = 0.4e1_dp / 0.9e1_dp * t140 * t141 * t399
      t432 = 0.1e1_dp / t19 / t383
      t433 = t18 * t432
      t435 = 0.88e2_dp / 0.9e1_dp * t433 * t30
      t442 = t167 * t167
      t443 = t48 * t442
      t446 = -0.2e1_dp * t5 + 0.2e1_dp * t381
      t450 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t443 + 0.8e1_dp / 0.3e1_dp * t166 * t446, t41)
      t451 = t172 * t172
      t452 = t55 * t451
      t454 = -t446
      t458 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t452 + 0.8e1_dp / 0.3e1_dp * t171 * t454, t52)
      t459 = t450 + t458
      t463 = t62 * t387
      t466 = t180 * t184
      t471 = t470 * t393
      t472 = t471 * t121
      t474 = t152 * t21
      t476 = t24 * t399
      t478 = -t472 / 0.81e2_dp + t474 / 0.27e2_dp - 0.2e1_dp / 0.81e2_dp * t476
      t479 = t478 * t80
      t481 = t63 * t479 / 0.32e2_dp
      t482 = t183 * t195
      t483 = t63 * t482
      t485 = t66 * t66
      t487 = 0.1e1_dp / t68 / t485
      t488 = sigma_aa * t487
      t489 = t488 * t50
      t491 = t190 * t170
      t493 = t71 * t450
      t494 = t78 * t458
      t495 = 0.88e2_dp / 0.9e1_dp * t489 - 0.16e2_dp / 0.3e1_dp * t491 + t493 + t494
      t496 = t65 * t495
      t501 = t180 * t203
      t508 = 0.2e1_dp / 0.9e1_dp * t472 - 0.2e1_dp / 0.3e1_dp * t474 + 0.4e1_dp / 0.9e1_dp * &
         t476
      t509 = t508 * t95
      t511 = t63 * t509 / 0.576e3_dp
      t512 = t202 * t216
      t513 = t63 * t512
      t524 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t166 * t442 + 0.11e2_dp / 0.3e1_dp * t49 * &
         t446, t41)
      t531 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t171 * t451 + 0.11e2_dp / 0.3e1_dp * t56 * &
         t454, t52)
      t533 = 0.88e2_dp / 0.9e1_dp * t488 * t89 - 0.16e2_dp / 0.3e1_dp * t190 * t210 + t71 * &
         t524 + t78 * t531
      t534 = t84 * t533
      t537 = t147 * t161
      t541 = t124 * t158
      t546 = -0.14e2_dp / 0.9e1_dp * t472 + 0.14e2_dp / 0.3e1_dp * t474 - 0.28e2_dp / &
         0.9e1_dp * t476
      t547 = t7 * t546
      t548 = t547 / 0.72e2_dp
      t549 = t387 * t27 / 0.72e2_dp + t541 / 0.36e2_dp + t548
      t558 = merge(0.0_dp, 0.2e1_dp * t40 * t446 + 0.2e1_dp * t442, t41)
      t559 = t558 * sigma_bb
      t564 = t77 * t458
      t570 = merge(0.0_dp, 0.2e1_dp * t51 * t454 + 0.2e1_dp * t451, t52)
      t571 = t570 * sigma_aa
      t578 = t487 * t50
      t581 = t189 * t170
      t584 = t70 * t450
      t587 = 0.176e3_dp / 0.27e2_dp * t489 - 0.32e2_dp / 0.9e1_dp * t491 + 0.2e1_dp / &
         0.3e1_dp * t493 + 0.2e1_dp / 0.3e1_dp * t494 - t559 * t103 / 0.4e1_dp - t226 * t229 &
         / 0.2e1_dp - t102 * t564 / 0.4e1_dp - t571 * t108 / 0.4e1_dp + 0.4e1_dp / 0.3e1_dp * &
         t235 * t238 - t235 * t241 / 0.2e1_dp - 0.22e2_dp / 0.9e1_dp * t107 * t578 + 0.4e1_dp &
         / 0.3e1_dp * t107 * t581 - t107 * t584 / 0.4e1_dp
      t590 = -t435 - 0.3e1_dp / 0.2e2_dp * t37 * t387 * t58 - 0.3e1_dp / 0.1e2_dp * t37 * &
         t124 * t176 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t459 + t463 * t81 / 0.32e2_dp + t466 &
         / 0.16e2_dp + t180 * t196 / 0.16e2_dp + t481 + t483 / 0.16e2_dp + t63 * t496 / &
         0.32e2_dp + t463 * t96 / 0.576e3_dp + t501 / 0.288e3_dp + t180 * t217 / 0.288e3_dp + &
         t511 + t513 / 0.288e3_dp + t63 * t534 / 0.576e3_dp + 0.16e2_dp / 0.3e1_dp * t537 - &
         t22 * t549 - t62 * t587 / 0.8e1_dp
      t593 = -t387 * t12 - 0.2e1_dp / 0.3e1_dp * t390 - t397 + t402 - t405 + t410 + t415 + &
         0.2e1_dp / 0.3e1_dp * t417 + t423 + 0.2e1_dp / 0.3e1_dp * t426 - t430 + t16 * t12 * &
         t590
      t595 = a * t335
      t596 = t380 - t386
      t598 = t253 * t127
      t599 = t598 * t131
      t604 = t136 * t332
      t605 = t135 * t604
      t607 = t332 * d
      t609 = t140 * t607 * t130
      t611 = t190 * t265
      t613 = t48 * t262
      t616 = t166 * t1
      t620 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t613 * t167 + 0.16e2_dp / 0.3e1_dp * t616 * &
         t121, t41)
      t621 = t71 * t620
      t623 = t281 * t175
      t625 = t55 * t266
      t628 = t171 * t1
      t632 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t625 * t172 - 0.16e2_dp / 0.3e1_dp * t628 * &
         t121, t52)
      t633 = t78 * t632
      t637 = t40 * t1
      t641 = merge(0.0_dp, 0.4e1_dp * t637 * t121 + 0.2e1_dp * t167 * t262, t41)
      t642 = t641 * sigma_bb
      t649 = t280 * t175
      t654 = t77 * t632
      t659 = t51 * t1
      t663 = merge(0.0_dp, -0.4e1_dp * t659 * t121 + 0.2e1_dp * t172 * t266, t52)
      t664 = t663 * sigma_aa
      t673 = t189 * t265
      t676 = t70 * t620
      t679 = -0.16e2_dp / 0.9e1_dp * t611 + 0.2e1_dp / 0.3e1_dp * t621 - 0.16e2_dp / 0.9e1_dp &
         * t623 + 0.2e1_dp / 0.3e1_dp * t633 - t642 * t103 / 0.4e1_dp - t311 * t229 / &
         0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t226 * t314 + 0.2e1_dp / 0.3e1_dp * t102 * t649 - &
         t226 * t317 / 0.4e1_dp - t102 * t654 / 0.4e1_dp - t664 * t108 / 0.4e1_dp + 0.2e1_dp &
         / 0.3e1_dp * t323 * t238 - t323 * t241 / 0.4e1_dp - t235 * t326 / 0.4e1_dp + &
         0.2e1_dp / 0.3e1_dp * t107 * t673 - t107 * t676 / 0.4e1_dp
      t683 = t253 * t158
      t685 = t596 * t27 / 0.72e2_dp + t541 / 0.72e2_dp + t547 / 0.72e2_dp + t683 / 0.72e2_dp
      t687 = t147 * t257
      t690 = t620 + t632
      t694 = t62 * t596
      t697 = t274 * t184
      t703 = t183 * t285
      t704 = t63 * t703
      t708 = -0.8e1_dp / 0.3e1_dp * t611 + t621 - 0.8e1_dp / 0.3e1_dp * t623 + t633
      t709 = t65 * t708
      t714 = -t62 * t679 / 0.8e1_dp - t22 * t685 + 0.8e1_dp / 0.3e1_dp * t687 + 0.8e1_dp / &
         0.3e1_dp * t537 - t435 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * t690 + t694 * t81 / &
         0.32e2_dp + t697 / 0.32e2_dp + t274 * t196 / 0.32e2_dp + t180 * t286 / 0.32e2_dp + &
         t704 / 0.32e2_dp + t63 * t709 / 0.32e2_dp + t694 * t96 / 0.576e3_dp
      t715 = t274 * t203
      t721 = t202 * t301
      t722 = t63 * t721
      t728 = t49 * t1
      t732 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t263 * t167 + 0.22e2_dp / 0.3e1_dp * t728 * &
         t121, t41)
      t738 = t56 * t1
      t742 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t267 * t172 - 0.22e2_dp / 0.3e1_dp * t738 * &
         t121, t52)
      t744 = -0.8e1_dp / 0.3e1_dp * t190 * t293 + t71 * t732 - 0.8e1_dp / 0.3e1_dp * t281 * &
         t214 + t78 * t742
      t745 = t84 * t744
      t761 = t715 / 0.576e3_dp + t274 * t217 / 0.576e3_dp + t180 * t302 / 0.576e3_dp + t722 / &
         0.576e3_dp + t63 * t745 / 0.576e3_dp - 0.3e1_dp / 0.2e2_dp * t37 * t596 * t58 - &
         0.3e1_dp / 0.2e2_dp * t37 * t253 * t176 - 0.3e1_dp / 0.2e2_dp * t37 * t124 * t270 + &
         t511 + t513 / 0.576e3_dp + t466 / 0.32e2_dp + t481 + t483 / 0.32e2_dp + t501 / &
         0.576e3_dp
      t762 = t714 + t761
      t765 = -t596 * t12 - t599 / 0.3e1_dp - t390 / 0.3e1_dp - t397 + t402 - t405 + t410 + &
         t415 + t417 / 0.3e1_dp + t423 + t426 / 0.3e1_dp - t430 + t605 / 0.3e1_dp + t609 / &
         0.3e1_dp + t16 * t12 * t762
      t768 = -t380 - t382 - t386
      t784 = t262 * t262
      t785 = t48 * t784
      t788 = 0.2e1_dp * t5 + 0.2e1_dp * t381
      t789 = t166 * t788
      t792 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t785 + 0.8e1_dp / 0.3e1_dp * t789, t41)
      t793 = t266 * t266
      t794 = t55 * t793
      t796 = -t788
      t797 = t171 * t796
      t800 = merge(0.0_dp, 0.4e2_dp / 0.9e1_dp * t794 + 0.8e1_dp / 0.3e1_dp * t797, t52)
      t801 = t792 + t800
      t805 = t62 * t768
      t810 = t71 * t792
      t811 = t73 * t73
      t813 = 0.1e1_dp / t75 / t811
      t814 = sigma_bb * t813
      t815 = t814 * t57
      t817 = t281 * t269
      t819 = t78 * t800
      t820 = t810 + 0.88e2_dp / 0.9e1_dp * t815 - 0.16e2_dp / 0.3e1_dp * t817 + t819
      t821 = t65 * t820
      t833 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t166 * t784 + 0.11e2_dp / 0.3e1_dp * t49 * &
         t788, t41)
      t844 = merge(0.0_dp, 0.88e2_dp / 0.9e1_dp * t171 * t793 + 0.11e2_dp / 0.3e1_dp * t56 * &
         t796, t52)
      t846 = t71 * t833 + 0.88e2_dp / 0.9e1_dp * t814 * t93 - 0.16e2_dp / 0.3e1_dp * t281 * &
         t299 + t78 * t844
      t847 = t84 * t846
      t853 = t768 * t27 / 0.72e2_dp + t683 / 0.36e2_dp + t548
      t862 = merge(0.0_dp, 0.2e1_dp * t40 * t788 + 0.2e1_dp * t784, t41)
      t863 = t862 * sigma_bb
      t870 = t813 * t57
      t873 = t280 * t269
      t876 = t77 * t800
      t882 = merge(0.0_dp, 0.2e1_dp * t51 * t796 + 0.2e1_dp * t793, t52)
      t883 = t882 * sigma_aa
      t888 = t70 * t792
      t891 = 0.2e1_dp / 0.3e1_dp * t810 + 0.176e3_dp / 0.27e2_dp * t815 - 0.32e2_dp / &
         0.9e1_dp * t817 + 0.2e1_dp / 0.3e1_dp * t819 - t863 * t103 / 0.4e1_dp + 0.4e1_dp / &
         0.3e1_dp * t311 * t314 - t311 * t317 / 0.2e1_dp - 0.22e2_dp / 0.9e1_dp * t102 * t870 &
         + 0.4e1_dp / 0.3e1_dp * t102 * t873 - t102 * t876 / 0.4e1_dp - t883 * t108 / &
         0.4e1_dp - t323 * t326 / 0.2e1_dp - t107 * t888 / 0.4e1_dp
      t894 = -t435 + t481 + t511 + 0.16e2_dp / 0.3e1_dp * t687 + t697 / 0.16e2_dp + t704 / &
         0.16e2_dp + t715 / 0.288e3_dp + t722 / 0.288e3_dp - 0.3e1_dp / 0.2e2_dp * t37 * t768 &
         * t58 - 0.3e1_dp / 0.1e2_dp * t37 * t253 * t270 - 0.3e1_dp / 0.2e2_dp * t37 * t7 * &
         t801 + t805 * t81 / 0.32e2_dp + t274 * t286 / 0.16e2_dp + t63 * t821 / 0.32e2_dp + &
         t805 * t96 / 0.576e3_dp + t274 * t302 / 0.288e3_dp + t63 * t847 / 0.576e3_dp - t22 * &
         t853 - t62 * t891 / 0.8e1_dp
      t897 = -t768 * t12 - 0.2e1_dp / 0.3e1_dp * t599 - t397 + t402 - t405 + t410 + t415 + &
         0.2e1_dp / 0.3e1_dp * t605 + t423 + 0.2e1_dp / 0.3e1_dp * t609 - t430 + t16 * t12 * &
         t894
      t900 = t899 * t355
      t902 = t9 * a * b
      t903 = c * t15
      t904 = t12 * t354
      t907 = t902 * t903 * t904 / 0.3e1_dp
      t909 = t412 * t354 * d
      t911 = t902 * t909 / 0.3e1_dp
      t913 = 0.8e1_dp / 0.3e1_dp * t146 * t30
      t914 = t21 * t161
      t917 = t183 * t70
      t918 = t917 * t50
      t920 = t63 * t918 / 0.32e2_dp
      t921 = t65 * t189
      t922 = t921 * t50
      t925 = t339 * t170
      t930 = t202 * t70
      t931 = t930 * t89
      t933 = t63 * t931 / 0.576e3_dp
      t934 = t84 * t189
      t935 = t934 * t89
      t938 = t343 * t210
      t943 = t234 * t70
      t946 = t106 * t189
      t954 = t913 - t914 + t180 * t340 / 0.32e2_dp + t920 - t63 * t922 / 0.12e2_dp + t63 * &
         t925 / 0.32e2_dp + t180 * t344 / 0.576e3_dp + t933 - t63 * t935 / 0.216e3_dp + t63 * &
         t938 / 0.576e3_dp - t62 * (-0.16e2_dp / 0.9e1_dp * t238 + 0.2e1_dp / 0.3e1_dp * t241 &
         - t943 * t50 / 0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t946 * t50 - t348 * t170 / 0.4e1_dp) &
         / 0.8e1_dp
      t955 = t136 * t954
      t958 = t21 * a * b
      t960 = 0.1e2_dp / 0.3e1_dp * t958 * t358
      t961 = t121 * a
      t962 = t961 * b
      t963 = t12 * t30
      t964 = t903 * t963
      t966 = 0.2e1_dp / 0.3e1_dp * t962 * t964
      t968 = t412 * t30 * d
      t970 = 0.2e1_dp / 0.3e1_dp * t962 * t968
      t971 = t136 * t161
      t974 = t899 * t377
      t975 = t12 * t376
      t978 = t902 * t903 * t975 / 0.3e1_dp
      t980 = t412 * t376 * d
      t982 = t902 * t980 / 0.3e1_dp
      t985 = t183 * t77
      t986 = t985 * t57
      t988 = t63 * t986 / 0.32e2_dp
      t989 = t361 * t175
      t994 = t202 * t77
      t995 = t994 * t93
      t997 = t63 * t995 / 0.576e3_dp
      t998 = t365 * t214
      t1002 = t225 * t77
      t1010 = t913 - t914 + t180 * t362 / 0.32e2_dp + t988 + t63 * t989 / 0.32e2_dp + t180 * &
         t366 / 0.576e3_dp + t997 + t63 * t998 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * &
         t229 - t1002 * t57 / 0.4e1_dp - t370 * t175 / 0.4e1_dp) / 0.8e1_dp
      t1011 = t136 * t1010
      t1013 = t21 * t257
      t1016 = t339 * t265
      t1021 = t343 * t293
      t1025 = t322 * t70
      t1033 = t913 - t1013 + t274 * t340 / 0.32e2_dp + t920 + t63 * t1016 / 0.32e2_dp + t274 &
         * t344 / 0.576e3_dp + t933 + t63 * t1021 / 0.576e3_dp - t62 * (0.2e1_dp / 0.3e1_dp * &
         t326 - t1025 * t50 / 0.4e1_dp - t348 * t265 / 0.4e1_dp) / 0.8e1_dp
      t1034 = t136 * t1033
      t1036 = t136 * t257
      t1041 = t65 * t280
      t1042 = t1041 * t57
      t1045 = t361 * t269
      t1050 = t84 * t280
      t1051 = t1050 * t93
      t1054 = t365 * t299
      t1059 = t310 * t77
      t1062 = t101 * t280
      t1070 = t913 - t1013 + t274 * t362 / 0.32e2_dp + t988 - t63 * t1042 / 0.12e2_dp + t63 * &
         t1045 / 0.32e2_dp + t274 * t366 / 0.576e3_dp + t997 - t63 * t1051 / 0.216e3_dp + t63 &
         * t1054 / 0.576e3_dp - t62 * (-0.16e2_dp / 0.9e1_dp * t314 + 0.2e1_dp / 0.3e1_dp * &
         t317 - t1059 * t57 / 0.4e1_dp + 0.2e1_dp / 0.3e1_dp * t1062 * t57 - t370 * t269 / &
         0.4e1_dp) / 0.8e1_dp
      t1071 = t136 * t1070
      vrho_a = t118 * t250 + tzk0
      vrho_b = t118 * t335 + tzk0
      vsigma_aa = t337 * t355
      vsigma_ab = -0.2e1_dp * t357 * t358
      vsigma_bb = t337 * t377
      v2rho2_aa = t118 * t593 + 0.2e1_dp * t378
      v2rho2_ab = t118 * t765 + t378 + t595
      v2rho2_bb = t118 * t897 + 0.2e1_dp * t595
      v2rhosigma_a_aa = t337 * t955 + t900 + t907 + t911
      v2rhosigma_a_ab = -0.2e1_dp * t357 * t971 + t960 - t966 - t970
      v2rhosigma_a_bb = t337 * t1011 + t974 + t978 + t982
      v2rhosigma_b_aa = t337 * t1034 + t900 + t907 + t911
      v2rhosigma_b_ab = -0.2e1_dp * t357 * t1036 + t960 - t966 - t970
      v2rhosigma_b_bb = t337 * t1071 + t974 + t978 + t982
      v2sigma2_aa_aa = 0.e0_dp
      v2sigma2_aa_ab = 0.e0_dp
      v2sigma2_aa_bb = 0.e0_dp
      v2sigma2_ab_ab = 0.e0_dp
      v2sigma2_ab_bb = 0.e0_dp
      v2sigma2_bb_bb = 0.e0_dp
   end subroutine lyp_vxc_fxc_polar_impl

end module trc_xc_lyp
