!
! SLATER_EXCHANGE: LDA exchange-correlation kernel.
!
! GENERATED by tools/exchcxx_to_fortran.py from ExchCXX's
! include/exchcxx/impl/builtin/kernels/slater_exchange.hpp -- do not edit.
!
! The arithmetic is ExchCXX's (MIT; Copyright (c) 2020-2024, The Regents
! of the University of California, through Lawrence Berkeley National
! Laboratory; portions Copyright (c) Microsoft Corporation), itself
! generated by Maple from the functional's definition. See
! https://github.com/wavefunction91/ExchCXX.
!
! Every routine is scalar, pure, and callable from `do concurrent`.
! The public `<name>_<what>_<polar>` routines apply the density and
! gradient thresholds the way ExchCXX's screening_interface.hpp does;
! the `_impl` bodies below them are the bare Maple expressions.
!
! Unpolarised routines take the TOTAL density and its gradient
! invariant; polarised ones take the two spin densities and the three
! gradient invariants. `eps` is the energy per particle, so the
! integrand is rho * eps.
!
module trc_xc_slater_exchange
   use trc_boys, only: dp
   use trc_xc_util, only: m_cbrt_2, m_cbrt_3, m_cbrt_pi, xc_cbrt
   implicit none
   private

   public :: slater_exchange_exc_unpolar
   public :: slater_exchange_exc_vxc_unpolar
   public :: slater_exchange_fxc_unpolar
   public :: slater_exchange_vxc_fxc_unpolar
   public :: slater_exchange_exc_polar
   public :: slater_exchange_exc_vxc_polar
   public :: slater_exchange_fxc_polar
   public :: slater_exchange_vxc_fxc_polar

   real(dp), parameter :: dens_tol = 1e-24_dp
   real(dp), parameter :: zeta_tol = 1e-15_dp
   real(dp), parameter :: sigma_tol = 1.000000000000004e-32_dp
   real(dp), parameter :: tau_tol = 1e-20_dp
   real(dp), parameter :: alpha = 1.0_dp

contains

   pure subroutine slater_exchange_exc_unpolar(rho, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps
      real(dp) :: rho_c
      eps = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call slater_exchange_exc_unpolar_impl(rho_c, eps)
      end if
   end subroutine slater_exchange_exc_unpolar

   pure subroutine slater_exchange_exc_vxc_unpolar(rho, eps, vrho)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps, vrho
      real(dp) :: rho_c
      eps = 0.0_dp
      vrho = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call slater_exchange_exc_vxc_unpolar_impl(rho_c, eps, vrho)
      end if
   end subroutine slater_exchange_exc_vxc_unpolar

   pure subroutine slater_exchange_fxc_unpolar(rho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: v2rho2
      real(dp) :: rho_c
      v2rho2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call slater_exchange_fxc_unpolar_impl(rho_c, v2rho2)
      end if
   end subroutine slater_exchange_fxc_unpolar

   pure subroutine slater_exchange_vxc_fxc_unpolar(rho, vrho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: vrho, v2rho2
      real(dp) :: rho_c
      vrho = 0.0_dp
      v2rho2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         call slater_exchange_vxc_fxc_unpolar_impl(rho_c, vrho, v2rho2)
      end if
   end subroutine slater_exchange_vxc_fxc_unpolar

   pure subroutine slater_exchange_exc_polar(rho_a, rho_b, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps
      real(dp) :: rho_a_c, rho_b_c
      eps = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call slater_exchange_exc_polar_impl(rho_a_c, rho_b_c, eps)
      end if
   end subroutine slater_exchange_exc_polar

   pure subroutine slater_exchange_exc_vxc_polar(rho_a, rho_b, eps, vrho_a, vrho_b)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps, vrho_a, vrho_b
      real(dp) :: rho_a_c, rho_b_c
      eps = 0.0_dp
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call slater_exchange_exc_vxc_polar_impl(rho_a_c, rho_b_c, eps, vrho_a, vrho_b)
      end if
   end subroutine slater_exchange_exc_vxc_polar

   pure subroutine slater_exchange_fxc_polar(rho_a, rho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb
      real(dp) :: rho_a_c, rho_b_c
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call slater_exchange_fxc_polar_impl(rho_a_c, rho_b_c, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      end if
   end subroutine slater_exchange_fxc_polar

   pure subroutine slater_exchange_vxc_fxc_polar(rho_a, rho_b, vrho_a, vrho_b, v2rho2_aa, &
      v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb
      real(dp) :: rho_a_c, rho_b_c
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         call slater_exchange_vxc_fxc_polar_impl(rho_a_c, rho_b_c, vrho_a, vrho_b, v2rho2_aa, &
            v2rho2_ab, v2rho2_bb)
      end if
   end subroutine slater_exchange_vxc_fxc_polar

   pure subroutine slater_exchange_exc_unpolar_impl(rho, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps
      logical :: t2
      real(dp) :: t3, t4, t6, t8, t10, t11, t15, t16
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t6 = t3 / t4
      t2 = rho / 0.2e1_dp <= dens_tol
      t8 = xc_cbrt(zeta_tol)
      t10 = merge(t8 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t11 = xc_cbrt(rho)
      t15 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t10 * t11, t2)
      t16 = alpha * t15
      eps = 0.2e1_dp * t16
   end subroutine slater_exchange_exc_unpolar_impl

   pure subroutine slater_exchange_exc_vxc_unpolar_impl(rho, eps, vrho)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: eps, vrho
      logical :: t2
      real(dp) :: t3, t4, t6, t8, t10, t11, t15, t16
      real(dp) :: t17, t18, t23
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t6 = t3 / t4
      t2 = rho / 0.2e1_dp <= dens_tol
      t8 = xc_cbrt(zeta_tol)
      t10 = merge(t8 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t11 = xc_cbrt(rho)
      t15 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t10 * t11, t2)
      t16 = alpha * t15
      t17 = rho * alpha
      t18 = t11 * t11
      t23 = merge(0.0_dp, -t6 * t10 / t18 / 0.8e1_dp, t2)
      eps = 0.2e1_dp * t16
      vrho = 0.2e1_dp * t17 * t23 + 0.2e1_dp * t16
   end subroutine slater_exchange_exc_vxc_unpolar_impl

   pure subroutine slater_exchange_fxc_unpolar_impl(rho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: v2rho2
      logical :: t2
      real(dp) :: t3, t4, t6, t8, t10, t11, t17, t18
      real(dp) :: t23, t33
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t6 = t3 / t4
      t2 = rho / 0.2e1_dp <= dens_tol
      t8 = xc_cbrt(zeta_tol)
      t10 = merge(t8 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t11 = xc_cbrt(rho)
      t17 = rho * alpha
      t18 = t11 * t11
      t23 = merge(0.0_dp, -t6 * t10 / t18 / 0.8e1_dp, t2)
      t33 = merge(0.0_dp, t6 * t10 / t18 / rho / 0.12e2_dp, t2)
      v2rho2 = 0.2e1_dp * t17 * t33 + 0.4e1_dp * alpha * t23
   end subroutine slater_exchange_fxc_unpolar_impl

   pure subroutine slater_exchange_vxc_fxc_unpolar_impl(rho, vrho, v2rho2)
      !$acc routine seq
      real(dp), intent(in) :: rho
      real(dp), intent(out) :: vrho, v2rho2
      logical :: t2
      real(dp) :: t3, t4, t6, t8, t10, t11, t15, t16
      real(dp) :: t17, t18, t23, t33
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t6 = t3 / t4
      t2 = rho / 0.2e1_dp <= dens_tol
      t8 = xc_cbrt(zeta_tol)
      t10 = merge(t8 * zeta_tol, 1.0_dp, 0.1e1_dp <= zeta_tol)
      t11 = xc_cbrt(rho)
      t15 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t10 * t11, t2)
      t16 = alpha * t15
      t17 = rho * alpha
      t18 = t11 * t11
      t23 = merge(0.0_dp, -t6 * t10 / t18 / 0.8e1_dp, t2)
      t33 = merge(0.0_dp, t6 * t10 / t18 / rho / 0.12e2_dp, t2)
      vrho = 0.2e1_dp * t17 * t23 + 0.2e1_dp * t16
      v2rho2 = 0.2e1_dp * t17 * t33 + 0.4e1_dp * alpha * t23
   end subroutine slater_exchange_vxc_fxc_unpolar_impl

   pure subroutine slater_exchange_exc_polar_impl(rho_a, rho_b, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps
      logical :: t1, t10, t26, t29
      real(dp) :: t2, t3, t13, t5, t6, t7, t8, t11
      real(dp) :: t12, t14, t15, t19, t20, t24, t25, t27
      real(dp) :: t30, t31, t35, t39, t40
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t13 = m_cbrt_2
      t5 = t2 / t3
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t8 = rho_a * t7
      t10 = 0.2e1_dp * t8 <= zeta_tol
      t11 = xc_cbrt(zeta_tol)
      t12 = t11 * zeta_tol
      t14 = t13 * rho_a
      t15 = xc_cbrt(t8)
      t19 = merge(t12, 0.2e1_dp * t14 * t7 * t15, t10)
      t20 = xc_cbrt(t6)
      t24 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t19 * t20, t1)
      t25 = alpha * t24
      t26 = rho_b <= dens_tol
      t27 = rho_b * t7
      t29 = 0.2e1_dp * t27 <= zeta_tol
      t30 = t13 * rho_b
      t31 = xc_cbrt(t27)
      t35 = merge(t12, 0.2e1_dp * t30 * t7 * t31, t29)
      t39 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t35 * t20, t26)
      t40 = alpha * t39
      eps = t25 + t40
   end subroutine slater_exchange_exc_polar_impl

   pure subroutine slater_exchange_exc_vxc_polar_impl(rho_a, rho_b, eps, vrho_a, vrho_b)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: eps, vrho_a, vrho_b
      logical :: t1, t10, t26, t29
      real(dp) :: t2, t3, t13, t5, t6, t7, t8, t11
      real(dp) :: t12, t14, t15, t19, t20, t24, t25, t27
      real(dp) :: t30, t31, t35, t39, t40, t41, t44, t45
      real(dp) :: t48, t49, t50, t51, t53, t58, t62, t63
      real(dp) :: t66, t68, t69, t72, t73, t74, t75, t76
      real(dp) :: t77, t78, t79, t83, t89, t91, t92, t95
      real(dp) :: t96, t97, t101, t106, t107, t110, t112, t117
      real(dp) :: t122, t123
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t13 = m_cbrt_2
      t5 = t2 / t3
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t8 = rho_a * t7
      t10 = 0.2e1_dp * t8 <= zeta_tol
      t11 = xc_cbrt(zeta_tol)
      t12 = t11 * zeta_tol
      t14 = t13 * rho_a
      t15 = xc_cbrt(t8)
      t19 = merge(t12, 0.2e1_dp * t14 * t7 * t15, t10)
      t20 = xc_cbrt(t6)
      t24 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t19 * t20, t1)
      t25 = alpha * t24
      t26 = rho_b <= dens_tol
      t27 = rho_b * t7
      t29 = 0.2e1_dp * t27 <= zeta_tol
      t30 = t13 * rho_b
      t31 = xc_cbrt(t27)
      t35 = merge(t12, 0.2e1_dp * t30 * t7 * t31, t29)
      t39 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t35 * t20, t26)
      t40 = alpha * t39
      t41 = t13 * t7
      t44 = t6 * t6
      t45 = 0.1e1_dp / t44
      t48 = 0.2e1_dp * t14 * t45 * t15
      t49 = t15 * t15
      t50 = 0.1e1_dp / t49
      t51 = t7 * t50
      t53 = -rho_a * t45 + t7
      t58 = merge(0.0_dp, 0.2e1_dp * t41 * t15 - t48 + 0.2e1_dp / 0.3e1_dp * t14 * t51 * t53, &
         t10)
      t62 = t20 * t20
      t63 = 0.1e1_dp / t62
      t66 = t5 * t19 * t63 / 0.8e1_dp
      t68 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t58 * t20 - t66, t1)
      t69 = alpha * t68
      t72 = 0.2e1_dp * t30 * t45 * t31
      t73 = rho_b * rho_b
      t74 = t13 * t73
      t75 = t44 * t6
      t76 = 0.1e1_dp / t75
      t77 = t31 * t31
      t78 = 0.1e1_dp / t77
      t79 = t76 * t78
      t83 = merge(0.0_dp, -t72 - 0.2e1_dp / 0.3e1_dp * t74 * t79, t29)
      t89 = t5 * t35 * t63 / 0.8e1_dp
      t91 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t83 * t20 - t89, t26)
      t92 = alpha * t91
      t95 = rho_a * rho_a
      t96 = t13 * t95
      t97 = t76 * t50
      t101 = merge(0.0_dp, -t48 - 0.2e1_dp / 0.3e1_dp * t96 * t97, t10)
      t106 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t101 * t20 - t66, t1)
      t107 = alpha * t106
      t110 = t7 * t78
      t112 = -rho_b * t45 + t7
      t117 = merge(0.0_dp, 0.2e1_dp * t41 * t31 - t72 + 0.2e1_dp / 0.3e1_dp * t30 * t110 * &
         t112, t29)
      t122 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t117 * t20 - t89, t26)
      t123 = alpha * t122
      eps = t25 + t40
      vrho_a = t25 + t40 + t6 * (t69 + t92)
      vrho_b = t25 + t40 + t6 * (t107 + t123)
   end subroutine slater_exchange_exc_vxc_polar_impl

   pure subroutine slater_exchange_fxc_polar_impl(rho_a, rho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb
      logical :: t1, t10, t26, t29
      real(dp) :: t2, t3, t13, t5, t6, t7, t8, t11
      real(dp) :: t12, t14, t15, t19, t20, t27, t30, t31
      real(dp) :: t35, t41, t44, t45, t48, t49, t50, t51
      real(dp) :: t53, t58, t62, t63, t66, t68, t69, t72
      real(dp) :: t73, t74, t75, t76, t77, t78, t79, t83
      real(dp) :: t89, t91, t92, t95, t96, t97, t101, t106
      real(dp) :: t107, t110, t112, t117, t122, t123, t128, t129
      real(dp) :: t131, t136, t137, t139, t142, t143, t144, t150
      real(dp) :: t155, t160, t163, t166, t168, t169, t172, t173
      real(dp) :: t174, t175, t176, t178, t179, t181, t183, t184
      real(dp) :: t188, t193, t197, t199, t200, t207, t208, t220
      real(dp) :: t226, t233, t235, t241, t253, t264, t265, t266
      real(dp) :: t270, t276, t277, t279, t283, t284, t289, t294
      real(dp) :: t300, t301
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t13 = m_cbrt_2
      t5 = t2 / t3
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t8 = rho_a * t7
      t10 = 0.2e1_dp * t8 <= zeta_tol
      t11 = xc_cbrt(zeta_tol)
      t12 = t11 * zeta_tol
      t14 = t13 * rho_a
      t15 = xc_cbrt(t8)
      t19 = merge(t12, 0.2e1_dp * t14 * t7 * t15, t10)
      t20 = xc_cbrt(t6)
      t26 = rho_b <= dens_tol
      t27 = rho_b * t7
      t29 = 0.2e1_dp * t27 <= zeta_tol
      t30 = t13 * rho_b
      t31 = xc_cbrt(t27)
      t35 = merge(t12, 0.2e1_dp * t30 * t7 * t31, t29)
      t41 = t13 * t7
      t44 = t6 * t6
      t45 = 0.1e1_dp / t44
      t48 = 0.2e1_dp * t14 * t45 * t15
      t49 = t15 * t15
      t50 = 0.1e1_dp / t49
      t51 = t7 * t50
      t53 = -rho_a * t45 + t7
      t58 = merge(0.0_dp, 0.2e1_dp * t41 * t15 - t48 + 0.2e1_dp / 0.3e1_dp * t14 * t51 * t53, &
         t10)
      t62 = t20 * t20
      t63 = 0.1e1_dp / t62
      t66 = t5 * t19 * t63 / 0.8e1_dp
      t68 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t58 * t20 - t66, t1)
      t69 = alpha * t68
      t72 = 0.2e1_dp * t30 * t45 * t31
      t73 = rho_b * rho_b
      t74 = t13 * t73
      t75 = t44 * t6
      t76 = 0.1e1_dp / t75
      t77 = t31 * t31
      t78 = 0.1e1_dp / t77
      t79 = t76 * t78
      t83 = merge(0.0_dp, -t72 - 0.2e1_dp / 0.3e1_dp * t74 * t79, t29)
      t89 = t5 * t35 * t63 / 0.8e1_dp
      t91 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t83 * t20 - t89, t26)
      t92 = alpha * t91
      t95 = rho_a * rho_a
      t96 = t13 * t95
      t97 = t76 * t50
      t101 = merge(0.0_dp, -t48 - 0.2e1_dp / 0.3e1_dp * t96 * t97, t10)
      t106 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t101 * t20 - t66, t1)
      t107 = alpha * t106
      t110 = t7 * t78
      t112 = -rho_b * t45 + t7
      t117 = merge(0.0_dp, 0.2e1_dp * t41 * t31 - t72 + 0.2e1_dp / 0.3e1_dp * t30 * t110 * &
         t112, t29)
      t122 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t117 * t20 - t89, t26)
      t123 = alpha * t122
      t128 = t13 * t45
      t129 = t128 * t15
      t131 = t50 * t53
      t136 = 0.4e1_dp * t14 * t76 * t15
      t137 = t45 * t50
      t139 = t14 * t137 * t53
      t142 = 0.1e1_dp / t49 / t8
      t143 = t7 * t142
      t144 = t53 * t53
      t150 = 0.2e1_dp * rho_a * t76 - 0.2e1_dp * t45
      t155 = merge(0.0_dp, -0.4e1_dp * t129 + 0.4e1_dp / 0.3e1_dp * t41 * t131 + t136 - &
         0.4e1_dp / 0.3e1_dp * t139 - 0.4e1_dp / 0.9e1_dp * t14 * t143 * t144 + 0.2e1_dp / &
         0.3e1_dp * t14 * t51 * t150, t10)
      t160 = t5 * t58 * t63
      t163 = 0.1e1_dp / t62 / t6
      t166 = t5 * t19 * t163 / 0.12e2_dp
      t168 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t155 * t20 - t160 / 0.4e1_dp + t166, t1)
      t169 = alpha * t168
      t172 = 0.4e1_dp * t30 * t76 * t31
      t173 = t44 * t44
      t174 = 0.1e1_dp / t173
      t175 = t174 * t78
      t176 = t74 * t175
      t178 = t73 * rho_b
      t179 = t13 * t178
      t181 = 0.1e1_dp / t173 / t6
      t183 = 0.1e1_dp / t77 / t27
      t184 = t181 * t183
      t188 = merge(0.0_dp, t172 + 0.8e1_dp / 0.3e1_dp * t176 - 0.4e1_dp / 0.9e1_dp * t179 * &
         t184, t29)
      t193 = t5 * t83 * t63
      t197 = t5 * t35 * t163 / 0.12e2_dp
      t199 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t188 * t20 - t193 / 0.4e1_dp + t197, t26)
      t200 = alpha * t199
      t207 = t174 * t50
      t208 = t96 * t207
      t220 = t5 * t101 * t63
      t226 = t128 * t31
      t233 = t45 * t78
      t235 = t30 * t233 * t112
      t241 = rho_b * t76
      t253 = t5 * t117 * t63
      t264 = t95 * rho_a
      t265 = t13 * t264
      t266 = t181 * t142
      t270 = merge(0.0_dp, t136 + 0.8e1_dp / 0.3e1_dp * t208 - 0.4e1_dp / 0.9e1_dp * t265 * &
         t266, t10)
      t276 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t270 * t20 - t220 / 0.4e1_dp + t166, t1)
      t277 = alpha * t276
      t279 = t78 * t112
      t283 = t7 * t183
      t284 = t112 * t112
      t289 = -0.2e1_dp * t45 + 0.2e1_dp * t241
      t294 = merge(0.0_dp, -0.4e1_dp * t226 + 0.4e1_dp / 0.3e1_dp * t41 * t279 + t172 - &
         0.4e1_dp / 0.3e1_dp * t235 - 0.4e1_dp / 0.9e1_dp * t30 * t283 * t284 + 0.2e1_dp / &
         0.3e1_dp * t30 * t110 * t289, t29)
      t300 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t294 * t20 - t253 / 0.4e1_dp + t197, t26)
      t301 = alpha * t300
      v2rho2_aa = 0.2e1_dp * t69 + 0.2e1_dp * t92 + t6 * (t169 + t200)
      v2rho2_bb = 0.2e1_dp * t107 + 0.2e1_dp * t123 + t6 * (t277 + t301)
      v2rho2_ab = 0.0_dp
   end subroutine slater_exchange_fxc_polar_impl

   pure subroutine slater_exchange_vxc_fxc_polar_impl(rho_a, rho_b, vrho_a, vrho_b, &
      v2rho2_aa, v2rho2_ab, v2rho2_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b
      real(dp), intent(out) :: vrho_a, vrho_b, v2rho2_aa, v2rho2_ab, v2rho2_bb
      logical :: t1, t10, t26, t29
      real(dp) :: t2, t3, t13, t5, t6, t7, t8, t11
      real(dp) :: t12, t14, t15, t19, t20, t24, t25, t27
      real(dp) :: t30, t31, t35, t39, t40, t41, t44, t45
      real(dp) :: t48, t49, t50, t51, t53, t58, t62, t63
      real(dp) :: t66, t68, t69, t72, t73, t74, t75, t76
      real(dp) :: t77, t78, t79, t83, t89, t91, t92, t95
      real(dp) :: t96, t97, t101, t106, t107, t110, t112, t117
      real(dp) :: t122, t123, t128, t129, t131, t136, t137, t139
      real(dp) :: t142, t143, t144, t150, t155, t160, t163, t166
      real(dp) :: t168, t169, t172, t173, t174, t175, t176, t178
      real(dp) :: t179, t181, t183, t184, t188, t193, t197, t199
      real(dp) :: t200, t207, t208, t220, t226, t233, t235, t241
      real(dp) :: t253, t264, t265, t266, t270, t276, t277, t279
      real(dp) :: t283, t284, t289, t294, t300, t301
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t13 = m_cbrt_2
      t5 = t2 / t3
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t8 = rho_a * t7
      t10 = 0.2e1_dp * t8 <= zeta_tol
      t11 = xc_cbrt(zeta_tol)
      t12 = t11 * zeta_tol
      t14 = t13 * rho_a
      t15 = xc_cbrt(t8)
      t19 = merge(t12, 0.2e1_dp * t14 * t7 * t15, t10)
      t20 = xc_cbrt(t6)
      t24 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t19 * t20, t1)
      t25 = alpha * t24
      t26 = rho_b <= dens_tol
      t27 = rho_b * t7
      t29 = 0.2e1_dp * t27 <= zeta_tol
      t30 = t13 * rho_b
      t31 = xc_cbrt(t27)
      t35 = merge(t12, 0.2e1_dp * t30 * t7 * t31, t29)
      t39 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t35 * t20, t26)
      t40 = alpha * t39
      t41 = t13 * t7
      t44 = t6 * t6
      t45 = 0.1e1_dp / t44
      t48 = 0.2e1_dp * t14 * t45 * t15
      t49 = t15 * t15
      t50 = 0.1e1_dp / t49
      t51 = t7 * t50
      t53 = -rho_a * t45 + t7
      t58 = merge(0.0_dp, 0.2e1_dp * t41 * t15 - t48 + 0.2e1_dp / 0.3e1_dp * t14 * t51 * t53, &
         t10)
      t62 = t20 * t20
      t63 = 0.1e1_dp / t62
      t66 = t5 * t19 * t63 / 0.8e1_dp
      t68 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t58 * t20 - t66, t1)
      t69 = alpha * t68
      t72 = 0.2e1_dp * t30 * t45 * t31
      t73 = rho_b * rho_b
      t74 = t13 * t73
      t75 = t44 * t6
      t76 = 0.1e1_dp / t75
      t77 = t31 * t31
      t78 = 0.1e1_dp / t77
      t79 = t76 * t78
      t83 = merge(0.0_dp, -t72 - 0.2e1_dp / 0.3e1_dp * t74 * t79, t29)
      t89 = t5 * t35 * t63 / 0.8e1_dp
      t91 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t83 * t20 - t89, t26)
      t92 = alpha * t91
      t95 = rho_a * rho_a
      t96 = t13 * t95
      t97 = t76 * t50
      t101 = merge(0.0_dp, -t48 - 0.2e1_dp / 0.3e1_dp * t96 * t97, t10)
      t106 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t101 * t20 - t66, t1)
      t107 = alpha * t106
      t110 = t7 * t78
      t112 = -rho_b * t45 + t7
      t117 = merge(0.0_dp, 0.2e1_dp * t41 * t31 - t72 + 0.2e1_dp / 0.3e1_dp * t30 * t110 * &
         t112, t29)
      t122 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t117 * t20 - t89, t26)
      t123 = alpha * t122
      t128 = t13 * t45
      t129 = t128 * t15
      t131 = t50 * t53
      t136 = 0.4e1_dp * t14 * t76 * t15
      t137 = t45 * t50
      t139 = t14 * t137 * t53
      t142 = 0.1e1_dp / t49 / t8
      t143 = t7 * t142
      t144 = t53 * t53
      t150 = 0.2e1_dp * rho_a * t76 - 0.2e1_dp * t45
      t155 = merge(0.0_dp, -0.4e1_dp * t129 + 0.4e1_dp / 0.3e1_dp * t41 * t131 + t136 - &
         0.4e1_dp / 0.3e1_dp * t139 - 0.4e1_dp / 0.9e1_dp * t14 * t143 * t144 + 0.2e1_dp / &
         0.3e1_dp * t14 * t51 * t150, t10)
      t160 = t5 * t58 * t63
      t163 = 0.1e1_dp / t62 / t6
      t166 = t5 * t19 * t163 / 0.12e2_dp
      t168 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t155 * t20 - t160 / 0.4e1_dp + t166, t1)
      t169 = alpha * t168
      t172 = 0.4e1_dp * t30 * t76 * t31
      t173 = t44 * t44
      t174 = 0.1e1_dp / t173
      t175 = t174 * t78
      t176 = t74 * t175
      t178 = t73 * rho_b
      t179 = t13 * t178
      t181 = 0.1e1_dp / t173 / t6
      t183 = 0.1e1_dp / t77 / t27
      t184 = t181 * t183
      t188 = merge(0.0_dp, t172 + 0.8e1_dp / 0.3e1_dp * t176 - 0.4e1_dp / 0.9e1_dp * t179 * &
         t184, t29)
      t193 = t5 * t83 * t63
      t197 = t5 * t35 * t163 / 0.12e2_dp
      t199 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t188 * t20 - t193 / 0.4e1_dp + t197, t26)
      t200 = alpha * t199
      t207 = t174 * t50
      t208 = t96 * t207
      t220 = t5 * t101 * t63
      t226 = t128 * t31
      t233 = t45 * t78
      t235 = t30 * t233 * t112
      t241 = rho_b * t76
      t253 = t5 * t117 * t63
      t264 = t95 * rho_a
      t265 = t13 * t264
      t266 = t181 * t142
      t270 = merge(0.0_dp, t136 + 0.8e1_dp / 0.3e1_dp * t208 - 0.4e1_dp / 0.9e1_dp * t265 * &
         t266, t10)
      t276 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t270 * t20 - t220 / 0.4e1_dp + t166, t1)
      t277 = alpha * t276
      t279 = t78 * t112
      t283 = t7 * t183
      t284 = t112 * t112
      t289 = -0.2e1_dp * t45 + 0.2e1_dp * t241
      t294 = merge(0.0_dp, -0.4e1_dp * t226 + 0.4e1_dp / 0.3e1_dp * t41 * t279 + t172 - &
         0.4e1_dp / 0.3e1_dp * t235 - 0.4e1_dp / 0.9e1_dp * t30 * t283 * t284 + 0.2e1_dp / &
         0.3e1_dp * t30 * t110 * t289, t29)
      t300 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t294 * t20 - t253 / 0.4e1_dp + t197, t26)
      t301 = alpha * t300
      vrho_a = t25 + t40 + t6 * (t69 + t92)
      vrho_b = t25 + t40 + t6 * (t107 + t123)
      v2rho2_aa = 0.2e1_dp * t69 + 0.2e1_dp * t92 + t6 * (t169 + t200)
      v2rho2_bb = 0.2e1_dp * t107 + 0.2e1_dp * t123 + t6 * (t277 + t301)
      v2rho2_ab = 0.0_dp
   end subroutine slater_exchange_vxc_fxc_polar_impl

end module trc_xc_slater_exchange
