!
! PBE_X: GGA exchange-correlation kernel.
!
! GENERATED by tools/exchcxx_to_fortran.py from ExchCXX's
! include/exchcxx/impl/builtin/kernels/pbe_x.hpp -- do not edit.
!
! The arithmetic is ExchCXX's (MIT; Copyright (c) 2020-2024, The Regents
! of the University of California, through Lawrence Berkeley National
! Laboratory; portions Copyright (c) Microsoft Corporation), itself
! generated by Maple from the functional's definition. See
! https://github.com/wavefunction91/ExchCXX.
!
! Every routine is scalar, pure, and callable from `do concurrent`.
! The public `<name>_<what>_<polar>` routines apply the density and
! gradient thresholds the way ExchCXX's screening_interface.hpp does;
! the `_impl` bodies below them are the bare Maple expressions.
!
! Unpolarised routines take the TOTAL density and its gradient
! invariant; polarised ones take the two spin densities and the three
! gradient invariants. `eps` is the energy per particle, so the
! integrand is rho * eps.
!
module trc_xc_pbe_x
   use trc_boys, only: dp
   use trc_xc_util, only: enforce_polar_sigma_constraints, m_cbrt_2, m_cbrt_3, m_cbrt_6, &
      m_cbrt_pi, m_cbrt_pi_sq, m_pi_sq, xc_cbrt
   implicit none
   private

   public :: pbe_x_exc_unpolar
   public :: pbe_x_exc_vxc_unpolar
   public :: pbe_x_fxc_unpolar
   public :: pbe_x_vxc_fxc_unpolar
   public :: pbe_x_exc_polar
   public :: pbe_x_exc_vxc_polar
   public :: pbe_x_fxc_polar
   public :: pbe_x_vxc_fxc_polar

   real(dp), parameter :: dens_tol = 1e-32_dp
   real(dp), parameter :: zeta_tol = 1e-15_dp
   real(dp), parameter :: sigma_tol = 2.1544346900318956e-43_dp
   real(dp), parameter :: tau_tol = 1e-20_dp
   real(dp), parameter :: kappa = 0.8040_dp
   real(dp), parameter :: mu = 0.2195149727645171_dp

contains

   pure subroutine pbe_x_exc_unpolar(rho, sigma, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps
      real(dp) :: rho_c, sigma_c
      eps = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call pbe_x_exc_unpolar_impl(rho_c, sigma_c, eps)
      end if
   end subroutine pbe_x_exc_unpolar

   pure subroutine pbe_x_exc_vxc_unpolar(rho, sigma, eps, vrho, vsigma)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps, vrho, vsigma
      real(dp) :: rho_c, sigma_c
      eps = 0.0_dp
      vrho = 0.0_dp
      vsigma = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call pbe_x_exc_vxc_unpolar_impl(rho_c, sigma_c, eps, vrho, vsigma)
      end if
   end subroutine pbe_x_exc_vxc_unpolar

   pure subroutine pbe_x_fxc_unpolar(rho, sigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: v2rho2, v2rhosigma, v2sigma2
      real(dp) :: rho_c, sigma_c
      v2rho2 = 0.0_dp
      v2rhosigma = 0.0_dp
      v2sigma2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call pbe_x_fxc_unpolar_impl(rho_c, sigma_c, v2rho2, v2rhosigma, v2sigma2)
      end if
   end subroutine pbe_x_fxc_unpolar

   pure subroutine pbe_x_vxc_fxc_unpolar(rho, sigma, vrho, vsigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: vrho, vsigma, v2rho2, v2rhosigma, v2sigma2
      real(dp) :: rho_c, sigma_c
      vrho = 0.0_dp
      vsigma = 0.0_dp
      v2rho2 = 0.0_dp
      v2rhosigma = 0.0_dp
      v2sigma2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call pbe_x_vxc_fxc_unpolar_impl(rho_c, sigma_c, vrho, vsigma, v2rho2, v2rhosigma, &
            v2sigma2)
      end if
   end subroutine pbe_x_vxc_fxc_unpolar

   pure subroutine pbe_x_exc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      eps = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call pbe_x_exc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, eps)
      end if
   end subroutine pbe_x_exc_polar

   pure subroutine pbe_x_exc_vxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps, &
      vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      eps = 0.0_dp
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      vsigma_aa = 0.0_dp
      vsigma_ab = 0.0_dp
      vsigma_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call pbe_x_exc_vxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      end if
   end subroutine pbe_x_exc_vxc_polar

   pure subroutine pbe_x_fxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, v2rho2_aa, &
      v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
      v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
      v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, &
         v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
         v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
         v2sigma2_bb_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      v2rhosigma_a_aa = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2rhosigma_b_bb = 0.0_dp
      v2sigma2_aa_aa = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
      v2sigma2_bb_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call pbe_x_fxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, &
            v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
            v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
            v2sigma2_bb_bb)
      end if
   end subroutine pbe_x_fxc_polar

   pure subroutine pbe_x_vxc_fxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, vrho_a, &
      vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
      v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, &
      v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, &
      v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, &
         v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
         v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
         v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      vsigma_aa = 0.0_dp
      vsigma_ab = 0.0_dp
      vsigma_bb = 0.0_dp
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      v2rhosigma_a_aa = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2rhosigma_b_bb = 0.0_dp
      v2sigma2_aa_aa = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
      v2sigma2_bb_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call pbe_x_vxc_fxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
            v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, &
            v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, &
            v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      end if
   end subroutine pbe_x_vxc_fxc_polar

   pure subroutine pbe_x_exc_unpolar_impl(rho, sigma, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps
      logical :: t2, t7
      real(dp) :: t3, t4, t20, t23, t27, t6, t24, t25
      real(dp) :: t28, t8, t10, t11, t13, t15, t17, t18
      real(dp) :: t30, t31, t33, t37, t42, t46
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t20 = m_cbrt_6
      t23 = m_cbrt_pi_sq
      t27 = m_cbrt_2
      t6 = t3 / t4
      t24 = t23 * t23
      t25 = 0.1e1_dp / t24
      t28 = t27 * t27
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t30 = rho * rho
      t31 = t18 * t18
      t33 = 0.1e1_dp / t31 / t30
      t37 = kappa + mu * t20 * t25 * sigma * t28 * t33 / 0.24e2_dp
      t42 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t37)
      t46 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t17 * t18 * t42, t2)
      eps = 0.2e1_dp * t46
   end subroutine pbe_x_exc_unpolar_impl

   pure subroutine pbe_x_exc_vxc_unpolar_impl(rho, sigma, eps, vrho, vsigma)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps, vrho, vsigma
      logical :: t2, t7
      real(dp) :: t3, t4, t20, t23, t27, t6, t24, t25
      real(dp) :: t28, t56, t78, t8, t10, t11, t13, t15
      real(dp) :: t17, t18, t30, t31, t33, t37, t42, t46
      real(dp) :: t52, t58, t59, t61, t64, t65, t69, t79
      real(dp) :: t82
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t20 = m_cbrt_6
      t23 = m_cbrt_pi_sq
      t27 = m_cbrt_2
      t6 = t3 / t4
      t24 = t23 * t23
      t25 = 0.1e1_dp / t24
      t28 = t27 * t27
      t56 = kappa * kappa
      t78 = t20 * t25 * t28
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t30 = rho * rho
      t31 = t18 * t18
      t33 = 0.1e1_dp / t31 / t30
      t37 = kappa + mu * t20 * t25 * sigma * t28 * t33 / 0.24e2_dp
      t42 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t37)
      t46 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t17 * t18 * t42, t2)
      t52 = t30 * rho
      t58 = t6 * t17 / t18 / t52 * t56
      t59 = t37 * t37
      t61 = 0.1e1_dp / t59 * mu
      t64 = t25 * sigma * t28
      t65 = t61 * t20 * t64
      t69 = merge(0.0_dp, -t6 * t17 / t31 * t42 / 0.8e1_dp + t58 * t65 / 0.24e2_dp, t2)
      t79 = t61 * t78
      t82 = merge(0.0_dp, -t6 * t17 / t18 / t30 * t56 * t79 / 0.64e2_dp, t2)
      eps = 0.2e1_dp * t46
      vrho = 0.2e1_dp * rho * t69 + 0.2e1_dp * t46
      vsigma = 0.2e1_dp * rho * t82
   end subroutine pbe_x_exc_vxc_unpolar_impl

   pure subroutine pbe_x_fxc_unpolar_impl(rho, sigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: v2rho2, v2rhosigma, v2sigma2
      logical :: t2, t7
      real(dp) :: t3, t4, t20, t22, t23, t27, t6, t24
      real(dp) :: t25, t28, t56, t78, t106, t108, t111, t8
      real(dp) :: t10, t11, t13, t15, t17, t18, t30, t31
      real(dp) :: t33, t37, t42, t52, t58, t59, t61, t64
      real(dp) :: t65, t69, t79, t82, t91, t96, t99, t103
      real(dp) :: t107, t109, t112, t115, t119, t124, t128, t131
      real(dp) :: t135, t138, t145, t148
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t20 = m_cbrt_6
      t22 = m_pi_sq
      t23 = m_cbrt_pi_sq
      t27 = m_cbrt_2
      t6 = t3 / t4
      t24 = t23 * t23
      t25 = 0.1e1_dp / t24
      t28 = t27 * t27
      t56 = kappa * kappa
      t78 = t20 * t25 * t28
      t106 = mu * mu
      t108 = t20 * t20
      t111 = 0.1e1_dp / t23 / t22
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t30 = rho * rho
      t31 = t18 * t18
      t33 = 0.1e1_dp / t31 / t30
      t37 = kappa + mu * t20 * t25 * sigma * t28 * t33 / 0.24e2_dp
      t42 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t37)
      t52 = t30 * rho
      t58 = t6 * t17 / t18 / t52 * t56
      t59 = t37 * t37
      t61 = 0.1e1_dp / t59 * mu
      t64 = t25 * sigma * t28
      t65 = t61 * t20 * t64
      t69 = merge(0.0_dp, -t6 * t17 / t31 * t42 / 0.8e1_dp + t58 * t65 / 0.24e2_dp, t2)
      t79 = t61 * t78
      t82 = merge(0.0_dp, -t6 * t17 / t18 / t30 * t56 * t79 / 0.64e2_dp, t2)
      t91 = t30 * t30
      t96 = t6 * t17 / t18 / t91 * t56
      t99 = t91 * t52
      t103 = t6 * t17 / t99 * t56
      t107 = 0.1e1_dp / t59 / t37 * t106
      t109 = t107 * t108
      t112 = sigma * sigma
      t115 = t109 * t111 * t112 * t27
      t119 = merge(0.0_dp, t6 * t17 / t31 / rho * t42 / 0.12e2_dp - t96 * t65 / 0.8e1_dp + &
         t103 * t115 / 0.54e2_dp, t2)
      t124 = t91 * t30
      t128 = t6 * t17 / t124 * t56
      t131 = t109 * t111 * t27 * sigma
      t135 = merge(0.0_dp, 0.7e1_dp / 0.192e3_dp * t58 * t79 - t128 * t131 / 0.144e3_dp, t2)
      t138 = t91 * rho
      t145 = t107 * t108 * t111 * t27
      t148 = merge(0.0_dp, t6 * t17 / t138 * t56 * t145 / 0.384e3_dp, t2)
      v2rho2 = 0.2e1_dp * rho * t119 + 0.4e1_dp * t69
      v2rhosigma = 0.2e1_dp * rho * t135 + 0.2e1_dp * t82
      v2sigma2 = 0.2e1_dp * rho * t148
   end subroutine pbe_x_fxc_unpolar_impl

   pure subroutine pbe_x_vxc_fxc_unpolar_impl(rho, sigma, vrho, vsigma, v2rho2, v2rhosigma, &
      v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: vrho, vsigma, v2rho2, v2rhosigma, v2sigma2
      logical :: t2, t7
      real(dp) :: t3, t4, t20, t22, t23, t27, t6, t24
      real(dp) :: t25, t28, t56, t78, t106, t108, t111, t8
      real(dp) :: t10, t11, t13, t15, t17, t18, t30, t31
      real(dp) :: t33, t37, t42, t46, t52, t58, t59, t61
      real(dp) :: t64, t65, t69, t79, t82, t91, t96, t99
      real(dp) :: t103, t107, t109, t112, t115, t119, t124, t128
      real(dp) :: t131, t135, t138, t145, t148
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t20 = m_cbrt_6
      t22 = m_pi_sq
      t23 = m_cbrt_pi_sq
      t27 = m_cbrt_2
      t6 = t3 / t4
      t24 = t23 * t23
      t25 = 0.1e1_dp / t24
      t28 = t27 * t27
      t56 = kappa * kappa
      t78 = t20 * t25 * t28
      t106 = mu * mu
      t108 = t20 * t20
      t111 = 0.1e1_dp / t23 / t22
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t30 = rho * rho
      t31 = t18 * t18
      t33 = 0.1e1_dp / t31 / t30
      t37 = kappa + mu * t20 * t25 * sigma * t28 * t33 / 0.24e2_dp
      t42 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t37)
      t46 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t17 * t18 * t42, t2)
      t52 = t30 * rho
      t58 = t6 * t17 / t18 / t52 * t56
      t59 = t37 * t37
      t61 = 0.1e1_dp / t59 * mu
      t64 = t25 * sigma * t28
      t65 = t61 * t20 * t64
      t69 = merge(0.0_dp, -t6 * t17 / t31 * t42 / 0.8e1_dp + t58 * t65 / 0.24e2_dp, t2)
      t79 = t61 * t78
      t82 = merge(0.0_dp, -t6 * t17 / t18 / t30 * t56 * t79 / 0.64e2_dp, t2)
      t91 = t30 * t30
      t96 = t6 * t17 / t18 / t91 * t56
      t99 = t91 * t52
      t103 = t6 * t17 / t99 * t56
      t107 = 0.1e1_dp / t59 / t37 * t106
      t109 = t107 * t108
      t112 = sigma * sigma
      t115 = t109 * t111 * t112 * t27
      t119 = merge(0.0_dp, t6 * t17 / t31 / rho * t42 / 0.12e2_dp - t96 * t65 / 0.8e1_dp + &
         t103 * t115 / 0.54e2_dp, t2)
      t124 = t91 * t30
      t128 = t6 * t17 / t124 * t56
      t131 = t109 * t111 * t27 * sigma
      t135 = merge(0.0_dp, 0.7e1_dp / 0.192e3_dp * t58 * t79 - t128 * t131 / 0.144e3_dp, t2)
      t138 = t91 * rho
      t145 = t107 * t108 * t111 * t27
      t148 = merge(0.0_dp, t6 * t17 / t138 * t56 * t145 / 0.384e3_dp, t2)
      vrho = 0.2e1_dp * rho * t69 + 0.2e1_dp * t46
      vsigma = 0.2e1_dp * rho * t82
      v2rho2 = 0.2e1_dp * rho * t119 + 0.4e1_dp * t69
      v2rhosigma = 0.2e1_dp * rho * t135 + 0.2e1_dp * t82
      v2sigma2 = 0.2e1_dp * rho * t148
   end subroutine pbe_x_vxc_fxc_unpolar_impl

   pure subroutine pbe_x_exc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps
      logical :: t1, t10, t14, t20, t53, t58
      real(dp) :: t2, t3, t28, t31, t5, t29, t32, t33
      real(dp) :: t6, t7, t11, t15, t16, t18, t19, t21
      real(dp) :: t22, t23, t25, t26, t27, t34, t35, t36
      real(dp) :: t37, t39, t43, t48, t52, t54, t56, t57
      real(dp) :: t59, t61, t62, t63, t64, t65, t66, t68
      real(dp) :: t72, t77, t81
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t28 = m_cbrt_6
      t31 = m_cbrt_pi_sq
      t5 = t2 / t3
      t29 = mu * t28
      t32 = t31 * t31
      t33 = 0.1e1_dp / t32
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t34 = t33 * sigma_aa
      t35 = rho_a * rho_a
      t36 = xc_cbrt(rho_a)
      t37 = t36 * t36
      t39 = 0.1e1_dp / t37 / t35
      t43 = kappa + t29 * t34 * t39 / 0.24e2_dp
      t48 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t43)
      t52 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t48, t1)
      t53 = rho_b <= dens_tol
      t54 = -t16
      t56 = merge(t11, merge(t15, t54 * t7, t10), t14)
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(t57)
      t61 = merge(t22, t59 * t57, t58)
      t62 = t61 * t26
      t63 = t33 * sigma_bb
      t64 = rho_b * rho_b
      t65 = xc_cbrt(rho_b)
      t66 = t65 * t65
      t68 = 0.1e1_dp / t66 / t64
      t72 = kappa + t29 * t63 * t68 / 0.24e2_dp
      t77 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t72)
      t81 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t62 * t77, t53)
      eps = t52 + t81
   end subroutine pbe_x_exc_polar_impl

   pure subroutine pbe_x_exc_vxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps, &
      vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb
      logical :: t1, t10, t14, t20, t53, t58
      real(dp) :: t2, t3, t28, t31, t5, t29, t32, t33
      real(dp) :: t100, t171, t6, t7, t11, t15, t16, t18
      real(dp) :: t19, t21, t22, t23, t25, t26, t27, t34
      real(dp) :: t35, t36, t37, t39, t43, t48, t52, t54
      real(dp) :: t56, t57, t59, t61, t62, t63, t64, t65
      real(dp) :: t66, t68, t72, t77, t81, t82, t83, t84
      real(dp) :: t86, t89, t90, t94, t95, t96, t99, t101
      real(dp) :: t102, t103, t105, t106, t107, t109, t111, t115
      real(dp) :: t116, t118, t121, t122, t126, t129, t131, t135
      real(dp) :: t138, t139, t144, t146, t149, t150, t154, t155
      real(dp) :: t156, t158, t159, t160, t162, t164, t168, t173
      real(dp) :: t176, t178, t181
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t28 = m_cbrt_6
      t31 = m_cbrt_pi_sq
      t5 = t2 / t3
      t29 = mu * t28
      t32 = t31 * t31
      t33 = 0.1e1_dp / t32
      t100 = kappa * kappa
      t171 = t28 * t33
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t34 = t33 * sigma_aa
      t35 = rho_a * rho_a
      t36 = xc_cbrt(rho_a)
      t37 = t36 * t36
      t39 = 0.1e1_dp / t37 / t35
      t43 = kappa + t29 * t34 * t39 / 0.24e2_dp
      t48 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t43)
      t52 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t48, t1)
      t53 = rho_b <= dens_tol
      t54 = -t16
      t56 = merge(t11, merge(t15, t54 * t7, t10), t14)
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(t57)
      t61 = merge(t22, t59 * t57, t58)
      t62 = t61 * t26
      t63 = t33 * sigma_bb
      t64 = rho_b * rho_b
      t65 = xc_cbrt(rho_b)
      t66 = t65 * t65
      t68 = 0.1e1_dp / t66 / t64
      t72 = kappa + t29 * t63 * t68 / 0.24e2_dp
      t77 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t72)
      t81 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t62 * t77, t53)
      t82 = t6 * t6
      t83 = 0.1e1_dp / t82
      t84 = t16 * t83
      t86 = merge(0.0_dp, merge(0.0_dp, t7 - t84, t14), t10)
      t89 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t86, t20)
      t90 = t89 * t26
      t94 = t26 * t26
      t95 = 0.1e1_dp / t94
      t96 = t25 * t95
      t99 = t5 * t96 * t48 / 0.8e1_dp
      t101 = t27 * t100
      t102 = t5 * t101
      t103 = t43 * t43
      t105 = 0.1e1_dp / t103 * mu
      t106 = t105 * t28
      t107 = t35 * rho_a
      t109 = 0.1e1_dp / t37 / t107
      t111 = t106 * t34 * t109
      t115 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t90 * t48 - t99 + t102 * t111 / &
         0.24e2_dp, t1)
      t116 = t54 * t83
      t118 = merge(0.0_dp, merge(0.0_dp, -t7 - t116, t10), t14)
      t121 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t59 * t118, t58)
      t122 = t121 * t26
      t126 = t61 * t95
      t129 = t5 * t126 * t77 / 0.8e1_dp
      t131 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t122 * t77 - t129, t53)
      t135 = merge(0.0_dp, merge(0.0_dp, -t7 - t84, t14), t10)
      t138 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t135, t20)
      t139 = t138 * t26
      t144 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t139 * t48 - t99, t1)
      t146 = merge(0.0_dp, merge(0.0_dp, t7 - t116, t10), t14)
      t149 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t59 * t146, t58)
      t150 = t149 * t26
      t154 = t62 * t100
      t155 = t5 * t154
      t156 = t72 * t72
      t158 = 0.1e1_dp / t156 * mu
      t159 = t158 * t28
      t160 = t64 * rho_b
      t162 = 0.1e1_dp / t66 / t160
      t164 = t159 * t63 * t162
      t168 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t150 * t77 - t129 + t155 * t164 / &
         0.24e2_dp, t53)
      t173 = t105 * t171 * t39
      t176 = merge(0.0_dp, -t102 * t173 / 0.64e2_dp, t1)
      t178 = t158 * t171 * t68
      t181 = merge(0.0_dp, -t155 * t178 / 0.64e2_dp, t53)
      eps = t52 + t81
      vrho_a = t52 + t81 + t6 * (t115 + t131)
      vrho_b = t52 + t81 + t6 * (t144 + t168)
      vsigma_aa = t6 * t176
      vsigma_ab = 0.e0_dp
      vsigma_bb = t6 * t181
   end subroutine pbe_x_exc_vxc_polar_impl

   pure subroutine pbe_x_fxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, &
      v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
      v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
      v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, &
         v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
         v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
         v2sigma2_bb_bb
      logical :: t1, t10, t14, t20, t53, t58
      real(dp) :: t2, t3, t28, t30, t31, t5, t29, t32
      real(dp) :: t33, t100, t171, t223, t225, t228, t442, t6
      real(dp) :: t7, t11, t15, t16, t18, t19, t21, t22
      real(dp) :: t23, t25, t26, t27, t34, t35, t36, t37
      real(dp) :: t39, t43, t48, t54, t56, t57, t59, t61
      real(dp) :: t62, t63, t64, t65, t66, t68, t72, t77
      real(dp) :: t82, t83, t84, t86, t89, t90, t94, t95
      real(dp) :: t96, t99, t101, t102, t103, t105, t106, t107
      real(dp) :: t109, t111, t115, t116, t118, t121, t122, t126
      real(dp) :: t129, t131, t135, t138, t139, t144, t146, t149
      real(dp) :: t150, t154, t155, t156, t158, t159, t160, t162
      real(dp) :: t164, t168, t173, t176, t178, t181, t184, t185
      real(dp) :: t186, t189, t190, t191, t194, t198, t199, t203
      real(dp) :: t205, t208, t212, t213, t216, t218, t219, t224
      real(dp) :: t226, t229, t230, t231, t234, t236, t240, t242
      real(dp) :: t246, t247, t248, t249, t252, t255, t259, t260
      real(dp) :: t264, t266, t268, t271, t273, t289, t291, t314
      real(dp) :: t316, t324, t325, t333, t338, t342, t343, t349
      real(dp) :: t350, t355, t359, t360, t366, t372, t373, t374
      real(dp) :: t375, t376, t379, t381, t385, t387, t391, t397
      real(dp) :: t398, t400, t403, t407, t411, t416, t427, t429
      real(dp) :: t432, t436, t440, t443, t447, t450, t451, t455
      real(dp) :: t458
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t28 = m_cbrt_6
      t30 = m_pi_sq
      t31 = m_cbrt_pi_sq
      t5 = t2 / t3
      t29 = mu * t28
      t32 = t31 * t31
      t33 = 0.1e1_dp / t32
      t100 = kappa * kappa
      t171 = t28 * t33
      t223 = mu * mu
      t225 = t28 * t28
      t228 = 0.1e1_dp / t31 / t30
      t442 = t225 * t228
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t34 = t33 * sigma_aa
      t35 = rho_a * rho_a
      t36 = xc_cbrt(rho_a)
      t37 = t36 * t36
      t39 = 0.1e1_dp / t37 / t35
      t43 = kappa + t29 * t34 * t39 / 0.24e2_dp
      t48 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t43)
      t53 = rho_b <= dens_tol
      t54 = -t16
      t56 = merge(t11, merge(t15, t54 * t7, t10), t14)
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(t57)
      t61 = merge(t22, t59 * t57, t58)
      t62 = t61 * t26
      t63 = t33 * sigma_bb
      t64 = rho_b * rho_b
      t65 = xc_cbrt(rho_b)
      t66 = t65 * t65
      t68 = 0.1e1_dp / t66 / t64
      t72 = kappa + t29 * t63 * t68 / 0.24e2_dp
      t77 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t72)
      t82 = t6 * t6
      t83 = 0.1e1_dp / t82
      t84 = t16 * t83
      t86 = merge(0.0_dp, merge(0.0_dp, t7 - t84, t14), t10)
      t89 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t86, t20)
      t90 = t89 * t26
      t94 = t26 * t26
      t95 = 0.1e1_dp / t94
      t96 = t25 * t95
      t99 = t5 * t96 * t48 / 0.8e1_dp
      t101 = t27 * t100
      t102 = t5 * t101
      t103 = t43 * t43
      t105 = 0.1e1_dp / t103 * mu
      t106 = t105 * t28
      t107 = t35 * rho_a
      t109 = 0.1e1_dp / t37 / t107
      t111 = t106 * t34 * t109
      t115 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t90 * t48 - t99 + t102 * t111 / &
         0.24e2_dp, t1)
      t116 = t54 * t83
      t118 = merge(0.0_dp, merge(0.0_dp, -t7 - t116, t10), t14)
      t121 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t59 * t118, t58)
      t122 = t121 * t26
      t126 = t61 * t95
      t129 = t5 * t126 * t77 / 0.8e1_dp
      t131 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t122 * t77 - t129, t53)
      t135 = merge(0.0_dp, merge(0.0_dp, -t7 - t84, t14), t10)
      t138 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t135, t20)
      t139 = t138 * t26
      t144 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t139 * t48 - t99, t1)
      t146 = merge(0.0_dp, merge(0.0_dp, t7 - t116, t10), t14)
      t149 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t59 * t146, t58)
      t150 = t149 * t26
      t154 = t62 * t100
      t155 = t5 * t154
      t156 = t72 * t72
      t158 = 0.1e1_dp / t156 * mu
      t159 = t158 * t28
      t160 = t64 * rho_b
      t162 = 0.1e1_dp / t66 / t160
      t164 = t159 * t63 * t162
      t168 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t150 * t77 - t129 + t155 * t164 / &
         0.24e2_dp, t53)
      t173 = t105 * t171 * t39
      t176 = merge(0.0_dp, -t102 * t173 / 0.64e2_dp, t1)
      t178 = t158 * t171 * t68
      t181 = merge(0.0_dp, -t155 * t178 / 0.64e2_dp, t53)
      t184 = t23 * t23
      t185 = 0.1e1_dp / t184
      t186 = t86 * t86
      t189 = t82 * t6
      t190 = 0.1e1_dp / t189
      t191 = t16 * t190
      t194 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t83 + 0.2e1_dp * t191, t14), t10)
      t198 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t185 * t186 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t194, t20)
      t199 = t198 * t26
      t203 = t89 * t95
      t205 = t5 * t203 * t48
      t208 = t5 * t90 * t100
      t212 = 0.1e1_dp / t94 / t6
      t213 = t25 * t212
      t216 = t5 * t213 * t48 / 0.12e2_dp
      t218 = t5 * t96 * t100
      t219 = t218 * t111
      t224 = 0.1e1_dp / t103 / t43 * t223
      t226 = t224 * t225
      t229 = sigma_aa * sigma_aa
      t230 = t228 * t229
      t231 = t35 * t35
      t234 = 0.1e1_dp / t36 / t231 / t107
      t236 = t226 * t230 * t234
      t240 = 0.1e1_dp / t37 / t231
      t242 = t106 * t34 * t240
      t246 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t199 * t48 - t205 / 0.4e1_dp + t208 * &
         t111 / 0.12e2_dp + t216 + t219 / 0.36e2_dp + t102 * t236 / 0.108e3_dp - 0.11e2_dp / &
         0.72e2_dp * t102 * t242, t1)
      t247 = t59 * t59
      t248 = 0.1e1_dp / t247
      t249 = t118 * t118
      t252 = t54 * t190
      t255 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t83 + 0.2e1_dp * t252, t10), t14)
      t259 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t248 * t249 + 0.4e1_dp / 0.3e1_dp * t59 * &
         t255, t58)
      t260 = t259 * t26
      t264 = t121 * t95
      t266 = t5 * t264 * t77
      t268 = t61 * t212
      t271 = t5 * t268 * t77 / 0.12e2_dp
      t273 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t260 * t77 - t266 / 0.4e1_dp + t271, t53)
      t289 = t138 * t95
      t291 = t5 * t289 * t48
      t314 = t149 * t95
      t316 = t5 * t314 * t77
      t324 = t5 * t126 * t100
      t325 = t324 * t164
      t333 = t135 * t135
      t338 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t83 + 0.2e1_dp * t191, t14), t10)
      t342 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t185 * t333 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t338, t20)
      t343 = t342 * t26
      t349 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t343 * t48 - t291 / 0.4e1_dp + t216, t1)
      t350 = t146 * t146
      t355 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t83 + 0.2e1_dp * t252, t10), t14)
      t359 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t248 * t350 + 0.4e1_dp / 0.3e1_dp * t59 * &
         t355, t58)
      t360 = t359 * t26
      t366 = t5 * t150 * t100
      t372 = 0.1e1_dp / t156 / t72 * t223
      t373 = t372 * t225
      t374 = sigma_bb * sigma_bb
      t375 = t228 * t374
      t376 = t64 * t64
      t379 = 0.1e1_dp / t65 / t376 / t160
      t381 = t373 * t375 * t379
      t385 = 0.1e1_dp / t66 / t376
      t387 = t159 * t63 * t385
      t391 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t360 * t77 - t316 / 0.4e1_dp + t366 * &
         t164 / 0.12e2_dp + t271 + t325 / 0.36e2_dp + t155 * t381 / 0.108e3_dp - 0.11e2_dp / &
         0.72e2_dp * t155 * t387, t53)
      t397 = t218 * t173 / 0.192e3_dp
      t398 = t231 * t35
      t400 = 0.1e1_dp / t36 / t398
      t403 = t226 * t228 * t400 * sigma_aa
      t407 = t105 * t171 * t109
      t411 = merge(0.0_dp, -t208 * t173 / 0.64e2_dp - t397 - t102 * t403 / 0.288e3_dp + t102 &
         * t407 / 0.24e2_dp, t1)
      t416 = t324 * t178 / 0.192e3_dp
      t427 = t376 * t64
      t429 = 0.1e1_dp / t65 / t427
      t432 = t373 * t228 * t429 * sigma_bb
      t436 = t158 * t171 * t162
      t440 = merge(0.0_dp, -t366 * t178 / 0.64e2_dp - t416 - t155 * t432 / 0.288e3_dp + t155 &
         * t436 / 0.24e2_dp, t53)
      t443 = t231 * rho_a
      t447 = t224 * t442 / t36 / t443
      t450 = merge(0.0_dp, t102 * t447 / 0.768e3_dp, t1)
      t451 = t376 * rho_b
      t455 = t372 * t442 / t65 / t451
      t458 = merge(0.0_dp, t155 * t455 / 0.768e3_dp, t53)
      v2rho2_aa = 0.2e1_dp * t115 + 0.2e1_dp * t131 + t6 * (t246 + t273)
      v2rho2_bb = 0.2e1_dp * t144 + 0.2e1_dp * t168 + t6 * (t349 + t391)
      v2rhosigma_a_aa = t6 * t411 + t176
      v2rhosigma_b_bb = t6 * t440 + t181
      v2sigma2_aa_aa = t6 * t450
      v2sigma2_bb_bb = t6 * t458
      v2rho2_ab = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
   end subroutine pbe_x_fxc_polar_impl

   pure subroutine pbe_x_vxc_fxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, &
      vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
      v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, &
      v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, &
      v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, &
         v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
         v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
         v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb
      logical :: t1, t10, t14, t20, t53, t58
      real(dp) :: t2, t3, t28, t30, t31, t5, t29, t32
      real(dp) :: t33, t100, t171, t223, t225, t228, t442, t6
      real(dp) :: t7, t11, t15, t16, t18, t19, t21, t22
      real(dp) :: t23, t25, t26, t27, t34, t35, t36, t37
      real(dp) :: t39, t43, t48, t52, t54, t56, t57, t59
      real(dp) :: t61, t62, t63, t64, t65, t66, t68, t72
      real(dp) :: t77, t81, t82, t83, t84, t86, t89, t90
      real(dp) :: t94, t95, t96, t99, t101, t102, t103, t105
      real(dp) :: t106, t107, t109, t111, t115, t116, t118, t121
      real(dp) :: t122, t126, t129, t131, t135, t138, t139, t144
      real(dp) :: t146, t149, t150, t154, t155, t156, t158, t159
      real(dp) :: t160, t162, t164, t168, t173, t176, t178, t181
      real(dp) :: t184, t185, t186, t189, t190, t191, t194, t198
      real(dp) :: t199, t203, t205, t208, t212, t213, t216, t218
      real(dp) :: t219, t224, t226, t229, t230, t231, t234, t236
      real(dp) :: t240, t242, t246, t247, t248, t249, t252, t255
      real(dp) :: t259, t260, t264, t266, t268, t271, t273, t289
      real(dp) :: t291, t314, t316, t324, t325, t333, t338, t342
      real(dp) :: t343, t349, t350, t355, t359, t360, t366, t372
      real(dp) :: t373, t374, t375, t376, t379, t381, t385, t387
      real(dp) :: t391, t397, t398, t400, t403, t407, t411, t416
      real(dp) :: t427, t429, t432, t436, t440, t443, t447, t450
      real(dp) :: t451, t455, t458
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t28 = m_cbrt_6
      t30 = m_pi_sq
      t31 = m_cbrt_pi_sq
      t5 = t2 / t3
      t29 = mu * t28
      t32 = t31 * t31
      t33 = 0.1e1_dp / t32
      t100 = kappa * kappa
      t171 = t28 * t33
      t223 = mu * mu
      t225 = t28 * t28
      t228 = 0.1e1_dp / t31 / t30
      t442 = t225 * t228
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t34 = t33 * sigma_aa
      t35 = rho_a * rho_a
      t36 = xc_cbrt(rho_a)
      t37 = t36 * t36
      t39 = 0.1e1_dp / t37 / t35
      t43 = kappa + t29 * t34 * t39 / 0.24e2_dp
      t48 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t43)
      t52 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t48, t1)
      t53 = rho_b <= dens_tol
      t54 = -t16
      t56 = merge(t11, merge(t15, t54 * t7, t10), t14)
      t57 = 0.1e1_dp + t56
      t58 = t57 <= zeta_tol
      t59 = xc_cbrt(t57)
      t61 = merge(t22, t59 * t57, t58)
      t62 = t61 * t26
      t63 = t33 * sigma_bb
      t64 = rho_b * rho_b
      t65 = xc_cbrt(rho_b)
      t66 = t65 * t65
      t68 = 0.1e1_dp / t66 / t64
      t72 = kappa + t29 * t63 * t68 / 0.24e2_dp
      t77 = 0.1e1_dp + kappa * (0.1e1_dp - kappa / t72)
      t81 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t62 * t77, t53)
      t82 = t6 * t6
      t83 = 0.1e1_dp / t82
      t84 = t16 * t83
      t86 = merge(0.0_dp, merge(0.0_dp, t7 - t84, t14), t10)
      t89 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t86, t20)
      t90 = t89 * t26
      t94 = t26 * t26
      t95 = 0.1e1_dp / t94
      t96 = t25 * t95
      t99 = t5 * t96 * t48 / 0.8e1_dp
      t101 = t27 * t100
      t102 = t5 * t101
      t103 = t43 * t43
      t105 = 0.1e1_dp / t103 * mu
      t106 = t105 * t28
      t107 = t35 * rho_a
      t109 = 0.1e1_dp / t37 / t107
      t111 = t106 * t34 * t109
      t115 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t90 * t48 - t99 + t102 * t111 / &
         0.24e2_dp, t1)
      t116 = t54 * t83
      t118 = merge(0.0_dp, merge(0.0_dp, -t7 - t116, t10), t14)
      t121 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t59 * t118, t58)
      t122 = t121 * t26
      t126 = t61 * t95
      t129 = t5 * t126 * t77 / 0.8e1_dp
      t131 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t122 * t77 - t129, t53)
      t135 = merge(0.0_dp, merge(0.0_dp, -t7 - t84, t14), t10)
      t138 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t135, t20)
      t139 = t138 * t26
      t144 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t139 * t48 - t99, t1)
      t146 = merge(0.0_dp, merge(0.0_dp, t7 - t116, t10), t14)
      t149 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t59 * t146, t58)
      t150 = t149 * t26
      t154 = t62 * t100
      t155 = t5 * t154
      t156 = t72 * t72
      t158 = 0.1e1_dp / t156 * mu
      t159 = t158 * t28
      t160 = t64 * rho_b
      t162 = 0.1e1_dp / t66 / t160
      t164 = t159 * t63 * t162
      t168 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t150 * t77 - t129 + t155 * t164 / &
         0.24e2_dp, t53)
      t173 = t105 * t171 * t39
      t176 = merge(0.0_dp, -t102 * t173 / 0.64e2_dp, t1)
      t178 = t158 * t171 * t68
      t181 = merge(0.0_dp, -t155 * t178 / 0.64e2_dp, t53)
      t184 = t23 * t23
      t185 = 0.1e1_dp / t184
      t186 = t86 * t86
      t189 = t82 * t6
      t190 = 0.1e1_dp / t189
      t191 = t16 * t190
      t194 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t83 + 0.2e1_dp * t191, t14), t10)
      t198 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t185 * t186 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t194, t20)
      t199 = t198 * t26
      t203 = t89 * t95
      t205 = t5 * t203 * t48
      t208 = t5 * t90 * t100
      t212 = 0.1e1_dp / t94 / t6
      t213 = t25 * t212
      t216 = t5 * t213 * t48 / 0.12e2_dp
      t218 = t5 * t96 * t100
      t219 = t218 * t111
      t224 = 0.1e1_dp / t103 / t43 * t223
      t226 = t224 * t225
      t229 = sigma_aa * sigma_aa
      t230 = t228 * t229
      t231 = t35 * t35
      t234 = 0.1e1_dp / t36 / t231 / t107
      t236 = t226 * t230 * t234
      t240 = 0.1e1_dp / t37 / t231
      t242 = t106 * t34 * t240
      t246 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t199 * t48 - t205 / 0.4e1_dp + t208 * &
         t111 / 0.12e2_dp + t216 + t219 / 0.36e2_dp + t102 * t236 / 0.108e3_dp - 0.11e2_dp / &
         0.72e2_dp * t102 * t242, t1)
      t247 = t59 * t59
      t248 = 0.1e1_dp / t247
      t249 = t118 * t118
      t252 = t54 * t190
      t255 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t83 + 0.2e1_dp * t252, t10), t14)
      t259 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t248 * t249 + 0.4e1_dp / 0.3e1_dp * t59 * &
         t255, t58)
      t260 = t259 * t26
      t264 = t121 * t95
      t266 = t5 * t264 * t77
      t268 = t61 * t212
      t271 = t5 * t268 * t77 / 0.12e2_dp
      t273 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t260 * t77 - t266 / 0.4e1_dp + t271, t53)
      t289 = t138 * t95
      t291 = t5 * t289 * t48
      t314 = t149 * t95
      t316 = t5 * t314 * t77
      t324 = t5 * t126 * t100
      t325 = t324 * t164
      t333 = t135 * t135
      t338 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t83 + 0.2e1_dp * t191, t14), t10)
      t342 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t185 * t333 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t338, t20)
      t343 = t342 * t26
      t349 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t343 * t48 - t291 / 0.4e1_dp + t216, t1)
      t350 = t146 * t146
      t355 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t83 + 0.2e1_dp * t252, t10), t14)
      t359 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t248 * t350 + 0.4e1_dp / 0.3e1_dp * t59 * &
         t355, t58)
      t360 = t359 * t26
      t366 = t5 * t150 * t100
      t372 = 0.1e1_dp / t156 / t72 * t223
      t373 = t372 * t225
      t374 = sigma_bb * sigma_bb
      t375 = t228 * t374
      t376 = t64 * t64
      t379 = 0.1e1_dp / t65 / t376 / t160
      t381 = t373 * t375 * t379
      t385 = 0.1e1_dp / t66 / t376
      t387 = t159 * t63 * t385
      t391 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t360 * t77 - t316 / 0.4e1_dp + t366 * &
         t164 / 0.12e2_dp + t271 + t325 / 0.36e2_dp + t155 * t381 / 0.108e3_dp - 0.11e2_dp / &
         0.72e2_dp * t155 * t387, t53)
      t397 = t218 * t173 / 0.192e3_dp
      t398 = t231 * t35
      t400 = 0.1e1_dp / t36 / t398
      t403 = t226 * t228 * t400 * sigma_aa
      t407 = t105 * t171 * t109
      t411 = merge(0.0_dp, -t208 * t173 / 0.64e2_dp - t397 - t102 * t403 / 0.288e3_dp + t102 &
         * t407 / 0.24e2_dp, t1)
      t416 = t324 * t178 / 0.192e3_dp
      t427 = t376 * t64
      t429 = 0.1e1_dp / t65 / t427
      t432 = t373 * t228 * t429 * sigma_bb
      t436 = t158 * t171 * t162
      t440 = merge(0.0_dp, -t366 * t178 / 0.64e2_dp - t416 - t155 * t432 / 0.288e3_dp + t155 &
         * t436 / 0.24e2_dp, t53)
      t443 = t231 * rho_a
      t447 = t224 * t442 / t36 / t443
      t450 = merge(0.0_dp, t102 * t447 / 0.768e3_dp, t1)
      t451 = t376 * rho_b
      t455 = t372 * t442 / t65 / t451
      t458 = merge(0.0_dp, t155 * t455 / 0.768e3_dp, t53)
      vrho_a = t52 + t81 + t6 * (t115 + t131)
      vrho_b = t52 + t81 + t6 * (t144 + t168)
      vsigma_aa = t6 * t176
      vsigma_ab = 0.e0_dp
      vsigma_bb = t6 * t181
      v2rho2_aa = 0.2e1_dp * t115 + 0.2e1_dp * t131 + t6 * (t246 + t273)
      v2rho2_bb = 0.2e1_dp * t144 + 0.2e1_dp * t168 + t6 * (t349 + t391)
      v2rhosigma_a_aa = t6 * t411 + t176
      v2rhosigma_b_bb = t6 * t440 + t181
      v2sigma2_aa_aa = t6 * t450
      v2sigma2_bb_bb = t6 * t458
      v2rho2_ab = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
   end subroutine pbe_x_vxc_fxc_polar_impl

end module trc_xc_pbe_x
