!
! B88: GGA exchange-correlation kernel.
!
! GENERATED by tools/exchcxx_to_fortran.py from ExchCXX's
! include/exchcxx/impl/builtin/kernels/b88.hpp -- do not edit.
!
! The arithmetic is ExchCXX's (MIT; Copyright (c) 2020-2024, The Regents
! of the University of California, through Lawrence Berkeley National
! Laboratory; portions Copyright (c) Microsoft Corporation), itself
! generated by Maple from the functional's definition. See
! https://github.com/wavefunction91/ExchCXX.
!
! Every routine is scalar, pure, and callable from `do concurrent`.
! The public `<name>_<what>_<polar>` routines apply the density and
! gradient thresholds the way ExchCXX's screening_interface.hpp does;
! the `_impl` bodies below them are the bare Maple expressions.
!
! Unpolarised routines take the TOTAL density and its gradient
! invariant; polarised ones take the two spin densities and the three
! gradient invariants. `eps` is the energy per particle, so the
! integrand is rho * eps.
!
module trc_xc_b88
   use trc_boys, only: dp
   use trc_xc_util, only: enforce_polar_sigma_constraints, m_cbrt_2, m_cbrt_3, m_cbrt_4, &
      m_cbrt_one_ov_pi, m_cbrt_pi, xc_cbrt, xc_square
   implicit none
   private

   public :: b88_exc_unpolar
   public :: b88_exc_vxc_unpolar
   public :: b88_fxc_unpolar
   public :: b88_vxc_fxc_unpolar
   public :: b88_exc_polar
   public :: b88_exc_vxc_polar
   public :: b88_fxc_polar
   public :: b88_vxc_fxc_polar

   real(dp), parameter :: dens_tol = 1e-15_dp
   real(dp), parameter :: zeta_tol = 1e-15_dp
   real(dp), parameter :: sigma_tol = 1.0000000000000027e-20_dp
   real(dp), parameter :: tau_tol = 1e-20_dp
   real(dp), parameter :: beta = 0.0042_dp
   real(dp), parameter :: gamma = 6.0_dp

contains

   pure subroutine b88_exc_unpolar(rho, sigma, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps
      real(dp) :: rho_c, sigma_c
      eps = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call b88_exc_unpolar_impl(rho_c, sigma_c, eps)
      end if
   end subroutine b88_exc_unpolar

   pure subroutine b88_exc_vxc_unpolar(rho, sigma, eps, vrho, vsigma)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps, vrho, vsigma
      real(dp) :: rho_c, sigma_c
      eps = 0.0_dp
      vrho = 0.0_dp
      vsigma = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call b88_exc_vxc_unpolar_impl(rho_c, sigma_c, eps, vrho, vsigma)
      end if
   end subroutine b88_exc_vxc_unpolar

   pure subroutine b88_fxc_unpolar(rho, sigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: v2rho2, v2rhosigma, v2sigma2
      real(dp) :: rho_c, sigma_c
      v2rho2 = 0.0_dp
      v2rhosigma = 0.0_dp
      v2sigma2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call b88_fxc_unpolar_impl(rho_c, sigma_c, v2rho2, v2rhosigma, v2sigma2)
      end if
   end subroutine b88_fxc_unpolar

   pure subroutine b88_vxc_fxc_unpolar(rho, sigma, vrho, vsigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: vrho, vsigma, v2rho2, v2rhosigma, v2sigma2
      real(dp) :: rho_c, sigma_c
      vrho = 0.0_dp
      vsigma = 0.0_dp
      v2rho2 = 0.0_dp
      v2rhosigma = 0.0_dp
      v2sigma2 = 0.0_dp
      if (rho > dens_tol) then
         rho_c = rho
         sigma_c = max(sigma, sigma_tol*sigma_tol)
         call b88_vxc_fxc_unpolar_impl(rho_c, sigma_c, vrho, vsigma, v2rho2, v2rhosigma, &
            v2sigma2)
      end if
   end subroutine b88_vxc_fxc_unpolar

   pure subroutine b88_exc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      eps = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call b88_exc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, eps)
      end if
   end subroutine b88_exc_polar

   pure subroutine b88_exc_vxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps, vrho_a, &
      vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      eps = 0.0_dp
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      vsigma_aa = 0.0_dp
      vsigma_ab = 0.0_dp
      vsigma_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call b88_exc_vxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      end if
   end subroutine b88_exc_vxc_polar

   pure subroutine b88_fxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, v2rho2_aa, &
      v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
      v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
      v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, &
         v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
         v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
         v2sigma2_bb_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      v2rhosigma_a_aa = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2rhosigma_b_bb = 0.0_dp
      v2sigma2_aa_aa = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
      v2sigma2_bb_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call b88_fxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, &
            v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
            v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
            v2sigma2_bb_bb)
      end if
   end subroutine b88_fxc_polar

   pure subroutine b88_vxc_fxc_polar(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, vrho_a, &
      vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
      v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, &
      v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, &
      v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, &
         v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
         v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
         v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb
      real(dp) :: rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c
      vrho_a = 0.0_dp
      vrho_b = 0.0_dp
      vsigma_aa = 0.0_dp
      vsigma_ab = 0.0_dp
      vsigma_bb = 0.0_dp
      v2rho2_aa = 0.0_dp
      v2rho2_ab = 0.0_dp
      v2rho2_bb = 0.0_dp
      v2rhosigma_a_aa = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2rhosigma_b_bb = 0.0_dp
      v2sigma2_aa_aa = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
      v2sigma2_bb_bb = 0.0_dp
      if (rho_a + rho_b > dens_tol) then
         rho_a_c = max(rho_a, dens_tol)
         rho_b_c = max(rho_b, dens_tol)
         sigma_aa_c = max(sigma_aa, sigma_tol*sigma_tol)
         sigma_bb_c = max(sigma_bb, sigma_tol*sigma_tol)
         sigma_ab_c = enforce_polar_sigma_constraints(sigma_aa_c, sigma_ab, sigma_bb_c)
         call b88_vxc_fxc_polar_impl(rho_a_c, rho_b_c, sigma_aa_c, sigma_ab_c, sigma_bb_c, &
            vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
            v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, &
            v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, &
            v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      end if
   end subroutine b88_vxc_fxc_polar

   pure subroutine b88_exc_unpolar_impl(rho, sigma, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps
      logical :: t2, t7
      real(dp) :: t3, t4, t23, t25, t28, t6, t20, t21
      real(dp) :: t24, t26, t27, t29, t35, t8, t10, t11
      real(dp) :: t13, t15, t17, t18, t19, t30, t31, t32
      real(dp) :: t34, t36, t37, t39, t43, t44, t46, t47
      real(dp) :: t48, t52, t56
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t23 = m_cbrt_one_ov_pi
      t25 = m_cbrt_4
      t28 = m_cbrt_2
      t6 = t3 / t4
      t20 = t3 * t3
      t21 = beta * t20
      t24 = 0.1e1_dp / t23
      t26 = t24 * t25
      t27 = t21 * t26
      t29 = t28 * t28
      t35 = gamma * beta
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t19 = t17 * t18
      t30 = sigma * t29
      t31 = rho * rho
      t32 = t18 * t18
      t34 = 0.1e1_dp / t32 / t31
      t36 = sqrt(sigma)
      t37 = t35 * t36
      t39 = 0.1e1_dp / t18 / rho
      t43 = log(t36 * t28 * t39 + sqrt(xc_square(t36 * t28 * t39) + 0.1e1_dp))
      t44 = t28 * t39 * t43
      t46 = t37 * t44 + 0.1e1_dp
      t47 = 0.1e1_dp / t46
      t48 = t34 * t47
      t52 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t27 * t30 * t48
      t56 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t52, t2)
      eps = 0.2e1_dp * t56
   end subroutine b88_exc_unpolar_impl

   pure subroutine b88_exc_vxc_unpolar_impl(rho, sigma, eps, vrho, vsigma)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: eps, vrho, vsigma
      logical :: t2, t7
      real(dp) :: t3, t4, t23, t25, t28, t6, t20, t21
      real(dp) :: t24, t26, t27, t29, t35, t99, t100, t8
      real(dp) :: t10, t11, t13, t15, t17, t18, t19, t30
      real(dp) :: t31, t32, t34, t36, t37, t39, t43, t44
      real(dp) :: t46, t47, t48, t52, t56, t58, t62, t64
      real(dp) :: t65, t69, t70, t71, t75, t77, t78, t80
      real(dp) :: t81, t82, t83, t86, t91, t96, t104, t106
      real(dp) :: t107, t110, t115, t119
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t23 = m_cbrt_one_ov_pi
      t25 = m_cbrt_4
      t28 = m_cbrt_2
      t6 = t3 / t4
      t20 = t3 * t3
      t21 = beta * t20
      t24 = 0.1e1_dp / t23
      t26 = t24 * t25
      t27 = t21 * t26
      t29 = t28 * t28
      t35 = gamma * beta
      t99 = t21 * t24
      t100 = t25 * t29
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t19 = t17 * t18
      t30 = sigma * t29
      t31 = rho * rho
      t32 = t18 * t18
      t34 = 0.1e1_dp / t32 / t31
      t36 = sqrt(sigma)
      t37 = t35 * t36
      t39 = 0.1e1_dp / t18 / rho
      t43 = log(t36 * t28 * t39 + sqrt(xc_square(t36 * t28 * t39) + 0.1e1_dp))
      t44 = t28 * t39 * t43
      t46 = t37 * t44 + 0.1e1_dp
      t47 = 0.1e1_dp / t46
      t48 = t34 * t47
      t52 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t27 * t30 * t48
      t56 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t52, t2)
      t58 = t17 / t32
      t62 = t31 * rho
      t64 = 0.1e1_dp / t32 / t62
      t65 = t64 * t47
      t69 = t46 * t46
      t70 = 0.1e1_dp / t69
      t71 = t34 * t70
      t75 = t28 / t18 / t31 * t43
      t77 = t35 * sigma
      t78 = t29 * t64
      t80 = t30 * t34 + 0.1e1_dp
      t81 = sqrt(t80)
      t82 = 0.1e1_dp / t81
      t83 = t78 * t82
      t86 = -0.4e1_dp / 0.3e1_dp * t37 * t75 - 0.4e1_dp / 0.3e1_dp * t77 * t83
      t91 = -0.16e2_dp / 0.27e2_dp * t27 * t30 * t65 - 0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 &
         * t86
      t96 = merge(0.0_dp, -t6 * t58 * t52 / 0.8e1_dp - 0.3e1_dp / 0.8e1_dp * t6 * t19 * t91, t2)
      t104 = t35 / t36
      t106 = t29 * t34
      t107 = t106 * t82
      t110 = t104 * t44 / 0.2e1_dp + t35 * t107 / 0.2e1_dp
      t115 = -0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 * t110 + 0.2e1_dp / 0.9e1_dp * t99 * t100 &
         * t48
      t119 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t115, t2)
      eps = 0.2e1_dp * t56
      vrho = 0.2e1_dp * rho * t96 + 0.2e1_dp * t56
      vsigma = 0.2e1_dp * rho * t119
   end subroutine b88_exc_vxc_unpolar_impl

   pure subroutine b88_fxc_unpolar_impl(rho, sigma, v2rho2, v2rhosigma, v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: v2rho2, v2rhosigma, v2sigma2
      logical :: t2, t7
      real(dp) :: t3, t4, t23, t25, t28, t6, t20, t21
      real(dp) :: t24, t26, t27, t29, t35, t99, t100, t210
      real(dp) :: t8, t10, t11, t13, t15, t17, t18, t19
      real(dp) :: t30, t31, t32, t34, t36, t37, t39, t43
      real(dp) :: t44, t46, t47, t48, t52, t58, t62, t64
      real(dp) :: t65, t69, t70, t71, t75, t77, t78, t80
      real(dp) :: t81, t82, t83, t86, t91, t96, t104, t106
      real(dp) :: t107, t110, t115, t119, t124, t131, t133, t134
      real(dp) :: t138, t144, t145, t146, t154, t157, t158, t161
      real(dp) :: t162, t165, t168, t169, t172, t177, t182, t191
      real(dp) :: t200, t201, t202, t203, t211, t213, t218, t223
      real(dp) :: t228, t231, t235, t242, t245, t246, t249, t252
      real(dp) :: t253, t256, t261, t265
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t23 = m_cbrt_one_ov_pi
      t25 = m_cbrt_4
      t28 = m_cbrt_2
      t6 = t3 / t4
      t20 = t3 * t3
      t21 = beta * t20
      t24 = 0.1e1_dp / t23
      t26 = t24 * t25
      t27 = t21 * t26
      t29 = t28 * t28
      t35 = gamma * beta
      t99 = t21 * t24
      t100 = t25 * t29
      t210 = t35 * t28
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t19 = t17 * t18
      t30 = sigma * t29
      t31 = rho * rho
      t32 = t18 * t18
      t34 = 0.1e1_dp / t32 / t31
      t36 = sqrt(sigma)
      t37 = t35 * t36
      t39 = 0.1e1_dp / t18 / rho
      t43 = log(t36 * t28 * t39 + sqrt(xc_square(t36 * t28 * t39) + 0.1e1_dp))
      t44 = t28 * t39 * t43
      t46 = t37 * t44 + 0.1e1_dp
      t47 = 0.1e1_dp / t46
      t48 = t34 * t47
      t52 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t27 * t30 * t48
      t58 = t17 / t32
      t62 = t31 * rho
      t64 = 0.1e1_dp / t32 / t62
      t65 = t64 * t47
      t69 = t46 * t46
      t70 = 0.1e1_dp / t69
      t71 = t34 * t70
      t75 = t28 / t18 / t31 * t43
      t77 = t35 * sigma
      t78 = t29 * t64
      t80 = t30 * t34 + 0.1e1_dp
      t81 = sqrt(t80)
      t82 = 0.1e1_dp / t81
      t83 = t78 * t82
      t86 = -0.4e1_dp / 0.3e1_dp * t37 * t75 - 0.4e1_dp / 0.3e1_dp * t77 * t83
      t91 = -0.16e2_dp / 0.27e2_dp * t27 * t30 * t65 - 0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 &
         * t86
      t96 = merge(0.0_dp, -t6 * t58 * t52 / 0.8e1_dp - 0.3e1_dp / 0.8e1_dp * t6 * t19 * t91, t2)
      t104 = t35 / t36
      t106 = t29 * t34
      t107 = t106 * t82
      t110 = t104 * t44 / 0.2e1_dp + t35 * t107 / 0.2e1_dp
      t115 = -0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 * t110 + 0.2e1_dp / 0.9e1_dp * t99 * t100 &
         * t48
      t119 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t115, t2)
      t124 = t17 / t32 / rho
      t131 = t31 * t31
      t133 = 0.1e1_dp / t32 / t131
      t134 = t133 * t47
      t138 = t64 * t70
      t144 = 0.1e1_dp / t69 / t46
      t145 = t34 * t144
      t146 = t86 * t86
      t154 = t28 / t18 / t62 * t43
      t157 = t29 * t133
      t158 = t157 * t82
      t161 = sigma * sigma
      t162 = t35 * t161
      t165 = 0.1e1_dp / t18 / t131 / t62
      t168 = 0.1e1_dp / t81 / t80
      t169 = t28 * t165 * t168
      t172 = 0.28e2_dp / 0.9e1_dp * t37 * t154 + 0.2e2_dp / 0.3e1_dp * t77 * t158 - 0.32e2_dp &
         / 0.9e1_dp * t162 * t169
      t177 = 0.176e3_dp / 0.81e2_dp * t27 * t30 * t134 + 0.32e2_dp / 0.27e2_dp * t27 * t30 * &
         t138 * t86 + 0.4e1_dp / 0.9e1_dp * t27 * t30 * t145 * t146 - 0.2e1_dp / 0.9e1_dp * &
         t27 * t30 * t71 * t172
      t182 = merge(0.0_dp, t6 * t124 * t52 / 0.12e2_dp - t6 * t58 * t91 / 0.4e1_dp - 0.3e1_dp &
         / 0.8e1_dp * t6 * t19 * t177, t2)
      t191 = t70 * t86
      t200 = t21 * t26 * sigma
      t201 = t144 * t110
      t202 = t201 * t86
      t203 = t106 * t202
      t211 = t131 * t31
      t213 = 0.1e1_dp / t18 / t211
      t218 = -0.2e1_dp / 0.3e1_dp * t104 * t75 - 0.2e1_dp * t35 * t83 + 0.4e1_dp / 0.3e1_dp * &
         t210 * t213 * t168 * sigma
      t223 = -0.16e2_dp / 0.27e2_dp * t99 * t100 * t65 - 0.2e1_dp / 0.9e1_dp * t27 * t106 * &
         t191 + 0.16e2_dp / 0.27e2_dp * t27 * t30 * t138 * t110 + 0.4e1_dp / 0.9e1_dp * t200 &
         * t203 - 0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 * t218
      t228 = merge(0.0_dp, -t6 * t58 * t115 / 0.8e1_dp - 0.3e1_dp / 0.8e1_dp * t6 * t19 * &
         t223, t2)
      t231 = t70 * t110
      t235 = t110 * t110
      t242 = t35 / t36 / sigma
      t245 = 0.1e1_dp / sigma
      t246 = t35 * t245
      t249 = t131 * rho
      t252 = t28 / t18 / t249
      t253 = t252 * t168
      t256 = -t242 * t44 / 0.4e1_dp + t246 * t107 / 0.4e1_dp - t35 * t253 / 0.2e1_dp
      t261 = -0.4e1_dp / 0.9e1_dp * t27 * t106 * t231 + 0.4e1_dp / 0.9e1_dp * t27 * t30 * &
         t145 * t235 - 0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 * t256
      t265 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t261, t2)
      v2rho2 = 0.2e1_dp * rho * t182 + 0.4e1_dp * t96
      v2rhosigma = 0.2e1_dp * rho * t228 + 0.2e1_dp * t119
      v2sigma2 = 0.2e1_dp * rho * t265
   end subroutine b88_fxc_unpolar_impl

   pure subroutine b88_vxc_fxc_unpolar_impl(rho, sigma, vrho, vsigma, v2rho2, v2rhosigma, &
      v2sigma2)
      !$acc routine seq
      real(dp), intent(in) :: rho, sigma
      real(dp), intent(out) :: vrho, vsigma, v2rho2, v2rhosigma, v2sigma2
      logical :: t2, t7
      real(dp) :: t3, t4, t23, t25, t28, t6, t20, t21
      real(dp) :: t24, t26, t27, t29, t35, t99, t100, t210
      real(dp) :: t8, t10, t11, t13, t15, t17, t18, t19
      real(dp) :: t30, t31, t32, t34, t36, t37, t39, t43
      real(dp) :: t44, t46, t47, t48, t52, t56, t58, t62
      real(dp) :: t64, t65, t69, t70, t71, t75, t77, t78
      real(dp) :: t80, t81, t82, t83, t86, t91, t96, t104
      real(dp) :: t106, t107, t110, t115, t119, t124, t131, t133
      real(dp) :: t134, t138, t144, t145, t146, t154, t157, t158
      real(dp) :: t161, t162, t165, t168, t169, t172, t177, t182
      real(dp) :: t191, t200, t201, t202, t203, t211, t213, t218
      real(dp) :: t223, t228, t231, t235, t242, t245, t246, t249
      real(dp) :: t252, t253, t256, t261, t265
      t3 = m_cbrt_3
      t4 = m_cbrt_pi
      t23 = m_cbrt_one_ov_pi
      t25 = m_cbrt_4
      t28 = m_cbrt_2
      t6 = t3 / t4
      t20 = t3 * t3
      t21 = beta * t20
      t24 = 0.1e1_dp / t23
      t26 = t24 * t25
      t27 = t21 * t26
      t29 = t28 * t28
      t35 = gamma * beta
      t99 = t21 * t24
      t100 = t25 * t29
      t210 = t35 * t28
      t2 = rho / 0.2e1_dp <= dens_tol
      t7 = 0.1e1_dp <= zeta_tol
      t8 = zeta_tol - 0.1e1_dp
      t10 = merge(t8, merge(-t8, 0.0_dp, t7), t7)
      t11 = 0.1e1_dp + t10
      t13 = xc_cbrt(zeta_tol)
      t15 = xc_cbrt(t11)
      t17 = merge(t13 * zeta_tol, t15 * t11, t11 <= zeta_tol)
      t18 = xc_cbrt(rho)
      t19 = t17 * t18
      t30 = sigma * t29
      t31 = rho * rho
      t32 = t18 * t18
      t34 = 0.1e1_dp / t32 / t31
      t36 = sqrt(sigma)
      t37 = t35 * t36
      t39 = 0.1e1_dp / t18 / rho
      t43 = log(t36 * t28 * t39 + sqrt(xc_square(t36 * t28 * t39) + 0.1e1_dp))
      t44 = t28 * t39 * t43
      t46 = t37 * t44 + 0.1e1_dp
      t47 = 0.1e1_dp / t46
      t48 = t34 * t47
      t52 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t27 * t30 * t48
      t56 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t52, t2)
      t58 = t17 / t32
      t62 = t31 * rho
      t64 = 0.1e1_dp / t32 / t62
      t65 = t64 * t47
      t69 = t46 * t46
      t70 = 0.1e1_dp / t69
      t71 = t34 * t70
      t75 = t28 / t18 / t31 * t43
      t77 = t35 * sigma
      t78 = t29 * t64
      t80 = t30 * t34 + 0.1e1_dp
      t81 = sqrt(t80)
      t82 = 0.1e1_dp / t81
      t83 = t78 * t82
      t86 = -0.4e1_dp / 0.3e1_dp * t37 * t75 - 0.4e1_dp / 0.3e1_dp * t77 * t83
      t91 = -0.16e2_dp / 0.27e2_dp * t27 * t30 * t65 - 0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 &
         * t86
      t96 = merge(0.0_dp, -t6 * t58 * t52 / 0.8e1_dp - 0.3e1_dp / 0.8e1_dp * t6 * t19 * t91, t2)
      t104 = t35 / t36
      t106 = t29 * t34
      t107 = t106 * t82
      t110 = t104 * t44 / 0.2e1_dp + t35 * t107 / 0.2e1_dp
      t115 = -0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 * t110 + 0.2e1_dp / 0.9e1_dp * t99 * t100 &
         * t48
      t119 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t115, t2)
      t124 = t17 / t32 / rho
      t131 = t31 * t31
      t133 = 0.1e1_dp / t32 / t131
      t134 = t133 * t47
      t138 = t64 * t70
      t144 = 0.1e1_dp / t69 / t46
      t145 = t34 * t144
      t146 = t86 * t86
      t154 = t28 / t18 / t62 * t43
      t157 = t29 * t133
      t158 = t157 * t82
      t161 = sigma * sigma
      t162 = t35 * t161
      t165 = 0.1e1_dp / t18 / t131 / t62
      t168 = 0.1e1_dp / t81 / t80
      t169 = t28 * t165 * t168
      t172 = 0.28e2_dp / 0.9e1_dp * t37 * t154 + 0.2e2_dp / 0.3e1_dp * t77 * t158 - 0.32e2_dp &
         / 0.9e1_dp * t162 * t169
      t177 = 0.176e3_dp / 0.81e2_dp * t27 * t30 * t134 + 0.32e2_dp / 0.27e2_dp * t27 * t30 * &
         t138 * t86 + 0.4e1_dp / 0.9e1_dp * t27 * t30 * t145 * t146 - 0.2e1_dp / 0.9e1_dp * &
         t27 * t30 * t71 * t172
      t182 = merge(0.0_dp, t6 * t124 * t52 / 0.12e2_dp - t6 * t58 * t91 / 0.4e1_dp - 0.3e1_dp &
         / 0.8e1_dp * t6 * t19 * t177, t2)
      t191 = t70 * t86
      t200 = t21 * t26 * sigma
      t201 = t144 * t110
      t202 = t201 * t86
      t203 = t106 * t202
      t211 = t131 * t31
      t213 = 0.1e1_dp / t18 / t211
      t218 = -0.2e1_dp / 0.3e1_dp * t104 * t75 - 0.2e1_dp * t35 * t83 + 0.4e1_dp / 0.3e1_dp * &
         t210 * t213 * t168 * sigma
      t223 = -0.16e2_dp / 0.27e2_dp * t99 * t100 * t65 - 0.2e1_dp / 0.9e1_dp * t27 * t106 * &
         t191 + 0.16e2_dp / 0.27e2_dp * t27 * t30 * t138 * t110 + 0.4e1_dp / 0.9e1_dp * t200 &
         * t203 - 0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 * t218
      t228 = merge(0.0_dp, -t6 * t58 * t115 / 0.8e1_dp - 0.3e1_dp / 0.8e1_dp * t6 * t19 * &
         t223, t2)
      t231 = t70 * t110
      t235 = t110 * t110
      t242 = t35 / t36 / sigma
      t245 = 0.1e1_dp / sigma
      t246 = t35 * t245
      t249 = t131 * rho
      t252 = t28 / t18 / t249
      t253 = t252 * t168
      t256 = -t242 * t44 / 0.4e1_dp + t246 * t107 / 0.4e1_dp - t35 * t253 / 0.2e1_dp
      t261 = -0.4e1_dp / 0.9e1_dp * t27 * t106 * t231 + 0.4e1_dp / 0.9e1_dp * t27 * t30 * &
         t145 * t235 - 0.2e1_dp / 0.9e1_dp * t27 * t30 * t71 * t256
      t265 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t6 * t19 * t261, t2)
      vrho = 0.2e1_dp * rho * t96 + 0.2e1_dp * t56
      vsigma = 0.2e1_dp * rho * t119
      v2rho2 = 0.2e1_dp * rho * t182 + 0.4e1_dp * t96
      v2rhosigma = 0.2e1_dp * rho * t228 + 0.2e1_dp * t119
      v2sigma2 = 0.2e1_dp * rho * t265
   end subroutine b88_vxc_fxc_unpolar_impl

   pure subroutine b88_exc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps
      logical :: t1, t10, t14, t20, t60, t65
      real(dp) :: t2, t3, t31, t34, t5, t28, t29, t32
      real(dp) :: t33, t41, t6, t7, t11, t15, t16, t18
      real(dp) :: t19, t21, t22, t23, t25, t26, t27, t35
      real(dp) :: t36, t37, t38, t40, t42, t44, t45, t46
      real(dp) :: t49, t50, t55, t59, t61, t63, t64, t66
      real(dp) :: t68, t69, t70, t71, t72, t73, t75, t76
      real(dp) :: t78, t79, t80, t83, t84, t89, t93
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t31 = m_cbrt_one_ov_pi
      t34 = m_cbrt_4
      t5 = t2 / t3
      t28 = t2 * t2
      t29 = beta * t28
      t32 = 0.1e1_dp / t31
      t33 = t29 * t32
      t41 = gamma * beta
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t35 = t34 * sigma_aa
      t36 = rho_a * rho_a
      t37 = xc_cbrt(rho_a)
      t38 = t37 * t37
      t40 = 0.1e1_dp / t38 / t36
      t42 = sqrt(sigma_aa)
      t44 = 0.1e1_dp / t37 / rho_a
      t45 = t42 * t44
      t46 = log(t45 + sqrt(t45 * t45 + 0.1e1_dp))
      t49 = t41 * t45 * t46 + 0.1e1_dp
      t50 = 0.1e1_dp / t49
      t55 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t35 * t40 * t50
      t59 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t55, t1)
      t60 = rho_b <= dens_tol
      t61 = -t16
      t63 = merge(t11, merge(t15, t61 * t7, t10), t14)
      t64 = 0.1e1_dp + t63
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t22, t66 * t64, t65)
      t69 = t68 * t26
      t70 = t34 * sigma_bb
      t71 = rho_b * rho_b
      t72 = xc_cbrt(rho_b)
      t73 = t72 * t72
      t75 = 0.1e1_dp / t73 / t71
      t76 = sqrt(sigma_bb)
      t78 = 0.1e1_dp / t72 / rho_b
      t79 = t76 * t78
      t80 = log(t79 + sqrt(t79 * t79 + 0.1e1_dp))
      t83 = t41 * t79 * t80 + 0.1e1_dp
      t84 = 0.1e1_dp / t83
      t89 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t70 * t75 * t84
      t93 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t89, t60)
      eps = t59 + t93
   end subroutine b88_exc_polar_impl

   pure subroutine b88_exc_vxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, eps, &
      vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: eps, vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb
      logical :: t1, t10, t14, t20, t60, t65
      real(dp) :: t2, t3, t31, t34, t5, t28, t29, t32
      real(dp) :: t33, t41, t119, t120, t6, t7, t11, t15
      real(dp) :: t16, t18, t19, t21, t22, t23, t25, t26
      real(dp) :: t27, t35, t36, t37, t38, t40, t42, t44
      real(dp) :: t45, t46, t49, t50, t55, t59, t61, t63
      real(dp) :: t64, t66, t68, t69, t70, t71, t72, t73
      real(dp) :: t75, t76, t78, t79, t80, t83, t84, t89
      real(dp) :: t93, t94, t95, t96, t98, t101, t102, t106
      real(dp) :: t107, t108, t111, t112, t114, t121, t122, t123
      real(dp) :: t125, t129, t130, t131, t132, t136, t137, t141
      real(dp) :: t146, t147, t149, t152, t153, t157, t160, t162
      real(dp) :: t166, t169, t170, t175, t177, t180, t181, t185
      real(dp) :: t187, t192, t193, t194, t196, t200, t201, t202
      real(dp) :: t203, t207, t208, t212, t217, t220, t223, t230
      real(dp) :: t231, t235, t239, t240, t243, t250, t251, t255
      real(dp) :: t259
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t31 = m_cbrt_one_ov_pi
      t34 = m_cbrt_4
      t5 = t2 / t3
      t28 = t2 * t2
      t29 = beta * t28
      t32 = 0.1e1_dp / t31
      t33 = t29 * t32
      t41 = gamma * beta
      t119 = t32 * t34
      t120 = t29 * t119
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t35 = t34 * sigma_aa
      t36 = rho_a * rho_a
      t37 = xc_cbrt(rho_a)
      t38 = t37 * t37
      t40 = 0.1e1_dp / t38 / t36
      t42 = sqrt(sigma_aa)
      t44 = 0.1e1_dp / t37 / rho_a
      t45 = t42 * t44
      t46 = log(t45 + sqrt(t45 * t45 + 0.1e1_dp))
      t49 = t41 * t45 * t46 + 0.1e1_dp
      t50 = 0.1e1_dp / t49
      t55 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t35 * t40 * t50
      t59 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t55, t1)
      t60 = rho_b <= dens_tol
      t61 = -t16
      t63 = merge(t11, merge(t15, t61 * t7, t10), t14)
      t64 = 0.1e1_dp + t63
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t22, t66 * t64, t65)
      t69 = t68 * t26
      t70 = t34 * sigma_bb
      t71 = rho_b * rho_b
      t72 = xc_cbrt(rho_b)
      t73 = t72 * t72
      t75 = 0.1e1_dp / t73 / t71
      t76 = sqrt(sigma_bb)
      t78 = 0.1e1_dp / t72 / rho_b
      t79 = t76 * t78
      t80 = log(t79 + sqrt(t79 * t79 + 0.1e1_dp))
      t83 = t41 * t79 * t80 + 0.1e1_dp
      t84 = 0.1e1_dp / t83
      t89 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t70 * t75 * t84
      t93 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t89, t60)
      t94 = t6 * t6
      t95 = 0.1e1_dp / t94
      t96 = t16 * t95
      t98 = merge(0.0_dp, merge(0.0_dp, t7 - t96, t14), t10)
      t101 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t98, t20)
      t102 = t101 * t26
      t106 = t26 * t26
      t107 = 0.1e1_dp / t106
      t108 = t25 * t107
      t111 = t5 * t108 * t55 / 0.8e1_dp
      t112 = t36 * rho_a
      t114 = 0.1e1_dp / t38 / t112
      t121 = sigma_aa * t40
      t122 = t49 * t49
      t123 = 0.1e1_dp / t122
      t125 = 0.1e1_dp / t37 / t36
      t129 = sigma_aa * t114
      t130 = t121 + 0.1e1_dp
      t131 = sqrt(t130)
      t132 = 0.1e1_dp / t131
      t136 = -0.4e1_dp / 0.3e1_dp * t41 * t42 * t125 * t46 - 0.4e1_dp / 0.3e1_dp * t41 * t129 &
         * t132
      t137 = t123 * t136
      t141 = -0.16e2_dp / 0.27e2_dp * t33 * t35 * t114 * t50 - 0.2e1_dp / 0.9e1_dp * t120 * &
         t121 * t137
      t146 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t102 * t55 - t111 - 0.3e1_dp / &
         0.8e1_dp * t5 * t27 * t141, t1)
      t147 = t61 * t95
      t149 = merge(0.0_dp, merge(0.0_dp, -t7 - t147, t10), t14)
      t152 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t149, t65)
      t153 = t152 * t26
      t157 = t68 * t107
      t160 = t5 * t157 * t89 / 0.8e1_dp
      t162 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t153 * t89 - t160, t60)
      t166 = merge(0.0_dp, merge(0.0_dp, -t7 - t96, t14), t10)
      t169 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t166, t20)
      t170 = t169 * t26
      t175 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t170 * t55 - t111, t1)
      t177 = merge(0.0_dp, merge(0.0_dp, t7 - t147, t10), t14)
      t180 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t177, t65)
      t181 = t180 * t26
      t185 = t71 * rho_b
      t187 = 0.1e1_dp / t73 / t185
      t192 = sigma_bb * t75
      t193 = t83 * t83
      t194 = 0.1e1_dp / t193
      t196 = 0.1e1_dp / t72 / t71
      t200 = sigma_bb * t187
      t201 = t192 + 0.1e1_dp
      t202 = sqrt(t201)
      t203 = 0.1e1_dp / t202
      t207 = -0.4e1_dp / 0.3e1_dp * t41 * t76 * t196 * t80 - 0.4e1_dp / 0.3e1_dp * t41 * t200 &
         * t203
      t208 = t194 * t207
      t212 = -0.16e2_dp / 0.27e2_dp * t33 * t70 * t187 * t84 - 0.2e1_dp / 0.9e1_dp * t120 * &
         t192 * t208
      t217 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t181 * t89 - t160 - 0.3e1_dp / &
         0.8e1_dp * t5 * t69 * t212, t60)
      t220 = t34 * t40
      t223 = 0.1e1_dp / t42
      t230 = t41 * t223 * t44 * t46 / 0.2e1_dp + t41 * t40 * t132 / 0.2e1_dp
      t231 = t123 * t230
      t235 = -0.2e1_dp / 0.9e1_dp * t120 * t121 * t231 + 0.2e1_dp / 0.9e1_dp * t33 * t220 * t50
      t239 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t235, t1)
      t240 = t34 * t75
      t243 = 0.1e1_dp / t76
      t250 = t41 * t243 * t78 * t80 / 0.2e1_dp + t41 * t75 * t203 / 0.2e1_dp
      t251 = t194 * t250
      t255 = -0.2e1_dp / 0.9e1_dp * t120 * t192 * t251 + 0.2e1_dp / 0.9e1_dp * t33 * t240 * t84
      t259 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t255, t60)
      eps = t59 + t93
      vrho_a = t59 + t93 + t6 * (t146 + t162)
      vrho_b = t59 + t93 + t6 * (t175 + t217)
      vsigma_aa = t6 * t239
      vsigma_ab = 0.e0_dp
      vsigma_bb = t6 * t259
   end subroutine b88_exc_vxc_polar_impl

   pure subroutine b88_fxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, v2rho2_aa, &
      v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
      v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
      v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: v2rho2_aa, v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, &
         v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, &
         v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, &
         v2sigma2_bb_bb
      logical :: t1, t10, t14, t20, t60, t65
      real(dp) :: t2, t3, t31, t34, t5, t28, t29, t32
      real(dp) :: t33, t41, t119, t120, t6, t7, t11, t15
      real(dp) :: t16, t18, t19, t21, t22, t23, t25, t26
      real(dp) :: t27, t35, t36, t37, t38, t40, t42, t44
      real(dp) :: t45, t46, t49, t50, t55, t61, t63, t64
      real(dp) :: t66, t68, t69, t70, t71, t72, t73, t75
      real(dp) :: t76, t78, t79, t80, t83, t84, t89, t94
      real(dp) :: t95, t96, t98, t101, t102, t106, t107, t108
      real(dp) :: t111, t112, t114, t121, t122, t123, t125, t129
      real(dp) :: t130, t131, t132, t136, t137, t141, t146, t147
      real(dp) :: t149, t152, t153, t157, t160, t162, t166, t169
      real(dp) :: t170, t175, t177, t180, t181, t185, t187, t192
      real(dp) :: t193, t194, t196, t200, t201, t202, t203, t207
      real(dp) :: t208, t212, t217, t220, t223, t230, t231, t235
      real(dp) :: t239, t240, t243, t250, t251, t255, t259, t262
      real(dp) :: t263, t264, t267, t268, t269, t272, t276, t277
      real(dp) :: t281, t283, t289, t290, t293, t295, t297, t299
      real(dp) :: t308, t309, t310, t315, t320, t324, t327, t330
      real(dp) :: t334, t335, t339, t344, t345, t346, t347, t350
      real(dp) :: t353, t357, t358, t362, t364, t366, t369, t371
      real(dp) :: t387, t389, t411, t413, t420, t428, t433, t437
      real(dp) :: t438, t444, t445, t450, t454, t455, t464, t466
      real(dp) :: t475, t476, t477, t482, t487, t491, t494, t497
      real(dp) :: t501, t502, t506, t511, t519, t520, t530, t531
      real(dp) :: t542, t544, t545, t549, t550, t554, t559, t566
      real(dp) :: t579, t589, t590, t601, t603, t604, t608, t609
      real(dp) :: t613, t618, t623, t624, t629, t633, t637, t639
      real(dp) :: t643, t644, t648, t652, t656, t657, t662, t666
      real(dp) :: t670, t672, t676, t677, t681, t685
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t31 = m_cbrt_one_ov_pi
      t34 = m_cbrt_4
      t5 = t2 / t3
      t28 = t2 * t2
      t29 = beta * t28
      t32 = 0.1e1_dp / t31
      t33 = t29 * t32
      t41 = gamma * beta
      t119 = t32 * t34
      t120 = t29 * t119
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t35 = t34 * sigma_aa
      t36 = rho_a * rho_a
      t37 = xc_cbrt(rho_a)
      t38 = t37 * t37
      t40 = 0.1e1_dp / t38 / t36
      t42 = sqrt(sigma_aa)
      t44 = 0.1e1_dp / t37 / rho_a
      t45 = t42 * t44
      t46 = log(t45 + sqrt(t45 * t45 + 0.1e1_dp))
      t49 = t41 * t45 * t46 + 0.1e1_dp
      t50 = 0.1e1_dp / t49
      t55 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t35 * t40 * t50
      t60 = rho_b <= dens_tol
      t61 = -t16
      t63 = merge(t11, merge(t15, t61 * t7, t10), t14)
      t64 = 0.1e1_dp + t63
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t22, t66 * t64, t65)
      t69 = t68 * t26
      t70 = t34 * sigma_bb
      t71 = rho_b * rho_b
      t72 = xc_cbrt(rho_b)
      t73 = t72 * t72
      t75 = 0.1e1_dp / t73 / t71
      t76 = sqrt(sigma_bb)
      t78 = 0.1e1_dp / t72 / rho_b
      t79 = t76 * t78
      t80 = log(t79 + sqrt(t79 * t79 + 0.1e1_dp))
      t83 = t41 * t79 * t80 + 0.1e1_dp
      t84 = 0.1e1_dp / t83
      t89 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t70 * t75 * t84
      t94 = t6 * t6
      t95 = 0.1e1_dp / t94
      t96 = t16 * t95
      t98 = merge(0.0_dp, merge(0.0_dp, t7 - t96, t14), t10)
      t101 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t98, t20)
      t102 = t101 * t26
      t106 = t26 * t26
      t107 = 0.1e1_dp / t106
      t108 = t25 * t107
      t111 = t5 * t108 * t55 / 0.8e1_dp
      t112 = t36 * rho_a
      t114 = 0.1e1_dp / t38 / t112
      t121 = sigma_aa * t40
      t122 = t49 * t49
      t123 = 0.1e1_dp / t122
      t125 = 0.1e1_dp / t37 / t36
      t129 = sigma_aa * t114
      t130 = t121 + 0.1e1_dp
      t131 = sqrt(t130)
      t132 = 0.1e1_dp / t131
      t136 = -0.4e1_dp / 0.3e1_dp * t41 * t42 * t125 * t46 - 0.4e1_dp / 0.3e1_dp * t41 * t129 &
         * t132
      t137 = t123 * t136
      t141 = -0.16e2_dp / 0.27e2_dp * t33 * t35 * t114 * t50 - 0.2e1_dp / 0.9e1_dp * t120 * &
         t121 * t137
      t146 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t102 * t55 - t111 - 0.3e1_dp / &
         0.8e1_dp * t5 * t27 * t141, t1)
      t147 = t61 * t95
      t149 = merge(0.0_dp, merge(0.0_dp, -t7 - t147, t10), t14)
      t152 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t149, t65)
      t153 = t152 * t26
      t157 = t68 * t107
      t160 = t5 * t157 * t89 / 0.8e1_dp
      t162 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t153 * t89 - t160, t60)
      t166 = merge(0.0_dp, merge(0.0_dp, -t7 - t96, t14), t10)
      t169 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t166, t20)
      t170 = t169 * t26
      t175 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t170 * t55 - t111, t1)
      t177 = merge(0.0_dp, merge(0.0_dp, t7 - t147, t10), t14)
      t180 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t177, t65)
      t181 = t180 * t26
      t185 = t71 * rho_b
      t187 = 0.1e1_dp / t73 / t185
      t192 = sigma_bb * t75
      t193 = t83 * t83
      t194 = 0.1e1_dp / t193
      t196 = 0.1e1_dp / t72 / t71
      t200 = sigma_bb * t187
      t201 = t192 + 0.1e1_dp
      t202 = sqrt(t201)
      t203 = 0.1e1_dp / t202
      t207 = -0.4e1_dp / 0.3e1_dp * t41 * t76 * t196 * t80 - 0.4e1_dp / 0.3e1_dp * t41 * t200 &
         * t203
      t208 = t194 * t207
      t212 = -0.16e2_dp / 0.27e2_dp * t33 * t70 * t187 * t84 - 0.2e1_dp / 0.9e1_dp * t120 * &
         t192 * t208
      t217 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t181 * t89 - t160 - 0.3e1_dp / &
         0.8e1_dp * t5 * t69 * t212, t60)
      t220 = t34 * t40
      t223 = 0.1e1_dp / t42
      t230 = t41 * t223 * t44 * t46 / 0.2e1_dp + t41 * t40 * t132 / 0.2e1_dp
      t231 = t123 * t230
      t235 = -0.2e1_dp / 0.9e1_dp * t120 * t121 * t231 + 0.2e1_dp / 0.9e1_dp * t33 * t220 * t50
      t239 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t235, t1)
      t240 = t34 * t75
      t243 = 0.1e1_dp / t76
      t250 = t41 * t243 * t78 * t80 / 0.2e1_dp + t41 * t75 * t203 / 0.2e1_dp
      t251 = t194 * t250
      t255 = -0.2e1_dp / 0.9e1_dp * t120 * t192 * t251 + 0.2e1_dp / 0.9e1_dp * t33 * t240 * t84
      t259 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t255, t60)
      t262 = t23 * t23
      t263 = 0.1e1_dp / t262
      t264 = t98 * t98
      t267 = t94 * t6
      t268 = 0.1e1_dp / t267
      t269 = t16 * t268
      t272 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t95 + 0.2e1_dp * t269, t14), t10)
      t276 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t263 * t264 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t272, t20)
      t277 = t276 * t26
      t281 = t101 * t107
      t283 = t5 * t281 * t55
      t289 = 0.1e1_dp / t106 / t6
      t290 = t25 * t289
      t293 = t5 * t290 * t55 / 0.12e2_dp
      t295 = t5 * t108 * t141
      t297 = t36 * t36
      t299 = 0.1e1_dp / t38 / t297
      t308 = 0.1e1_dp / t122 / t49
      t309 = t136 * t136
      t310 = t308 * t309
      t315 = 0.1e1_dp / t37 / t112
      t320 = sigma_aa * t299
      t324 = sigma_aa * sigma_aa
      t327 = 0.1e1_dp / t37 / t297 / t112
      t330 = 0.1e1_dp / t131 / t130
      t334 = 0.28e2_dp / 0.9e1_dp * t41 * t42 * t315 * t46 + 0.2e2_dp / 0.3e1_dp * t41 * t320 &
         * t132 - 0.16e2_dp / 0.9e1_dp * t41 * t324 * t327 * t330
      t335 = t123 * t334
      t339 = 0.176e3_dp / 0.81e2_dp * t33 * t35 * t299 * t50 + 0.32e2_dp / 0.27e2_dp * t120 * &
         t129 * t137 + 0.4e1_dp / 0.9e1_dp * t120 * t121 * t310 - 0.2e1_dp / 0.9e1_dp * t120 &
         * t121 * t335
      t344 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t277 * t55 - t283 / 0.4e1_dp - &
         0.3e1_dp / 0.4e1_dp * t5 * t102 * t141 + t293 - t295 / 0.4e1_dp - 0.3e1_dp / &
         0.8e1_dp * t5 * t27 * t339, t1)
      t345 = t66 * t66
      t346 = 0.1e1_dp / t345
      t347 = t149 * t149
      t350 = t61 * t268
      t353 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t95 + 0.2e1_dp * t350, t10), t14)
      t357 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t346 * t347 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t353, t65)
      t358 = t357 * t26
      t362 = t152 * t107
      t364 = t5 * t362 * t89
      t366 = t68 * t289
      t369 = t5 * t366 * t89 / 0.12e2_dp
      t371 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t358 * t89 - t364 / 0.4e1_dp + t369, t60)
      t387 = t169 * t107
      t389 = t5 * t387 * t55
      t411 = t180 * t107
      t413 = t5 * t411 * t89
      t420 = t5 * t157 * t212
      t428 = t166 * t166
      t433 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t95 + 0.2e1_dp * t269, t14), t10)
      t437 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t263 * t428 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t433, t20)
      t438 = t437 * t26
      t444 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t438 * t55 - t389 / 0.4e1_dp + t293, t1)
      t445 = t177 * t177
      t450 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t95 + 0.2e1_dp * t350, t10), t14)
      t454 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t346 * t445 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t450, t65)
      t455 = t454 * t26
      t464 = t71 * t71
      t466 = 0.1e1_dp / t73 / t464
      t475 = 0.1e1_dp / t193 / t83
      t476 = t207 * t207
      t477 = t475 * t476
      t482 = 0.1e1_dp / t72 / t185
      t487 = sigma_bb * t466
      t491 = sigma_bb * sigma_bb
      t494 = 0.1e1_dp / t72 / t464 / t185
      t497 = 0.1e1_dp / t202 / t201
      t501 = 0.28e2_dp / 0.9e1_dp * t41 * t76 * t482 * t80 + 0.2e2_dp / 0.3e1_dp * t41 * t487 &
         * t203 - 0.16e2_dp / 0.9e1_dp * t41 * t491 * t494 * t497
      t502 = t194 * t501
      t506 = 0.176e3_dp / 0.81e2_dp * t33 * t70 * t466 * t84 + 0.32e2_dp / 0.27e2_dp * t120 * &
         t200 * t208 + 0.4e1_dp / 0.9e1_dp * t120 * t192 * t477 - 0.2e1_dp / 0.9e1_dp * t120 &
         * t192 * t502
      t511 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t455 * t89 - t413 / 0.4e1_dp - &
         0.3e1_dp / 0.4e1_dp * t5 * t181 * t212 + t369 - t420 / 0.4e1_dp - 0.3e1_dp / &
         0.8e1_dp * t5 * t69 * t506, t60)
      t519 = t5 * t108 * t235 / 0.8e1_dp
      t520 = t34 * t114
      t530 = t308 * t230
      t531 = t530 * t136
      t542 = t297 * t36
      t544 = 0.1e1_dp / t37 / t542
      t545 = t544 * t330
      t549 = -0.2e1_dp / 0.3e1_dp * t41 * t223 * t125 * t46 - 0.2e1_dp * t41 * t114 * t132 + &
         0.2e1_dp / 0.3e1_dp * t41 * t545 * sigma_aa
      t550 = t123 * t549
      t554 = -0.16e2_dp / 0.27e2_dp * t33 * t520 * t50 - 0.2e1_dp / 0.9e1_dp * t33 * t220 * &
         t137 + 0.16e2_dp / 0.27e2_dp * t120 * t129 * t231 + 0.4e1_dp / 0.9e1_dp * t120 * &
         t121 * t531 - 0.2e1_dp / 0.9e1_dp * t120 * t121 * t550
      t559 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t102 * t235 - t519 - 0.3e1_dp / &
         0.8e1_dp * t5 * t27 * t554, t1)
      t566 = t5 * t157 * t255 / 0.8e1_dp
      t579 = t34 * t187
      t589 = t475 * t250
      t590 = t589 * t207
      t601 = t464 * t71
      t603 = 0.1e1_dp / t72 / t601
      t604 = t603 * t497
      t608 = -0.2e1_dp / 0.3e1_dp * t41 * t243 * t196 * t80 - 0.2e1_dp * t41 * t187 * t203 + &
         0.2e1_dp / 0.3e1_dp * t41 * t604 * sigma_bb
      t609 = t194 * t608
      t613 = -0.16e2_dp / 0.27e2_dp * t33 * t579 * t84 - 0.2e1_dp / 0.9e1_dp * t33 * t240 * &
         t208 + 0.16e2_dp / 0.27e2_dp * t120 * t200 * t251 + 0.4e1_dp / 0.9e1_dp * t120 * &
         t192 * t590 - 0.2e1_dp / 0.9e1_dp * t120 * t192 * t609
      t618 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t181 * t255 - t566 - 0.3e1_dp / &
         0.8e1_dp * t5 * t69 * t613, t60)
      t623 = t230 * t230
      t624 = t308 * t623
      t629 = 0.1e1_dp / t42 / sigma_aa
      t633 = 0.1e1_dp / sigma_aa
      t637 = t297 * rho_a
      t639 = 0.1e1_dp / t37 / t637
      t643 = t41 * t633 * t40 * t132 / 0.4e1_dp - t41 * t629 * t44 * t46 / 0.4e1_dp - t41 * &
         t639 * t330 / 0.4e1_dp
      t644 = t123 * t643
      t648 = -0.4e1_dp / 0.9e1_dp * t33 * t220 * t231 + 0.4e1_dp / 0.9e1_dp * t120 * t121 * &
         t624 - 0.2e1_dp / 0.9e1_dp * t120 * t121 * t644
      t652 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t648, t1)
      t656 = t250 * t250
      t657 = t475 * t656
      t662 = 0.1e1_dp / t76 / sigma_bb
      t666 = 0.1e1_dp / sigma_bb
      t670 = t464 * rho_b
      t672 = 0.1e1_dp / t72 / t670
      t676 = t41 * t666 * t75 * t203 / 0.4e1_dp - t41 * t662 * t78 * t80 / 0.4e1_dp - t41 * &
         t672 * t497 / 0.4e1_dp
      t677 = t194 * t676
      t681 = -0.4e1_dp / 0.9e1_dp * t33 * t240 * t251 + 0.4e1_dp / 0.9e1_dp * t120 * t192 * &
         t657 - 0.2e1_dp / 0.9e1_dp * t120 * t192 * t677
      t685 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t681, t60)
      v2rho2_aa = 0.2e1_dp * t146 + 0.2e1_dp * t162 + t6 * (t344 + t371)
      v2rho2_bb = 0.2e1_dp * t175 + 0.2e1_dp * t217 + t6 * (t444 + t511)
      v2rhosigma_a_aa = t6 * t559 + t239
      v2rhosigma_b_bb = t6 * t618 + t259
      v2sigma2_aa_aa = t6 * t652
      v2sigma2_bb_bb = t6 * t685
      v2rho2_ab = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
   end subroutine b88_fxc_polar_impl

   pure subroutine b88_vxc_fxc_polar_impl(rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb, vrho_a, &
      vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, v2rho2_ab, v2rho2_bb, &
      v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, v2rhosigma_b_aa, v2rhosigma_b_ab, &
      v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, v2sigma2_aa_bb, v2sigma2_ab_ab, &
      v2sigma2_ab_bb, v2sigma2_bb_bb)
      !$acc routine seq
      real(dp), intent(in) :: rho_a, rho_b, sigma_aa, sigma_ab, sigma_bb
      real(dp), intent(out) :: vrho_a, vrho_b, vsigma_aa, vsigma_ab, vsigma_bb, v2rho2_aa, &
         v2rho2_ab, v2rho2_bb, v2rhosigma_a_aa, v2rhosigma_a_ab, v2rhosigma_a_bb, &
         v2rhosigma_b_aa, v2rhosigma_b_ab, v2rhosigma_b_bb, v2sigma2_aa_aa, v2sigma2_aa_ab, &
         v2sigma2_aa_bb, v2sigma2_ab_ab, v2sigma2_ab_bb, v2sigma2_bb_bb
      logical :: t1, t10, t14, t20, t60, t65
      real(dp) :: t2, t3, t31, t34, t5, t28, t29, t32
      real(dp) :: t33, t41, t119, t120, t6, t7, t11, t15
      real(dp) :: t16, t18, t19, t21, t22, t23, t25, t26
      real(dp) :: t27, t35, t36, t37, t38, t40, t42, t44
      real(dp) :: t45, t46, t49, t50, t55, t59, t61, t63
      real(dp) :: t64, t66, t68, t69, t70, t71, t72, t73
      real(dp) :: t75, t76, t78, t79, t80, t83, t84, t89
      real(dp) :: t93, t94, t95, t96, t98, t101, t102, t106
      real(dp) :: t107, t108, t111, t112, t114, t121, t122, t123
      real(dp) :: t125, t129, t130, t131, t132, t136, t137, t141
      real(dp) :: t146, t147, t149, t152, t153, t157, t160, t162
      real(dp) :: t166, t169, t170, t175, t177, t180, t181, t185
      real(dp) :: t187, t192, t193, t194, t196, t200, t201, t202
      real(dp) :: t203, t207, t208, t212, t217, t220, t223, t230
      real(dp) :: t231, t235, t239, t240, t243, t250, t251, t255
      real(dp) :: t259, t262, t263, t264, t267, t268, t269, t272
      real(dp) :: t276, t277, t281, t283, t289, t290, t293, t295
      real(dp) :: t297, t299, t308, t309, t310, t315, t320, t324
      real(dp) :: t327, t330, t334, t335, t339, t344, t345, t346
      real(dp) :: t347, t350, t353, t357, t358, t362, t364, t366
      real(dp) :: t369, t371, t387, t389, t411, t413, t420, t428
      real(dp) :: t433, t437, t438, t444, t445, t450, t454, t455
      real(dp) :: t464, t466, t475, t476, t477, t482, t487, t491
      real(dp) :: t494, t497, t501, t502, t506, t511, t519, t520
      real(dp) :: t530, t531, t542, t544, t545, t549, t550, t554
      real(dp) :: t559, t566, t579, t589, t590, t601, t603, t604
      real(dp) :: t608, t609, t613, t618, t623, t624, t629, t633
      real(dp) :: t637, t639, t643, t644, t648, t652, t656, t657
      real(dp) :: t662, t666, t670, t672, t676, t677, t681, t685
      t2 = m_cbrt_3
      t3 = m_cbrt_pi
      t31 = m_cbrt_one_ov_pi
      t34 = m_cbrt_4
      t5 = t2 / t3
      t28 = t2 * t2
      t29 = beta * t28
      t32 = 0.1e1_dp / t31
      t33 = t29 * t32
      t41 = gamma * beta
      t119 = t32 * t34
      t120 = t29 * t119
      t1 = rho_a <= dens_tol
      t6 = rho_a + rho_b
      t7 = 0.1e1_dp / t6
      t10 = 0.2e1_dp * rho_a * t7 <= zeta_tol
      t11 = zeta_tol - 0.1e1_dp
      t14 = 0.2e1_dp * rho_b * t7 <= zeta_tol
      t15 = -t11
      t16 = rho_a - rho_b
      t18 = merge(t11, merge(t15, t16 * t7, t14), t10)
      t19 = 0.1e1_dp + t18
      t20 = t19 <= zeta_tol
      t21 = xc_cbrt(zeta_tol)
      t22 = t21 * zeta_tol
      t23 = xc_cbrt(t19)
      t25 = merge(t22, t23 * t19, t20)
      t26 = xc_cbrt(t6)
      t27 = t25 * t26
      t35 = t34 * sigma_aa
      t36 = rho_a * rho_a
      t37 = xc_cbrt(rho_a)
      t38 = t37 * t37
      t40 = 0.1e1_dp / t38 / t36
      t42 = sqrt(sigma_aa)
      t44 = 0.1e1_dp / t37 / rho_a
      t45 = t42 * t44
      t46 = log(t45 + sqrt(t45 * t45 + 0.1e1_dp))
      t49 = t41 * t45 * t46 + 0.1e1_dp
      t50 = 0.1e1_dp / t49
      t55 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t35 * t40 * t50
      t59 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t55, t1)
      t60 = rho_b <= dens_tol
      t61 = -t16
      t63 = merge(t11, merge(t15, t61 * t7, t10), t14)
      t64 = 0.1e1_dp + t63
      t65 = t64 <= zeta_tol
      t66 = xc_cbrt(t64)
      t68 = merge(t22, t66 * t64, t65)
      t69 = t68 * t26
      t70 = t34 * sigma_bb
      t71 = rho_b * rho_b
      t72 = xc_cbrt(rho_b)
      t73 = t72 * t72
      t75 = 0.1e1_dp / t73 / t71
      t76 = sqrt(sigma_bb)
      t78 = 0.1e1_dp / t72 / rho_b
      t79 = t76 * t78
      t80 = log(t79 + sqrt(t79 * t79 + 0.1e1_dp))
      t83 = t41 * t79 * t80 + 0.1e1_dp
      t84 = 0.1e1_dp / t83
      t89 = 0.1e1_dp + 0.2e1_dp / 0.9e1_dp * t33 * t70 * t75 * t84
      t93 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t89, t60)
      t94 = t6 * t6
      t95 = 0.1e1_dp / t94
      t96 = t16 * t95
      t98 = merge(0.0_dp, merge(0.0_dp, t7 - t96, t14), t10)
      t101 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t98, t20)
      t102 = t101 * t26
      t106 = t26 * t26
      t107 = 0.1e1_dp / t106
      t108 = t25 * t107
      t111 = t5 * t108 * t55 / 0.8e1_dp
      t112 = t36 * rho_a
      t114 = 0.1e1_dp / t38 / t112
      t121 = sigma_aa * t40
      t122 = t49 * t49
      t123 = 0.1e1_dp / t122
      t125 = 0.1e1_dp / t37 / t36
      t129 = sigma_aa * t114
      t130 = t121 + 0.1e1_dp
      t131 = sqrt(t130)
      t132 = 0.1e1_dp / t131
      t136 = -0.4e1_dp / 0.3e1_dp * t41 * t42 * t125 * t46 - 0.4e1_dp / 0.3e1_dp * t41 * t129 &
         * t132
      t137 = t123 * t136
      t141 = -0.16e2_dp / 0.27e2_dp * t33 * t35 * t114 * t50 - 0.2e1_dp / 0.9e1_dp * t120 * &
         t121 * t137
      t146 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t102 * t55 - t111 - 0.3e1_dp / &
         0.8e1_dp * t5 * t27 * t141, t1)
      t147 = t61 * t95
      t149 = merge(0.0_dp, merge(0.0_dp, -t7 - t147, t10), t14)
      t152 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t149, t65)
      t153 = t152 * t26
      t157 = t68 * t107
      t160 = t5 * t157 * t89 / 0.8e1_dp
      t162 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t153 * t89 - t160, t60)
      t166 = merge(0.0_dp, merge(0.0_dp, -t7 - t96, t14), t10)
      t169 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t23 * t166, t20)
      t170 = t169 * t26
      t175 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t170 * t55 - t111, t1)
      t177 = merge(0.0_dp, merge(0.0_dp, t7 - t147, t10), t14)
      t180 = merge(0.0_dp, 0.4e1_dp / 0.3e1_dp * t66 * t177, t65)
      t181 = t180 * t26
      t185 = t71 * rho_b
      t187 = 0.1e1_dp / t73 / t185
      t192 = sigma_bb * t75
      t193 = t83 * t83
      t194 = 0.1e1_dp / t193
      t196 = 0.1e1_dp / t72 / t71
      t200 = sigma_bb * t187
      t201 = t192 + 0.1e1_dp
      t202 = sqrt(t201)
      t203 = 0.1e1_dp / t202
      t207 = -0.4e1_dp / 0.3e1_dp * t41 * t76 * t196 * t80 - 0.4e1_dp / 0.3e1_dp * t41 * t200 &
         * t203
      t208 = t194 * t207
      t212 = -0.16e2_dp / 0.27e2_dp * t33 * t70 * t187 * t84 - 0.2e1_dp / 0.9e1_dp * t120 * &
         t192 * t208
      t217 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t181 * t89 - t160 - 0.3e1_dp / &
         0.8e1_dp * t5 * t69 * t212, t60)
      t220 = t34 * t40
      t223 = 0.1e1_dp / t42
      t230 = t41 * t223 * t44 * t46 / 0.2e1_dp + t41 * t40 * t132 / 0.2e1_dp
      t231 = t123 * t230
      t235 = -0.2e1_dp / 0.9e1_dp * t120 * t121 * t231 + 0.2e1_dp / 0.9e1_dp * t33 * t220 * t50
      t239 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t235, t1)
      t240 = t34 * t75
      t243 = 0.1e1_dp / t76
      t250 = t41 * t243 * t78 * t80 / 0.2e1_dp + t41 * t75 * t203 / 0.2e1_dp
      t251 = t194 * t250
      t255 = -0.2e1_dp / 0.9e1_dp * t120 * t192 * t251 + 0.2e1_dp / 0.9e1_dp * t33 * t240 * t84
      t259 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t255, t60)
      t262 = t23 * t23
      t263 = 0.1e1_dp / t262
      t264 = t98 * t98
      t267 = t94 * t6
      t268 = 0.1e1_dp / t267
      t269 = t16 * t268
      t272 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t95 + 0.2e1_dp * t269, t14), t10)
      t276 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t263 * t264 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t272, t20)
      t277 = t276 * t26
      t281 = t101 * t107
      t283 = t5 * t281 * t55
      t289 = 0.1e1_dp / t106 / t6
      t290 = t25 * t289
      t293 = t5 * t290 * t55 / 0.12e2_dp
      t295 = t5 * t108 * t141
      t297 = t36 * t36
      t299 = 0.1e1_dp / t38 / t297
      t308 = 0.1e1_dp / t122 / t49
      t309 = t136 * t136
      t310 = t308 * t309
      t315 = 0.1e1_dp / t37 / t112
      t320 = sigma_aa * t299
      t324 = sigma_aa * sigma_aa
      t327 = 0.1e1_dp / t37 / t297 / t112
      t330 = 0.1e1_dp / t131 / t130
      t334 = 0.28e2_dp / 0.9e1_dp * t41 * t42 * t315 * t46 + 0.2e2_dp / 0.3e1_dp * t41 * t320 &
         * t132 - 0.16e2_dp / 0.9e1_dp * t41 * t324 * t327 * t330
      t335 = t123 * t334
      t339 = 0.176e3_dp / 0.81e2_dp * t33 * t35 * t299 * t50 + 0.32e2_dp / 0.27e2_dp * t120 * &
         t129 * t137 + 0.4e1_dp / 0.9e1_dp * t120 * t121 * t310 - 0.2e1_dp / 0.9e1_dp * t120 &
         * t121 * t335
      t344 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t277 * t55 - t283 / 0.4e1_dp - &
         0.3e1_dp / 0.4e1_dp * t5 * t102 * t141 + t293 - t295 / 0.4e1_dp - 0.3e1_dp / &
         0.8e1_dp * t5 * t27 * t339, t1)
      t345 = t66 * t66
      t346 = 0.1e1_dp / t345
      t347 = t149 * t149
      t350 = t61 * t268
      t353 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t95 + 0.2e1_dp * t350, t10), t14)
      t357 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t346 * t347 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t353, t65)
      t358 = t357 * t26
      t362 = t152 * t107
      t364 = t5 * t362 * t89
      t366 = t68 * t289
      t369 = t5 * t366 * t89 / 0.12e2_dp
      t371 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t358 * t89 - t364 / 0.4e1_dp + t369, t60)
      t387 = t169 * t107
      t389 = t5 * t387 * t55
      t411 = t180 * t107
      t413 = t5 * t411 * t89
      t420 = t5 * t157 * t212
      t428 = t166 * t166
      t433 = merge(0.0_dp, merge(0.0_dp, 0.2e1_dp * t95 + 0.2e1_dp * t269, t14), t10)
      t437 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t263 * t428 + 0.4e1_dp / 0.3e1_dp * t23 * &
         t433, t20)
      t438 = t437 * t26
      t444 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t438 * t55 - t389 / 0.4e1_dp + t293, t1)
      t445 = t177 * t177
      t450 = merge(0.0_dp, merge(0.0_dp, -0.2e1_dp * t95 + 0.2e1_dp * t350, t10), t14)
      t454 = merge(0.0_dp, 0.4e1_dp / 0.9e1_dp * t346 * t445 + 0.4e1_dp / 0.3e1_dp * t66 * &
         t450, t65)
      t455 = t454 * t26
      t464 = t71 * t71
      t466 = 0.1e1_dp / t73 / t464
      t475 = 0.1e1_dp / t193 / t83
      t476 = t207 * t207
      t477 = t475 * t476
      t482 = 0.1e1_dp / t72 / t185
      t487 = sigma_bb * t466
      t491 = sigma_bb * sigma_bb
      t494 = 0.1e1_dp / t72 / t464 / t185
      t497 = 0.1e1_dp / t202 / t201
      t501 = 0.28e2_dp / 0.9e1_dp * t41 * t76 * t482 * t80 + 0.2e2_dp / 0.3e1_dp * t41 * t487 &
         * t203 - 0.16e2_dp / 0.9e1_dp * t41 * t491 * t494 * t497
      t502 = t194 * t501
      t506 = 0.176e3_dp / 0.81e2_dp * t33 * t70 * t466 * t84 + 0.32e2_dp / 0.27e2_dp * t120 * &
         t200 * t208 + 0.4e1_dp / 0.9e1_dp * t120 * t192 * t477 - 0.2e1_dp / 0.9e1_dp * t120 &
         * t192 * t502
      t511 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t455 * t89 - t413 / 0.4e1_dp - &
         0.3e1_dp / 0.4e1_dp * t5 * t181 * t212 + t369 - t420 / 0.4e1_dp - 0.3e1_dp / &
         0.8e1_dp * t5 * t69 * t506, t60)
      t519 = t5 * t108 * t235 / 0.8e1_dp
      t520 = t34 * t114
      t530 = t308 * t230
      t531 = t530 * t136
      t542 = t297 * t36
      t544 = 0.1e1_dp / t37 / t542
      t545 = t544 * t330
      t549 = -0.2e1_dp / 0.3e1_dp * t41 * t223 * t125 * t46 - 0.2e1_dp * t41 * t114 * t132 + &
         0.2e1_dp / 0.3e1_dp * t41 * t545 * sigma_aa
      t550 = t123 * t549
      t554 = -0.16e2_dp / 0.27e2_dp * t33 * t520 * t50 - 0.2e1_dp / 0.9e1_dp * t33 * t220 * &
         t137 + 0.16e2_dp / 0.27e2_dp * t120 * t129 * t231 + 0.4e1_dp / 0.9e1_dp * t120 * &
         t121 * t531 - 0.2e1_dp / 0.9e1_dp * t120 * t121 * t550
      t559 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t102 * t235 - t519 - 0.3e1_dp / &
         0.8e1_dp * t5 * t27 * t554, t1)
      t566 = t5 * t157 * t255 / 0.8e1_dp
      t579 = t34 * t187
      t589 = t475 * t250
      t590 = t589 * t207
      t601 = t464 * t71
      t603 = 0.1e1_dp / t72 / t601
      t604 = t603 * t497
      t608 = -0.2e1_dp / 0.3e1_dp * t41 * t243 * t196 * t80 - 0.2e1_dp * t41 * t187 * t203 + &
         0.2e1_dp / 0.3e1_dp * t41 * t604 * sigma_bb
      t609 = t194 * t608
      t613 = -0.16e2_dp / 0.27e2_dp * t33 * t579 * t84 - 0.2e1_dp / 0.9e1_dp * t33 * t240 * &
         t208 + 0.16e2_dp / 0.27e2_dp * t120 * t200 * t251 + 0.4e1_dp / 0.9e1_dp * t120 * &
         t192 * t590 - 0.2e1_dp / 0.9e1_dp * t120 * t192 * t609
      t618 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t181 * t255 - t566 - 0.3e1_dp / &
         0.8e1_dp * t5 * t69 * t613, t60)
      t623 = t230 * t230
      t624 = t308 * t623
      t629 = 0.1e1_dp / t42 / sigma_aa
      t633 = 0.1e1_dp / sigma_aa
      t637 = t297 * rho_a
      t639 = 0.1e1_dp / t37 / t637
      t643 = t41 * t633 * t40 * t132 / 0.4e1_dp - t41 * t629 * t44 * t46 / 0.4e1_dp - t41 * &
         t639 * t330 / 0.4e1_dp
      t644 = t123 * t643
      t648 = -0.4e1_dp / 0.9e1_dp * t33 * t220 * t231 + 0.4e1_dp / 0.9e1_dp * t120 * t121 * &
         t624 - 0.2e1_dp / 0.9e1_dp * t120 * t121 * t644
      t652 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t27 * t648, t1)
      t656 = t250 * t250
      t657 = t475 * t656
      t662 = 0.1e1_dp / t76 / sigma_bb
      t666 = 0.1e1_dp / sigma_bb
      t670 = t464 * rho_b
      t672 = 0.1e1_dp / t72 / t670
      t676 = t41 * t666 * t75 * t203 / 0.4e1_dp - t41 * t662 * t78 * t80 / 0.4e1_dp - t41 * &
         t672 * t497 / 0.4e1_dp
      t677 = t194 * t676
      t681 = -0.4e1_dp / 0.9e1_dp * t33 * t240 * t251 + 0.4e1_dp / 0.9e1_dp * t120 * t192 * &
         t657 - 0.2e1_dp / 0.9e1_dp * t120 * t192 * t677
      t685 = merge(0.0_dp, -0.3e1_dp / 0.8e1_dp * t5 * t69 * t681, t60)
      vrho_a = t59 + t93 + t6 * (t146 + t162)
      vrho_b = t59 + t93 + t6 * (t175 + t217)
      vsigma_aa = t6 * t239
      vsigma_ab = 0.e0_dp
      vsigma_bb = t6 * t259
      v2rho2_aa = 0.2e1_dp * t146 + 0.2e1_dp * t162 + t6 * (t344 + t371)
      v2rho2_bb = 0.2e1_dp * t175 + 0.2e1_dp * t217 + t6 * (t444 + t511)
      v2rhosigma_a_aa = t6 * t559 + t239
      v2rhosigma_b_bb = t6 * t618 + t259
      v2sigma2_aa_aa = t6 * t652
      v2sigma2_bb_bb = t6 * t685
      v2rho2_ab = 0.0_dp
      v2rhosigma_a_ab = 0.0_dp
      v2rhosigma_a_bb = 0.0_dp
      v2rhosigma_b_aa = 0.0_dp
      v2rhosigma_b_ab = 0.0_dp
      v2sigma2_aa_ab = 0.0_dp
      v2sigma2_aa_bb = 0.0_dp
      v2sigma2_ab_ab = 0.0_dp
      v2sigma2_ab_bb = 0.0_dp
   end subroutine b88_vxc_fxc_polar_impl

end module trc_xc_b88
