#!/usr/bin/env python3
"""Generate trc_boys.F90: Chebyshev coefficients for the Boys function.

    F_m(T) = int_0^1 u^(2m) exp(-T u^2) du

WHY THIS FILE EXISTS NOW
------------------------
`src/trc_boys.F90` has always said "GENERATED by scripts/gen_boys_table.py",
and that script was not in the repository. The table was therefore
unreproducible: raising BOYS_MMAX to reach f functions (which need m up to
4*lmax = 12) meant either finding the original generator or writing one.

Validated against the committed MMAX=8 table, though NOT byte for byte: the
leading coefficient of each series agrees to 16 digits, and the trailing ones
diverge in their own low digits because they are O(1e-14) and the original was
produced by some other quadrature. The absolute disagreement is ~1e-17, below
double precision, so the EVALUATED function agrees even where the file does
not. Check function values, not the diff.

LAYOUT (load-bearing, matches the Clenshaw loop in trc_boys.F90)
---------------------------------------------------------------
    element(i, m, j) = i*(MMAX+1)*(NCHEB+1) + m*(NCHEB+1) + j + 1

with i the interval, m the order, j the coefficient -- coefficient fastest, so
one order's coefficients are contiguous and one interval's block is too.

Interval i covers T in [i*DT, (i+1)*DT] and is mapped to [-1, 1] by
    x = 2*(T - i*DT)/DT - 1
which is what the evaluator computes as
    bx = 2*(tval - bi*BOYS_DT)*BOYS_DTINV - 1

Above BOYS_TMAX the evaluator does not use the table at all: it takes
F_0 from erf and climbs with the upward recurrence, so the table stops there.

Needs mpmath, and the CI job that regenerates and diffs must install it pinned.
"""
import argparse

from mpmath import mp, mpf, gammainc, cos, pi


def boys(m, T):
    """F_m(T) = gamma_lower(m+1/2, T) / (2 T^(m+1/2)).

    The closed form rather than the integral: it agrees with adaptive
    quadrature to the full working precision and is ~26x faster, which matters
    at MMAX=12 where the table is 74,880 coefficients.
    """
    if T < mpf("1e-12"):
        return mpf(1) / (2 * m + 1)
    a = m + mpf(1) / 2
    return gammainc(a, 0, T) / (2 * T ** a)


def cheb(f, lo, hi, deg):
    """Degree-`deg` Chebyshev coefficients of f on [lo, hi]."""
    N = deg + 1
    xs = [cos(pi * (k + mpf(1) / 2) / N) for k in range(N)]
    ys = [f(mpf(1) / 2 * (hi - lo) * x + mpf(1) / 2 * (hi + lo)) for x in xs]
    c = [2 * sum(ys[k] * cos(pi * j * (k + mpf(1) / 2) / N) for k in range(N)) / N
         for j in range(N)]
    c[0] /= 2
    return c


def fort(x):
    s = mp.nstr(x, 17, strip_zeros=False)
    if "e" not in s:
        s += "e+00" if "." in s else ".0e+00"
    return s + "_dp"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--mmax", type=int, default=8,
                    help="highest Boys order; a kernel needs 4*lmax")
    ap.add_argument("--ncheb", type=int, default=5)
    ap.add_argument("--ngrid", type=int, default=960)
    ap.add_argument("--tmax", type=float, default=30.0)
    ap.add_argument("--dps", type=int, default=40)
    ap.add_argument("-o", "--output", default="src/trc_boys.F90")
    args = ap.parse_args()
    mp.dps = args.dps

    MMAX, NCHEB, NGRID = args.mmax, args.ncheb, args.ngrid
    TMAX = mpf(args.tmax)
    DT = TMAX / NGRID

    flat = []
    for i in range(NGRID):
        lo, hi = i * DT, (i + 1) * DT
        for m in range(MMAX + 1):
            flat.extend(cheb(lambda T, m=m: boys(m, T), lo, hi, NCHEB))
        if (i + 1) % 120 == 0:
            print(f"    interval {i + 1}/{NGRID}")

    lines = []
    for k in range(0, len(flat), 3):
        lines.append("      " + ", ".join(fort(v) for v in flat[k:k + 3])
                     + ("," if k + 3 < len(flat) else ""))
    body = " &\n".join(lines)

    src = f'''!
! Boys function F_m(T) = int_0^1 u^(2m) exp(-T u^2) du.
!
! GENERATED by scripts/gen_boys_table.py -- do not edit.  Regenerate with
!     python3 scripts/gen_boys_table.py --mmax {MMAX}
!
! Degree-{NCHEB} Chebyshev coefficients for EVERY order 0..{MMAX}, on each
! interval of a uniform grid.  Each order is evaluated directly by Clenshaw
! recurrence -- no downward recurrence between orders, hence no divisions and
! no exp(-T) on the common path.
!
! Chebyshev rather than Taylor because it is minimax-optimal: it spreads the
! error evenly across the interval instead of being exact at the centre and
! worst at the edges, so it reaches the same accuracy at a lower degree, which
! is one fewer coefficient to load per evaluation.
!
! NOT a `parameter` array, deliberately: nvfortran's fort2 segfaults on
! parameter arrays this size.  A plain module array with an initialiser is
! fine and is what gamess-libERI settled on for the same reason.
!
!
! [1] J. L. Galvez Vallejo, G. M. J. Barca and M. S. Gordon,
!     "High-performance GPU-accelerated evaluation of electron repulsion
!     integrals", Mol. Phys. (2022) e2112987, doi:10.1080/00268976.2022.2112987
!
module trc_boys
   implicit none
   private
   integer, parameter, public :: dp = selected_real_kind(15, 307)
   public :: boys_eval, boys_init
   integer,  parameter, public :: BOYS_MMAX   = {MMAX}
   integer,  parameter, public :: BOYS_NCHEB  = {NCHEB}
   integer,  parameter, public :: BOYS_NGRID  = {NGRID}
   real(dp), parameter, public :: BOYS_TMAX   = {fort(TMAX)}
   real(dp), parameter, public :: BOYS_DT     = {fort(DT)}
   real(dp), parameter, public :: BOYS_DTINV  = {fort(1/DT)}
'''
    TABLE_COMMENT = f"""   ! Flattened (coefficient, order, interval), coefficient fastest:
   !   element(i,m,j) = i*(BOYS_MMAX+1)*(BOYS_NCHEB+1) + m*(BOYS_NCHEB+1) + j + 1
   ! One order's {NCHEB+1} coefficients are contiguous, and one interval's whole
   ! block is too, so a thread reads a single short run.
"""
    # The evaluator itself is hand-written and not regenerated: take everything
    # from `!$acc declare create` onward out of the current file. That keeps the
    # Clenshaw loop, boys_init and the asymptotic branch under human control,
    # and means this script only ever rewrites data.
    import pathlib
    old = pathlib.Path(args.output).read_text()
    tail = old[old.index("   !$acc declare create(boys_table)"):]
    tail = tail.replace("boys_table(51840)", f"boys_table({len(flat)})")

    body_decl = f"   real(dp), public :: boys_table({len(flat)}) = (/ &\n{body} &\n      /)\n"
    pathlib.Path(args.output).write_text(src + TABLE_COMMENT + body_decl + tail)
    print(f"  {args.output}: mmax={MMAX}, {len(flat)} coefficients")


if __name__ == "__main__":
    main()
