function(print_terco_summary)
  message(STATUS "")
  message(STATUS "========== terco Configuration Summary ==========")
  message(STATUS "  Fortran compiler      : ${CMAKE_Fortran_COMPILER_ID}")
  message(STATUS "  TERCO_ENABLE_GPU      : ${TERCO_ENABLE_GPU}")
  message(STATUS "  TERCO_LMAX            : ${TERCO_LMAX} (four-centre ceiling)")
  message(STATUS "  TERCO_GPU_ARCH        : ${TERCO_GPU_ARCH}")
  message(STATUS "  TERCO_BUILD_SHARED    : ${TERCO_BUILD_SHARED}")
  message(STATUS "  TERCO_ENABLE_TESTING  : ${TERCO_ENABLE_TESTING}")
  message(STATUS "  TERCO_REGENERATE      : ${TERCO_REGENERATE}")
  if(NOT TERCO_LMAX STREQUAL "2")
    message(STATUS "  kernels               : regenerated in the build tree")
  elseif(TERCO_REGENERATE)
    message(STATUS "  kernels               : regenerated in-tree (src/generated)")
  else()
    message(STATUS "  kernels               : committed set in src/generated")
  endif()
  message(STATUS "=================================================")
endfunction()
